import type { ModuleDefinition } from "@/content/content-types";

export const m13KubernetesProductionEksModule: ModuleDefinition = {
  id: "m13",
  slug: "m13-kubernetes-production-eks",
  phaseId: "phase-4",
  order: 13,
  weeks: "Tuần 21",
  title: "Kubernetes Production & Amazon EKS",
  emoji: "🏗️",
  eli5Summary:
    "Ở M12 bạn tự quản lý một cảng nhỏ trên laptop. Giờ bạn thuê AWS vận hành phần 'ban quản lý cảng' (EKS), đóng gói hàng theo bộ khuôn có thể tái sử dụng (Helm, Kustomize), và lắp thêm các dịch vụ tự động: cổng vào, biển tên miền, chứng chỉ, và đội xe tự gọi thêm cầu tàu khi đông hàng.",
  objectives: [
    "Đóng gói app bằng Helm chart và Kustomize overlays cho nhiều môi trường",
    "Dựng EKS bằng Terraform, phân biệt managed node groups, Fargate và Karpenter",
    "Cho pod truy cập AWS không cần access key bằng EKS Pod Identity hoặc IRSA",
    "Mở app ra internet với AWS Load Balancer Controller, ExternalDNS và TLS",
    "Tự scale node bằng Karpenter, lập kế hoạch nâng cấp cluster và kiểm soát chi phí EKS",
  ],
  lessons: [
    { slug: "helm-kustomize-packaging", title: "Helm & Kustomize: đóng gói manifest", minutes: 50, summary: "Khuôn bánh có chỗ điền (Helm) vs bản gốc + giấy dán sửa đổi (Kustomize)." },
    { slug: "eks-architecture-terraform", title: "Kiến trúc EKS & dựng cluster bằng Terraform", minutes: 55, summary: "AWS lo ban quản lý cảng, bạn chọn kiểu cầu tàu: node group, Fargate hay Karpenter." },
    { slug: "eks-pod-identity-irsa", title: "Pod Identity & IRSA: quyền AWS cho pod", minutes: 45, summary: "Pod nhận thẻ tạm thời để gọi S3 — không còn access key nằm trong Secret." },
    { slug: "load-balancer-externaldns-cert-manager", title: "Load Balancer Controller, ExternalDNS & TLS", minutes: 50, summary: "Viết một Ingress, nhận về ALB, bản ghi DNS và HTTPS tự động." },
    { slug: "karpenter-autoscaling-upgrades-cost", title: "Karpenter, nâng cấp cluster & chi phí", minutes: 50, summary: "Pod chờ chỗ → node mới trong một phút; nâng cấp an toàn và không để hoá đơn phình to." },
  ],
  labs: [
    {
      id: "helm-chart-multi-env",
      title: "Helm chart cho app mẫu với values dev/staging/prod",
      description: "Biến manifest M12 thành chart có thể cài cho 3 môi trường khác nhau chỉ bằng file values.",
      steps: [
        "`helm create shop-api` rồi xoá template mẫu không dùng, giữ `deployment.yaml`, `service.yaml`, `hpa.yaml`, `_helpers.tpl`",
        "Đưa image tag, replicas, resources, probes, ingress host vào `values.yaml`; tạo `values-dev.yaml`, `values-staging.yaml`, `values-prod.yaml`",
        "Kiểm tra bằng `helm lint ./shop-api` và `helm template shop-api ./shop-api -f values-prod.yaml | kubectl apply --dry-run=server -f -`",
        "Cài lên kind: `helm upgrade --install shop-api ./shop-api -n dev --create-namespace -f values-dev.yaml`",
        "Đổi image tag, upgrade, xem `helm history shop-api -n dev` và thử `helm rollback shop-api 1 -n dev`",
        "Bonus: viết lại cùng app bằng Kustomize `base/` + `overlays/{dev,prod}` và so sánh `kubectl kustomize overlays/prod`",
      ],
    },
    {
      id: "terraform-eks-addons",
      title: "Terraform dựng EKS + add-ons, ALB tự tạo từ Ingress",
      description: "Dựng VPC + EKS bằng module cộng đồng, cài add-ons và deploy chart của lab trước ra internet. Dựng, làm, destroy trong ngày.",
      steps: [
        "Dùng module `terraform-aws-modules/vpc/aws` (3 AZ, private subnet có tag `kubernetes.io/role/internal-elb`, public subnet có tag `kubernetes.io/role/elb`)",
        "Dùng module `terraform-aws-modules/eks/aws` (ghim version) với 1 managed node group nhỏ và add-ons `vpc-cni`, `coredns`, `kube-proxy`, `eks-pod-identity-agent`, `aws-ebs-csi-driver`",
        "`terraform apply`, rồi `aws eks update-kubeconfig --name shop-lab --region ap-southeast-1` và `kubectl get nodes`",
        "Cài AWS Load Balancer Controller bằng Helm (ServiceAccount có quyền IAM qua Pod Identity)",
        "Deploy chart với `values-staging.yaml` có Ingress `ingressClassName: alb`; chờ `kubectl get ingress` hiện địa chỉ ALB rồi `curl` thử",
        "Xoá Ingress/Service LoadBalancer TRƯỚC khi `terraform destroy` để controller dọn ALB; kiểm tra console không còn ALB, EBS, NAT Gateway",
      ],
    },
    {
      id: "pod-identity-s3-read",
      title: "Pod đọc S3 qua EKS Pod Identity",
      description: "Chứng minh pod gọi được S3 mà không có access key nào trong cluster.",
      steps: [
        "Tạo bucket `shop-lab-reports-<tên>` và upload một file thử",
        "Tạo IAM role có trust policy principal `pods.eks.amazonaws.com` (actions `sts:AssumeRole`, `sts:TagSession`) và policy chỉ `s3:GetObject`, `s3:ListBucket` trên bucket đó",
        "Tạo ServiceAccount `report-reader` trong namespace `shop`, rồi `aws eks create-pod-identity-association --cluster-name shop-lab --namespace shop --service-account report-reader --role-arn <role-arn>`",
        "Chạy pod `amazon/aws-cli` dùng ServiceAccount đó: `aws sts get-caller-identity` và `aws s3 ls s3://shop-lab-reports-<tên>`",
        "Thử `aws s3 rm` → phải bị `AccessDenied`; thử cùng pod với ServiceAccount `default` → không có quyền",
        "Ghi lại khác biệt nếu làm bằng IRSA (OIDC provider + annotation `eks.amazonaws.com/role-arn`)",
      ],
    },
    {
      id: "karpenter-scale-out",
      title: "Karpenter scale node khi tăng replicas",
      description: "Quan sát pod Pending biến thành node EC2 mới trong khoảng một phút, rồi node bị dọn khi hết tải.",
      steps: [
        "Cài Karpenter theo tài liệu chính thức (IAM role cho node + controller, SQS interruption queue, tag `karpenter.sh/discovery` cho subnet/security group)",
        "Tạo `EC2NodeClass` (`amiSelectorTerms` alias `al2023@latest`) và `NodePool` cho phép `spot` + `on-demand`, `limits.cpu: 20`",
        "Deploy `inflate` (image `public.ecr.aws/eks-distro/kubernetes/pause`, request `cpu: 1`) với `replicas: 0`, rồi `kubectl scale deployment inflate --replicas=10`",
        "Theo dõi `kubectl get nodeclaims -w` và `kubectl logs -n kube-system -l app.kubernetes.io/name=karpenter -f`",
        "Scale về 0 và quan sát consolidation xoá node thừa; ghi lại thời gian scale-out/scale-in",
      ],
    },
  ],
  deliverable:
    "Repo gồm Helm chart (values dev/staging/prod), code Terraform dựng VPC + EKS + add-ons, manifest Pod Identity, cấu hình Karpenter NodePool, và README có ảnh chụp ALB hoạt động cùng checklist destroy.",
  successCriteria:
    "Từ repo trống dựng lại được EKS chạy app qua HTTPS trong dưới 1 giờ; pod truy cập S3 không dùng access key; Karpenter thêm node khi scale; destroy sạch không để lại tài nguyên tính tiền.",
  resources: [
    { title: "Amazon EKS User Guide", url: "https://docs.aws.amazon.com/eks/latest/userguide/what-is-eks.html", kind: "doc" },
    { title: "EKS Best Practices Guides", url: "https://docs.aws.amazon.com/eks/latest/best-practices/introduction.html", kind: "doc" },
    { title: "Helm Docs", url: "https://helm.sh/docs/", kind: "doc" },
    { title: "Kustomize — tài liệu trên kubernetes.io", url: "https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/", kind: "doc" },
    { title: "terraform-aws-modules/eks", url: "https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest", kind: "tool" },
    { title: "Karpenter Docs", url: "https://karpenter.sh/docs/", kind: "doc" },
    { title: "AWS Load Balancer Controller", url: "https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/", kind: "doc" },
    { title: "EKS Workshop (hands-on miễn phí)", url: "https://www.eksworkshop.com/", kind: "practice" },
  ],
  quiz: [
    {
      id: "helm-vs-kustomize-choice",
      question: "Team muốn phân phối app cho nhiều khách hàng, mỗi khách chỉnh 30 tham số (replicas, domain, bật/tắt tính năng). Công cụ nào hợp nhất?",
      options: [
        "Kustomize, vì không cần template",
        "kubectl apply từng file YAML riêng cho mỗi khách",
        "Helm chart với values.yaml, vì được thiết kế để đóng gói và tham số hoá",
        "ConfigMap chứa toàn bộ manifest",
      ],
      answerIndex: 2,
      explanation: "Helm là khuôn bánh có chỗ điền — hợp khi người dùng cuối cần nhiều tham số và cài/nâng cấp như một gói. Kustomize hợp khi bạn sở hữu YAML gốc và chỉ vá khác biệt theo môi trường.",
    },
    {
      id: "helm-template-debug",
      question: "`helm upgrade` báo lỗi YAML khó hiểu. Cách nhanh nhất để xem Helm thực sự sinh ra manifest gì?",
      options: [
        "`helm template` (hoặc `helm upgrade --dry-run --debug`) để render ra YAML và đọc",
        "Xoá release rồi cài lại",
        "Đọc trực tiếp Secret `sh.helm.release.v1` trong namespace",
        "`kubectl get all -o yaml`",
      ],
      answerIndex: 0,
      explanation: "Helm chỉ là máy đổ khuôn: `helm template` cho bạn xem 'chiếc bánh' trước khi đưa lên cluster. Lỗi thụt lề trong template hiện rõ ngay ở output.",
    },
    {
      id: "eks-shared-responsibility",
      question: "Với EKS dùng managed node groups, việc nào vẫn là trách nhiệm của BẠN?",
      options: [
        "Vận hành và backup etcd",
        "Chạy nhiều API server qua nhiều AZ",
        "Vá lỗi hệ điều hành của control plane",
        "Kích hoạt nâng cấp phiên bản node group và cập nhật add-ons sau khi nâng control plane",
      ],
      answerIndex: 3,
      explanation: "AWS thuê người vận hành ban quản lý cảng (control plane, etcd). Nhưng bạn vẫn quyết định khi nào nâng cấp, cập nhật cầu tàu (node), add-on và mọi thứ chạy bên trong.",
    },
    {
      id: "fargate-limitation",
      question: "Workload nào KHÔNG chạy được trên EKS Fargate?",
      options: ["Deployment API stateless", "DaemonSet thu thập log trên mỗi node", "Job xử lý batch ngắn", "Pod dùng Pod Identity/IRSA để gọi S3"],
      answerIndex: 1,
      explanation: "Fargate: mỗi pod một 'phòng riêng' do AWS quản lý, không có node để bạn đặt 'bảo vệ mỗi toà nhà'. DaemonSet không được hỗ trợ — dùng sidecar hoặc tính năng log tích hợp của Fargate.",
    },
    {
      id: "pod-identity-no-keys",
      question: "Pod cần đọc S3. Cách nào đúng best practice trên EKS?",
      options: [
        "Tạo IAM user, lưu access key vào Kubernetes Secret",
        "Gắn quyền S3 vào IAM role của node để mọi pod dùng chung",
        "EKS Pod Identity (hoặc IRSA): gắn IAM role vào ServiceAccount, pod nhận credentials tạm thời tự xoay vòng",
        "Mount file ~/.aws/credentials từ laptop vào pod",
      ],
      answerIndex: 2,
      explanation: "Như thẻ khách có hạn dùng cấp theo đúng người: chỉ pod dùng ServiceAccount đó nhận quyền, credentials hết hạn tự đổi. Role của node thì mọi pod trên node đều 'mượn' được.",
    },
    {
      id: "irsa-trust-policy",
      question: "Dùng IRSA, pod báo `Not authorized to perform sts:AssumeRoleWithWebIdentity`. Kiểm tra gì trước tiên?",
      options: [
        "Trust policy của role: OIDC provider đúng cluster và điều kiện `sub` khớp `system:serviceaccount:<namespace>:<serviceaccount>`",
        "Security group của node",
        "Số replicas của Deployment",
        "Phiên bản Helm",
      ],
      answerIndex: 0,
      explanation: "Role chỉ tin 'giấy giới thiệu' từ đúng OIDC provider và đúng ServiceAccount. Sai namespace hoặc tên SA trong điều kiện `sub` là lỗi cực kỳ phổ biến.",
    },
    {
      id: "alb-target-type-ip",
      question: "Với AWS Load Balancer Controller và Amazon VPC CNI, `alb.ingress.kubernetes.io/target-type: ip` mang lại gì?",
      options: [
        "ALB gửi traffic tới NodePort rồi kube-proxy chuyển tiếp",
        "ALB đăng ký thẳng IP của pod làm target, bỏ qua bước nhảy qua node",
        "ALB dùng IP tĩnh",
        "Bắt buộc dùng Fargate",
      ],
      answerIndex: 1,
      explanation: "Với VPC CNI, pod có IP thật trong VPC nên ALB có thể giao hàng thẳng tới cửa từng phòng (pod). Target type `ip` cũng là lựa chọn bắt buộc cho pod trên Fargate.",
    },
    {
      id: "externaldns-role",
      question: "ExternalDNS làm gì trong cluster?",
      options: [
        "Thay thế CoreDNS cho DNS nội bộ",
        "Cấp chứng chỉ TLS",
        "Tạo load balancer cho Service",
        "Đọc host của Ingress/Service/Gateway route rồi tạo bản ghi tương ứng trên Route 53 trỏ về load balancer",
      ],
      answerIndex: 3,
      explanation: "ExternalDNS là người treo biển tên đường ngoài phố: thấy cổng mới có tên `shop.example.com` là cập nhật danh bạ Route 53. DNS nội bộ vẫn là việc của CoreDNS.",
    },
    {
      id: "karpenter-pending-trigger",
      question: "Điều gì khiến Karpenter tạo node mới?",
      options: [
        "CPU trung bình của node vượt 80%",
        "Có pod ở trạng thái Pending vì không node nào đủ chỗ theo requests/ràng buộc",
        "HPA tăng maxReplicas",
        "Mỗi 5 phút Karpenter thêm 1 node dự phòng",
      ],
      answerIndex: 1,
      explanation: "Karpenter nhìn hàng người đứng chờ (pod unschedulable) rồi thuê đúng loại cầu tàu vừa đủ chỗ. Nó không nhìn CPU usage — việc tăng số pod theo tải là của HPA.",
    },
    {
      id: "eks-upgrade-order",
      question: "Thứ tự nâng cấp EKS an toàn từ 1.33 lên 1.34?",
      options: [
        "Kiểm tra API deprecated → nâng control plane → cập nhật add-ons → nâng data plane (node)",
        "Nâng node lên 1.34 trước, control plane sau",
        "Nhảy thẳng từ 1.33 lên 1.35 để đỡ tốn công",
        "Xoá cluster và tạo lại mỗi lần nâng cấp là cách duy nhất",
      ],
      answerIndex: 0,
      explanation: "Ban quản lý phải hiểu luật mới trước, rồi mới tới đốc công. Control plane chỉ nâng từng minor một, và kubelet không được mới hơn API server.",
    },
    {
      id: "eks-cost-trap",
      question: "Bạn `terraform destroy` xong nhưng hoá đơn vẫn tăng. Thủ phạm khả dĩ nhất?",
      options: [
        "IAM role còn tồn tại",
        "ServiceAccount chưa xoá",
        "ALB/NLB do controller tạo từ Ingress/Service và ổ EBS từ PVC không được Terraform quản lý nên còn sót lại",
        "File kubeconfig trên laptop",
      ],
      answerIndex: 2,
      explanation: "Terraform chỉ dọn thứ nó tạo. Load balancer và EBS do controller trong cluster tạo — xoá Ingress/Service/PVC trước khi destroy, rồi kiểm tra lại console. IAM role và kubeconfig không tính tiền.",
    },
  ],
};
