import type { ModuleDefinition } from "@/content/content-types";

export const m14GitopsArgocdModule: ModuleDefinition = {
  id: "m14",
  slug: "m14-gitops-argocd",
  phaseId: "phase-4",
  order: 14,
  weeks: "Tuần 22–23",
  title: "GitOps với Argo CD",
  emoji: "🔄",
  eli5Summary:
    "Thay vì bạn tự tay `kubectl apply` mỗi khi deploy (đẩy hàng vào kho), bạn viết đúng những gì kho cần có vào một cuốn sổ chung (Git), rồi một nhân viên kho luôn túc trực (Argo CD) tự đọc sổ và tự sắp xếp cho khớp — kể cả khi ai đó lỡ tay sắp sai, nhân viên cũng tự sửa lại theo đúng sổ. Module cuối Phase 4 này còn có buổi ôn tập tổng hợp cho kỳ thi CKA.",
  objectives: [
    "Giải thích 4 nguyên tắc GitOps và vì sao pull tốt hơn push cho bảo mật/độ tin cậy",
    "Cài Argo CD, đọc trạng thái Sync/Health, và hiểu vòng lặp reconcile tự sửa khi có drift",
    "Tổ chức app repo tách khỏi config repo, dùng Kustomize overlays để promote dev → staging → prod",
    "Đưa secret vào GitOps an toàn bằng External Secrets Operator, so sánh với Sealed Secrets",
    "Triển khai canary bằng Argo Rollouts với traffic splitting và auto-rollback theo metric",
    "Tổng hợp kiến thức Kubernetes/CKA và tự đánh giá qua bài thi thử killer.sh",
  ],
  lessons: [
    { slug: "gitops-principles", title: "GitOps là gì: push vs pull deploy", minutes: 40, summary: "Git là nguồn sự thật duy nhất; cluster tự kéo về thay vì bị đẩy vào." },
    { slug: "argocd-architecture-reconcile-loop", title: "Kiến trúc Argo CD & vòng lặp reconcile", minutes: 50, summary: "Application, Sync/Health status, và cách Argo CD tự phát hiện + sửa drift." },
    { slug: "repo-structure-promotion-workflow", title: "App repo vs config repo & promotion qua môi trường", minutes: 50, summary: "Tách code khỏi cấu hình deploy; đẩy một image tag qua dev → staging → prod bằng PR." },
    { slug: "secrets-in-gitops", title: "Secret trong GitOps: External Secrets Operator & Sealed Secrets", minutes: 45, summary: "Không commit secret thật vào Git — hai cách lấy secret an toàn từ nguồn bên ngoài." },
    { slug: "progressive-delivery-argo-rollouts", title: "Progressive delivery: canary với Argo Rollouts", minutes: 50, summary: "Chia traffic dần sang bản mới, tự rollback khi error rate tăng." },
  ],
  labs: [
    {
      id: "argocd-install-config-repo",
      title: "Cài Argo CD + config repo Kustomize 3 môi trường",
      description: "Dựng Argo CD trên cluster kind, tạo config repo riêng với overlays dev/staging/prod và Application đầu tiên.",
      steps: [
        "Cài Argo CD vào namespace `argocd` bằng manifest chính thức, lấy mật khẩu admin ban đầu từ Secret `argocd-initial-admin-secret`",
        "Đăng nhập `argocd login` (CLI) hoặc UI qua `kubectl port-forward svc/argocd-server -n argocd 8080:443`, đổi mật khẩu admin",
        "Tạo repo Git riêng `shop-config` với cấu trúc `base/` + `overlays/{dev,staging,prod}` (Kustomize, dùng lại kiến thức M13)",
        "Tạo `Application` trỏ `overlays/dev`, `syncPolicy.automated` bật `prune` và `selfHeal`",
        "Kiểm tra `argocd app get shop-api-dev` thấy `Synced`/`Healthy`; sửa tay 1 field bằng `kubectl edit` và xem Argo CD tự sync lại (selfHeal)",
      ],
    },
    {
      id: "ci-image-tag-auto-sync",
      title: "CI cập nhật image tag → Argo CD tự sync",
      description: "Mô phỏng luồng CI/CD đầy đủ: build image, cập nhật config repo bằng commit, Argo CD tự phát hiện và deploy.",
      steps: [
        "Viết script (hoặc GitHub Actions job) build image, tag theo commit SHA, và `git commit` sửa `newTag` trong `overlays/dev/kustomization.yaml` của config repo",
        "Xác nhận Argo CD tự phát hiện thay đổi trong vòng vài phút (hoặc trigger webhook để tức thời) và tạo revision đồng bộ mới",
        "Xem `argocd app history shop-api-dev` và thử `argocd app rollback shop-api-dev <id>`",
        "Bật `Notifications` (hoặc đơn giản là polling `argocd app get`) để biết khi sync thất bại",
        "Ghi lại toàn bộ luồng: commit app repo → build → commit config repo → Argo CD sync → pod mới chạy, kèm thời gian mỗi bước",
      ],
    },
    {
      id: "external-secrets-db-password",
      title: "External Secrets Operator lấy DB password từ AWS Secrets Manager",
      description: "Đảm bảo Git không bao giờ chứa secret thật — chỉ chứa tham chiếu tới secret.",
      steps: [
        "Tạo secret trong AWS Secrets Manager (ví dụ `shop/postgres-password`), gắn quyền `secretsmanager:GetSecretValue` cho ServiceAccount của External Secrets Operator qua Pod Identity (M13)",
        "Cài External Secrets Operator bằng Helm; tạo `SecretStore` (hoặc `ClusterSecretStore`) trỏ tới AWS Secrets Manager",
        "Viết `ExternalSecret` tham chiếu `shop/postgres-password`, `refreshInterval: 1h`, tạo ra Secret Kubernetes `postgres-auth`",
        "Xác nhận Secret Kubernetes được tạo đúng, pod đọc được; commit `ExternalSecret` (không phải giá trị thật) vào config repo",
        "Đổi giá trị secret trong Secrets Manager và xác nhận Secret Kubernetes tự cập nhật sau `refreshInterval`",
      ],
    },
    {
      id: "argo-rollouts-canary",
      title: "Canary release với Argo Rollouts + rollback tự động",
      description: "Chuyển Deployment sang Rollout, triển khai canary theo bước, và để analysis tự rollback khi lỗi tăng.",
      steps: [
        "Cài Argo Rollouts controller + plugin `kubectl argo rollouts`; đổi `Deployment` app mẫu thành `Rollout` với `strategy.canary`",
        "Định nghĩa các bước: 20% traffic → pause 2 phút → 50% → pause → 100%, dùng Service ổn định + Service canary",
        "Thêm `AnalysisTemplate` truy vấn tỉ lệ lỗi (giả lập bằng metric provider `web` gọi endpoint `/metrics` hoặc Prometheus nếu đã có từ M15)",
        "Deploy bản lỗi có chủ đích (tăng tỉ lệ lỗi 500) và quan sát Rollout tự `Degraded` rồi rollback về bản ổn định",
        "Chạy `kubectl argo rollouts get rollout shop-api --watch` để xem biểu đồ traffic split theo thời gian thực",
      ],
    },
    {
      id: "checkpoint-3-cka-review",
      title: "Checkpoint 3 + ôn CKA",
      description: "Tổng ôn toàn bộ Phase 4 (M12–M14), luyện tốc độ kubectl và tự đánh giá bằng bài thi thử killer.sh trước khi đăng ký CKA.",
      steps: [
        "Thiết lập `alias k=kubectl`, `export do=\"--dry-run=client -o yaml\"`, cấu hình vim/bash completion cho kubectl trong môi trường thi",
        "Luyện lại bằng lệnh imperative: `kubectl create/run/expose $do`, sinh nhanh Role/RoleBinding/NetworkPolicy skeleton, không gõ YAML từ đầu",
        "Ôn tập theo domain CKA: cluster setup/upgrade với kubeadm, etcd backup/restore (`etcdctl snapshot save`), troubleshooting (M12), networking (Service/Gateway API), storage (PV/PVC), workloads (Deployment/Job/CronJob), Helm/Kustomize (M13), Gateway API",
        "Làm bài thi thử **killer.sh** (đi kèm khi đăng ký CKA), chấm điểm và ghi lại từng câu sai vào `CKA-REVIEW.md` kèm lý do sai",
        "Lặp lại killer.sh lần 2 sau khi ôn lại phần yếu; mục tiêu ≥ 70% trước khi đăng ký lịch thi CKA chính thức",
      ],
    },
  ],
  deliverable:
    "Hai repo Git (app + config) với Argo CD Application tự sync 3 môi trường, ExternalSecret lấy password từ AWS Secrets Manager, Rollout canary có AnalysisTemplate, và file CKA-REVIEW.md ghi điểm + phân tích lỗi 2 lần làm killer.sh.",
  successCriteria:
    "Sửa tay một resource trên cluster thì Argo CD tự sync lại trong vài phút; đổi image tag trong config repo thì app tự deploy không cần `kubectl apply` tay; canary tự rollback khi tỉ lệ lỗi tăng; điểm killer.sh lần gần nhất ≥ 70%.",
  resources: [
    { title: "OpenGitOps — nguyên tắc GitOps chính thức (CNCF)", url: "https://opengitops.dev/", kind: "doc" },
    { title: "Argo CD — Getting Started", url: "https://argo-cd.readthedocs.io/en/stable/getting_started/", kind: "doc" },
    { title: "Argo CD — Application spec reference", url: "https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/", kind: "doc" },
    { title: "Argo Rollouts Docs", url: "https://argoproj.github.io/rollouts/", kind: "doc" },
    { title: "External Secrets Operator Docs", url: "https://external-secrets.io/latest/", kind: "doc" },
    { title: "Flux CD Docs (so sánh với Argo CD)", url: "https://fluxcd.io/flux/", kind: "doc" },
    { title: "killer.sh — bài thi thử CKA/CKAD chính thức", url: "https://killer.sh/", kind: "practice" },
    { title: "Kubernetes Docs — kubeadm & etcd backup/restore", url: "https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/", kind: "doc" },
  ],
  quiz: [
    {
      id: "gitops-pull-vs-push",
      question: "Trong GitOps, vì sao mô hình 'pull' (agent trong cluster tự kéo về) thường an toàn hơn mô hình 'push' (CI có quyền apply thẳng vào cluster) trên production?",
      options: [
        "Pull nhanh hơn push",
        "Pull không cần Git",
        "CI không cần giữ credentials có quyền ghi vào cluster; agent trong cluster mới cần quyền đó và có thể giới hạn chặt",
        "Push không hỗ trợ rollback",
      ],
      answerIndex: 2,
      explanation: "Push nghĩa là hệ thống bên ngoài (CI, thường public hoặc ít kiểm soát hơn) cầm chìa khoá vào cluster. Pull thu hẹp bề mặt tấn công: chỉ agent nội bộ (Argo CD) mới có quyền ghi, và nó chỉ làm đúng theo Git.",
    },
    {
      id: "argocd-outofsync-selfheal",
      question: "Application có `syncPolicy.automated.selfHeal: true`. Ai đó `kubectl scale` sửa tay `replicas` trực tiếp trên cluster. Điều gì xảy ra?",
      options: [
        "Argo CD báo OutOfSync và tự động apply lại theo Git, ghi đè thay đổi tay",
        "Argo CD xoá Application để tránh xung đột",
        "Không có gì xảy ra vì replicas không quan trọng",
        "Argo CD cập nhật Git theo giá trị mới trên cluster",
      ],
      answerIndex: 0,
      explanation: "selfHeal là 'nhân viên kho tự sửa lại giá không đúng sổ'. Git luôn là nguồn sự thật — Argo CD kéo cluster về khớp Git, không bao giờ làm ngược lại (trừ khi bạn chủ động sửa Git).",
    },
    {
      id: "argocd-health-vs-sync",
      question: "Argo CD hiện Application `Synced` nhưng `Degraded`. Ý nghĩa đúng nhất?",
      options: [
        "Manifest trên cluster khớp đúng Git, nhưng resource đó (ví dụ Deployment) đang không chạy khoẻ mạnh (pod CrashLoopBackOff…)",
        "Argo CD chưa áp dụng xong manifest",
        "Git repo bị lỗi cú pháp",
        "Application đã bị xoá khỏi cluster",
      ],
      answerIndex: 0,
      explanation: "Sync status = 'có khớp Git không', Health status = 'resource đó có đang hoạt động tốt không'. Hai trục độc lập: apply đúng file không có nghĩa là app chạy đúng.",
    },
    {
      id: "app-repo-vs-config-repo",
      question: "Vì sao tách app repo (source code) khỏi config repo (manifest deploy)?",
      options: [
        "Để giảm số lượng commit",
        "Git không hỗ trợ nhiều loại file trong một repo",
        "Vì Argo CD chỉ đọc được repo riêng cho manifest",
        "CI của app repo build/test/push image; commit vào config repo là bước RIÊNG (thường tự động) đại diện cho 'quyết định deploy' — tách biệt giúp audit, rollback, và phân quyền rõ ràng",
      ],
      answerIndex: 3,
      explanation: "Tách repo giống tách 'công thức nấu ăn' khỏi 'đơn đặt hàng hôm nay bếp nào nấu món gì'. Mỗi commit vào config repo là một sự kiện deploy có thể audit và revert độc lập với lịch sử code.",
    },
    {
      id: "promotion-dev-to-prod",
      question: "Cách promote một image tag đã qua staging lên production theo đúng tinh thần GitOps?",
      options: [
        "SSH vào server prod và pull image mới nhất",
        "Chạy `kubectl set image` trực tiếp trên cluster prod",
        "Sửa `newTag` trong `overlays/prod/kustomization.yaml` của config repo qua Pull Request, merge xong Argo CD tự sync prod",
        "Copy toàn bộ overlays/staging đè lên overlays/prod bằng script cron",
      ],
      answerIndex: 2,
      explanation: "Promotion là một commit có review (PR), không phải thao tác tay trên cluster. Đây cũng là điểm kiểm soát chính: ai được merge vào overlays/prod quyết định ai được phép deploy prod.",
    },
    {
      id: "external-secrets-vs-sealed-secrets",
      question: "Khác biệt chính giữa External Secrets Operator và Sealed Secrets?",
      options: [
        "External Secrets Operator chỉ dùng được với AWS, Sealed Secrets dùng được mọi cloud",
        "External Secrets Operator LẤY secret từ hệ thống bên ngoài (Secrets Manager, Vault…) về cluster; Sealed Secrets MÃ HOÁ secret để commit an toàn thẳng vào Git rồi controller trong cluster giải mã",
        "Cả hai đều lưu secret dạng plaintext trong Git",
        "Sealed Secrets không cần controller trong cluster",
      ],
      answerIndex: 1,
      explanation: "Hai triết lý khác nhau: một bên 'secret ở ngoài, chỉ commit tham chiếu' (External Secrets Operator), một bên 'secret mã hoá thì commit thẳng vào Git cũng an toàn' (Sealed Secrets, dùng khoá riêng của cluster để giải mã).",
    },
    {
      id: "externalsecret-refresh",
      question: "Đổi giá trị secret trong AWS Secrets Manager, nhưng Secret Kubernetes chưa cập nhật ngay. Nguyên nhân hợp lý nhất?",
      options: [
        "External Secrets Operator bị lỗi",
        "`ExternalSecret` có `refreshInterval` (ví dụ 1h) — nó chỉ đồng bộ lại theo chu kỳ đó, không realtime",
        "AWS Secrets Manager không hỗ trợ cập nhật",
        "Cần restart toàn bộ cluster",
      ],
      answerIndex: 1,
      explanation: "`refreshInterval` là chu kỳ 'nhân viên đi lấy hàng mới', không phải theo dõi realtime. Đặt ngắn hơn nếu cần cập nhật nhanh, nhưng đổi quá ngắn tăng số lần gọi API tới Secrets Manager.",
    },
    {
      id: "argo-rollouts-canary-traffic",
      question: "Rollout đang ở bước canary 20%. Điều gì đúng về traffic lúc này?",
      options: [
        "100% traffic vẫn vào bản cũ, bản mới chỉ chạy nền không nhận traffic",
        "20% request thật được route tới ReplicaSet bản mới, 80% vẫn vào bản ổn định — traffic thật, không phải giả lập",
        "Toàn bộ traffic được nhân đôi gửi tới cả hai bản",
        "20% là số pod, không liên quan gì tới traffic",
      ],
      answerIndex: 1,
      explanation: "Canary weight là tỉ lệ TRAFFIC THẬT (qua Service/Ingress/Gateway API có traffic splitting) đi vào bản mới, khác với chỉ đơn thuần tăng số pod. Đây là lý do canary phát hiện lỗi thật trước khi ảnh hưởng 100% người dùng.",
    },
    {
      id: "argo-rollouts-auto-rollback",
      question: "AnalysisTemplate đo tỉ lệ lỗi vượt ngưỡng ở bước canary 50%. Argo Rollouts làm gì tiếp theo (mặc định)?",
      options: [
        "Tiếp tục tăng traffic lên 100% vì đã qua nửa chặng",
        "Đánh dấu Rollout Degraded và tự động rollback traffic về 100% bản ổn định cũ",
        "Gửi email cảnh báo nhưng vẫn giữ nguyên 50%",
        "Xoá luôn Rollout",
      ],
      answerIndex: 1,
      explanation: "Đây là giá trị cốt lõi của progressive delivery: phát hiện xấu ở quy mô nhỏ (50% chứ không phải 100%) và tự rút lui ngay, không cần người trực đêm bấm rollback tay.",
    },
    {
      id: "flux-vs-argocd",
      question: "Flux CD và Argo CD giống nhau ở điểm cốt lõi nào?",
      options: [
        "Cả hai đều bắt buộc dùng Helm, không hỗ trợ Kustomize",
        "Cả hai đều là GitOps controller: pull manifest từ Git và reconcile liên tục vào cluster — khác nhau chủ yếu ở UI, kiến trúc mở rộng (ApplicationSet vs Kustomization/HelmRelease CRD) và hệ sinh thái đi kèm",
        "Flux CD chỉ chạy được ngoài Kubernetes",
        "Argo CD không hỗ trợ multi-cluster",
      ],
      answerIndex: 1,
      explanation: "Cả hai cùng thuộc họ GitOps controller theo nguyên tắc OpenGitOps. Argo CD nổi bật với UI trực quan và Argo Rollouts đi kèm; Flux CD thiên về bộ CRD nhỏ gọn (`Kustomization`, `HelmRelease`) và tích hợp sâu với Flagger cho progressive delivery.",
    },
    {
      id: "etcd-backup-cka",
      question: "Trong phạm vi ôn CKA, lệnh nào dùng để backup etcd của cluster tự quản lý (kubeadm)?",
      options: [
        "kubectl backup etcd",
        "etcdctl snapshot save <file> với đúng --endpoints, --cert, --key, --cacert của etcd",
        "helm backup etcd",
        "argocd app backup etcd",
      ],
      answerIndex: 1,
      explanation: "etcd là sổ cái của cluster (M12) — backup nó cần công cụ riêng `etcdctl`, không qua `kubectl`. Đây là chủ đề trọng tâm của domain 'Cluster Architecture, Installation & Configuration' trong CKA.",
    },
  ],
};
