import type { ModuleDefinition } from "@/content/content-types";

export const sd04CachingCdnModule: ModuleDefinition = {
  id: "sd04",
  slug: "sd04-caching-cdn",
  phaseId: "sd-phase-1",
  order: 4,
  weeks: "Tuần 5",
  title: "Caching & CDN",
  emoji: "🧊",
  eli5Summary:
    "Lần nào nấu cơm cũng chạy ra chợ thì mệt lắm — nhà nào cũng có tủ lạnh để trữ đồ hay dùng, và cửa hàng tiện lợi đầu ngõ trữ sẵn hàng bán chạy. Cache là tủ lạnh, CDN là chuỗi cửa hàng gần nhà. Module này dạy bạn trữ gì, trữ bao lâu, dọn tủ ra sao, và tránh cảnh cả xóm cùng đổ ra chợ một lúc khi tủ hết đồ.",
  objectives: [
    "Chỉ ra các tầng cache (browser, CDN, reverse proxy, application, database) và chọn tầng phù hợp cho từng loại dữ liệu",
    "Cài đặt cache-aside bằng Redis và so sánh với read-through, write-through, write-behind",
    "Chọn TTL, chính sách eviction (LRU/LFU) và cách invalidation khi dữ liệu thay đổi",
    "Nhận diện và xử lý cache stampede, cache penetration, hot key, cache avalanche",
    "Cấu hình `Cache-Control` cho static asset và API, hiểu cache key và purge của CDN",
    "Giải thích khi nào không nên cache và vì sao Redis không phải database chính",
  ],
  lessons: [
    { slug: "cache-layers", title: "Các tầng cache: từ trình duyệt tới database", minutes: 35, summary: "Tủ lạnh nhà mình, cửa hàng đầu ngõ, kho quận — mỗi tầng tiết kiệm một đoạn đường." },
    { slug: "cache-aside-write-strategies", title: "Cache-aside & các chiến lược ghi", minutes: 45, summary: "Mở tủ trước, hết thì mới đi chợ — và ghi đồ mới vào tủ lúc nào cho đúng." },
    { slug: "eviction-invalidation", title: "Eviction, TTL & invalidation", minutes: 40, summary: "Tủ đầy thì bỏ món nào, và làm sao không ăn phải đồ đã hỏng." },
    { slug: "stampede-penetration-hot-key", title: "Stampede, penetration & hot key", minutes: 45, summary: "Các sự cố cache kinh điển: cả xóm đổ ra chợ, hỏi món không tồn tại, một món ai cũng muốn." },
    { slug: "cdn-cache-control", title: "CDN & Cache-Control", minutes: 40, summary: "Đưa hàng tới cửa hàng gần khách và dán nhãn hạn dùng đúng cách." },
  ],
  labs: [
    {
      id: "cache-aside-hit-rate",
      title: "Cache-aside Redis cho endpoint đọc chậm",
      description: "Thêm cache-aside cho `GET /api/products/:id` (query Postgres giả lập ~50ms), đo hit-rate và p95 trước/sau bằng k6.",
      steps: [
        "Tạo bảng `products` với 10.000 dòng: `docker compose exec postgres psql -U postgres -c \"CREATE TABLE products AS SELECT g AS id, 'Product ' || g AS name, (random()*1000)::int AS price FROM generate_series(1,10000) g; ALTER TABLE products ADD PRIMARY KEY (id);\"`",
        "Viết endpoint không cache, query có `pg_sleep(0.05)` để giả lập 50ms; chạy `k6 run k6/products-test.js` (id phân bố lệch: 80% request vào 1.000 id đầu) và ghi p95, `http_reqs/s`",
        "Thêm cache-aside: `redis.get(key)` → miss thì query DB → `redis.set(key, value, { EX: 60 })`; rebuild bằng `docker compose up -d --build`",
        "Reset thống kê bằng `docker compose exec redis redis-cli CONFIG RESETSTAT`, chạy lại k6, rồi đọc `redis-cli INFO stats | grep keyspace` để tính hit-rate = hits ÷ (hits + misses)",
        "Điền bảng trước/sau: p95, throughput, hit-rate, CPU Postgres (`docker stats --no-stream`); ghi giả định về phân bố id",
      ],
    },
    {
      id: "reproduce-fix-cache-stampede",
      title: "Tái hiện và sửa cache stampede",
      description: "Cho một key rất nóng hết hạn dưới tải cao, đếm số query DB trùng lặp, rồi sửa bằng lock `SET NX PX` hoặc làm mới sớm.",
      steps: [
        "Tạo endpoint `/api/top-products` query nặng (`pg_sleep(0.5)`) với TTL cache 10 giây, thêm counter đếm số lần thực sự query DB (log `db_query` hoặc `redis.incr('stats:db_queries')`)",
        "Chạy k6 300 VU chỉ gọi endpoint này trong 1 phút; đếm số query DB mỗi lần key hết hạn bằng `docker compose exec redis redis-cli GET stats:db_queries`",
        "Sửa bằng lock: `SET lock:top-products <token> NX PX 3000`; chỉ request lấy được lock mới query DB, request khác chờ ngắn rồi đọc lại cache (hoặc trả bản cũ)",
        "Giải phóng lock an toàn bằng script Lua so khớp token trước khi `DEL`; thử `redis-cli SET lock:demo abc NX PX 30000` hai lần để thấy lần hai trả `(nil)`",
        "Chạy lại k6, so sánh số query DB mỗi chu kỳ và p99 trước/sau; thử thêm phương án làm mới sớm (refresh trước khi hết hạn) và ghi trade-off",
      ],
    },
    {
      id: "cache-control-headers",
      title: "Cấu hình Cache-Control cho static và API",
      description: "Đặt header cache đúng cho file tĩnh có hash trong tên, API public và API riêng tư; bật proxy cache của Nginx và kiểm tra bằng `curl -I`.",
      steps: [
        "Trong Nginx, cho `location /static/` trả `Cache-Control: public, max-age=31536000, immutable`; kiểm tra bằng `curl -I localhost:8080/static/app.3f9a1c.js`",
        "Cho `GET /api/products/:id` trả `Cache-Control: public, max-age=30, stale-while-revalidate=60` và `/api/me` trả `Cache-Control: private, no-store`; kiểm tra từng endpoint bằng `curl -I`",
        "Bật `proxy_cache_path` + `proxy_cache` trong Nginx, thêm `add_header X-Cache-Status $upstream_cache_status always;`; gọi `curl -I` hai lần để thấy `MISS` rồi `HIT`",
        "Kiểm tra revalidation: `curl -I -H 'If-None-Match: \"<etag>\"' localhost:8080/static/app.3f9a1c.js` phải trả `304 Not Modified`",
        "Viết bảng: loại tài nguyên → `Cache-Control` → lý do → cách cập nhật khi nội dung đổi (đổi tên file vs purge)",
      ],
    },
    {
      id: "product-cache-design-doc",
      title: "Design doc: cache cho trang chi tiết sản phẩm",
      description: "Viết design doc ngắn theo template Phụ lục A cho trang sản phẩm của một sàn thương mại điện tử 10M DAU.",
      steps: [
        "Ước lượng: DAU, lượt xem sản phẩm/ngày, QPS đọc trung bình và đỉnh, số sản phẩm nóng, bộ nhớ Redis cần (ghi rõ giả định)",
        "Chọn tầng cache cho từng phần: ảnh/JS (CDN), thông tin sản phẩm (Redis cache-aside), tồn kho và giá (TTL ngắn hoặc không cache) — giải thích vì sao",
        "Mô tả luồng invalidation khi người bán sửa giá: ghi DB → xoá key; nêu race condition có thể xảy ra và cách giới hạn (TTL, version trong key)",
        "Liệt kê cách xử lý stampede, penetration, hot key cho sự kiện flash sale; kèm bảng trade-off `Quyết định | Chọn | Bỏ | Vì sao | Khi nào đổi ý`",
      ],
    },
  ],
  deliverable: "Cache-aside Redis trong `sd-playground` có số đo hit-rate và p95 trước/sau, bản sửa stampede có số query DB trước/sau, cấu hình `Cache-Control` được kiểm chứng bằng `curl -I`, và design doc cache cho trang sản phẩm.",
  successCriteria: "Giải thích được khi nào không nên cache và cách xử lý dữ liệu cũ khi update.",
  resources: [
    { title: "Redis documentation", url: "https://redis.io/docs/latest/", kind: "doc" },
    { title: "Redis — SET command (NX, PX, EX)", url: "https://redis.io/docs/latest/commands/set/", kind: "doc" },
    { title: "AWS Builders' Library — Caching challenges and strategies", url: "https://aws.amazon.com/builders-library/caching-challenges-and-strategies/", kind: "doc" },
    { title: "Cloudflare Learning — What is a CDN?", url: "https://www.cloudflare.com/learning/cdn/what-is-a-cdn/", kind: "doc" },
    { title: "MDN — Cache-Control", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control", kind: "doc" },
    { title: "MDN — HTTP caching", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching", kind: "doc" },
    { title: "nginx — ngx_http_proxy_module (proxy_cache, proxy_cache_lock)", url: "https://nginx.org/en/docs/http/ngx_http_proxy_module.html", kind: "doc" },
    { title: "RFC 9111 — HTTP Caching", url: "https://www.rfc-editor.org/rfc/rfc9111", kind: "doc" },
  ],
  quiz: [
    {
      id: "when-not-to-cache",
      question: "Dữ liệu nào KHÔNG nên đưa vào cache với TTL 5 phút?",
      options: [
        "Mô tả và ảnh sản phẩm",
        "Danh sách danh mục trên menu",
        "Số dư tài khoản dùng để quyết định cho phép rút tiền",
        "Bài viết blog đã xuất bản",
      ],
      answerIndex: 2,
      explanation: "Tủ lạnh hợp với đồ để được lâu và ăn hơi cũ vẫn ổn. Số dư dùng để ra quyết định tiền bạc cần đọc nguồn chính xác (DB) — trả số cũ 5 phút có thể cho rút tiền hai lần.",
    },
    {
      id: "cache-aside-miss-flow",
      question: "Trong cache-aside, khi `GET product:42` trả về rỗng, app nên làm gì?",
      options: [
        "Query database, trả kết quả cho client và ghi vào cache kèm TTL",
        "Trả lỗi 404 ngay vì cache không có",
        "Chờ Redis tự nạp dữ liệu từ database",
        "Xoá toàn bộ cache rồi thử lại",
      ],
      answerIndex: 0,
      explanation: "Cache-aside = mở tủ lạnh trước, hết thì chính bạn đi chợ rồi cất vào tủ. Redis không tự biết database của bạn; tự nạp là mô hình read-through, cần thư viện/lớp cache làm hộ.",
    },
    {
      id: "update-invalidation",
      question: "Người bán sửa giá sản phẩm. Cách cập nhật cache nào an toàn hơn cho cache-aside?",
      options: [
        "Xoá key cache trước, rồi mới ghi database",
        "Ghi database thành công rồi xoá key cache, giữ TTL làm lưới an toàn",
        "Chỉ ghi vào cache, database cập nhật sau",
        "Không làm gì, chờ cache hết hạn sau 24 giờ",
      ],
      answerIndex: 1,
      explanation: "Mua đồ mới về thì bỏ đồ cũ trong tủ đi — sau khi đồ mới đã về nhà. Xoá trước khi ghi DB để hở một khe cho request khác nạp lại giá cũ. Ghi DB rồi xoá vẫn có race hiếm gặp nên cần TTL.",
    },
    {
      id: "write-behind-risk",
      question: "Team muốn dùng write-behind: ghi vào Redis rồi một worker ghi dồn xuống Postgres mỗi 5 giây. Rủi ro chính là gì?",
      options: [
        "Đọc chậm hơn cache-aside",
        "Không dùng được TTL",
        "Postgres bị ghi quá nhiều",
        "Redis chết trước khi flush thì mất các ghi chưa xuống DB",
      ],
      answerIndex: 3,
      explanation: "Write-behind giống ghi order vào giấy nháp rồi mới chép vào sổ cái — giấy nháp bay mất là mất order. Redis không phải database chính trừ khi cấu hình persistence và chấp nhận rõ trade-off.",
    },
    {
      id: "lru-vs-lfu",
      question: "Cache sản phẩm có một nhóm nhỏ món bán chạy quanh năm, và mỗi đêm một job quét qua toàn bộ sản phẩm một lần. Sau job, hit-rate buổi sáng tụt mạnh. Chính sách eviction nào giảm vấn đề này?",
      options: ["allkeys-lru", "noeviction", "allkeys-lfu", "volatile-ttl"],
      answerIndex: 2,
      explanation: "LRU chỉ nhớ 'món nào vừa đụng tới' nên job quét đêm đẩy món bán chạy ra khỏi tủ. LFU nhớ 'món nào hay dùng' nên món bán chạy vẫn được giữ.",
    },
    {
      id: "stampede",
      question: "Key `homepage:feed` được đọc 5.000 lần/giây, query DB mất 800ms. Mỗi lần key hết hạn, Postgres CPU vọt lên 100%. Đây là gì và sửa thế nào?",
      options: [
        "Cache penetration — thêm Bloom filter",
        "Cache stampede — chỉ cho một request nạp lại (lock `SET NX PX`) hoặc làm mới trước khi hết hạn",
        "Hot key — chia key thành nhiều bản",
        "Eviction — tăng `maxmemory`",
      ],
      answerIndex: 1,
      explanation: "Tủ lạnh vừa hết đồ thì cả xóm cùng đổ ra chợ. Để một người đi chợ (lock) và những người khác chờ/ăn tạm đồ cũ, hoặc đi chợ sớm trước khi tủ trống.",
    },
    {
      id: "penetration",
      question: "Bot gửi hàng triệu request `GET /api/products/-7` và id ngẫu nhiên không tồn tại. Cache không giúp gì và DB quá tải. Cách xử lý phù hợp?",
      options: [
        "Tăng TTL của các key đang có",
        "Chuyển sang write-through",
        "Tắt cache cho endpoint này",
        "Validate input, cache kết quả 'không tồn tại' với TTL ngắn, cân nhắc Bloom filter cho tập id hợp lệ",
      ],
      answerIndex: 3,
      explanation: "Khách cứ hỏi món quán không bán thì tủ lạnh không bao giờ có sẵn. Ghi nhớ luôn câu trả lời 'không có món này' trong ít phút và chặn câu hỏi vô lý từ cửa.",
    },
    {
      id: "cdn-versioned-assets",
      question: "Bạn đặt `Cache-Control: public, max-age=31536000, immutable` cho `app.js`. Deploy bản mới, user vẫn chạy code cũ. Cách làm chuẩn là gì?",
      options: [
        "Đặt tên file theo hash nội dung (`app.3f9a1c.js`) và để HTML tham chiếu tên mới",
        "Giảm `max-age` xuống 60 giây cho mọi file",
        "Nhắn user xoá cache trình duyệt",
        "Purge CDN là đủ, trình duyệt sẽ tự cập nhật",
      ],
      answerIndex: 0,
      explanation: "Hàng đã dán nhãn 'dùng được 1 năm' thì cửa hàng và tủ nhà khách cứ thế dùng. Đổi tên file = hàng mới hẳn nên ai cũng lấy bản mới. Purge CDN không xoá được bản đã nằm trong trình duyệt.",
    },
    {
      id: "private-no-store",
      question: "Endpoint `/api/me` trả thông tin cá nhân. Header nào tránh việc CDN/proxy dùng chung lưu và trả nhầm cho người khác?",
      options: [
        "`Cache-Control: public, max-age=60`",
        "`Cache-Control: s-maxage=300`",
        "`Cache-Control: private, no-store`",
        "Không cần header, CDN tự hiểu",
      ],
      answerIndex: 2,
      explanation: "Đồ riêng của một nhà không được bày ở cửa hàng chung. `private` cấm cache dùng chung lưu lại; `no-store` cấm lưu ở bất cứ đâu.",
    },
    {
      id: "redis-not-primary",
      question: "Vì sao câu 'dùng Redis làm database chính cho đơn hàng vì nó nhanh' là quyết định rủi ro nếu không có thêm lý do?",
      options: [
        "Redis không hỗ trợ key dạng chuỗi",
        "Dữ liệu nằm trong RAM; với RDB/AOF mặc định vẫn có thể mất ghi gần nhất khi crash, và bộ nhớ đầy có thể bị evict",
        "Redis chậm hơn Postgres",
        "Redis không chạy được trong Docker",
      ],
      answerIndex: 1,
      explanation: "Tủ lạnh rất tiện nhưng mất điện là rủi ro — không ai cất giấy tờ nhà trong tủ lạnh. Redis làm nguồn chính chỉ hợp lý khi đã cấu hình persistence/replication và chấp nhận rõ mức mất dữ liệu.",
    },
  ],
};
