import type { ModuleDefinition } from "@/content/content-types";

export const b06AuthorizationMultiTenantRbacModule: ModuleDefinition = {
  id: "b06",
  slug: "b06-authorization-multi-tenant-rbac",
  phaseId: "b-phase-1",
  order: 6,
  weeks: "Tuần 8",
  title: "Authorization & multi-tenant RBAC",
  emoji: "🛂",
  eli5Summary:
    "Một chung cư có nhiều căn hộ (organization). Bạn có thể là chủ nhà ở căn A nhưng chỉ là khách thuê ở căn B — chìa khoá (JWT) chứng minh bạn là ai, nhưng bảo vệ toà nhà (middleware) còn phải tra sổ xem bạn được vào CĂN NÀO và được làm GÌ ở đó. Module này dạy `taskflow-api` tra đúng sổ đó trước khi cho phép bất kỳ hành động nào.",
  objectives: [
    "Phân biệt RBAC (role cố định) và ABAC (thuộc tính linh hoạt), giải thích vì sao `taskflow-api` chọn RBAC ở giai đoạn này",
    "Thiết kế route + middleware resolve đúng 'organization hiện tại' và role của user trong tổ chức đó",
    "Viết `requireRole(...roles)` chặn hành động theo role, áp dụng cho route xoá project",
    "Lọc mọi truy vấn theo `organization_id` ngay trong mệnh đề WHERE, kể cả khi route không có `organizationId` trong URL (phải JOIN)",
    "Nhận diện lỗi IDOR/rò rỉ chéo tổ chức, và chọn đúng `403` hay `404` cho từng tình huống thay vì đoán bừa",
  ],
  lessons: [
    {
      slug: "rbac-vs-abac-multi-tenant-roles",
      title: "RBAC vs ABAC & vai trò owner/admin/member",
      minutes: 35,
      summary: "Vì sao `taskflow-api` gắn quyền vào một role cố định theo từng tổ chức, thay vì tính toán quyền từ nhiều thuộc tính mỗi lần.",
    },
    {
      slug: "multi-tenant-organization-scoping",
      title: "Multi-tenancy: lọc theo organization_id",
      minutes: 40,
      summary: "Route nào có `:organizationId` sẵn trong URL, route nào phải JOIN ngược để tìm ra tổ chức — và vì sao lọc trong WHERE mạnh hơn kiểm tra sau khi đã lấy dữ liệu.",
    },
    {
      slug: "require-role-middleware",
      title: "Middleware resolve organization + requireRole",
      minutes: 45,
      summary: "Hai preHandler hook nối tiếp nhau: một tra ra bạn thuộc tổ chức nào với role gì, một chặn hành động nếu role không đủ.",
    },
    {
      slug: "idor-cross-tenant-leak-mistake",
      title: "Sai lầm IDOR: rò rỉ dữ liệu chéo tổ chức",
      minutes: 35,
      summary: "Token thật, chữ ký đúng, hết hạn còn xa — nhưng thiếu một điều kiện `organization_id` là đủ để sửa được dữ liệu của tổ chức khác.",
    },
  ],
  labs: [
    {
      id: "resolve-organization-role-middleware",
      title: "Middleware resolve organization + role hiện tại",
      description: "Viết `resolveOrganizationContext` — preHandler hook tra ra tổ chức và role của user cho MỌI route đụng tới `projects`/`tasks`, dùng đúng 2 cách: đọc `:organizationId` từ URL, hoặc JOIN ngược từ resource.",
      steps: [
        "Tạo `src/plugins/authorization.ts`, decorate Fastify request bằng `organizationId: string` và `membershipRole: 'owner' | 'admin' | 'member'` (khởi tạo rỗng ở `onRequest`)",
        "Viết hàm `getMembership(db, userId, organizationId)` — truy vấn `memberships` theo `(user_id, organization_id)`, trả `null` nếu không có row",
        "Viết `resolveOrganizationFromParam`: dùng cho route có `:organizationId` trong path (`/api/v1/organizations/:organizationId/projects`) — lấy thẳng từ `request.params.organizationId`",
        "Viết `resolveOrganizationFromProjectId`: dùng cho `/api/v1/projects/:id` — query `SELECT organization_id FROM projects WHERE id = $1`; nếu không có row, trả `404` ngay (resource không tồn tại, chưa cần biết tổ chức nào)",
        "Viết `resolveOrganizationFromTaskId`: dùng cho `/api/v1/tasks/:id` — JOIN `tasks` với `projects` (`tasks.project_id = projects.id`) để lấy `organization_id`, vì bảng `tasks` không có cột này trực tiếp",
        "Cả 3 hàm trên đều gọi `getMembership` sau khi có `organizationId`; nếu không tìm thấy membership, trả `404` (chưa lộ việc resource thuộc tổ chức nào); nếu có, gán `request.organizationId` và `request.membershipRole` rồi `done()`",
      ],
    },
    {
      id: "require-role-guard-project-delete",
      title: "requireRole('admin') guard cho route xoá project",
      description: "Chặn `member` xoá project — chỉ `owner`/`admin` được phép — và đảm bảo câu lệnh DELETE thật sự lọc theo `organization_id`, không chỉ tin vào middleware.",
      steps: [
        "Viết factory `requireRole(...allowed: MembershipRole[])` trả về một preHandler hook: nếu `request.membershipRole` không nằm trong `allowed`, trả `403` với format lỗi chuẩn `{ error: { code: 'FORBIDDEN', message: '...' } }`",
        "Đăng ký chain hook cho `DELETE /api/v1/projects/:id`: `[authenticate, resolveOrganizationFromProjectId, requireRole('owner', 'admin')]` — đúng thứ tự, vì `requireRole` cần `request.membershipRole` đã được gán trước đó",
        "Sửa câu lệnh xoá trong handler từ `DELETE FROM projects WHERE id = $1` thành `DELETE FROM projects WHERE id = $1 AND organization_id = $2` (dùng `request.organizationId`) — phòng hờ ngay cả khi một middleware phía trước có bug",
        "Áp dụng lại đúng pattern cho `POST /api/v1/organizations/:organizationId/projects` (tạo project): chain `[authenticate, resolveOrganizationFromParam]`, không cần `requireRole` vì cả 3 role đều được tạo project theo curriculum",
        "Test thủ công bằng `curl`: đăng nhập user role `member`, gọi `DELETE /api/v1/projects/:id` của project trong tổ chức mình → xác nhận nhận `403`, không phải `500` hay xoá nhầm",
      ],
    },
    {
      id: "cross-tenant-idor-test",
      title: "Test IDOR: token tổ chức A không sửa được dữ liệu tổ chức B",
      description: "Viết test Vitest chứng minh cả hai lớp phòng thủ (thiếu membership → 404, đủ membership nhưng sai role → 403) hoạt động đúng, không chỉ 'nhìn có vẻ đúng'.",
      steps: [
        "Trong test setup, tạo 2 tổ chức A và B, mỗi tổ chức 1 project; tạo user `attacker` chỉ có membership (role `member`) trong tổ chức A, không có bất kỳ membership nào trong tổ chức B",
        "Test 1: đăng nhập `attacker`, lấy access token của tổ chức A, gọi `DELETE /api/v1/projects/:idProjectB` (project thuộc tổ chức B) — assert response `404`, và assert project B trong DB vẫn còn nguyên (chưa bị xoá)",
        "Test 2: thêm `attacker` làm `member` thật sự trong tổ chức B (khác kịch bản trên), gọi lại `DELETE /api/v1/projects/:idProjectB` — lần này assert `403` (khác `404` ở test 1, vì giờ có membership nhưng role không đủ)",
        "Test 3: nâng `attacker` lên role `admin` trong tổ chức B, gọi lại `DELETE /api/v1/projects/:idProjectB` — assert `200`/`204` và project thật sự bị xoá khỏi DB",
        "Chạy `pnpm test` — cả 3 test phải xanh; xoá thử điều kiện `AND organization_id = $2` ở lab trước để xác nhận test 1 chuyển sang đỏ (test thật sự bắt được lỗi, không phải test giả)",
      ],
    },
  ],
  deliverable:
    "`taskflow-api` có middleware `resolveOrganizationContext` (3 biến thể: từ param, từ project id, từ task id qua JOIN) và `requireRole(...roles)` áp dụng cho route xoá project; mọi câu lệnh SQL đụng tới `projects`/`tasks` theo id đều lọc kèm `organization_id`.",
  successCriteria:
    "Gọi API bằng token của tổ chức A để sửa/xoá dữ liệu tổ chức B luôn bị chặn (`404` nếu không có membership, `403` nếu có membership nhưng sai role) — không có endpoint nào truy vấn theo `id` mà thiếu điều kiện `organization_id`; `pnpm test` xanh cho cả 3 test IDOR.",
  resources: [
    { title: "OWASP Authorization Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html", kind: "doc" },
    { title: "OWASP Top 10 (2021) — A01: Broken Access Control", url: "https://owasp.org/Top10/A01_2021-Broken_Access_Control/", kind: "doc" },
    { title: "OWASP Insecure Direct Object Reference Prevention Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.html", kind: "doc" },
    { title: "PostgreSQL docs — Row Security Policies", url: "https://www.postgresql.org/docs/current/ddl-rowsecurity.html", kind: "doc" },
    { title: "Fastify docs — Hooks", url: "https://fastify.dev/docs/latest/Reference/Hooks/", kind: "doc" },
    { title: "MDN — 403 Forbidden", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403", kind: "doc" },
  ],
  quiz: [
    {
      id: "rbac-vs-abac-choice",
      question: "`taskflow-api` gắn quyền theo role cố định (`owner`/`admin`/`member`) trong `memberships` thay vì tính quyền từ nhiều thuộc tính (giờ trong ngày, thiết bị, độ tin cậy IP...). Đây là ví dụ của mô hình nào, và vì sao hợp lý ở giai đoạn này?",
      options: [
        "ABAC — vì role cũng là một thuộc tính",
        "RBAC — quyền gắn với một vai trò rời rạc, lưu sẵn trong DB, dễ kiểm tra bằng một câu `SELECT`; ABAC cần engine đánh giá policy phức tạp hơn mà `taskflow-api` chưa cần",
        "Không có mô hình nào áp dụng vì đây chỉ là kiểm tra `if/else` thông thường",
        "ACL (Access Control List) vì mỗi user có một danh sách quyền riêng",
      ],
      answerIndex: 1,
      explanation: "RBAC (Role-Based Access Control) gán quyền cho một vai trò cố định, rồi gán vai trò đó cho user — đúng với cột `role` trong `memberships`. ABAC linh hoạt hơn (đánh giá nhiều thuộc tính cùng lúc) nhưng phức tạp hơn nhiều, phù hợp khi RBAC không đủ diễn tả (ví dụ: 'chỉ được sửa task do chính mình tạo, giờ hành chính').",
    },
    {
      id: "membership-per-organization",
      question: "Một user là `owner` ở tổ chức A và `member` ở tổ chức B. Khi user này gọi `DELETE /api/v1/projects/:id` cho một project thuộc tổ chức B, `request.membershipRole` middleware gán vào là gì?",
      options: [
        "`owner`, vì đó là role cao nhất user từng có",
        "`member` — role được tra theo ĐÚNG cặp `(user_id, organization_id)` của project đang thao tác, không phải role cao nhất user có ở bất kỳ tổ chức nào",
        "Middleware sẽ báo lỗi vì user có 2 role khác nhau",
        "`admin`, vì đó là giá trị mặc định",
      ],
      answerIndex: 1,
      explanation: "Role không phải thuộc tính toàn cục của user — nó gắn với từng tổ chức qua khoá chính gộp `(user_id, organization_id)` của `memberships`. `resolveOrganizationContext` phải tra đúng organization_id của RESOURCE đang thao tác, không phải tổ chức nào user nhớ tới đầu tiên.",
    },
    {
      id: "task-route-needs-join",
      question: "Route `DELETE /api/v1/tasks/:id` không có `:organizationId` trong URL và bảng `tasks` cũng không có cột `organization_id`. Làm sao middleware biết task đó thuộc tổ chức nào?",
      options: [
        "Không cần biết — chỉ cần user đã đăng nhập là đủ",
        "JOIN `tasks` với `projects` qua `tasks.project_id = projects.id` để lấy `projects.organization_id`, rồi mới tra membership theo tổ chức đó",
        "Thêm `organization_id` trực tiếp vào JWT payload và tin luôn giá trị đó",
        "Gọi thêm một endpoint riêng để hỏi client tổ chức nào",
      ],
      answerIndex: 1,
      explanation: "`tasks` chỉ biết `project_id`; muốn ra `organization_id` phải đi qua bảng trung gian `projects`. Đây chính là lý do curriculum yêu cầu 'JOIN qua projects.organization_id khi route không có organizationId trực tiếp' — tin vào giá trị client tự khai (kể cả trong JWT) là sai vì JWT không tự cập nhật khi membership thay đổi.",
    },
    {
      id: "where-clause-vs-fetch-then-check",
      question: "Cách 1: `SELECT * FROM projects WHERE id = $1`, rồi code JS so sánh `project.organizationId === request.organizationId` trước khi xoá. Cách 2: `DELETE FROM projects WHERE id = $1 AND organization_id = $2` ngay trong câu lệnh. Vì sao cách 2 được khuyến nghị làm mặc định?",
      options: [
        "Cách 2 nhanh hơn vì Postgres cache câu lệnh",
        "Cách 1 sai hoàn toàn, không bao giờ dùng được",
        "Cách 2 đưa điều kiện lọc vào ngay tầng dữ liệu — không phụ thuộc việc lập trình viên có nhớ viết `if` kiểm tra ở MỌI nơi hay không; thiếu một chỗ kiểm tra ở cách 1 là đủ để lộ lỗi IDOR",
        "Cách 2 không cần transaction còn cách 1 thì cần",
      ],
      answerIndex: 2,
      explanation: "Cách 1 vẫn có thể đúng nếu làm cẩn thận, nhưng an toàn của nó phụ thuộc vào việc không quên `if` kiểm tra ở bất kỳ route nào — một điểm quên là một lỗ hổng. Đưa `organization_id` vào WHERE khiến việc 'quên' gần như không thể: nếu quên, câu lệnh không xoá được gì cả (row count = 0) thay vì xoá nhầm.",
    },
    {
      id: "404-vs-403-no-membership",
      question: "Attacker dùng token hợp lệ của tổ chức A gọi `DELETE /api/v1/projects/:id` cho project thuộc tổ chức B — attacker KHÔNG có bất kỳ membership nào trong tổ chức B. `taskflow-api` nên trả gì?",
      options: [
        "`403 Forbidden`, vì attacker đã đăng nhập nhưng không đủ quyền",
        "`404 Not Found` — vì với attacker, project đó coi như không tồn tại; trả `403` sẽ vô tình xác nhận resource CÓ tồn tại (chỉ là không có quyền), lộ thông tin không cần thiết",
        "`401 Unauthorized`, vì token không hợp lệ",
        "`200 OK` với body rỗng để tránh lộ thông tin",
      ],
      answerIndex: 1,
      explanation: "`403` xác nhận ngầm 'resource này tồn tại, chỉ là bạn không được phép' — với người hoàn toàn ngoài tổ chức, đó là rò rỉ thông tin không cần thiết (biết được id nào đó là hợp lệ). `404` an toàn hơn: coi như tài nguyên không tồn tại đối với người này.",
    },
    {
      id: "403-vs-404-has-membership-wrong-role",
      question: "Vẫn ví dụ trên, nhưng lần này attacker LÀ `member` thật sự trong tổ chức B (ví dụ cựu nhân viên chưa bị revoke), chỉ là role không đủ để xoá project. `requireRole('owner', 'admin')` nên trả gì?",
      options: [
        "`404`, giống hệt trường hợp không có membership",
        "`403 Forbidden` — người này đã được xác nhận có mặt trong tổ chức (không cần giấu sự tồn tại của project với chính thành viên tổ chức đó), chỉ là role hiện tại không đủ quyền thực hiện hành động",
        "`401`, vì token đã hết hiệu lực",
        "`204 No Content`, coi như đã xử lý xong",
      ],
      answerIndex: 1,
      explanation: "Khi đã xác nhận user CÓ membership hợp lệ trong đúng tổ chức, việc giấu sự tồn tại của project không còn ý nghĩa (họ là thành viên, có thể thấy nó qua `GET /projects` bình thường) — `403` mô tả đúng bản chất: xác thực rồi nhưng không đủ quyền cho hành động cụ thể.",
    },
    {
      id: "hook-order-matters",
      question: "Một dev đăng ký chain hook theo thứ tự `[requireRole('admin'), authenticate, resolveOrganizationFromProjectId]` cho route xoá project. Điều gì xảy ra?",
      options: [
        "Không sao, Fastify tự sắp xếp lại thứ tự hook cho đúng",
        "`requireRole` chạy trước khi `request.membershipRole` được gán (vì `resolveOrganizationFromProjectId` chưa chạy) — code sẽ đọc `undefined`, dẫn tới chặn nhầm mọi request hoặc lỗi runtime tuỳ cách viết điều kiện",
        "Request sẽ được xử lý nhanh hơn vì kiểm tra role trước",
        "Fastify sẽ trả lỗi cấu hình ngay khi khởi động server",
      ],
      answerIndex: 1,
      explanation: "preHandler hook chạy tuần tự theo đúng thứ tự đăng ký. `requireRole` phụ thuộc dữ liệu (`request.membershipRole`) do `resolveOrganizationFromProjectId` gán — đặt sai thứ tự là lỗi logic âm thầm, không phải lỗi cú pháp nên rất dễ bị bỏ sót khi review.",
    },
    {
      id: "row-level-security-mention",
      question: "PostgreSQL Row Security Policies (RLS) có thể tự động lọc `organization_id` ở TẦNG DATABASE cho mọi câu query, kể cả khi code quên viết điều kiện WHERE. Vì sao `taskflow-api` ở module này chỉ lọc ở tầng ứng dụng, chưa dùng RLS?",
      options: [
        "Vì Postgres không hỗ trợ RLS",
        "Vì RLS thêm một tầng cấu hình mới (policy, `SET app.current_org`) cần thiết lập và kiểm thử riêng — curriculum giới thiệu RLS như một lựa chọn nâng cao để tham khảo, không bắt buộc làm ngay khi lọc ở tầng ứng dụng đã đúng",
        "Vì RLS chỉ hoạt động với MySQL, không hoạt động với PostgreSQL",
        "Vì dùng RLS sẽ làm chậm mọi câu query gấp 10 lần",
      ],
      answerIndex: 1,
      explanation: "RLS là một lớp phòng thủ bổ sung mạnh (chặn được cả trường hợp code quên lọc), nhưng cần thiết lập policy đúng và một session variable báo tổ chức hiện tại cho mỗi kết nối — độ phức tạp vận hành tăng lên. Ở giai đoạn này, lọc đúng ở tầng ứng dụng (WHERE + JOIN) là đủ; RLS là hướng mở rộng khi cần phòng thủ theo chiều sâu.",
    },
    {
      id: "member-create-project-allowed",
      question: "Theo bảng quyền của module này, `member` có được phép tạo project mới trong tổ chức mình không?",
      options: [
        "Không, chỉ `owner`/`admin` được tạo project",
        "Có — curriculum chỉ yêu cầu chặn `member` ở hành động XOÁ project; tạo project không bị giới hạn theo role trong bài này",
        "Chỉ được tạo nếu có sự đồng ý của `owner` qua một bước duyệt riêng",
        "Không, vì `member` không có `organizationId` trong middleware",
      ],
      answerIndex: 1,
      explanation: "Bài học và lab tập trung vào việc chặn `member` xoá project (theo đúng mục tiêu curriculum) — route tạo project (`POST /organizations/:organizationId/projects`) chỉ cần `resolveOrganizationFromParam` để xác nhận có membership hợp lệ, không cần `requireRole` bổ sung.",
    },
    {
      id: "test-catches-regression",
      question: "Lab 3 yêu cầu cố tình xoá điều kiện `AND organization_id = $2` khỏi câu lệnh DELETE rồi chạy lại test. Mục đích của bước này là gì?",
      options: [
        "Chỉ để luyện thao tác git revert",
        "Chứng minh test thật sự PHÁT HIỆN được lỗi IDOR nếu nó xảy ra — nếu xoá điều kiện mà test vẫn xanh, nghĩa là test đó chỉ 'nhìn có vẻ đúng' chứ không kiểm tra được cái cần kiểm tra",
        "Để đo thời gian chạy test nhanh hơn bao nhiêu",
        "Vì Vitest yêu cầu phải có ít nhất một lần test đỏ trước khi merge",
      ],
      answerIndex: 1,
      explanation: "Một test coverage cao nhưng không đỏ khi cố tình đưa lỗi vào là test vô nghĩa (coverage giả). Đây là kỹ thuật kiểm tra chất lượng test: cố tình gây lỗi (mutation thủ công) và xác nhận bộ test bắt được — đúng tinh thần 'Test trước khi tự tin refactor' của cả course.",
    },
  ],
};
