import type { ModuleDefinition } from "@/content/content-types";

export const m05CicdGithubActionsModule: ModuleDefinition = {
  id: "m05",
  slug: "m05-cicd-github-actions",
  phaseId: "phase-1",
  order: 5,
  weeks: "Tuần 7–9",
  title: "CI/CD với GitHub Actions",
  emoji: "🔄",
  eli5Summary:
    "CI/CD giống dây chuyền nhà máy: mỗi thay đổi code tự động đi qua các trạm kiểm tra, được đóng gói thành thùng hàng chuẩn và giao tới server mà không cần ai khuân vác bằng tay. Module này dạy bạn dựng dây chuyền đó bằng GitHub Actions và kết thúc bằng việc tự động deploy app lên một VM thật.",
  objectives: [
    "Phân biệt Continuous Integration, Continuous Delivery và Continuous Deployment",
    "Đọc và viết workflow GitHub Actions: trigger, job, step, runner, needs, expression",
    "Xây pipeline lint → test → quét bảo mật → build image → scan → push, chặn merge khi đỏ",
    "Kết nối AWS bằng OIDC thay cho access key tĩnh; dùng environment có người duyệt",
    "Chọn chiến lược deploy (rolling, blue-green, canary) và chuẩn bị rollback",
    "Tăng tốc và chuẩn hoá pipeline bằng cache, matrix, reusable workflow và Dependabot",
  ],
  lessons: [
    { slug: "ci-cd-fundamentals", title: "CI vs Continuous Delivery vs Deployment", minutes: 35, summary: "Dây chuyền lắp ráp xe máy: kiểm tra liên tục, xe đậu sẵn chờ ký, hay tự lên xe tải." },
    { slug: "github-actions-anatomy", title: "Giải phẫu GitHub Actions", minutes: 45, summary: "Event, workflow, job, step, runner — bếp nhà hàng nhận order và chia việc cho các tổ." },
    { slug: "ci-pipeline-stages", title: "Pipeline chuẩn: lint → test → scan → build → push", minutes: 50, summary: "Các trạm kiểm tra nhà máy sữa: trạm rẻ đứng trước, trượt một trạm là bị gạt khỏi băng chuyền." },
    { slug: "secrets-environments-oidc", title: "Secrets, environments & OIDC tới AWS", minutes: 45, summary: "Vé vào cổng có ảnh, hết hạn sau 1 giờ thay cho chìa khoá copy sống mãi." },
    { slug: "deployment-strategies-rollback", title: "Chiến lược deploy & rollback", minutes: 50, summary: "Rolling, blue-green, canary, feature flag — và cách auto-deploy lên một VM cho Checkpoint 1." },
    { slug: "caching-matrix-reusable-workflows", title: "Cache, matrix & reusable workflow", minutes: 40, summary: "Nước mắm pha sẵn, nếm thử ở nhiều chi nhánh, sổ tay công thức chung cho cả chuỗi." },
  ],
  labs: [
    {
      id: "pr-ci-workflow",
      title: "Workflow CI cho Pull Request",
      description: "Lint + test + coverage report cho mọi PR, chặn merge khi pipeline đỏ.",
      steps: [
        "Tạo `.github/workflows/ci.yml` với trigger `pull_request` vào `main`, `permissions: contents: read`",
        "Job `lint-test`: `actions/checkout`, `actions/setup-node` với `cache: npm`, rồi `npm ci`, `npm run lint`, `npm test -- --coverage`",
        "Upload thư mục `coverage/` bằng `actions/upload-artifact` với `if: always()`",
        "Thêm `concurrency` với `cancel-in-progress: true` và `timeout-minutes` cho job",
        "Bật ruleset cho `main`: bắt buộc PR và required status check `lint-test`",
        "Mở một PR cố tình làm test fail, xác nhận nút Merge bị chặn; sửa test và thấy check chuyển xanh",
      ],
    },
    {
      id: "cd-build-scan-push",
      title: "Workflow CD: build → Trivy → push GHCR",
      description: "Khi merge `main`, build image, quét Trivy, push lên GHCR; tag semver khi tạo release.",
      steps: [
        "Tạo `.github/workflows/cd.yml` trigger `push` vào `main` và tag `v*.*.*`, `permissions: packages: write`",
        "Đăng nhập GHCR bằng `docker/login-action` với `secrets.GITHUB_TOKEN`",
        "Sinh tag bằng `docker/metadata-action`: `type=sha,prefix=sha-,format=long` và `type=semver,pattern={{version}}`",
        "Build với `docker/build-push-action` (`load: true`, `cache-from: type=gha`), quét bằng Trivy với `exit-code: 1` cho CRITICAL, rồi mới push",
        "Pin action bên thứ ba (Trivy) theo commit SHA đầy đủ",
        "Tạo release `git tag v1.0.0 && git push origin v1.0.0`, kiểm tra GHCR có tag `1.0.0` và `sha-...`",
        "Đo thời gian từ merge tới khi image xuất hiện trên GHCR — mục tiêu dưới 10 phút",
      ],
    },
    {
      id: "reusable-workflow",
      title: "Reusable workflow dùng chung cho nhiều service",
      description: "Tách bước build/scan/push thành một workflow `workflow_call` và gọi từ ít nhất hai service.",
      steps: [
        "Tạo repo (hoặc thư mục) `platform-workflows` chứa `.github/workflows/docker-build.yml` với `on: workflow_call`",
        "Khai báo `inputs` (`image-name`, `context`) và dùng chúng thay cho giá trị hard-code",
        "Gắn tag `v1` cho repo platform",
        "Trong 2 service, thay job build bằng `uses: <org>/platform-workflows/.github/workflows/docker-build.yml@v1` kèm `with:` và `permissions`",
        "Đổi mức severity Trivy trong reusable workflow, gắn `v1.1`, nâng một service lên `@v1.1` và xác nhận service kia vẫn chạy bản cũ",
      ],
    },
    {
      id: "dependabot-updates",
      title: "Tự động cập nhật dependency với Dependabot",
      description: "Để bot tự mở PR cập nhật npm package, base image Docker và GitHub Actions.",
      steps: [
        "Tạo `.github/dependabot.yml` với `version: 2` và ba ecosystem: `npm`, `docker`, `github-actions`",
        "Đặt `schedule.interval: weekly` và nhóm bản minor/patch của npm bằng `groups`",
        "Bật Dependabot alerts và security updates trong Settings → Code security",
        "Đợi (hoặc kích hoạt từ tab Insights → Dependency graph → Dependabot) PR đầu tiên, xác nhận CI tự chạy trên PR đó",
        "Review và merge một PR cập nhật; ghi lại trong README quy trình xử lý PR của bot",
      ],
    },
    {
      id: "checkpoint-1-auto-deploy-vm",
      title: "✅ Checkpoint 1: auto-deploy app mẫu lên một VM",
      description: "Merge vào `main` → pipeline build & push image → deploy lên EC2 t3.micro (hoặc VPS) chạy `docker compose`, có Nginx + HTTPS, healthcheck trước khi nhận traffic và hướng dẫn rollback.",
      steps: [
        "Tạo EC2 `t3.micro` Ubuntu LTS (hoặc VPS), cài Docker Engine + compose plugin bằng một script `bootstrap.sh` (hoặc user-data) để dựng lại được trên VM mới",
        "Gắn IAM instance profile có `AmazonSSMManagedInstanceCore`, xác nhận instance hiện trong `aws ssm describe-instance-information`; không mở port 22 ra Internet",
        "Cài Nginx làm reverse proxy tới `127.0.0.1:3000`, lấy chứng chỉ HTTPS bằng `certbot --nginx` cho domain của bạn",
        "Đặt `/opt/shop/compose.yaml` dùng `image: ghcr.io/<user>/<app>:${IMAGE_TAG}` có `healthcheck`, và `deploy.sh` chạy `docker compose pull` + `docker compose up -d --wait`, tự quay về tag trước nếu healthcheck fail",
        "Tạo IAM role OIDC cho repo (trust `sub` khớp `environment:production`), quyền tối thiểu `ssm:SendCommand` trên đúng instance",
        "Thêm job `deploy` (`needs` job build, `environment: production`, `permissions: id-token: write`) gọi `aws ssm send-command` chạy `deploy.sh sha-${{ github.sha }}` rồi `aws ssm wait command-executed`",
        "Merge một thay đổi nhỏ vào `main`, xác nhận `curl https://<domain>/healthz` trả 200 với version mới; thử deploy bản lỗi healthcheck để thấy tự rollback",
        "Viết README: sơ đồ kiến trúc, luồng pipeline, cách rollback thủ công về tag trước; tự đánh giá bằng cách dựng lại toàn bộ trên VM mới trong dưới 1 giờ",
      ],
    },
  ],
  deliverable:
    "Repo app mẫu có workflow CI cho PR, workflow CD build → Trivy → push GHCR (tag SHA + semver), reusable workflow, `dependabot.yml`, và Checkpoint 1: job deploy tự động lên VM qua OIDC + SSM kèm README (sơ đồ kiến trúc, cách rollback).",
  successCriteria:
    "Từ lúc merge đến lúc có image mới dưới 10 phút; không có secret hay access key nào hard-code; PR đỏ không merge được; merge `main` tự deploy lên VM qua HTTPS và rollback được về version trước; dựng lại toàn bộ trên VM mới trong dưới 1 giờ nhờ script.",
  resources: [
    { title: "GitHub Actions documentation", url: "https://docs.github.com/en/actions", kind: "doc" },
    { title: "Security hardening for GitHub Actions", url: "https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions", kind: "doc" },
    { title: "Configuring OpenID Connect in Amazon Web Services", url: "https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services", kind: "doc" },
    { title: "aws-actions/configure-aws-credentials", url: "https://github.com/aws-actions/configure-aws-credentials", kind: "tool" },
    { title: "Docker Docs — GitHub Actions", url: "https://docs.docker.com/build/ci/github-actions/", kind: "doc" },
    { title: "actionlint — lint workflow GitHub Actions", url: "https://github.com/rhysd/actionlint", kind: "tool" },
    { title: "Dependabot version updates", url: "https://docs.github.com/en/code-security/dependabot/dependabot-version-updates", kind: "doc" },
    { title: "DORA — capabilities & metrics", url: "https://dora.dev/", kind: "doc" },
  ],
  quiz: [
    {
      id: "delivery-vs-deployment",
      question: "Team muốn mọi commit qua test tự động là lên production ngay, không cần ai bấm duyệt. Đây là gì?",
      options: ["Continuous Integration", "Continuous Delivery", "Continuous Deployment", "Nightly build"],
      answerIndex: 2,
      explanation: "Xe qua kiểm định là tự lên xe tải giao đại lý, không cần quản lý ký: Continuous Deployment. Còn nút duyệt thì là Continuous Delivery.",
    },
    {
      id: "jobs-no-shared-files",
      question: "Job `build` tạo thư mục `dist/`, job `deploy` (needs: build) báo không tìm thấy `dist/`. Vì sao?",
      options: [
        "Mỗi job chạy trên runner riêng; phải truyền file bằng upload/download artifact",
        "Thiếu `permissions: contents: write`",
        "`needs` làm các job chạy song song",
        "GitHub tự xoá thư mục dist vì lý do bảo mật",
      ],
      answerIndex: 0,
      explanation: "Mỗi tổ bếp có gian bếp sạch riêng; muốn chuyển đồ phải gửi qua quầy trung chuyển (artifact).",
    },
    {
      id: "fast-checks-first",
      question: "Pipeline nào sắp xếp hợp lý nhất cho PR?",
      options: [
        "build image → push → lint → test",
        "deploy staging → test → lint",
        "test → push → lint → scan",
        "lint → unit test → SAST, và chỉ build/scan/push image sau khi merge",
      ],
      answerIndex: 3,
      explanation: "Trạm cân rẻ và nhanh đứng đầu băng chuyền để loại hàng lỗi sớm; đóng thùng và nhập kho chỉ làm với hàng đã đạt.",
    },
    {
      id: "scan-before-push",
      question: "Vì sao nên quét Trivy TRƯỚC khi push image lên registry?",
      options: [
        "Trivy không quét được image trên registry",
        "Để image có lỗ hổng CRITICAL không bao giờ nằm trên registry và không thể bị deploy nhầm",
        "Push trước làm build chậm hơn",
        "GHCR từ chối image chưa quét",
      ],
      answerIndex: 1,
      explanation: "Máy soi hành lý phải đứng trước cửa kho. Hàng cấm đã vào kho thì hệ thống giao hàng tự động có thể kéo đi mất.",
    },
    {
      id: "required-status-check",
      question: "Workflow CI đỏ nhưng mọi người vẫn bấm Merge được. Thiếu cấu hình gì?",
      options: [
        "Thêm `workflow_dispatch`",
        "Đổi runner sang self-hosted",
        "Ruleset/branch protection cho `main` với required status checks",
        "Thêm `continue-on-error: true`",
      ],
      answerIndex: 2,
      explanation: "Workflow chỉ bật đèn đỏ; phải có luật bảo vệ nhánh thì cánh cửa Merge mới thực sự khoá lại.",
    },
    {
      id: "oidc-id-token-permission",
      question: "Job dùng `aws-actions/configure-aws-credentials` với `role-to-assume` nhưng lỗi không lấy được credential. Workflow có `permissions: contents: read`. Thiếu gì?",
      options: ["`id-token: write`", "`packages: write`", "Secret `AWS_SECRET_ACCESS_KEY`", "`pull-requests: write`"],
      answerIndex: 0,
      explanation: "Không có quyền `id-token: write`, shipper không xin được vé có ảnh từ GitHub nên không có gì để đưa bảo vệ AWS soát.",
    },
    {
      id: "oidc-sub-condition",
      question: "Trust policy của role deploy chỉ kiểm tra `aud = sts.amazonaws.com`, không có điều kiện `sub`. Rủi ro là gì?",
      options: [
        "Không có rủi ro, aud là đủ",
        "Chỉ nhánh main mới dùng được",
        "Credential sống vĩnh viễn",
        "Workflow từ repo GitHub bất kỳ (kể cả của người lạ) cũng có thể assume role",
      ],
      answerIndex: 3,
      explanation: "Bảo vệ chỉ kiểm 'vé do công ty chuyển phát ký' mà không xem vé của đơn hàng nào: ai có vé GitHub cũng vào được kho.",
    },
    {
      id: "pin-third-party-action",
      question: "Cách an toàn nhất để dùng một action bên thứ ba trong workflow deploy production?",
      options: [
        "`uses: owner/action@main`",
        "`uses: owner/action@<commit-sha-đầy-đủ>` và để Dependabot cập nhật",
        "`uses: owner/action@latest`",
        "Copy action vào repo rồi không bao giờ cập nhật",
      ],
      answerIndex: 1,
      explanation: "Tag hay nhánh là nhãn dán có thể bị trỏ sang code khác (như sự cố tj-actions). Commit SHA là mã vạch cố định; bot giúp nâng cấp có kiểm soát.",
    },
    {
      id: "canary-blast-radius",
      question: "Bản mới có bug chỉ lộ ra với traffic thật. Chiến lược nào khiến ít người dùng bị ảnh hưởng nhất trước khi phát hiện?",
      options: ["Rolling update 50% mỗi đợt", "Blue-green chuyển 100%", "Canary 5% kèm theo dõi error rate", "Recreate: tắt hết bản cũ rồi bật bản mới"],
      answerIndex: 2,
      explanation: "Cho vài khách quen nếm nồi nước dùng mới trước: chỉ 5% gặp bug, và số liệu thật quyết định rút lại hay tăng tiếp.",
    },
    {
      id: "rollback-artifact",
      question: "Production lỗi sau deploy `sha-8a41d0c`. Cách rollback nhanh và an toàn nhất?",
      options: [
        "Deploy lại image `sha-` của bản chạy tốt trước đó",
        "`git revert`, đợi pipeline build lại image mới",
        "SSH vào server sửa code trực tiếp",
        "Build lại image từ commit cũ trên laptop rồi push",
      ],
      answerIndex: 0,
      explanation: "Thùng hàng cũ vẫn nằm nguyên trong kho với mã vạch riêng — lấy ra giao lại mất vài chục giây. Revert code để sửa lâu dài làm sau.",
    },
    {
      id: "cache-key-lockfile",
      question: "Cache npm dùng `key: deps-v1` cố định. Hậu quả dễ gặp nhất?",
      options: [
        "Workflow không chạy được",
        "Cache không bao giờ được làm mới khi package-lock.json đổi, CI chạy với dependency cũ",
        "Mỗi lần chạy đều cache miss",
        "GitHub tính phí gấp đôi",
      ],
      answerIndex: 1,
      explanation: "Nồi nước mắm phải gắn với công thức: key cần chứa `hashFiles` của lock file để đổi công thức thì pha nồi mới.",
    },
    {
      id: "reusable-workflow-vs-copy",
      question: "15 repo có workflow build/scan/push gần giống hệt nhau. Cách giảm công bảo trì tốt nhất?",
      options: [
        "Matrix 15 tổ hợp trong một repo",
        "Composite action chứa toàn bộ cả job deploy nhiều runner",
        "Viết script đồng bộ copy file sang 15 repo mỗi đêm",
        "Reusable workflow (`workflow_call`) ở repo platform, các repo gọi theo tag",
      ],
      answerIndex: 3,
      explanation: "Sổ tay công thức chung của cả chuỗi: sửa một chỗ, các chi nhánh nâng phiên bản sổ tay có kiểm soát.",
    },
  ],
};
