import type { ModuleDefinition } from "@/content/content-types";

export const b13GrpcInternalServicesModule: ModuleDefinition = {
  id: "b13",
  slug: "b13-grpc-internal-services",
  phaseId: "b-phase-3",
  order: 13,
  weeks: "Tuần 17",
  title: "gRPC & giao tiếp service nội bộ",
  emoji: "📡",
  eli5Summary:
    "Từ B09, `worker` vừa nấu vừa tự giao notification tận tay. Module này thuê một đội giao hàng riêng — `notification-service` — chỉ lo phần giao, gọi qua điện thoại nội bộ có biểu mẫu chuẩn (gRPC + `.proto`) thay vì hét vọng sang phòng bên.",
  objectives: [
    "Giải thích vì sao gRPC phù hợp cho giao tiếp nội bộ giữa hai service tự viết (contract qua `.proto`, HTTP/2, streaming) — và thừa nhận trung thực rằng tốc độ không phải lý do chính cho một cuộc gọi lẻ",
    "Phân biệt unary RPC và server-streaming RPC, biết khi nào dùng loại nào",
    "Viết `.proto` định nghĩa service + message, hiểu vì sao field NUMBER (không phải tên) mới là thứ nằm trên wire",
    "Dựng một gRPC server (`notification-service`) bằng `@grpc/grpc-js` + `@grpc/proto-loader`, và một client gọi từ `worker`",
    "Tiến hoá `.proto` an toàn: thêm field mới không phá client cũ, và nhận diện thay đổi thật sự phá vỡ (đổi kiểu, tái sử dụng field number)",
    "Nêu rõ và bảo vệ được một quyết định data ownership khi tách service (ai giữ bảng `notifications`, ai chỉ lo side effect gửi đi)",
  ],
  lessons: [
    {
      slug: "vi-sao-can-grpc-cho-service-noi-bo",
      title: "Vì sao cần gRPC cho service nội bộ",
      minutes: 30,
      summary: "So sánh REST/JSON vs gRPC/Protobuf cho cuộc gọi nội bộ `worker → notification-service` — giá trị thật nằm ở contract, không phải tốc độ.",
    },
    {
      slug: "unary-va-streaming-rpc",
      title: "Unary vs streaming RPC & viết notification.proto",
      minutes: 40,
      summary: "Định nghĩa `NotificationService` với `SendNotification` (unary) và `StreamNotifications` (server-streaming) trong `notification.proto`.",
    },
    {
      slug: "dung-notification-service-va-goi-tu-worker",
      title: "Dựng notification-service & đổi worker gọi qua gRPC",
      minutes: 50,
      summary: "Scaffold service Node riêng implement `NotificationService`, quyết định data ownership, và đổi `worker` gọi `SendNotification` qua gRPC.",
    },
    {
      slug: "tien-hoa-proto-an-toan-va-so-sanh-voi-rest",
      title: "Tiến hoá `.proto` an toàn & so sánh với REST",
      minutes: 35,
      summary: "Quy tắc field-numbering: thêm field mới an toàn, thay đổi nào thực sự phá vỡ — và đúc kết khi nào chọn gRPC, khi nào giữ REST nội bộ.",
    },
  ],
  labs: [
    {
      id: "viet-proto-va-dung-notification-service",
      title: "Viết `notification.proto` & dựng `notification-service`",
      description: "Định nghĩa contract gRPC cho `NotificationService` và scaffold service Node riêng implement nó, thêm vào `docker-compose.yml` theo đúng mục 3 curriculum.",
      steps: [
        "Tạo `notification-service/proto/notification.proto` định nghĩa `service NotificationService` với `rpc SendNotification (SendNotificationRequest) returns (SendNotificationResponse)` (unary) và `rpc StreamNotifications (StreamNotificationsRequest) returns (stream Notification)` (server-streaming), field number bắt đầu từ `1`, không nhảy số tuỳ tiện",
        "Khởi tạo `notification-service/package.json` riêng (không dùng chung `node_modules` với `api`), cài `@grpc/grpc-js` và `@grpc/proto-loader`",
        "Viết `notification-service/src/server.ts`: load `.proto` bằng `protoLoader.loadSync(...)`, implement `SendNotification` (log giả lập gửi đi, trả `{ delivered: true, delivery_id }`) và `StreamNotifications` (demo `call.write(...)` rồi `call.end()`), bind server vào `0.0.0.0:50051`",
        "Viết `notification-service/Dockerfile` base `node:22-slim`, `EXPOSE 50051`",
        "Thêm service `notification-service` vào `docker-compose.yml` (copy verbatim mục 3 curriculum): `build: ./notification-service`, `ports: [\"50051:50051\"]` — KHÔNG khai báo `DATABASE_URL` (quyết định data ownership: service này không kết nối Postgres)",
        "Chạy `docker compose up -d --build notification-service`, xác nhận log `gRPC server listening on :50051`",
      ],
    },
    {
      id: "doi-worker-goi-grpc-thay-vi-ghi-truc-tiep",
      title: "Đổi `worker` gọi `SendNotification` qua gRPC",
      description: "`worker` (B09) vẫn ghi bảng `notifications`, nhưng phần side effect 'gửi đi' chuyển từ code trực tiếp sang gọi gRPC tới `notification-service`.",
      steps: [
        "Thêm `NOTIFICATION_SERVICE_URL=notification-service:50051` vào biến môi trường của service `worker` trong `docker-compose.yml`",
        "Viết `src/grpc/notification-client.ts`: load cùng file `.proto`, tạo `client = new notificationProto.NotificationService(env.NOTIFICATION_SERVICE_URL, grpc.credentials.createInsecure())`, export hàm `sendNotification(input)` trả `Promise`, có set `deadline` 3 giây cho mỗi call",
        "Sửa `src/worker.ts`: sau khi transaction `INSERT notifications` (giữ nguyên như B09) commit thành công, gọi `await sendNotification({...})` với dữ liệu vừa insert — KHÔNG gọi gRPC bên trong transaction Postgres",
        "Nếu `sendNotification` throw lỗi, để lỗi đó propagate ra khỏi job processor — BullMQ tự retry theo cấu hình `attempts`/`backoff` đã có từ B09, không tự viết thêm cơ chế rollback bảng `notifications`",
        "Chạy `docker compose up -d --build worker notification-service`, đổi trạng thái 1 task thật (`PATCH /api/v1/tasks/:id`), xác nhận `docker compose logs notification-service` in đúng dòng log 'delivering ...' tương ứng",
      ],
    },
    {
      id: "tien-hoa-proto-them-field-backward-compatible",
      title: "Tiến hoá `.proto`: thêm field không phá client cũ",
      description: "Thêm `optional string priority = 5;` vào `SendNotificationRequest` và chứng minh việc deploy lệch version giữa `notification-service` và `worker` không làm vỡ giao tiếp.",
      steps: [
        "Thêm `optional string priority = 5;` vào cuối `SendNotificationRequest` trong `notification.proto` — không đổi, không xoá bất kỳ field number nào đã có (1–4)",
        "Deploy lại `notification-service` trước (`docker compose up -d --build notification-service`) trong khi `worker` (client) vẫn đang chạy code cũ, chưa biết field `priority`",
        "Đổi 1 task status để kích hoạt request thật từ `worker` (client cũ) tới `notification-service` (server mới), xác nhận `docker compose logs notification-service` KHÔNG có lỗi decode nào dù request thiếu field `5`",
        "Cập nhật `notification-client.ts` để bắt đầu gửi kèm `priority`, deploy lại `worker` sau (`docker compose up -d --build worker`) — xác nhận không cần deploy đồng thời hai service",
        "Viết lại đoạn giải thích ngắn (dạng comment hoặc trong `learnings.md` của module) nêu rõ: nếu sau này cần xoá `payload_json` (field `4`), phải khai `reserved 4; reserved \"payload_json\";` — không bao giờ tái sử dụng số `4` cho field khác",
      ],
    },
  ],
  deliverable:
    "`taskflow-api` có service `notification-service` (gRPC, cổng `50051`, không kết nối Postgres) chạy độc lập với `api`/`worker`; `worker` gọi `SendNotification` qua gRPC thay vì tự thực hiện side effect gửi đi, trong khi vẫn giữ quyền ghi bảng `notifications`; `.proto` đã qua một lần tiến hoá backward-compatible (thêm field `priority`) mà không cần deploy đồng thời hai service.",
  successCriteria:
    "`docker compose up -d` chạy đủ `api`, `worker`, `notification-service` như 3 process riêng, giao tiếp `worker → notification-service` qua gRPC quan sát được trong log; đổi `.proto` thêm field mới không làm `notification-service` lỗi khi nhận request từ `worker` chưa cập nhật (và ngược lại); có thể giải thích rõ vì sao `notification-service` chưa có DB riêng ở module này.",
  resources: [
    { title: "grpc.io — Node.js Quickstart", url: "https://grpc.io/docs/languages/node/quickstart/", kind: "doc" },
    { title: "grpc.io — Basics concepts (unary, streaming)", url: "https://grpc.io/docs/what-is-grpc/core-concepts/", kind: "doc" },
    { title: "Protocol Buffers — Proto3 Language Guide", url: "https://protobuf.dev/programming-guides/proto3/", kind: "doc" },
    { title: "@grpc/grpc-js (npm)", url: "https://www.npmjs.com/package/@grpc/grpc-js", kind: "tool" },
    { title: "@grpc/proto-loader (npm)", url: "https://www.npmjs.com/package/@grpc/proto-loader", kind: "tool" },
    { title: "grpc/grpc-node (GitHub)", url: "https://github.com/grpc/grpc-node", kind: "tool" },
  ],
  quiz: [
    {
      id: "ly-do-chinh-chon-grpc-noi-bo",
      question: "Lý do THUYẾT PHỤC NHẤT để `taskflow-api` chuyển giao tiếp `worker → notification-service` sang gRPC (thay vì lý do 'gRPC luôn nhanh hơn REST') là gì?",
      options: [
        "gRPC bắt buộc dùng ít băng thông hơn REST trong mọi trường hợp",
        "Contract rõ ràng qua `.proto` + sinh code tự động + streaming có sẵn qua HTTP/2 — không phải vì chênh lệch tốc độ ở một cuộc gọi lẻ",
        "REST/JSON không thể dùng cho giao tiếp giữa hai service nội bộ",
        "gRPC không cần cấu hình gì, tự động hoạt động ngay khi cài đặt",
      ],
      answerIndex: 1,
      explanation: "Với một cuộc gọi nội bộ đơn lẻ trong cùng hạ tầng, chênh lệch tốc độ REST/JSON vs gRPC/Protobuf thường không đáng kể. Giá trị thật nằm ở việc `.proto` ép buộc cả hai phía tuân theo cùng một contract, cộng với tooling sinh code và mô hình streaming built-in.",
    },
    {
      id: "field-number-vs-ten-field",
      question: "Trong `string user_id = 2;`, con số `2` có ý nghĩa gì?",
      options: [
        "Giá trị mặc định của `user_id` là số 2",
        "Vị trí dòng thứ 2 trong file `.proto`",
        "Field number — con số THẬT SỰ được mã hoá lên wire để định danh field này, độc lập với tên `user_id` hay vị trí khai báo",
        "Số byte tối đa mà field này được phép chiếm",
      ],
      answerIndex: 2,
      explanation: "Field number là thứ Protobuf dùng để mã hoá/giải mã trên wire — đổi tên field hay đổi thứ tự dòng không ảnh hưởng gì, nhưng đổi số này (hoặc tái sử dụng số đã xoá) sẽ phá vỡ khả năng đọc dữ liệu giữa các version.",
    },
    {
      id: "unary-vs-server-streaming-shape",
      question: "`SendNotification` là unary, `StreamNotifications` là server-streaming. Khác biệt cốt lõi giữa hai loại RPC này là gì?",
      options: [
        "Unary chạy nhanh hơn streaming trong mọi trường hợp",
        "Unary trả đúng 1 response rồi kết thúc; server-streaming giữ kết nối mở để server đẩy nhiều response theo thời gian sau 1 request duy nhất từ client",
        "Server-streaming bắt buộc phải mã hoá TLS, unary thì không",
        "Unary chỉ dùng được cho request GET, server-streaming chỉ dùng được cho POST",
      ],
      answerIndex: 1,
      explanation: "Đây là khác biệt về HÌNH DẠNG giao tiếp: unary giống gọi hàm bình thường (1-1), server-streaming giữ 1 connection mở để server chủ động đẩy nhiều message — không liên quan gì tới TLS hay HTTP method.",
    },
    {
      id: "quyet-dinh-data-ownership-b13",
      question: "Ở B13, `notification-service` có kết nối Postgres riêng để đọc/ghi bảng `notifications` không?",
      options: [
        "Có — mỗi service tách ra đều phải có DB riêng ngay lập tức",
        "Không — `worker` vẫn là chủ sở hữu duy nhất của bảng `notifications`; `notification-service` chỉ nhận dữ liệu qua gRPC và chịu trách nhiệm side effect gửi đi, việc tách DB riêng được để lại cho B14 cùng với outbox pattern",
        "Có, nhưng chỉ được phép đọc (read-only), không được ghi",
        "Không cố định — tài liệu để tuỳ ý author chọn mà không cần nêu lý do",
      ],
      answerIndex: 1,
      explanation: "B13 cố tình giới hạn phạm vi ở việc tách GIAO TIẾP (gọi hàm trực tiếp → gRPC). Tách quyền sở hữu dữ liệu là nội dung được dạy có chủ đích ở B14, đi cùng outbox pattern — nhét cả hai vào B13 sẽ làm module quá tải và trùng lặp nội dung với B14.",
    },
    {
      id: "them-field-optional-co-pha-vo-khong",
      question: "Thêm `optional string priority = 5;` vào `SendNotificationRequest` (chưa từng dùng số `5` trước đó) có làm vỡ `worker` (client) đang chạy code cũ, chưa biết field này, không?",
      options: [
        "Có, vì `worker` sẽ nhận lỗi 'unknown field' ngay khi gọi",
        "Không — client cũ đơn giản là không gửi/không biết field `5`; server đọc field đó ở giá trị mặc định. Đây chính là ví dụ kinh điển của thay đổi backward-compatible",
        "Có, vì mọi thay đổi `.proto` đều yêu cầu deploy lại toàn bộ client cùng lúc",
        "Không xác định được nếu chưa chạy `protoc` để generate lại code",
      ],
      answerIndex: 1,
      explanation: "Thêm field mới với number chưa từng dùng là thay đổi an toàn kinh điển trong Protobuf: bên không biết field đó vẫn hoạt động bình thường, chỉ đơn giản là không gửi/không đọc field đó.",
    },
    {
      id: "thay-doi-thuc-su-pha-vo",
      question: "Thay đổi nào dưới đây THỰC SỰ có nguy cơ phá vỡ giao tiếp giữa `worker` và `notification-service` nếu hai bên chạy lệch version tạm thời?",
      options: [
        "Đổi tên field `user_id` thành `userId` trong file `.proto` nhưng giữ nguyên field number `2`",
        "Thêm field mới `string priority = 6;` với số chưa từng dùng",
        "Xoá field `type = 3` rồi sau đó dùng lại đúng số `3` cho một field kiểu `int32` khác, không khai `reserved`",
        "Thêm một RPC method mới vào `service NotificationService` mà không đổi field nào trong message hiện có",
      ],
      answerIndex: 2,
      explanation: "Tái sử dụng field number đã xoá cho một field có Ý NGHĨA và KIỂU DỮ LIỆU khác là thay đổi phá vỡ kinh điển: bên còn dùng version cũ sẽ gửi/đọc dữ liệu sai kiểu tại đúng vị trí đó. Đổi tên field, thêm field mới, hay thêm RPC method đều an toàn.",
    },
    {
      id: "grpc-call-nam-trong-hay-ngoai-transaction",
      question: "Trong `worker`, lệnh `await sendNotification(...)` (gọi gRPC tới `notification-service`) nên đặt ở đâu so với `db.transaction(...)` ghi bảng `notifications`?",
      options: [
        "Bên trong transaction, trước khi commit — để đảm bảo cả hai cùng thành công hoặc cùng thất bại",
        "Sau khi transaction Postgres đã commit thành công — vì gRPC call không phải một phần của transaction database, và Postgres không thể rollback một side effect mạng đã gửi đi",
        "Không quan trọng, đặt đâu cũng được vì BullMQ tự đồng bộ cả hai",
        "Phải chạy song song (`Promise.all`) với transaction để tiết kiệm thời gian",
      ],
      answerIndex: 1,
      explanation: "Một transaction Postgres chỉ kiểm soát được các thao tác trên chính Postgres. Gọi gRPC là một side effect ra bên ngoài — không thể 'rollback' một request mạng đã gửi. Đặt gRPC call sau khi transaction commit là đúng, và nếu nó lỗi thì để BullMQ retry đúng job (chấp nhận rủi ro at-least-once, giống bài học retry ở B09).",
    },
    {
      id: "vi-sao-can-deadline",
      question: "Vì sao lab yêu cầu set `deadline` (ví dụ 3 giây) cho mỗi lệnh gọi `SendNotification` từ `worker`?",
      options: [
        "Để tiết kiệm băng thông mạng",
        "Vì gRPC bắt buộc phải có deadline mới compile được",
        "Nếu `notification-service` treo (chậm nhưng chưa lỗi hẳn), không có deadline khiến `worker` có thể chờ vô thời hạn, chiếm giữ tài nguyên xử lý job trong khi các job khác vẫn phải đợi",
        "Deadline giúp `notification-service` tự động khởi động lại khi quá giờ",
      ],
      answerIndex: 2,
      explanation: "Deadline là cơ chế phòng thủ chuẩn cho mọi lệnh gọi mạng đồng bộ: giới hạn thời gian chờ tối đa để tránh một dependency chậm/treo kéo theo toàn bộ hệ thống gọi nó bị nghẽn theo.",
    },
    {
      id: "so-sanh-rest-vs-grpc-khi-nao-giu-rest",
      question: "Route công khai `/api/v1/tasks` mà app di động của `taskflow-api` gọi trực tiếp có nên đổi sang gRPC theo tinh thần module này không?",
      options: [
        "Có, vì toàn bộ hệ thống nên nhất quán dùng một giao thức duy nhất",
        "Không — gRPC phù hợp cho giao tiếp NỘI BỘ giữa các service tự viết (như `worker` ↔ `notification-service`); route công khai cho browser/app di động nên giữ REST/JSON vì gọi thẳng từ browser cần thêm lớp trung gian (grpc-web/gateway) mới dùng được gRPC",
        "Có, vì gRPC luôn bảo mật hơn REST",
        "Không quan trọng, cả hai route đều phải dùng cùng lúc cả REST lẫn gRPC",
      ],
      answerIndex: 1,
      explanation: "Ranh giới hợp lý: gRPC cho giao tiếp service-to-service nội bộ, REST/JSON cho API công khai mà client bên ngoài (browser, app di động) gọi trực tiếp — vì gọi gRPC thẳng từ browser cần thêm hạ tầng trung gian không có sẵn.",
    },
    {
      id: "notification-service-khong-co-database-url",
      question: "Trong `docker-compose.yml`, vì sao service `notification-service` KHÔNG có biến môi trường `DATABASE_URL` như `api`/`worker`?",
      options: [
        "Vì `node:22-slim` không hỗ trợ kết nối Postgres",
        "Vì đó là lỗi cấu hình cần sửa ngay",
        "Vì theo quyết định data ownership của module này, `notification-service` không đọc/ghi trực tiếp Postgres — nó chỉ nhận dữ liệu qua gRPC và lo phần side effect gửi đi, còn `worker` vẫn là chủ sở hữu bảng `notifications`",
        "Vì `DATABASE_URL` chỉ cần khai báo một lần cho toàn bộ `docker-compose.yml`, không cần lặp lại ở từng service",
      ],
      answerIndex: 2,
      explanation: "Đây là hệ quả trực tiếp của quyết định thiết kế đã nêu trong lesson 3: `notification-service` cố tình không có quyền truy cập Postgres ở B13, để giữ đúng phạm vi 'tách giao tiếp' và dành việc 'tách dữ liệu' cho B14.",
    },
  ],
};
