import type { ModuleDefinition } from "@/content/content-types";

export const sd16CaseChatPresenceModule: ModuleDefinition = {
  id: "sd16",
  slug: "sd16-case-chat-presence",
  phaseId: "sd-phase-4",
  order: 16,
  weeks: "Tuần 20",
  title: "Case: Chat & presence",
  emoji: "💬",
  eli5Summary:
    "Chat 1-1 và group giống một tổng đài bưu điện giữ hàng triệu đường dây điện thoại mở cùng lúc: mỗi khách nối vào đúng một tổng đài viên (instance), nhưng tổng đài viên A phải gọi được cho khách đang đứng ở bàn của tổng đài viên B. Module này thiết kế trọn hệ thống chat realtime nhiều server: ai giữ đường dây, tin nhắn ghi vào sổ nào để không lẫn thứ tự, khách tắt máy thì tin nhắn chờ ở đâu, và làm sao báo 'đang online' mà không hét vào tai cả toà nhà mỗi giây.",
  objectives: [
    "Áp dụng framework SD01 để làm rõ requirements và ước lượng quy mô cho một hệ thống chat 1-1 + group",
    "Giải thích vì sao WebSocket là kết nối có state, và thiết kế cách route tin nhắn tới đúng instance đang giữ kết nối của người nhận (registry lookup hoặc fan-out qua pub/sub)",
    "Thiết kế thứ tự tin nhắn bằng sequence number theo từng conversation (không phải thứ tự toàn cục) và data model lưu trữ có shard theo conversation",
    "Thiết kế đường đi cho tin nhắn khi người nhận offline hoặc dùng nhiều thiết bị: inbox bền vững, push notification fallback, fetch-on-reconnect",
    "Thiết kế presence (heartbeat + TTL) có debouncing/coalescing để không fan-out mọi nhịp tim tới mọi liên hệ",
    "Dựng prototype WebSocket 2 instance sau Nginx dùng Redis pub/sub để relay tin nhắn cross-instance, và viết design doc theo Phụ lục A",
  ],
  lessons: [
    {
      slug: "yeu-cau-uoc-luong-api-chat",
      title: "Yêu cầu, ước lượng & API cho hệ thống chat",
      minutes: 45,
      summary: "Trước khi vẽ box nào, trả lời: 1-1 hay group, bao nhiêu người online cùng lúc, và ai chịu được mất tin nhắn.",
    },
    {
      slug: "websocket-gateway-nhieu-instance-redis-pubsub",
      title: "WebSocket gateway nhiều instance & Redis pub/sub",
      minutes: 55,
      summary: "Kết nối là state — route tin nhắn cross-instance bằng registry lookup hoặc fan-out pub/sub, mỗi cách một cái giá.",
    },
    {
      slug: "thu-tu-tin-nhan-luu-tru-offline-da-thiet-bi",
      title: "Thứ tự tin nhắn, lưu trữ & offline/đa thiết bị",
      minutes: 55,
      summary: "Sequence theo từng conversation, shard theo conversation_id, và inbox bền vững khi người nhận đang tắt máy.",
    },
    {
      slug: "presence-heartbeat-ttl-tradeoff",
      title: "Presence: heartbeat, TTL & trade-off khi mở rộng",
      minutes: 40,
      summary: "Online/away/offline bằng heartbeat + TTL, coalescing để không hét vào tai cả toà nhà, và bảng trade-off tổng kết.",
    },
  ],
  labs: [
    {
      id: "websocket-two-instance-redis-relay",
      title: "Chat WebSocket 2 instance sau Nginx, relay qua Redis pub/sub",
      description:
        "Dựng gateway chat trong `sd-playground`: 2 replica của `app` (Fastify + `@fastify/websocket`) sau Nginx, route tin nhắn cross-instance bằng Redis pub/sub, rồi kill 1 instance và kiểm tra client reconnect không mất tin.",
      steps: [
        "Thêm `@fastify/websocket` vào `app`; route `GET /ws?userId=<id>` nâng cấp lên WebSocket và lưu kết nối vào `Map<string, WebSocket>` cục bộ của instance đó",
        "Tạo 2 kết nối `ioredis` riêng (publisher và subscriber — một connection ở chế độ `SUBSCRIBE` không thể chạy lệnh khác); subscribe channel `chat:relay` lúc app khởi động",
        "Route `POST /conversations/:id/messages`: ghi tin nhắn vào Postgres với `seq` tăng dần theo `conversation_id` (xem lesson 3), rồi `redis.publish(\"chat:relay\", JSON.stringify({ conversationId, recipientId, message }))`",
        "Handler subscribe: nhận message từ Redis, tra `Map` cục bộ — có `recipientId` thì `ws.send(...)`, không có thì bỏ qua (instance khác sẽ tự lo)",
        "Sửa `nginx/default.conf`: `proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection \"upgrade\";` cho location `/ws`; chạy `docker compose up -d --build --scale app=2` rồi `docker compose exec nginx nginx -s reload`",
        "Mở 2 client WebSocket (script Node dùng thư viện `ws`, hoặc `websocat wss://localhost:8080/ws?userId=alice`) — thử vài lần tới khi 2 client rơi vào 2 instance khác nhau (log `X-Upstream` hoặc `process.env.HOSTNAME`); gửi tin từ alice, xác nhận bob nhận được dù khác instance",
        "`docker compose kill <container-app-2>` giữa lúc chat; xác nhận client của bob tự reconnect (thư viện `ws` client có `reconnecting-websocket` hoặc vòng lặp `setTimeout` retry) và gọi `GET /conversations/:id/messages?afterSeq=` để lấy nốt tin nhắn đã gửi lúc mất kết nối",
      ],
    },
    {
      id: "presence-heartbeat-ttl-latency",
      title: "Presence bằng heartbeat + Redis TTL",
      description: "Đo độ trễ từ lúc client ngừng gửi heartbeat tới lúc hệ thống coi user là offline, và kiểm tra coalescing không spam mỗi nhịp tim.",
      steps: [
        "Client gửi WebSocket message `{ type: \"heartbeat\" }` mỗi 15 giây; server `SET presence:<userId> online EX 30 NX` — không cần lệnh riêng, tận dụng luôn kết nối WS đang mở",
        "Khi TTL hết hạn, Redis tự xoá key; bật keyspace notification (`notify-keyspace-events Ex` trong `redis.conf`) và subscribe `__keyevent@0__:expired` để phát hiện chuyển sang offline mà không cần polling liên tục",
        "Chỉ publish sự kiện `presence-changed` cho danh sách liên hệ khi trạng thái *thực sự đổi* (debounce ví dụ 5 giây) — không publish ở mỗi heartbeat 15 giây",
        "Viết script đo: dừng heartbeat của một client tại `t0`, poll `GET /presence/:userId` mỗi giây, ghi thời điểm chuyển từ `online` sang `offline` — so với TTL 30s cấu hình",
        "Giả lập mạng chập chờn: client connect/disconnect 5 lần trong 3 giây (dùng Toxiproxy cắt kết nối); đếm số sự kiện `presence-changed` được publish — phải ít hơn nhiều so với 5 (nhờ debounce), không fan-out từng lần chớp tắt",
      ],
    },
    {
      id: "chat-design-doc-whatsapp-scale",
      title: "Design doc: chat 1-1 + group kiểu WhatsApp, 1 tỷ user",
      description: "Viết design doc đầy đủ theo template Phụ lục A cho hệ thống chat 1-1 và group ở quy mô 1 tỷ user đăng ký, bấm giờ 45–60 phút trước khi so với bài tham khảo.",
      steps: [
        "Mục 1–2: viết functional (1-1, group tối đa ~256 thành viên, delivery/read receipt, offline sync) + non-functional (latency gửi-nhận p99, không mất tin nhắn, thứ tự đúng trong 1 conversation) và ước lượng DAU/QPS/storage 5 năm (nêu rõ giả định, làm tròn theo Phụ lục B)",
        "Mục 3–4: thiết kế API (`POST /conversations/:id/messages`, `GET .../messages?afterSeq=`, WebSocket `/ws`) và chọn data model — vì sao bảng `messages` nên shard theo `conversation_id` thay vì `user_id` hay theo thời gian",
        "Mục 5: vẽ high-level design (client → LB/Nginx → WebSocket gateway → connection registry/pub/sub → message store → push service); mô tả bằng văn bản đủ để người khác vẽ lại được",
        "Mục 6: chọn 2–3 deep dive khó nhất — ví dụ 'route tin nhắn cross-instance', 'đảm bảo thứ tự khi client offline rồi reconnect', 'group 256 người thì fan-out presence thế nào' — mỗi mục có ít nhất một con số hoặc phép so sánh chi phí",
        "Mục 7–8: bảng trade-off (registry lookup vs pub/sub fan-out, SQL sharded vs wide-column) và bottleneck/failure mode (một node Redis pub/sub chết thì sao, connection registry lệch dữ liệu thì sao)",
      ],
    },
  ],
  deliverable:
    "Prototype `sd-playground` chạy 2 replica WebSocket sau Nginx, relay tin nhắn cross-instance qua Redis pub/sub, sống sót khi kill 1 instance; demo presence heartbeat + TTL có debounce; design doc chat 1-1/group 1 tỷ user theo Phụ lục A.",
  successCriteria: "Tin nhắn không mất và đúng thứ tự trong một conversation khi client reconnect; giải thích được vì sao presence không thể fan-out mỗi heartbeat tới toàn bộ danh sách liên hệ.",
  resources: [
    { title: "System Design Interview Vol. 1 (Alex Xu) — chat system, ByteByteGo", url: "https://bytebytego.com/", kind: "book" },
    { title: "Hello Interview — System Design breakdowns", url: "https://www.hellointerview.com/", kind: "course" },
    { title: "Discord Engineering — How Discord Stores Billions of Messages", url: "https://discord.com/blog/how-discord-stores-billions-of-messages", kind: "doc" },
    { title: "The System Design Primer (donnemartin, GitHub)", url: "https://github.com/donnemartin/system-design-primer", kind: "course" },
    { title: "Redis docs — Pub/Sub", url: "https://redis.io/docs/latest/develop/interact/pubsub/", kind: "doc" },
    { title: "Redis docs — Keyspace notifications", url: "https://redis.io/docs/latest/develop/use/keyspace-notifications/", kind: "doc" },
    { title: "fastify/fastify-websocket", url: "https://github.com/fastify/fastify-websocket", kind: "tool" },
    { title: "nginx docs — WebSocket proxying", url: "https://nginx.org/en/docs/http/websocket.html", kind: "doc" },
  ],
  quiz: [
    {
      id: "websocket-stateful-lb",
      question: "Load balancer round-robin trước 4 instance WebSocket gateway. User A đang nối vào instance 2 thì Nginx bị reload và route lại request tiếp theo sang instance 3. Chuyện gì xảy ra với kết nối WebSocket đang mở của A?",
      options: [
        "Không sao, WebSocket tự động 'nhảy' sang instance 3 vì cùng một load balancer",
        "Kết nối TCP hiện tại của A ở instance 2 không đổi — WebSocket là kết nối lâu dài, việc LB route request *mới* không ảnh hưởng tới connection đang mở",
        "A sẽ nhận tin nhắn từ cả 2 instance cùng lúc",
        "A bị ngắt kết nối ngay lập tức vì round-robin không hỗ trợ WebSocket",
      ],
      answerIndex: 1,
      explanation: "WebSocket là một kết nối TCP dài đã 'chốt' vào một instance cụ thể sau bước Upgrade — giống một cuộc gọi điện thoại đã nối máy, không phải mỗi câu nói là một cuộc gọi mới. Vấn đề route lại chỉ xảy ra khi A cần *kết nối mới* (reconnect); lúc đó A có thể rơi vào bất kỳ instance nào, kể cả instance không giữ dữ liệu cũ của A trong RAM.",
    },
    {
      id: "cross-instance-delivery",
      question: "Alice nối vào instance 1, Bob nối vào instance 2. Alice gửi tin cho Bob. Nếu mỗi instance chỉ giữ `Map<userId, WebSocket>` cục bộ và không có cơ chế nào khác, chuyện gì xảy ra?",
      options: [
        "Tin nhắn tự động tới Bob vì cả 2 instance dùng chung load balancer",
        "Instance 1 tìm Bob trong `Map` của chính nó, không thấy, và tin nhắn không bao giờ tới Bob dù Bob đang online ở instance 2",
        "Postgres tự đẩy tin nhắn qua WebSocket cho Bob",
        "Nginx tự phát hiện và chuyển tiếp gói WebSocket sang instance 2",
      ],
      answerIndex: 1,
      explanation: "Đây chính là lý do WebSocket 'khó load balance': mỗi instance chỉ biết những connection nó tự giữ. Cần một cơ chế liên instance — registry tra 'user X đang ở instance nào' rồi gửi thẳng, hoặc fan-out qua pub/sub để mọi instance tự kiểm tra Map cục bộ của mình.",
    },
    {
      id: "pubsub-vs-registry-tradeoff",
      question: "So với publish tin nhắn lên một channel Redis pub/sub mà MỌI instance đều subscribe (fan-out), cách dùng registry (Redis hash `userId -> instanceId`) rồi chỉ gửi tới đúng instance đó có nhược điểm gì?",
      options: [
        "Không nhược điểm nào, registry luôn tốt hơn",
        "Registry phải được cập nhật chính xác khi connect/disconnect/instance crash — dữ liệu registry lệch (stale) làm tin nhắn gửi nhầm chỗ hoặc rơi vào hư không",
        "Registry làm tăng thứ tự tin nhắn bị đảo lộn",
        "Redis không hỗ trợ lưu hash",
      ],
      answerIndex: 1,
      explanation: "Fan-out pub/sub đơn giản (mọi instance tự lọc) nhưng tốn băng thông nội bộ khi số instance lớn. Registry tiết kiệm băng thông hơn nhưng thêm một nguồn sự thật phải giữ đồng bộ — instance crash mà không kịp xoá entry, hoặc set TTL sai, sẽ khiến hệ thống tưởng user vẫn ở instance đã chết.",
    },
    {
      id: "message-ordering-scope",
      question: "Hệ thống cần đảm bảo thứ tự tin nhắn. Cách tiếp cận nào đúng và đủ dùng cho hầu hết ứng dụng chat?",
      options: [
        "Một sequence number toàn cục (global) cho tất cả tin nhắn của mọi user, mọi conversation",
        "Sequence number scoped theo từng conversation — chỉ cần đúng thứ tự bên trong một conversation, không cần thứ tự giữa các conversation khác nhau",
        "Dùng timestamp `Date.now()` của client làm sequence vì đơn giản nhất",
        "Không cần sequence, cứ dựa vào thứ tự TCP là đủ",
      ],
      answerIndex: 1,
      explanation: "Người dùng chỉ quan tâm 'trong đoạn chat này, tin nào trước tin nào sau' — không ai để ý tin nhắn ở conversation A có 'thứ tự toàn cục' so với conversation B. Scoped-per-conversation vừa đủ, tránh việc phải đồng bộ một bộ đếm toàn cục (điểm nghẽn ghi). Timestamp client không đáng tin vì đồng hồ client có thể lệch hoặc tua ngược.",
    },
    {
      id: "storage-sharding-key",
      question: "Bảng `messages` ở quy mô hàng tỷ dòng nên shard/partition theo khoá nào là hợp lý nhất?",
      options: [
        "Theo `message_id` sinh ngẫu nhiên (UUID)",
        "Theo `conversation_id` — mọi tin nhắn của một conversation nằm cùng shard nên đọc lịch sử chat (thao tác phổ biến nhất) không cần query nhiều shard",
        "Theo ngày tạo tin nhắn",
        "Theo `sender_id` để mỗi user có một shard riêng",
      ],
      answerIndex: 1,
      explanation: "Truy vấn phổ biến nhất là 'lấy N tin nhắn gần nhất của conversation X theo thứ tự' — shard theo `conversation_id` giữ toàn bộ lịch sử một cuộc trò chuyện trên cùng partition/node (như consistent hashing ở SD06), tránh scatter-gather. Shard theo `sender_id` làm nhóm chat nhiều người phải gom dữ liệu từ nhiều shard mỗi lần đọc.",
    },
    {
      id: "offline-delivery-strategy",
      question: "Bob offline khi Alice gửi tin. Thiết kế nào đảm bảo Bob không mất tin nhắn?",
      options: [
        "Chỉ cần gửi qua WebSocket; nếu Bob offline thì bỏ qua, coi như chưa từng gửi",
        "Giữ tin nhắn trong RAM của instance cho tới khi Bob online lại",
        "Ghi tin nhắn vào một inbox bền vững (DB) trước khi cố gắng đẩy qua WebSocket; khi Bob offline, gửi push notification, và khi Bob mở app lại thì fetch các tin nhắn có `seq` lớn hơn seq cuối đã đồng bộ",
        "Bắt Alice gửi lại tin nhắn thủ công",
      ],
      answerIndex: 2,
      explanation: "Nguồn sự thật phải là bản ghi bền vững (durable), không phải kết nối WebSocket đang mở hay RAM của một instance (mất khi instance restart). Push notification chỉ là 'chuông báo' — dữ liệu thật được đồng bộ qua fetch-on-reconnect dựa trên sequence number.",
    },
    {
      id: "multi-device-sync",
      question: "Bob đăng nhập cùng lúc trên điện thoại và laptop. Alice gửi 1 tin nhắn. Thiết kế đa thiết bị đúng là gì?",
      options: [
        "Chỉ thiết bị đăng nhập gần nhất nhận được tin nhắn, các thiết bị khác không cần biết",
        "Server coi mỗi thiết bị là một 'kết nối/registry entry' riêng của cùng userId, fan-out tin nhắn (và trạng thái đã đọc) tới tất cả thiết bị đang online của Bob, thiết bị offline thì fetch-on-reconnect như bình thường",
        "Bắt Bob chỉ được đăng nhập 1 thiết bị tại một thời điểm",
        "Laptop và điện thoại tự đồng bộ với nhau qua Bluetooth",
      ],
      answerIndex: 1,
      explanation: "Đa thiết bị nghĩa là một user có thể có N kết nối WebSocket đang mở cùng lúc (registry/Map nên là `userId -> Set<connection>`, không phải 1-1). Đọc/gửi trên thiết bị nào cũng phải đồng bộ trạng thái 'đã đọc tới đâu' cho các thiết bị còn lại.",
    },
    {
      id: "presence-fanout-cost",
      question: "App có 500 triệu user, trung bình mỗi user có 150 liên hệ. Nếu mỗi heartbeat (mỗi 15 giây) đều publish trạng thái 'online' tới toàn bộ danh sách liên hệ của user đó, vấn đề lớn nhất là gì?",
      options: [
        "Không có vấn đề gì vì Redis pub/sub rất nhanh",
        "Số sự kiện fan-out tăng theo (số user online × số liên hệ) mỗi 15 giây — cực lớn và lãng phí vì phần lớn liên hệ không đang mở app để xem trạng thái ngay lúc đó",
        "Heartbeat sẽ làm sai thứ tự tin nhắn",
        "TTL của Redis sẽ tự động giảm xuống 0",
      ],
      answerIndex: 1,
      explanation: "Đây là lý do phải debounce/coalesce: chỉ publish khi trạng thái *thực sự đổi* (online→away, away→offline), không publish ở mỗi heartbeat giữ-kết-nối. Với hệ thống lớn, cân nhắc thêm: chỉ tính presence 'theo yêu cầu' (pull) cho danh sách đang hiển thị trên màn hình, thay vì push toàn bộ liên hệ mọi lúc.",
    },
    {
      id: "presence-ttl-choice",
      question: "TTL của key `presence:<userId>` trong Redis được set là 30 giây, heartbeat gửi mỗi 15 giây. Nếu đổi TTL xuống 5 giây mà vẫn giữ heartbeat 15 giây, chuyện gì xảy ra?",
      options: [
        "Không ảnh hưởng gì, TTL chỉ là chi tiết cấu hình",
        "User bị hệ thống coi là 'offline giả' liên tục giữa hai lần heartbeat vì key hết hạn trước khi heartbeat kế tiếp tới",
        "Hệ thống sẽ tự tăng heartbeat lên nhanh hơn",
        "Redis sẽ báo lỗi vì TTL quá ngắn",
      ],
      answerIndex: 1,
      explanation: "TTL phải lớn hơn chu kỳ heartbeat với biên độ đủ chịu được trễ mạng và mất gói lẻ tẻ (ví dụ TTL = 2× chu kỳ heartbeat). TTL ngắn hơn hoặc bằng chu kỳ heartbeat gây ra hiện tượng nhấp nháy online/offline liên tục dù kết nối vẫn ổn định.",
    },
    {
      id: "single-redis-failure-mode",
      question: "Trong kiến trúc dùng một Redis instance duy nhất vừa làm pub/sub relay vừa giữ presence TTL, Redis đó bị crash 30 giây. Ảnh hưởng thực tế là gì?",
      options: [
        "Không ảnh hưởng vì WebSocket không phụ thuộc Redis",
        "Tin nhắn cross-instance không được relay (người nhận ở instance khác không nhận realtime) và mọi presence key hết hạn/không cập nhật được, khiến toàn bộ user trông như offline — cần Redis HA (Sentinel/Cluster) hoặc ít nhất giám sát + fallback rõ ràng cho case sản xuất",
        "Chỉ ảnh hưởng tới việc gửi tin nhắn 1-1, group chat vẫn hoạt động bình thường",
        "Tin nhắn sẽ tự chuyển sang gửi qua email",
      ],
      answerIndex: 1,
      explanation: "Redis ở đây là một điểm chịu tải quan trọng cho cả 2 luồng (relay + presence) — mất nó là mất khả năng route cross-instance và làm sai lệch trạng thái online. Thiết kế production cần Redis HA và một chiến lược degrade rõ ràng (ví dụ: tin nhắn vẫn được ghi DB nên không mất dữ liệu, chỉ mất tính 'realtime' tạm thời).",
    },
  ],
};
