import type { ModuleDefinition } from "@/content/content-types";

export const b17ContainerizationCicdBackendModule: ModuleDefinition = {
  id: "b17",
  slug: "b17-containerization-cicd-backend",
  phaseId: "b-phase-3",
  order: 17,
  weeks: "Tuần 21",
  title: "Container hoá & CI/CD cho backend",
  emoji: "🚢",
  eli5Summary:
    "`taskflow-api` đã chạy trong container từ B01, nhưng đó mới là đóng gói tạm: thùng hàng vẫn giữ nguyên đồ nghề đóng gói (devDependencies) bên trong, và ai mở được thùng cũng có toàn quyền như chủ kho (chạy bằng root). Module này niêm phong lại thùng cho gọn, đổi khoá cho một nhân viên quyền hạn thấp thay vì chủ kho, dán nhãn \"còn sống\" đúng nghĩa (thật sự kiểm tra tim — DB/Redis — chứ không phải nhãn in sẵn), dạy nhân viên đóng cửa từ tốn khi hết ca thay vì sập cửa giữa chừng, và dựng một trạm kiểm tra tự động không cho lô hàng lỗi rời kho.",
  objectives: [
    "Tối ưu tiếp Dockerfile multi-stage đã có từ B01: loại sạch devDependencies khỏi stage runtime, giảm kích thước image, đo lại bằng `docker images`/`docker history` thay vì đoán",
    "Chạy container `api` bằng non-root user và giải thích đúng \"blast radius\" nếu container bị RCE (Remote Code Execution)",
    "Viết `/healthz` kiểm tra thật kết nối Postgres + Redis, phân biệt rõ với `/api/v1/health` (liveness đơn giản) đã có từ B01",
    "Xử lý `SIGTERM` đúng cách: ngừng nhận connection mới, đợi request đang chạy xong, rồi mới đóng pool Postgres/Redis và thoát — trong đúng giới hạn grace period của `docker stop`",
    "Thêm service `nginx` vào `docker-compose.yml` làm reverse proxy trần trước `api`, đúng spec dùng chung của cả course",
    "Viết GitHub Actions workflow chạy lint → typecheck → test → build trên mỗi PR, và giải thích vì sao thứ tự đó (rẻ trước, đắt sau) tiết kiệm thời gian CI",
  ],
  lessons: [
    {
      slug: "dockerfile-multistage-non-root-user",
      title: "Multi-stage Dockerfile & non-root user",
      minutes: 40,
      summary: "Tối ưu tiếp Dockerfile 2-stage đã có từ B01: bỏ hẳn devDependencies khỏi runtime, đo lại kích thước image, và chạy container bằng user thường thay vì root.",
    },
    {
      slug: "healthcheck-graceful-shutdown-sigterm",
      title: "Healthcheck thật & graceful shutdown khi SIGTERM",
      minutes: 45,
      summary: "/healthz kiểm tra thật kết nối DB/Redis thay vì trả 200 cứng; SIGTERM phải ngừng nhận request mới, đợi request đang chạy xong rồi mới đóng pool và thoát.",
    },
    {
      slug: "ci-pipeline-lint-typecheck-test-build",
      title: "Pipeline CI tối thiểu: lint → typecheck → test → build",
      minutes: 40,
      summary: "GitHub Actions chạy 4 bước tuần tự trên mỗi PR, dừng ngay ở bước rẻ nhất khi có lỗi thay vì tốn thời gian chạy build với code còn lỗi cú pháp.",
    },
  ],
  labs: [
    {
      id: "harden-dockerfile-compare-image-size",
      title: "Tối ưu Dockerfile multi-stage & so sánh kích thước image",
      description: "Siết lại Dockerfile 2-stage của B01: dọn cache, sắp lại thứ tự COPY để tận dụng layer cache, thêm .dockerignore, rồi đo lại kích thước image trước/sau bằng công cụ thật.",
      steps: [
        "Ghi lại baseline: `docker compose build api && docker images taskflow-api-api --format '{{.Repository}}:{{.Tag}}\\t{{.Size}}'` — lưu số MB hiện tại làm mốc so sánh",
        "Tạo `.dockerignore` ở gốc `taskflow-api` liệt kê `node_modules`, `dist`, `.git`, `*.test.ts`, `learnings.md` — tránh build context cõng theo rác không cần thiết vào cả hai stage",
        "Sửa stage `builder`: tách `COPY package*.json ./` + `RUN npm ci` thành bước riêng TRƯỚC `COPY . .` (đã đúng từ B01) — xác nhận lại rằng sửa code không làm invalidate cache của bước `npm ci` khi source thay đổi nhưng `package.json` không đổi",
        "Sửa stage runtime: thêm `RUN npm ci --omit=dev && npm cache clean --force` (dọn cache npm ngay trong layer đó, không để lại ở layer riêng) và thêm `USER node` (đã có sẵn trong base image `node:22-slim`) trước dòng `CMD`",
        "Build lại: `docker compose build api && docker images taskflow-api-api` — so sánh kích thước mới với baseline; chạy `docker history taskflow-api-api:latest` để xem layer nào còn nặng nhất",
        "Ghi baseline, kích thước sau tối ưu, và layer nặng nhất vào `learnings.md`",
      ],
    },
    {
      id: "healthz-endpoint-and-sigterm-handler",
      title: "Thêm /healthz kiểm tra DB/Redis thật + xử lý SIGTERM",
      description: "Viết endpoint healthcheck thật sự gọi tới Postgres và Redis, rồi dạy `src/app.ts` đóng cửa đúng thứ tự khi nhận SIGTERM thay vì thoát ngay lập tức.",
      steps: [
        "Mở `src/db/client.ts` (đã tạo ở B04) — đổi `const client = postgres(...)` thành `export const client = postgres(...)` để module này có thể gọi `client.end()` lúc shutdown (biến này trước giờ chỉ dùng nội bộ cho `drizzle()`)",
        "Viết route `GET /healthz` (đặt ngoài prefix `/api/v1`, không qua middleware auth) gọi `await db.execute(sql\\`select 1\\`)` và `await redis.ping()` trong `Promise.allSettled`, trả `200` với chi tiết từng dependency nếu cả hai `fulfilled`, trả `503` kèm dependency nào fail nếu có ít nhất một `rejected`",
        "Ở cuối `src/app.ts`, sau dòng `app.listen(...)`, đăng ký `process.on(\"SIGTERM\", ...)`: gọi `await app.close()` (Fastify tự ngừng nhận connection mới và đợi request đang xử lý xong), rồi `await client.end()`, `await redis.quit()`, rồi `process.exit(0)`",
        "Thêm `HEALTHCHECK` instruction vào Dockerfile (stage runtime) trỏ vào `/healthz` với `--interval=10s --timeout=3s --start-period=5s --retries=3`",
        "Test dependency thật sự chết: `docker compose stop postgres`, gọi `curl -i http://localhost:3000/healthz` — xác nhận trả `503` và JSON nêu rõ `postgres` là dependency lỗi; `docker compose start postgres` trước khi tiếp tục",
        "Test graceful shutdown: thêm tạm 1 route `GET /slow` gọi `await new Promise((r) => setTimeout(r, 5000))` rồi trả `200`; gọi route đó, ngay lập tức chạy `docker compose kill -s SIGTERM api` ở terminal khác, xác nhận request `/slow` vẫn nhận đủ response thay vì bị cắt ngang",
      ],
    },
    {
      id: "add-nginx-reverse-proxy",
      title: "Thêm nginx làm reverse proxy trần trước api",
      description: "Đưa service `nginx` vào docker-compose.yml đúng spec chung của course, cấu hình proxy_pass tối giản — không đụng tới versioning (đó là việc của B18).",
      steps: [
        "Thêm service `nginx` vào `docker-compose.yml` đúng spec mục 3 của curriculum: `image: nginx:1.27`, `ports: [\"8081:80\"]`, `depends_on: [api]`, mount `./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro`",
        "Tạo file `nginx/nginx.conf` với đúng một `location /` proxy thẳng mọi request sang `api:3000` (`proxy_pass http://api:3000;`), kèm `proxy_set_header Host $host;` và `proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;` — chưa có logic route `/v1`/`/v2` gì cả, đó là phạm vi B18",
        "`docker compose up -d nginx`, gọi `curl http://localhost:8081/api/v1/health` — xác nhận nginx forward đúng response `{\"status\":\"ok\"}` từ `api` phía sau",
        "Gọi `curl http://localhost:8081/healthz` — xác nhận đi qua nginx vẫn thấy đúng kết quả kiểm tra DB/Redis vừa viết ở lab trước",
        "Tắt tạm `api` (`docker compose stop api`), gọi lại `curl -i http://localhost:8081/api/v1/health` — xác nhận nginx tự trả `502 Bad Gateway` thay vì treo vô thời hạn; bật lại `api`",
      ],
    },
    {
      id: "github-actions-ci-lint-typecheck-test-build",
      title: "Viết GitHub Actions workflow lint → typecheck → test → build",
      description: "Dựng pipeline CI tối thiểu chạy trên mỗi PR: 4 bước tuần tự, dừng ngay ở bước rẻ nhất nếu có lỗi, không đi sâu vào deploy (phạm vi course DevOps).",
      steps: [
        "Tạo `.github/workflows/ci.yml` với `on: pull_request: branches: [main]` và một job `ci` chạy trên `runs-on: ubuntu-latest`, có `services:` khai báo `postgres:17` và `redis:7` (cần cho bước test — B07 đã có test DB riêng)",
        "Step 1 — `pnpm install --frozen-lockfile` rồi `pnpm lint`: dừng workflow ngay nếu lỗi cú pháp/style, không tốn thời gian chạy 3 bước sau",
        "Step 2 — `pnpm exec tsc --noEmit` (typecheck): bắt lỗi kiểu dữ liệu trước khi tốn thời gian chạy test thật",
        "Step 3 — `pnpm test` (trỏ `DATABASE_URL`/`REDIS_URL` vào service Postgres/Redis vừa khai báo ở trên, không phải instance dev)",
        "Step 4 — `docker build -t taskflow-api:ci .` để xác nhận Dockerfile đã tối ưu ở lab 1 build sạch, không có lỗi cú pháp trong Dockerfile lọt qua tới tận lúc deploy",
        "Cố tình push 1 commit có lỗi lint lên branch, mở PR, xác nhận workflow đỏ ngay ở step lint và 3 step sau hiển thị `skipped`; sửa lỗi, push lại, xác nhận cả 4 step chuyển xanh",
      ],
    },
  ],
  deliverable:
    "`taskflow-api` có Dockerfile multi-stage tối ưu hơn (không devDependencies, chạy non-root, có HEALTHCHECK), endpoint `/healthz` kiểm tra thật Postgres/Redis, `src/app.ts` xử lý `SIGTERM` graceful shutdown đúng thứ tự, service `nginx` làm reverse proxy trần trong `docker-compose.yml`, và GitHub Actions workflow chạy lint/typecheck/test/build trên mỗi PR.",
  successCriteria:
    "Image runtime sau tối ưu nhỏ hơn baseline B01 và không chứa devDependencies (kiểm bằng `docker history`); `docker exec ... whoami` trong container `api` KHÔNG trả về `root`; `/healthz` trả `503` đúng lúc Postgres hoặc Redis down và trả `200` khi cả hai sống; gửi SIGTERM giữa lúc có request đang xử lý không làm mất response của request đó, trong giới hạn grace period 10 giây của `docker stop`; CI đỏ ngay khi lint/typecheck/test lỗi và các step sau bị skip.",
  resources: [
    { title: "Docker docs — Multi-stage builds", url: "https://docs.docker.com/build/building/multi-stage/", kind: "doc" },
    { title: "Docker docs — Dockerfile best practices (USER, non-root)", url: "https://docs.docker.com/build/building/best-practices/", kind: "doc" },
    { title: "Node.js Docker Working Group — Best Practices (non-root user)", url: "https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md", kind: "doc" },
    { title: "Docker docs — Dockerfile reference (HEALTHCHECK)", url: "https://docs.docker.com/reference/dockerfile/#healthcheck", kind: "doc" },
    { title: "Node.js docs — Signal events (SIGTERM)", url: "https://nodejs.org/api/process.html#signal-events", kind: "doc" },
    { title: "GitHub Actions docs — Understanding GitHub Actions", url: "https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions", kind: "doc" },
  ],
  quiz: [
    {
      id: "multistage-runtime-copy-scope",
      question: "Ở stage runtime của Dockerfile `taskflow-api`, lệnh nào sau đây là SAI vì sẽ mang devDependencies và source TypeScript vào image cuối?",
      options: [
        "`COPY --from=builder /app/dist ./dist`",
        "`COPY --from=builder /app ./` (copy nguyên thư mục `/app` của stage builder, kể cả `node_modules` và `src/`)",
        "`RUN npm ci --omit=dev`",
        "`COPY package*.json ./`",
      ],
      answerIndex: 1,
      explanation: "Copy nguyên `/app` từ stage builder mang theo `node_modules` (đã cài cả devDependencies để build) và toàn bộ source `.ts` gốc — đúng thứ multi-stage sinh ra để loại bỏ. Chỉ nên `COPY --from=builder` đúng thư mục `dist/` đã biên dịch.",
    },
    {
      id: "non-root-blast-radius",
      question: "Container `api` bị khai thác một lỗ hổng RCE (Remote Code Execution) trong một dependency. Chạy container bằng `USER node` thay vì mặc định root giúp ích gì?",
      options: [
        "Ngăn hoàn toàn không cho lỗ hổng RCE xảy ra",
        "Không giúp gì — attacker vẫn kiểm soát được toàn bộ máy host ngay khi vào được container",
        "Giới hạn \"blast radius\": attacker chỉ có quyền của user thường bên trong container, khó ghi vào các thư mục hệ thống, khó leo thang lên quyền root của host hơn — dù vẫn cần thêm các lớp phòng thủ khác (container escape vẫn là rủi ro riêng)",
        "Làm container chạy nhanh hơn vì bớt được kiểm tra quyền",
      ],
      answerIndex: 2,
      explanation: "Non-root user không ngăn được RCE xảy ra, nhưng giảm mức độ thiệt hại nếu nó xảy ra — attacker bị giới hạn trong quyền của user thường, không thể tự do ghi đè file hệ thống hay dễ dàng leo thang đặc quyền như khi tiến trình chạy bằng root.",
    },
    {
      id: "dockerignore-purpose",
      question: "Thêm `.dockerignore` liệt kê `node_modules`, `.git`, `dist` cho `taskflow-api` giải quyết vấn đề gì?",
      options: [
        "Chỉ để rút gọn output khi chạy `docker build`, không ảnh hưởng gì tới image",
        "Tránh build context (những gì Docker daemon nhận khi build) cõng theo file rác/nặng không cần thiết — build context nhỏ hơn build nhanh hơn, và tránh vô tình `COPY . .` đè `node_modules` của host vào container",
        "Bắt buộc phải có thì `Dockerfile` mới chạy được, thiếu sẽ báo lỗi cú pháp",
        "Thay thế hoàn toàn cho việc viết multi-stage build",
      ],
      answerIndex: 1,
      explanation: "`.dockerignore` lọc bớt build context gửi lên Docker daemon trước khi build — tránh gửi `node_modules`/`.git` nặng nề, và tránh rủi ro `COPY . .` vô tình copy `node_modules` đã cài trên host (có thể khác kiến trúc CPU với image) đè lên bản cài trong container.",
    },
    {
      id: "healthz-hardcoded-200-false-confidence",
      question: "`/api/v1/health` từ B01 luôn trả `200 { \"status\": \"ok\" }` ngay cả khi Postgres đã chết hẳn. Vì sao đây là vấn đề đủ nghiêm trọng để B17 thêm riêng `/healthz`?",
      options: [
        "Không phải vấn đề — health check chỉ cần xác nhận process Node.js còn chạy là đủ",
        "Vì tên route `/health` phải đổi thành `/healthz` mới đúng chuẩn REST",
        "Vì cơ chế orchestration (Docker/Compose HEALTHCHECK, hoặc load balancer ở production) sẽ tiếp tục coi container là \"khoẻ mạnh\" và tiếp tục route traffic tới nó dù mọi request đọc/ghi DB đều sẽ lỗi — health check hardcoded tạo ra ảo giác an toàn (false confidence)",
        "Vì `/api/v1/health` chỉ hoạt động trong môi trường development, không chạy được trong Docker",
      ],
      answerIndex: 2,
      explanation: "Một health check trả 200 vô điều kiện chỉ chứng minh \"process còn sống\" (liveness), không chứng minh \"process còn phục vụ được\" (readiness). Nếu hệ thống điều phối dựa vào đó để quyết định route traffic, nó sẽ tiếp tục gửi request tới một container đã mất kết nối DB — user nhận lỗi 500 hàng loạt trong khi orchestrator vẫn nghĩ mọi thứ ổn.",
    },
    {
      id: "sigterm-vs-sigkill-grace-period",
      question: "`docker stop api` gửi `SIGTERM` rồi đợi một khoảng \"grace period\" (mặc định 10 giây) trước khi làm gì tiếp theo?",
      options: [
        "Gửi lại `SIGTERM` thêm một lần nữa, lặp vô hạn cho tới khi process tự thoát",
        "Gửi `SIGKILL` — buộc kill process ngay lập tức, không cho cơ hội dọn dẹp thêm, bất kể request có đang xử lý dở hay không",
        "Tự động khởi động lại container với cấu hình cũ",
        "Chuyển sang gọi `/healthz` để kiểm tra trước khi quyết định có kill tiếp hay không",
      ],
      answerIndex: 1,
      explanation: "Nếu process không tự thoát trong grace period (mặc định 10 giây, chỉnh được bằng `docker stop -t`), Docker gửi `SIGKILL` — kill cứng, không có cơ hội chạy thêm bất kỳ dòng code dọn dẹp nào. Đây là lý do graceful shutdown phải xong việc TRONG khoảng thời gian đó, không phải một quy trình có thể kéo dài tuỳ ý.",
    },
    {
      id: "server-close-vs-process-exit",
      question: "Trong handler `SIGTERM`, vì sao phải gọi `await app.close()` TRƯỚC rồi mới `client.end()`/`redis.quit()`, thay vì gọi `process.exit(0)` ngay khi nhận được tín hiệu?",
      options: [
        "Thứ tự không quan trọng, `process.exit(0)` ngay lập tức luôn là lựa chọn an toàn nhất",
        "`process.exit(0)` ngay lập tức sẽ chấm dứt process trong khi vẫn còn request đang xử lý dở — connection tới client bị cắt ngang giữa chừng; `app.close()` cho Fastify ngừng nhận connection MỚI và đợi request đang chạy hoàn tất trước khi coi là đóng xong, rồi mới an toàn để đóng pool và thoát",
        "Vì `client.end()` bắt buộc phải chạy trước `app.close()` mới không bị lỗi cú pháp",
        "Vì Redis không cho phép gọi `quit()` khi server vẫn đang chạy",
      ],
      answerIndex: 1,
      explanation: "`process.exit(0)` ngay lập tức là một dạng \"sập cửa giữa chừng\" — client đang chờ response của một request đang xử lý sẽ nhận connection reset. `app.close()` để Fastify hoàn tất đúng vòng đời: ngừng nhận connection mới, đợi in-flight request xong, rồi mới coi là an toàn để đóng các connection pool phía sau (DB, Redis) và thoát process.",
    },
    {
      id: "graceful-shutdown-exceeds-grace-period",
      question: "Một request đang xử lý mất tới 15 giây để hoàn tất (ví dụ đang chờ một query Postgres chậm). Container nhận `SIGTERM`, `app.close()` đang đợi request đó xong. Chuyện gì xảy ra nếu `docker stop` dùng grace period mặc định 10 giây?",
      options: [
        "Fastify tự động kéo dài grace period lên 15 giây để chờ đủ",
        "Không có gì xảy ra — Docker sẽ đợi vô thời hạn cho tới khi process tự thoát",
        "Sau 10 giây, Docker gửi `SIGKILL` bất kể request có xong hay chưa — request đó vẫn bị cắt ngang giữa chừng, đúng thứ mà graceful shutdown đang cố tránh, chỉ là xảy ra muộn hơn 10 giây thay vì ngay lập tức",
        "Redis sẽ tự động rollback request đó",
      ],
      answerIndex: 2,
      explanation: "Graceful shutdown chỉ hiệu quả nếu toàn bộ quá trình dọn dẹp (đợi request + đóng pool) xong TRONG grace period. Nếu một request đơn lẻ chạy lâu hơn cả grace period, `SIGKILL` vẫn sẽ cắt ngang nó — đây là lý do cần đặt timeout hợp lý cho request dài và cân nhắc tăng grace period (`docker stop -t`) nếu nghiệp vụ thực sự cần request chạy lâu.",
    },
    {
      id: "nginx-scope-b17-vs-b18",
      question: "Ở B17, cấu hình `nginx.conf` chỉ có một `location /` proxy thẳng sang `api:3000`, không có logic route theo `/v1`/`/v2`. Vì sao chưa cần logic đó ở module này?",
      options: [
        "Vì nginx không hỗ trợ route theo path prefix",
        "Vì `taskflow-api` chưa từng có `/api/v1` — điều đó chỉ được thêm ở B18",
        "Vì B17 chỉ cần dựng nginx chạy được như một reverse proxy trần (chứng minh hạ tầng compose hoạt động); việc biến nó thành gateway thật sự có route `/v1`/`/v2`, rate limit tập trung là phạm vi của B18 — tách hai việc để mỗi module tập trung đúng một mục tiêu",
        "Vì rate limit chỉ hoạt động khi có route versioning",
      ],
      answerIndex: 2,
      explanation: "Curriculum tách rõ: B17 chỉ cần nginx chạy được, forward request nguyên vẹn sang `api`. B18 mới thêm `/api/v2` (response shape mới) và biến nginx thành gateway thật (route `/v1`/`/v2`, rate limit tập trung). Làm cả hai trong một module sẽ trộn lẫn hai mục tiêu học khác nhau.",
    },
    {
      id: "ci-stage-order-fail-fast",
      question: "Pipeline CI của `taskflow-api` chạy đúng thứ tự lint → typecheck → test → build. Vì sao thứ tự này (không phải build → test → typecheck → lint) tiết kiệm thời gian CI hơn?",
      options: [
        "Thứ tự không ảnh hưởng gì tới tổng thời gian chạy CI",
        "Vì GitHub Actions chỉ cho phép chạy step theo thứ tự bảng chữ cái",
        "Vì lint/typecheck là các bước rẻ và nhanh nhất, bắt được phần lớn lỗi cú pháp/kiểu dữ liệu; đặt chúng trước để dừng pipeline sớm (fail fast) thay vì tốn vài phút chạy test suite và build Docker image cho một PR có lỗi cú pháp đơn giản",
        "Vì `pnpm test` bắt buộc phải chạy sau khi có image Docker",
      ],
      answerIndex: 2,
      explanation: "Nguyên tắc \"fail fast\": xếp các bước rẻ, nhanh, bắt được nhiều lỗi phổ biến lên trước (lint, typecheck), rồi mới tới các bước tốn thời gian hơn (test suite chạy thật với DB, build Docker image). Một PR lỗi cú pháp bị chặn ngay ở giây thứ vài chục thay vì phải đợi hết cả pipeline vài phút mới biết.",
    },
    {
      id: "ci-test-needs-real-services",
      question: "Job CI khai báo `services: postgres, redis` (Postgres 17, Redis 7) thay vì để `pnpm test` chạy mà không có DB. Vì sao cần bước này?",
      options: [
        "Không cần thiết — Vitest tự mock toàn bộ Postgres/Redis khi chạy trong CI",
        "Vì B07 đã thiết lập test dùng DB thật riêng (không mock DB — chỉ mock các thứ thật sự bên ngoài tầm kiểm soát); CI cần một Postgres/Redis thật để `pnpm test` chạy được các integration test đó, giống hệt cách chạy ở máy local qua Docker Compose",
        "Vì GitHub Actions không cho phép chạy `pnpm test` nếu thiếu khai báo `services`",
        "Vì `services` chỉ dùng để tăng tốc độ tải dependency, không liên quan tới test",
      ],
      answerIndex: 1,
      explanation: "Nguyên tắc từ B07: không mock DB, chỉ mock các phụ thuộc thật sự ngoài tầm kiểm soát (email, PSP...). CI phải cung cấp Postgres/Redis thật (qua `services:` của GitHub Actions, tương đương `docker-compose.yml` ở local) để các integration test chạy đúng như trên máy dev, không phải một phiên bản test giả lập khác hành vi.",
    },
  ],
};
