import type { ModuleDefinition } from "@/content/content-types";

export const sd14CaseUrlShortenerRateLimiterModule: ModuleDefinition = {
  id: "sd14",
  slug: "sd14-case-url-shortener-rate-limiter",
  phaseId: "sd-phase-4",
  order: 14,
  weeks: "Tuần 18",
  title: "Case: URL shortener, Pastebin & rate limiter",
  emoji: "🔗",
  eli5Summary:
    "Đây là bài thi thử đầu tiên: một hệ thống nhỏ nhưng đủ 'đầy đủ vị' — sinh mã ngắn không trùng, phục vụ hàng nghìn lượt đọc mỗi lần có một lượt ghi, và một người gác cửa (rate limiter) không cho ai spam. Bạn sẽ đi đúng framework 4 bước của SD01, nhưng lần này code chạy thật trên máy.",
  objectives: [
    "Viết requirements + ước lượng (QPS, storage) cho URL shortener 100M link/tháng theo Phụ lục A",
    "So sánh 3 chiến lược sinh short code (counter+base62, hash+collision retry, pre-generated pool) và chọn đúng cho từng tình huống",
    "Thiết kế read path có cache, giải thích trade-off 301 vs 302 cho redirect",
    "Mở rộng thiết kế sang Pastebin: nội dung lớn ở object storage, metadata ở DB, có expiration",
    "Thiết kế rate limiter như một service dùng chung, chọn vị trí đặt và chính sách fail-open/fail-closed",
    "Build được URL shortener mini chạy trên sd-playground, đo p95 redirect bằng k6 với tải 100:1",
  ],
  lessons: [
    {
      slug: "url-shortener-requirements-and-estimation",
      title: "Yêu cầu & ước lượng cho URL shortener",
      minutes: 45,
      summary: "Áp dụng framework 4 bước của SD01 vào một case cụ thể: 100 triệu link/tháng, read:write 100:1.",
    },
    {
      slug: "short-code-generation-strategies",
      title: "Sinh short code: counter, hash, pre-generated",
      minutes: 50,
      summary: "Ba cách sinh mã ngắn, ba cách xử lý (hoặc né) collision — và khi nào code bị đoán được là một vấn đề.",
    },
    {
      slug: "read-path-cache-redirect-and-pastebin",
      title: "Read path, cache & Pastebin",
      minutes: 55,
      summary: "Đường đọc read-heavy: cache, 301 vs 302, rồi mở rộng sang Pastebin với nội dung lớn và expiration.",
    },
    {
      slug: "rate-limiter-service-design-and-tradeoffs",
      title: "Rate limiter như một service riêng",
      minutes: 50,
      summary: "Đặt rate limiter ở đâu, thuật toán nào, fail-open hay fail-closed — rồi tổng kết bottleneck & trade-off cả case.",
    },
  ],
  labs: [
    {
      id: "build-url-shortener-mini",
      title: "Build URL shortener mini trên sd-playground",
      description: "Thêm bảng `urls`, endpoint tạo/redirect (counter+base62) và cache Redis vào app trong sd-playground.",
      steps: [
        "Thêm vào `db/init.sql`: bảng `urls(short_code TEXT PRIMARY KEY, long_url TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now(), click_count BIGINT DEFAULT 0)` và `CREATE SEQUENCE url_id_seq;`",
        "Thêm `POST /api/shorten` vào `app/src/server.ts`: lấy `nextval('url_id_seq')`, encode base62, `INSERT` vào `urls`, trả `{ shortCode, shortUrl }`",
        "Thêm `GET /:code`: đọc `long_url` từ Redis (`GET short:<code>`); nếu miss thì query Postgres, `SET` lại Redis với TTL (ví dụ 3600s), rồi `INCR click_count` bất đồng bộ (không chặn response) và trả `reply.redirect(302, longUrl)`",
        "`docker compose up -d --build` rồi tạo thử 1 link: `curl -s -X POST localhost:8080/api/shorten -H 'Content-Type: application/json' -d '{\"longUrl\":\"https://example.com/rat-dai-can-rut-gon\"}'`",
        "Theo short code nhận được, `curl -sD - -o /dev/null localhost:8080/<code>` hai lần — lần 1 phải query Postgres (cache miss), lần 2 phải phục vụ từ Redis (kiểm tra bằng `docker compose exec redis redis-cli GET short:<code>`)",
      ],
    },
    {
      id: "k6-100-to-1-read-write-load-test",
      title: "k6: tải read:write 100:1 và đo p95 redirect",
      description: "Viết script k6 mô phỏng đúng tỉ lệ đọc/ghi đã ước lượng, xác nhận p95 redirect dưới 20ms trên máy local.",
      steps: [
        "Viết `k6/url-shortener-100-to-1.js`: 1% VU gọi `POST /api/shorten` với URL ngẫu nhiên, 99% gọi `GET /:code` với code lấy từ một danh sách đã tạo sẵn (seed trước bằng vài chục request tạo link)",
        "Đặt `thresholds`: `http_req_duration{name:redirect}: [\"p(95)<20\"]` và `http_req_failed: [\"rate<0.01\"]`; tag riêng request redirect bằng `params.tags.name = \"redirect\"`",
        "Chạy `k6 run --vus 20 --duration 30s k6/url-shortener-100-to-1.js` và đọc số `http_req_duration{name:redirect}` ở p(95)",
        "Nếu p95 vượt 20ms: kiểm tra tỉ lệ cache hit (`docker compose exec redis redis-cli INFO stats | grep keyspace`), tăng TTL hoặc kiểm tra có đang vô tình query Postgres ở đường redirect không",
        "Ghi lại kết quả (p95, throughput, % lỗi) vào ghi chú lab — đây là số liệu cụ thể để đưa vào phần deep dive của design doc",
      ],
    },
    {
      id: "rate-limit-shorten-by-ip",
      title: "Rate limit tạo link theo IP",
      description: "Chặn spam tạo link hàng loạt bằng fixed window counter trên Redis, áp cho endpoint `POST /api/shorten`.",
      steps: [
        "Thêm middleware trước handler `POST /api/shorten`: lấy IP từ `req.ip`, tăng counter `INCR ratelimit:shorten:<ip>` trên Redis, `EXPIRE` 60s nếu counter vừa tạo (giá trị trả về của `INCR` là 1)",
        "Nếu counter > 10 (ví dụ 10 link/phút/IP), trả `429 Too Many Requests` kèm header `Retry-After`",
        "Kiểm tra bằng vòng lặp: `for i in {1..15}; do curl -s -o /dev/null -w \"%{http_code}\\n\" -X POST localhost:8080/api/shorten -H 'Content-Type: application/json' -d '{\"longUrl\":\"https://example.com\"}'; done` — phải thấy `201` mười lần đầu rồi `429`",
        "Đợi hơn 60 giây (hoặc `docker compose exec redis redis-cli DEL ratelimit:shorten:<ip>`), lặp lại bước trên để xác nhận counter reset đúng",
        "Ghi vào README: limit đã chọn, vì sao (ví dụ so với QPS ghi trung bình 33 QPS toàn hệ thống, limit 10/phút/IP không chặn user thật dùng bình thường)",
      ],
    },
    {
      id: "design-doc-url-shortener-100m-per-month",
      title: "Design doc: URL shortener 100M link/tháng",
      description: "Viết design doc đầy đủ theo template Phụ lục A — bài tập viết, không phải code — bấm giờ 45–60 phút trước khi đối chiếu lại bài học.",
      steps: [
        "Mục 1–2: viết functional/non-functional requirements và bảng ước lượng (DAU, QPS đọc/ghi, storage 5 năm) — tự làm lại phép tính, không copy số trong bài học",
        "Mục 3–4: viết API (`POST /api/shorten`, `GET /:code`) và data model, giải thích vì sao chọn Postgres cho mapping thay vì NoSQL",
        "Mục 5–6: vẽ high-level design (có thể vẽ tay/ASCII) và chọn 2–3 điểm để đào sâu (ví dụ: chiến lược sinh code, cache invalidation, custom alias)",
        "Mục 7: bảng trade-off `| Quyết định | Chọn | Bỏ | Vì sao | Khi nào đổi ý |` cho ít nhất 2 quyết định (chiến lược sinh code, 301 vs 302)",
        "Mục 8: liệt kê bottleneck có thể xảy ra ở 10× quy mô hiện tại (ví dụ counter tập trung, một node Redis) và hướng mở rộng cho từng cái",
      ],
    },
  ],
  deliverable:
    "URL shortener mini chạy được trên sd-playground (Postgres + Redis cache + rate limit theo IP) với kết quả k6 100:1 đạt p95 redirect < 20ms trên máy local, cùng 1 design doc đầy đủ theo Phụ lục A.",
  successCriteria:
    "Trình bày trọn case (yêu cầu → ước lượng → API/data model → design → deep dive → trade-off) trong 45 phút mà không cần mở lại bài học; code đạt tiêu chí p95 đã nêu.",
  resources: [
    { title: "System Design Interview Vol. 1 (Alex Xu) & ByteByteGo — URL shortener, rate limiter", url: "https://bytebytego.com/", kind: "book" },
    { title: "Hello Interview — System Design (delivery framework, Bit.ly breakdown)", url: "https://www.hellointerview.com/", kind: "course" },
    { title: "The System Design Primer (donnemartin, GitHub)", url: "https://github.com/donnemartin/system-design-primer", kind: "course" },
    { title: "PostgreSQL Docs — CREATE SEQUENCE (counter cho short code)", url: "https://www.postgresql.org/docs/current/sql-createsequence.html", kind: "doc" },
    { title: "Redis Docs", url: "https://redis.io/docs/latest/", kind: "tool" },
    { title: "Grafana k6 Docs", url: "https://grafana.com/docs/k6/latest/", kind: "tool" },
  ],
  quiz: [
    {
      id: "base62-combinations",
      question: "Short code dùng base62 (`0-9a-zA-Z`), dài 7 ký tự. Số tổ hợp có thể sinh ra cỡ bao nhiêu?",
      options: ["Cỡ 3,5 triệu", "Cỡ 3,5 tỷ", "Cỡ 3,5 nghìn tỷ (62⁷)", "Cỡ 62 × 7 = 434"],
      answerIndex: 2,
      explanation: "62⁷ ≈ 3,5 × 10¹² ≈ 3,5 nghìn tỷ. Với 6 tỷ link tích luỹ sau 5 năm (giả định 100M/tháng), không gian này còn dư sức chứa — không cần thêm ký tự ngay.",
    },
    {
      id: "counter-needs-coordination",
      question: "Counter + base62 không bao giờ sinh trùng code — vậy tại sao vẫn cần một 'counter dùng chung' thay vì để mỗi instance app tự đếm riêng từ 0?",
      options: [
        "Vì base62 chỉ hoạt động đúng với số bắt đầu từ 0",
        "Nếu mỗi instance tự đếm riêng, nhiều instance sẽ cùng sinh ra id 1, 2, 3… → trùng code dù thuật toán encode đúng",
        "Vì Postgres không hỗ trợ sequence trên nhiều bảng",
        "Vì base62 chậm hơn nếu chạy song song trên nhiều instance",
      ],
      answerIndex: 1,
      explanation: "Tính 'không trùng' của counter đến từ việc MỖI ID CHỈ ĐƯỢC PHÁT MỘT LẦN trên toàn hệ thống — cần một nguồn phát duy nhất (DB sequence) hoặc chia range id riêng cho từng instance, không phải để từng instance tự đếm độc lập.",
    },
    {
      id: "hash-collision-scales-with-size",
      question: "Dùng SHA-256(long_url) rồi lấy 7 ký tự base62 đầu làm code. Điều gì đúng khi số link đã lưu tăng lên hàng tỷ?",
      options: [
        "Xác suất hai long_url khác nhau ra cùng 7 ký tự đầu tăng dần (birthday paradox) — bắt buộc phải có bước kiểm tra và thử lại khi trùng",
        "SHA-256 đảm bảo không bao giờ trùng vì là hàm băm mật mã học",
        "Chỉ cần lấy đủ 7 ký tự là luôn duy nhất tuyệt đối, không cần retry",
        "Vấn đề chỉ xảy ra nếu hai người dùng nhập đúng cùng một long_url",
      ],
      answerIndex: 0,
      explanation: "Cắt ngắn hash luôn có xác suất trùng tăng theo số lượng bản ghi (bài toán sinh nhật), bất kể hash gốc mạnh cỡ nào. Thiết kế đúng phải có bước kiểm tra trùng trong DB và thử lại với salt/offset khác.",
    },
    {
      id: "pregenerated-pool-operational-cost",
      question: "Chiến lược pre-generated key pool cần thêm gì để vận hành ổn định lâu dài?",
      options: [
        "Không cần gì thêm, pool tạo một lần là dùng mãi mãi",
        "Một worker nền liên tục sinh thêm code mới vào pool và cảnh báo khi pool sắp cạn",
        "Một Postgres sequence để cấp phát pool",
        "Một hàm hash để kiểm tra trùng mỗi lần lấy code từ pool",
      ],
      answerIndex: 1,
      explanation: "Pool hữu hạn: nếu tốc độ tiêu thụ code vượt tốc độ sinh mới, hệ thống hết code để phát dù không gian base62 còn rất nhiều. Cần worker nền theo dõi và bổ sung liên tục.",
    },
    {
      id: "redirect-code-for-accurate-analytics",
      question: "Sản phẩm cần đếm chính xác số click mỗi ngày cho mục đích tính phí quảng cáo theo lượt click. Nên trả mã redirect nào?",
      options: ["301 Moved Permanently", "302 Found", "Không mã nào quan trọng, click luôn được đếm giống nhau", "200 OK kèm link trong body"],
      answerIndex: 1,
      explanation: "301 cho phép trình duyệt cache và tự nhảy ở các lần sau — server không còn thấy request, mất khả năng đếm click chính xác. 302 buộc trình duyệt luôn hỏi lại server, đổi lấy analytics đúng bằng việc chấp nhận thêm tải.",
    },
    {
      id: "write-through-cache-on-create",
      question: "Một short link vừa tạo có khả năng được chia sẻ viral ngay lập tức (traffic đổ về trong vài phút). Nên xử lý cache thế nào lúc tạo link?",
      options: [
        "Không làm gì, để lần đọc đầu tiên tự tạo cache (lazy load) như bình thường",
        "Ghi luôn mapping vào Redis ngay khi tạo (write-through), tránh dồn cache miss vào Postgres khi traffic đổ về đột ngột",
        "Xoá cache của tất cả short code khác để nhường chỗ",
        "Chỉ ghi vào Postgres, không dùng Redis cho link mới tạo trong giờ đầu",
      ],
      answerIndex: 1,
      explanation: "Với nội dung có khả năng viral, lazy load để lần đọc đầu tiên mới tạo cache có thể khiến hàng loạt request đầu cùng miss và dội vào Postgres cùng lúc (thundering herd). Ghi cache ngay lúc tạo (write-through) né được tình huống đó.",
    },
    {
      id: "pastebin-large-content-storage",
      question: "Mở rộng sang Pastebin: một đoạn paste có thể tới vài MB text. Nên lưu nội dung đó ở đâu?",
      options: [
        "Nhét thẳng nội dung vào một cột `TEXT` lớn trong cùng bảng metadata trên Postgres",
        "Lưu nội dung vào object storage (kiểu S3), Postgres chỉ giữ metadata (id, key trỏ tới object, size, expires_at)",
        "Lưu nội dung trong Redis vĩnh viễn vì Redis nhanh nhất",
        "Lưu nội dung trực tiếp trong short code",
      ],
      answerIndex: 1,
      explanation: "Nội dung lớn, ít khi cần query theo nội dung, và tần suất đọc/ghi khác hẳn metadata — tách ra object storage giữ Postgres nhỏ gọn, nhanh, và storage chi phí thấp hơn cho blob lớn. Postgres chỉ cần biết 'nội dung nằm ở đâu'.",
    },
    {
      id: "rate-limiter-fail-closed-shared-service",
      question: "Rate limiter service dùng chung cho 50 service nội bộ, chạy chính sách fail-closed, bất ngờ bị sập 5 phút. Hệ quả trực tiếp nhất là gì?",
      options: [
        "Không ảnh hưởng gì vì fail-closed chỉ tác động tới service gọi nó đầu tiên",
        "Cả 50 service phụ thuộc đều từ chối request trong 5 phút đó — một service phụ trợ dùng chung trở thành single point of failure cho toàn bộ hệ thống",
        "Fail-closed tự động chuyển sang fail-open sau vài giây",
        "Chỉ có Shorten service bị ảnh hưởng, các service khác không đổi",
      ],
      answerIndex: 1,
      explanation: "Fail-closed nghĩa là 'không chắc thì từ chối' — an toàn cho từng service riêng lẻ nhưng khi limiter là hạ tầng DÙNG CHUNG, sự cố của nó lan ra toàn bộ 50 service phụ thuộc cùng lúc.",
    },
    {
      id: "rate-limit-position-per-plan",
      question: "Cần giới hạn khác nhau theo gói dịch vụ (free: 10 link/phút, pro: 1.000 link/phút). Nên áp rule này ở đâu?",
      options: [
        "Chỉ ở Nginx `limit_req` tại edge, vì edge luôn nhanh hơn",
        "Ở tầng service (trong code nghiệp vụ), vì cần biết user thuộc gói nào — logic đó không có sẵn ở edge",
        "Không thể làm được vì rate limiter chỉ hoạt động theo IP",
        "Ở CDN, vì CDN cache được mọi loại rule",
      ],
      answerIndex: 1,
      explanation: "Edge (Nginx/API gateway) thường chỉ biết IP hoặc token thô, không có ngữ cảnh nghiệp vụ như gói dịch vụ. Rule cần business logic (tra cứu plan của user) phải nằm ở tầng service — có thể kết hợp với một lớp rate limit thô hơn ở edge để chặn abuse chung.",
    },
    {
      id: "estimate-write-qps",
      question: "URL shortener nhận 100 triệu link mới mỗi tháng. QPS ghi trung bình cỡ bao nhiêu (dùng 1 tháng ≈ 30 × 10⁵ giây)?",
      options: ["Cỡ 3,3 QPS", "Cỡ 33 QPS", "Cỡ 333 QPS", "Cỡ 3.300 QPS"],
      answerIndex: 1,
      explanation: "100.000.000 / (30 × 10⁵) = 100.000.000 / 3.000.000 ≈ 33 QPS trung bình. Với read:write ≈ 100:1, QPS đọc (redirect) tương ứng cỡ 3.300 QPS trung bình — đây là con số quyết định phải đầu tư cache ngay từ đầu.",
    },
  ],
};
