import type { ModuleDefinition } from "@/content/content-types";

export const m08AwsStorageDatabaseServerlessModule: ModuleDefinition = {
  id: "m08",
  slug: "m08-aws-storage-database-serverless",
  phaseId: "phase-2",
  order: 8,
  weeks: "Tuần 13",
  title: "AWS Storage, Database & Serverless",
  emoji: "🗄️",
  eli5Summary:
    "App nào cũng cần chỗ cất đồ: kho hàng (S3), ổ cứng riêng (EBS), sổ sách kế toán (RDS), tủ lạnh để lấy nhanh (ElastiCache) và két sắt cho mật khẩu (Secrets Manager). Module này dạy bạn chọn đúng chỗ cất, và cho những 'nhân viên thời vụ' Lambda tự làm việc mỗi khi có sự kiện.",
  objectives: [
    "Chọn đúng giữa S3, EBS và EFS cho từng loại dữ liệu",
    "Bảo vệ S3 bucket (Block Public Access, bucket policy), dùng pre-signed URL và lifecycle để tiết kiệm",
    "Phân biệt RDS Multi-AZ với read replica; backup, restore và parameter group",
    "Thiết kế bảng DynamoDB theo partition key và giảm tải DB bằng ElastiCache (cache-aside)",
    "Xây luồng event-driven với Lambda, API Gateway, SQS, SNS, EventBridge",
    "Lấy secret từ Secrets Manager / Parameter Store thay vì file env",
  ],
  lessons: [
    { slug: "ebs-efs-s3-storage-types", title: "EBS vs EFS vs S3", minutes: 35, summary: "Ổ cứng riêng, ổ mạng chung và kho hàng object — mỗi loại một việc." },
    { slug: "s3-deep-dive", title: "S3 chuyên sâu: bảo mật, lifecycle, pre-signed URL", minutes: 50, summary: "Storage classes, versioning, bucket policy, upload trực tiếp bằng URL có chữ ký." },
    { slug: "rds-aurora-high-availability", title: "RDS & Aurora: Multi-AZ, read replica, backup", minutes: 50, summary: "Database quản lý sẵn: failover tự động, chia tải đọc và khôi phục theo thời điểm." },
    { slug: "dynamodb-elasticache", title: "DynamoDB & ElastiCache", minutes: 45, summary: "NoSQL theo partition key và tủ lạnh Redis giúp đọc nhanh hơn." },
    { slug: "lambda-event-driven-serverless", title: "Lambda, API Gateway & event-driven", minutes: 50, summary: "Nhân viên thời vụ Lambda cùng bưu điện SQS, loa phát thanh SNS, tổng đài EventBridge." },
    { slug: "secrets-manager-parameter-store", title: "Secrets Manager vs Parameter Store", minutes: 35, summary: "Két sắt cho mật khẩu: lấy secret bằng IAM role, xoay vòng tự động." },
  ],
  labs: [
    {
      id: "rds-multi-az-elasticache",
      title: "Chuyển Postgres sang RDS Multi-AZ & Redis sang ElastiCache",
      description: "Đưa database và cache của app vào private subnet, dùng dịch vụ quản lý sẵn thay vì tự chạy container.",
      steps: [
        "Tạo DB subnet group gồm 2 private subnet ở 2 AZ: `aws rds create-db-subnet-group --db-subnet-group-name app-db-subnets --db-subnet-group-description \"app db\" --subnet-ids subnet-aaa subnet-bbb`",
        "Tạo security group `db-sg` chỉ cho phép port 5432 từ security group của app (không mở 0.0.0.0/0)",
        "Tạo RDS Postgres: `aws rds create-db-instance --db-instance-identifier app-db --engine postgres --db-instance-class db.t4g.micro --allocated-storage 20 --master-username appadmin --manage-master-user-password --multi-az --no-publicly-accessible --db-subnet-group-name app-db-subnets --vpc-security-group-ids sg-db --backup-retention-period 7`",
        "`pg_dump` database cũ và `pg_restore` vào endpoint RDS mới; đổi `DATABASE_HOST` của app",
        "Tạo ElastiCache Redis/Valkey 2 node Multi-AZ trong cache subnet group riêng; app đọc sản phẩm theo cache-aside với TTL",
        "Thử failover: `aws rds reboot-db-instance --db-instance-identifier app-db --force-failover`, đo thời gian app mất kết nối và xác nhận endpoint không đổi",
      ],
    },
    {
      id: "s3-presigned-upload-lifecycle",
      title: "Upload file người dùng qua pre-signed URL + lifecycle",
      description: "Người dùng upload thẳng lên S3 private bucket; file cũ tự chuyển sang lớp lưu trữ rẻ hơn.",
      steps: [
        "Tạo bucket, bật versioning và Block Public Access: `aws s3api put-bucket-versioning --bucket shop-uploads-<account-id> --versioning-configuration Status=Enabled`",
        "Thêm CORS cho phép `PUT` từ domain frontend của bạn",
        "Viết endpoint `POST /uploads` dùng SDK tạo pre-signed URL cho `PutObject`, hết hạn 5 phút, key do server đặt (`uploads/<user-id>/<uuid>`)",
        "Frontend `PUT` file lên URL; thử dùng lại URL sau khi hết hạn và xác nhận nhận `403`",
        "Tạo lifecycle rule: `uploads/` sang `STANDARD_IA` sau 30 ngày, xoá multipart upload dở dang sau 7 ngày (`aws s3api put-bucket-lifecycle-configuration`)",
        "Kiểm tra lại bằng `aws s3api get-bucket-lifecycle-configuration --bucket shop-uploads-<account-id>`",
      ],
    },
    {
      id: "lambda-s3-image-resize",
      title: "Lambda resize ảnh khi có object mới",
      description: "S3 event notification kích hoạt Lambda tạo thumbnail — không cần server nào chạy chờ.",
      steps: [
        "Tạo IAM role cho Lambda: đọc `shop-uploads/uploads/*`, ghi vào bucket `shop-thumbnails`, và `AWSLambdaBasicExecutionRole` để ghi log",
        "Viết hàm resize (vd Python + Pillow hoặc Node + sharp), đóng gói và `aws lambda create-function ... --timeout 30 --memory-size 512`",
        "Cho S3 quyền gọi hàm: `aws lambda add-permission --function-name resize-image --statement-id s3-invoke --action lambda:InvokeFunction --principal s3.amazonaws.com --source-arn arn:aws:s3:::shop-uploads-<account-id>`",
        "Cấu hình event notification `s3:ObjectCreated:*` với prefix `uploads/` (`aws s3api put-bucket-notification-configuration`)",
        "Upload một ảnh, xem log bằng `aws logs tail /aws/lambda/resize-image --follow` và kiểm tra thumbnail xuất hiện ở bucket đích",
        "Ghi thumbnail sang bucket/prefix khác để tránh vòng lặp vô hạn Lambda tự kích hoạt chính nó",
      ],
    },
    {
      id: "secrets-manager-db-password",
      title: "Lấy DB password từ Secrets Manager",
      description: "Xoá mật khẩu khỏi file env; app lấy secret lúc khởi động bằng IAM role.",
      steps: [
        "Tìm secret RDS đã tạo bởi `--manage-master-user-password`: `aws rds describe-db-instances --db-instance-identifier app-db --query \"DBInstances[0].MasterUserSecret.SecretArn\"`",
        "Tạo user riêng cho app trong Postgres và lưu vào secret `prod/shop/db` bằng `aws secretsmanager create-secret`",
        "Gắn policy cho role của app: chỉ `secretsmanager:GetSecretValue` trên ARN của `prod/shop/db`",
        "Sửa app: đọc secret bằng SDK khi khởi động (hoặc dùng `secrets` trong ECS task definition), cache trong bộ nhớ",
        "Xoá `DB_PASSWORD` khỏi `.env`, user data và biến môi trường dạng plaintext; chạy lại app và xác nhận kết nối DB OK",
        "Đưa cấu hình không bí mật (log level, feature flag) vào Parameter Store: `aws ssm put-parameter --name /prod/shop/log-level --type String --value info`",
      ],
    },
  ],
  deliverable: "App chạy với RDS Multi-AZ + ElastiCache trong private subnet, upload ảnh lên S3 qua pre-signed URL, 1 Lambda tạo thumbnail, DB password lấy từ Secrets Manager — kèm README mô tả kiến trúc.",
  successCriteria:
    "Force failover RDS mà app tự kết nối lại không cần sửa cấu hình; bucket không public; không còn secret nào trong Git, image hay file env; upload ảnh mới sinh thumbnail trong vài giây.",
  resources: [
    { title: "Amazon S3 User Guide", url: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html", kind: "doc" },
    { title: "Amazon RDS Multi-AZ deployments", url: "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html", kind: "doc" },
    { title: "Amazon DynamoDB Developer Guide", url: "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Introduction.html", kind: "doc" },
    { title: "AWS Lambda Developer Guide", url: "https://docs.aws.amazon.com/lambda/latest/dg/welcome.html", kind: "doc" },
    { title: "Tutorial: Using an Amazon S3 trigger to invoke a Lambda function", url: "https://docs.aws.amazon.com/lambda/latest/dg/with-s3-example.html", kind: "practice" },
    { title: "AWS Secrets Manager User Guide", url: "https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html", kind: "doc" },
    { title: "Caching strategies for ElastiCache", url: "https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/Strategies.html", kind: "doc" },
    { title: "Serverless Land — patterns & tutorials", url: "https://serverlessland.com/", kind: "practice" },
  ],
  quiz: [
    {
      id: "shared-file-system-linux",
      question: "10 EC2 Linux ở 2 AZ cần cùng đọc/ghi một thư mục chứa file cấu hình và ảnh qua giao diện file system chuẩn. Chọn gì?",
      options: ["EBS gp3 gắn vào từng máy", "Amazon EFS", "S3 bucket mount như ổ đĩa", "Instance store"],
      answerIndex: 1,
      explanation: "EFS là 'ổ mạng chung của công ty': NFS, nhiều máy ở nhiều AZ mount cùng lúc. EBS gắn trong 1 AZ, instance store mất dữ liệu khi stop, S3 là object storage qua API.",
    },
    {
      id: "presigned-upload",
      question: "App mobile cần cho user upload video lớn lên bucket private mà không làm quá tải backend và không public bucket. Cách tốt nhất?",
      options: [
        "Tắt Block Public Access và cho phép public PUT",
        "Upload video qua API server rồi server chuyển lên S3",
        "Nhúng access key IAM user vào app mobile",
        "Backend tạo pre-signed URL ngắn hạn cho PutObject, app PUT thẳng lên S3",
      ],
      answerIndex: 3,
      explanation: "Pre-signed URL là 'phiếu gửi hàng có chữ ký': đúng key, đúng thao tác, có hạn. File đi thẳng vào S3, bucket vẫn private, không lộ credentials.",
    },
    {
      id: "s3-lifecycle-infrequent",
      question: "Log ứng dụng được đọc thường xuyên trong 30 ngày đầu, hiếm khi sau đó, phải giữ 1 năm và có thể chờ vài giờ khi cần lấy lại. Thiết kế tiết kiệm nhất?",
      options: [
        "Lifecycle: Standard → Glacier Flexible Retrieval sau 30 ngày → expire sau 365 ngày",
        "Để Standard mãi, xoá thủ công mỗi năm",
        "Ghi thẳng vào Glacier Deep Archive từ ngày đầu",
        "Lưu trên EBS io2 để truy xuất nhanh",
      ],
      answerIndex: 0,
      explanation: "Lifecycle tự 'chuyển đồ ít dùng xuống kho lạnh'. Đọc nhiều 30 ngày đầu nên chưa đưa vào kho lạnh ngay; chấp nhận chờ vài giờ nên Glacier Flexible Retrieval phù hợp, rồi expire để khỏi trả tiền mãi.",
    },
    {
      id: "rds-multi-az-vs-replica",
      question: "Yêu cầu: database Postgres phải tự động chuyển sang AZ khác khi AZ chính sự cố, app giữ nguyên endpoint. Chọn cấu hình nào?",
      options: ["Read replica cùng region", "Manual snapshot mỗi giờ", "RDS Multi-AZ", "Tăng instance class lớn hơn"],
      answerIndex: 2,
      explanation: "Multi-AZ = 'thủ quỹ dự bị ghi sổ song song': replication đồng bộ, failover tự động, cùng endpoint. Read replica bất đồng bộ và phải promote thủ công.",
    },
    {
      id: "read-heavy-reporting",
      question: "Truy vấn báo cáo nặng buổi tối làm chậm trang thanh toán trên RDS MySQL. Báo cáo chấp nhận dữ liệu trễ vài giây. Giải pháp phù hợp nhất?",
      options: [
        "Bật Multi-AZ và chạy báo cáo trên standby",
        "Tạo read replica và trỏ công cụ báo cáo vào endpoint của replica",
        "Chuyển sang DynamoDB",
        "Tăng backup retention lên 35 ngày",
      ],
      answerIndex: 1,
      explanation: "Standby của Multi-AZ (dạng một instance) không phục vụ đọc. Read replica có endpoint riêng để chia tải đọc, và 'trễ vài giây' đúng là replica lag chấp nhận được.",
    },
    {
      id: "restore-point-in-time",
      question: "Lúc 10:05 một migration xoá nhầm bảng. Automated backup đang bật. Bạn khôi phục thế nào?",
      options: [
        "Force failover sang standby Multi-AZ",
        "Promote read replica",
        "Chờ RDS tự sửa",
        "Restore to point in time lúc 10:04 ra một instance mới, rồi chuyển app/dữ liệu sang",
      ],
      answerIndex: 3,
      explanation: "Standby và replica sao chép luôn cả lệnh xoá — chúng bảo vệ khỏi hỏng hạ tầng, không bảo vệ khỏi lỗi dữ liệu. PITR tạo instance mới ở thời điểm trước sự cố.",
    },
    {
      id: "dynamodb-hot-partition",
      question: "Bảng DynamoDB `Orders` dùng partition key là `status` (chỉ có PENDING/PAID/SHIPPED). Khi tải tăng, request bị throttle dù tổng capacity còn dư. Nguyên nhân chính?",
      options: [
        "Partition key ít giá trị khiến dữ liệu dồn vào vài partition nóng",
        "DynamoDB không hỗ trợ quá 3 giá trị khác nhau",
        "Cần bật Multi-AZ cho DynamoDB",
        "Item vượt quá 1 KB",
      ],
      answerIndex: 0,
      explanation: "Partition key như 'số tủ' trong kho: chỉ 3 tủ thì mọi người chen vào cùng tủ. Chọn key có nhiều giá trị, phân bố đều (vd `customerId`, `orderId`).",
    },
    {
      id: "cache-stale-data",
      question: "Sau khi thêm ElastiCache cache-aside với TTL 1 giờ, khách thấy giá cũ sau khi admin đổi giá. Cách sửa hợp lý nhất?",
      options: [
        "Bỏ TTL để cache giữ mãi",
        "Chuyển cache sang read replica",
        "Khi cập nhật giá trong DB, xoá (DEL) key tương ứng trong cache; giữ TTL làm lưới an toàn",
        "Tăng số node Redis",
      ],
      answerIndex: 2,
      explanation: "Tủ lạnh vẫn giữ món cũ tới hết hạn. Ghi DB xong thì 'dọn món cũ' khỏi cache để lần đọc sau nạp giá mới.",
    },
    {
      id: "decouple-sqs",
      question: "API nhận đơn hàng bị timeout khi dịch vụ xuất hoá đơn chậm. Muốn API trả lời ngay, hoá đơn xử lý sau, không mất đơn khi worker lỗi. Chọn gì?",
      options: [
        "Gọi Lambda đồng bộ và tăng timeout API Gateway",
        "Đẩy message vào SQS, worker poll xử lý, lỗi nhiều lần thì vào DLQ",
        "SNS gửi email cho kế toán",
        "Tăng instance size của dịch vụ hoá đơn",
      ],
      answerIndex: 1,
      explanation: "SQS là 'hộp thư chờ': API chỉ bỏ thư vào hộp rồi trả lời. Message nằm đó tới khi worker xử lý xong; lỗi lặp lại thì chuyển sang DLQ để điều tra.",
    },
    {
      id: "fan-out-sns-sqs",
      question: "Mỗi đơn hàng mới cần đồng thời: gửi email, cập nhật analytics, ghi audit — và sau này sẽ thêm consumer khác mà không sửa code producer. Pattern nào?",
      options: ["Một SQS queue chung cho 3 dịch vụ", "Producer gọi lần lượt 3 API", "Cron job quét database mỗi phút", "SNS topic fan-out tới nhiều SQS queue/Lambda"],
      answerIndex: 3,
      explanation: "SNS như 'loa phát thanh': mọi subscriber nhận bản sao. Một queue chung thì mỗi message chỉ một consumer lấy được.",
    },
    {
      id: "secrets-rotation",
      question: "Kiểm toán yêu cầu mật khẩu RDS được xoay vòng tự động định kỳ và app lấy mật khẩu bằng IAM. Dịch vụ phù hợp nhất?",
      options: ["AWS Secrets Manager", "SSM Parameter Store SecureString", "Biến môi trường Lambda", "File .env mã hoá trong S3"],
      answerIndex: 0,
      explanation: "Secrets Manager là 'két sắt có thợ đổi khoá': hỗ trợ rotation sẵn (có cả managed rotation cho RDS). Parameter Store lưu SecureString tốt nhưng không có rotation tích hợp.",
    },
  ],
};
