import type { ModuleDefinition } from "@/content/content-types";

export const b05AuthenticationJwtRefreshTokenModule: ModuleDefinition = {
  id: "b05",
  slug: "b05-authentication-jwt-refresh-token",
  phaseId: "b-phase-1",
  order: 5,
  weeks: "Tuần 7",
  title: "Authentication: JWT & refresh token",
  emoji: "🔐",
  eli5Summary:
    "Đăng nhập một lần, nhưng mỗi request sau đó `taskflow-api` phải biết bạn là ai mà không hỏi lại mật khẩu. Module này dạy cách phát một 'vé ra vào' ngắn hạn (access token) cùng một 'thẻ đổi vé mới' dài hạn (refresh token) mà server có thể thu hồi bất cứ lúc nào — và cách cất giữ mật khẩu để dù DB bị lộ cũng không ai đăng nhập giả được.",
  objectives: [
    "Hash mật khẩu đúng cách bằng argon2id + salt, giải thích vì sao không dùng SHA-256/MD5",
    "Phát hành access token (JWT, 15 phút) và refresh token (opaque, 7 ngày, lưu hash trong DB)",
    "Chọn đúng nơi lưu token (cookie httpOnly vs Authorization header) theo từng loại client",
    "Xây luồng `/auth/refresh` cấp access token mới và `/auth/logout` revoke refresh token thật sự trong DB",
    "Nhận diện các sai lầm JWT phổ biến: nhét dữ liệu nhạy cảm vào payload, không kiểm tra `exp`, tin token mà không xác minh chữ ký",
  ],
  lessons: [
    {
      slug: "password-hashing-salt",
      title: "Hash mật khẩu: salt & argon2id",
      minutes: 35,
      summary: "Vì sao hai người dùng cùng mật khẩu vẫn có hash khác nhau trong DB — và vì sao SHA-256 là lựa chọn sai.",
    },
    {
      slug: "jwt-access-refresh-tokens",
      title: "JWT access token & refresh token",
      minutes: 45,
      summary: "Vé ra vào ngắn hạn ký bằng JWT, thẻ đổi vé dài hạn lưu hash trong DB — và luồng issue/verify/refresh qua nhiều request.",
    },
    {
      slug: "cookie-vs-authorization-header",
      title: "Lưu token: cookie httpOnly vs Authorization header",
      minutes: 35,
      summary: "Trình duyệt thì dùng cookie httpOnly, app di động/CLI thì dùng header — chọn sai chỗ nào cũng lộ token.",
    },
    {
      slug: "refresh-logout-flow",
      title: "Luồng refresh & logout đúng cách",
      minutes: 40,
      summary: "Refresh token phải revoke được trong DB — logout mà chỉ xoá cookie thì token cũ vẫn dùng được.",
    },
    {
      slug: "jwt-common-pitfalls",
      title: "Sai lầm JWT thường gặp",
      minutes: 30,
      summary: "JWT được ký chứ không được mã hoá — ai cũng đọc được payload, và những cạm bẫy khác dễ bị bỏ sót.",
    },
  ],
  labs: [
    {
      id: "users-memberships-refresh-tokens-migration",
      title: "Migration: users, memberships, refresh_tokens",
      description: "Thêm 3 bảng mới vào schema Drizzle của `taskflow-api` bằng migration riêng, không đụng vào bảng của B04.",
      steps: [
        "Trong `src/db/schema.ts`, thêm `users` (`id uuid pk default gen_random_uuid()`, `email text unique`, `password_hash text`, `name text`, `created_at timestamptz default now()`) đúng tên cột ở mục 3 curriculum",
        "Thêm `memberships` (`user_id` fk `users.id`, `organization_id` fk `organizations.id`, `role text` check `owner|admin|member`, khoá chính gộp `(user_id, organization_id)`)",
        "Thêm `refresh_tokens` (`id uuid pk`, `user_id` fk `users.id`, `token_hash text not null`, `expires_at timestamptz not null`, `revoked_at timestamptz`, `created_at timestamptz default now()`) — thiết kế riêng cho module này vì chưa được chốt ở mục 3",
        "Sinh migration: `pnpm drizzle-kit generate` rồi kiểm tra file SQL sinh ra trong `drizzle/` đúng 3 bảng, không đổi bảng cũ",
        "Chạy migration vào Postgres của `taskflow-api`: `pnpm drizzle-kit migrate`",
        "Xác nhận bằng `docker compose exec postgres psql -U taskflow -c '\\dt'` thấy đủ 6 bảng (4 bảng B04 + `users` + `memberships`), và `refresh_tokens` (bảng thứ 7)",
      ],
    },
    {
      id: "register-login-endpoints",
      title: "Endpoint đăng ký & đăng nhập",
      description: "`POST /api/v1/auth/register` và `/api/v1/auth/login` — hash mật khẩu bằng argon2id, phát access + refresh token.",
      steps: [
        "Cài `argon2` (`pnpm add argon2`) và `@fastify/jwt` (`pnpm add @fastify/jwt`)",
        "Đăng ký plugin `@fastify/jwt` trong `src/plugins/jwt.ts` với `secret: env.JWT_ACCESS_SECRET`, `sign: { expiresIn: '15m' }`",
        "Viết `POST /api/v1/auth/register`: validate body bằng Zod (`email`, `password` ≥ 8 ký tự, `name`), kiểm tra email chưa tồn tại (trả `409` nếu trùng), hash bằng `argon2.hash(password, { type: argon2.argon2id })`, insert vào `users`",
        "Viết `POST /api/v1/auth/login`: tìm user theo email, `argon2.verify(user.passwordHash, password)`, sai thì trả `401` chung chung (không tiết lộ email có tồn tại hay không)",
        "Khi login thành công: ký access token bằng `reply.jwtSign({ sub: user.id })`, sinh refresh token bằng `crypto.randomBytes(32).toString('base64url')`, hash bằng SHA-256 rồi insert vào `refresh_tokens` với `expires_at = now() + 7 ngày`",
        "Trả về access token trong body, refresh token trong cookie `httpOnly; Secure; SameSite=Strict` (dùng `@fastify/cookie`)",
      ],
    },
    {
      id: "refresh-logout-endpoints",
      title: "Endpoint refresh & logout",
      description: "`POST /api/v1/auth/refresh` cấp access token mới, `POST /api/v1/auth/logout` revoke refresh token thật sự trong DB.",
      steps: [
        "Viết `POST /api/v1/auth/refresh`: đọc refresh token từ cookie, hash SHA-256, query `refresh_tokens` theo `token_hash`",
        "Từ chối (`401`) nếu không tìm thấy row, hoặc `revoked_at IS NOT NULL`, hoặc `expires_at < now()`",
        "Nếu hợp lệ: ký access token mới bằng `@fastify/jwt`, xoay vòng refresh token (revoke row cũ, insert row mới) để giới hạn thời gian sống của một refresh token nếu bị lộ",
        "Viết `POST /api/v1/auth/logout`: hash refresh token từ cookie, `UPDATE refresh_tokens SET revoked_at = now() WHERE token_hash = $1`, rồi mới xoá cookie ở response",
        "Thêm `preHandler` hook `authenticate` dùng `request.jwtVerify()` để bảo vệ route cần đăng nhập, trả `401` kèm `{ error: { code: 'UNAUTHORIZED', ... } }` đúng format lỗi chuẩn khi verify thất bại",
      ],
    },
    {
      id: "auth-security-tests",
      title: "Test: token hết hạn & token đã revoke",
      description: "Viết test Vitest chứng minh access token hết hạn và refresh token đã revoke đều bị từ chối, không chỉ 'nhìn có vẻ đúng'.",
      steps: [
        "Test 1: ký một access token với `expiresIn: '-1s'` (đã hết hạn ngay khi tạo), gọi route được bảo vệ, assert response `401`",
        "Test 2: login thật để lấy refresh token, gọi `/auth/logout` để revoke, sau đó gọi `/auth/refresh` bằng chính refresh token đó, assert `401` (không được cấp access token mới)",
        "Test 3: gọi `/auth/refresh` bằng một chuỗi ngẫu nhiên không tồn tại trong `refresh_tokens`, assert `401` — chứng minh không lộ thông tin qua timing hay lỗi khác nhau giữa 'không tồn tại' và 'đã revoke'",
        "Chạy `pnpm test` — cả 3 test phải xanh trước khi coi lab hoàn thành",
      ],
    },
  ],
  deliverable:
    "`taskflow-api` có migration `users`/`memberships`/`refresh_tokens`, 4 endpoint `/api/v1/auth/{register,login,refresh,logout}` hoạt động thật với Postgres, cùng bộ test Vitest cho token hết hạn và token bị revoke.",
  successCriteria:
    "Đăng ký → đăng nhập → gọi route bảo vệ bằng access token → đợi hết hạn → refresh lấy token mới → logout → refresh lại bằng token cũ bị từ chối. Toàn bộ luồng chạy được bằng `curl` thật, `pnpm test` xanh.",
  resources: [
    { title: "OWASP Authentication Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html", kind: "doc" },
    { title: "jwt.io — Introduction to JSON Web Tokens", url: "https://jwt.io/introduction", kind: "doc" },
    { title: "Auth0 blog — Refresh Token Rotation", url: "https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/", kind: "doc" },
    { title: "node-argon2 (npm)", url: "https://www.npmjs.com/package/argon2", kind: "tool" },
    { title: "@fastify/jwt docs", url: "https://github.com/fastify/fastify-jwt", kind: "doc" },
    { title: "OWASP JSON Web Token Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html", kind: "doc" },
  ],
  quiz: [
    {
      id: "why-not-sha256-password",
      question: "Vì sao không nên hash mật khẩu bằng SHA-256 dù nó rất phổ biến để hash file?",
      options: [
        "SHA-256 không chạy được trên Node.js",
        "SHA-256 quá nhanh — kẻ tấn công có DB leak có thể thử hàng tỷ mật khẩu/giây bằng GPU",
        "SHA-256 tạo ra chuỗi quá ngắn để lưu",
        "SHA-256 không hỗ trợ tiếng Việt có dấu",
      ],
      answerIndex: 1,
      explanation: "SHA-256 được thiết kế để NHANH (tốt cho checksum), nhưng nhanh lại là điểm yếu chí mạng cho mật khẩu — argon2id cố tình chậm và tốn RAM để việc dò brute-force trở nên đắt đỏ.",
    },
    {
      id: "purpose-of-salt",
      question: "Hai user cùng đặt mật khẩu `matkhau123`. Salt giúp gì trong tình huống này?",
      options: [
        "Làm hash chạy nhanh hơn",
        "Giúp hai hash trong DB khác nhau hoàn toàn, dù mật khẩu gốc giống hệt nhau — chặn rainbow table",
        "Mã hoá mật khẩu để giải mã lại khi cần",
        "Nén mật khẩu để tốn ít dung lượng hơn",
      ],
      answerIndex: 1,
      explanation: "Salt là một chuỗi ngẫu nhiên riêng cho mỗi user, trộn vào trước khi hash. Cùng mật khẩu nhưng khác salt → hash khác nhau, và attacker không thể dùng một bảng tra cứu (rainbow table) chung cho mọi user.",
    },
    {
      id: "argon2id-vs-sha256-refresh-token",
      question: "Refresh token của `taskflow-api` lại được hash bằng SHA-256 (nhanh) thay vì argon2id (chậm) như mật khẩu. Vì sao khác nhau mà cả hai vẫn hợp lý?",
      options: [
        "Refresh token không quan trọng bằng mật khẩu nên không cần hash kỹ",
        "SHA-256 rẻ hơn để chạy trên server",
        "Refresh token là chuỗi ngẫu nhiên 256-bit entropy cao — không thể brute-force dù hash nhanh; mật khẩu do người chọn, entropy thấp, cần hash chậm để bù lại",
        "Vì refresh token không lưu trong DB nên hash thế nào cũng được",
      ],
      answerIndex: 2,
      explanation: "argon2id chậm là để bù cho việc mật khẩu con người dễ đoán. Refresh token do `crypto.randomBytes(32)` sinh ra có độ ngẫu nhiên rất cao — dò ngược gần như bất khả thi dù hash nhanh, và hash nhanh còn cần thiết để so sánh/lookup hiệu quả trong DB.",
    },
    {
      id: "jwt-not-encrypted",
      question: "Một dev nhét `{ sub: userId, creditCardNumber: '...' }` vào payload JWT vì \"đã ký (signed) rồi nên an toàn\". Sai ở đâu?",
      options: [
        "Không sai, JWT đã ký thì không ai đọc được payload",
        "JWT mặc định chỉ được KÝ (signature chống giả mạo), không được MÃ HOÁ — ai có token đều decode base64 đọc được payload",
        "Chỉ sai vì tên field `creditCardNumber` quá dài",
        "Sai vì JWT không hỗ trợ nested object",
      ],
      answerIndex: 1,
      explanation: "Chữ ký (HMAC/RSA) chứng minh token không bị sửa, nhưng payload chỉ base64url-encode — decode được bằng một dòng lệnh, không cần biết secret. Không bao giờ đặt dữ liệu nhạy cảm vào payload JWT.",
    },
    {
      id: "short-lived-access-token-reason",
      question: "Vì sao access token chỉ nên sống ngắn (~15 phút) thay vì để 7 ngày như refresh token?",
      options: [
        "Vì JWT dài quá 15 phút sẽ lỗi cú pháp",
        "Vì access token không thể revoke được (server chỉ kiểm tra chữ ký + `exp`, không tra DB mỗi request) — sống ngắn giới hạn thiệt hại nếu nó bị đánh cắp",
        "Vì Fastify giới hạn thời gian sống của JWT",
        "Vì access token cần đổi liên tục để tăng tốc độ xử lý",
      ],
      answerIndex: 1,
      explanation: "Access token thường được verify chỉ bằng chữ ký (không query DB) để nhanh — đổi lại là không thể revoke giữa chừng. Thời hạn ngắn là cơ chế 'tự huỷ' bù cho việc không revoke được.",
    },
    {
      id: "logout-must-revoke-db",
      question: "Client gọi `/auth/logout`. Server chỉ set cookie refresh token thành rỗng rồi trả `200`. Vấn đề gì có thể xảy ra?",
      options: [
        "Không có vấn đề gì, cookie rỗng là đã đăng xuất",
        "Nếu attacker đã sao chép refresh token gốc trước đó (ví dụ qua XSS), họ vẫn gọi `/auth/refresh` bằng token cũ và tiếp tục có access token mới — vì DB chưa revoke token đó",
        "Trình duyệt sẽ tự động xoá luôn access token",
        "Server sẽ bị crash vì cookie rỗng",
      ],
      answerIndex: 1,
      explanation: "Xoá cookie chỉ ảnh hưởng trình duyệt của người dùng đó — refresh token (chuỗi thật) vẫn còn nguyên và hợp lệ trong DB. Logout đúng cách phải `UPDATE refresh_tokens SET revoked_at = now()` để token đó không dùng lại được, dù ai đang giữ nó.",
    },
    {
      id: "cookie-httponly-vs-header",
      question: "Vì sao trình duyệt web nên lưu refresh token trong cookie `httpOnly` thay vì `localStorage` rồi tự gắn vào header?",
      options: [
        "localStorage chậm hơn cookie",
        "Cookie `httpOnly` không thể đọc được bằng JavaScript — nếu site dính lỗi XSS, script độc hại không lấy được token; localStorage thì JavaScript nào cũng đọc được",
        "Cookie có dung lượng lớn hơn localStorage",
        "Authorization header không hoạt động trên HTTPS",
      ],
      answerIndex: 1,
      explanation: "`httpOnly` chặn `document.cookie` đọc giá trị đó — lớp phòng thủ quan trọng nếu site có XSS. Đổi lại cookie cần `SameSite`/CSRF token để chống CSRF. Với client không phải trình duyệt (mobile app, CLI, service-to-service), không có khái niệm cookie httpOnly nên Authorization header là lựa chọn hợp lý hơn.",
    },
    {
      id: "expired-token-rejected",
      question: "Access token hết hạn 2 phút trước vẫn được client gửi lên route bảo vệ. Điều gì xảy ra khi gọi `request.jwtVerify()`?",
      options: [
        "Verify vẫn pass vì chữ ký vẫn đúng, chỉ có `exp` là sai",
        "`jwtVerify()` kiểm tra cả chữ ký lẫn claim `exp` — token hết hạn ném lỗi, route trả `401` dù chữ ký hợp lệ",
        "Server tự động gia hạn thêm 15 phút nữa",
        "Chỉ bị từ chối nếu server restart",
      ],
      answerIndex: 1,
      explanation: "Xác minh JWT gồm 2 phần: chữ ký đúng (chưa bị sửa) VÀ chưa hết hạn theo `exp`. Thiếu bước kiểm tra `exp` là lỗi bảo mật kinh điển — `@fastify/jwt` làm cả hai khi bạn gọi `jwtVerify()`.",
    },
    {
      id: "refresh-token-rotation",
      question: "\"Refresh token rotation\" (mỗi lần refresh, revoke token cũ và phát token mới) giúp giảm rủi ro gì?",
      options: [
        "Giúp giảm tải cho database",
        "Giới hạn thời gian một refresh token bị đánh cắp còn dùng được — nếu attacker dùng token đã bị rotate, hệ thống phát hiện được (token đó đã revoke) và có thể revoke luôn cả chuỗi",
        "Giúp access token không cần chữ ký nữa",
        "Giúp người dùng không cần đăng nhập lại sau 7 ngày",
      ],
      answerIndex: 1,
      explanation: "Rotation biến mỗi refresh token thành dùng-một-lần. Nếu cả client thật và attacker cùng cố refresh bằng token đã bị rotate, request thứ hai sẽ thấy token đó `revoked_at` khác null — dấu hiệu rõ ràng của việc token bị lộ.",
    },
    {
      id: "generic-login-error",
      question: "Vì sao `/auth/login` nên trả cùng một lỗi `401` chung chung cho cả hai trường hợp \"email không tồn tại\" và \"sai mật khẩu\"?",
      options: [
        "Vì viết ít code hơn",
        "Vì phân biệt hai lỗi cho phép attacker dò được danh sách email nào đã đăng ký (user enumeration) trước khi tấn công mật khẩu",
        "Vì Fastify không cho phép trả nhiều loại lỗi khác nhau",
        "Vì argon2 chỉ trả về đúng một loại lỗi",
      ],
      answerIndex: 1,
      explanation: "Nếu \"email không tồn tại\" và \"sai mật khẩu\" trả thông báo khác nhau, attacker có thể quét hàng loạt email để biết cái nào đã đăng ký (user enumeration), thu hẹp mục tiêu tấn công tiếp theo.",
    },
  ],
};
