import type { ModuleDefinition } from "@/content/content-types";

export const sd18CaseProximityBookingPaymentModule: ModuleDefinition = {
  id: "sd18",
  slug: "sd18-case-proximity-booking-payment",
  phaseId: "sd-phase-4",
  order: 18,
  weeks: "Tuần 22–23",
  title: "Case: Proximity, booking & payment",
  emoji: "📍",
  eli5Summary:
    "Ba bài toán tưởng khác nhau nhưng chung một gốc: dữ liệu không gian (tìm tài xế gần nhất kiểu Uber), tài nguyên có hạn nhiều người tranh (giữ ghế kiểu Ticketmaster), và tiền (thanh toán không được sai một đồng). Module này ghép cả ba vào chung một tuần vì đều cần cùng một kỹ năng: làm cho một thao tác 'kiểm tra rồi ghi' trở thành atomic dưới tải cạnh tranh cao.",
  objectives: [
    "Chọn đúng cấu trúc geospatial index (geohash, quadtree, H3, PostGIS + GiST) theo mật độ điểm và tần suất ghi, giải thích được vì sao geohash cần check thêm ô lân cận",
    "Thiết kế luồng cập nhật vị trí tần suất cao và matching có mở rộng bán kính khi chưa tìm được tài xế",
    "Chống double-booking bằng unique constraint / conditional update / `SELECT ... FOR UPDATE` thay vì chỉ thêm kiểm tra ở tầng app, kèm giữ chỗ có TTL",
    "Thiết kế virtual waiting room để giảm tải khi có traffic đột biến vào một tài nguyên giới hạn",
    "Thiết kế idempotency key được kiểm tra atomic với việc ghi ý định thanh toán, tránh double charge khi client retry",
    "Giải thích double-entry ledger (mỗi giao dịch là một cặp Nợ/Có cân nhau) và dùng nó để đối soát (reconciliation)",
  ],
  lessons: [
    {
      slug: "geospatial-index-nearest-driver",
      title: "Geospatial index & tìm tài xế gần nhất",
      minutes: 50,
      summary: "Geohash, quadtree, H3 và PostGIS `ST_DWithin` + GiST index — cách tránh quét toàn bộ 1 triệu điểm mỗi lần tìm tài xế gần nhất.",
    },
    {
      slug: "location-updates-and-matching",
      title: "Cập nhật vị trí tần suất cao & matching",
      minutes: 45,
      summary: "Vì sao không ghi mỗi ping GPS thẳng vào DB chính, và cách matching mở rộng bán kính tìm kiếm khi khu vực thưa tài xế.",
    },
    {
      slug: "booking-seat-hold-double-booking",
      title: "Booking: giữ chỗ, chống double-booking & virtual waiting room",
      minutes: 55,
      summary: "Giữ chỗ có TTL, atomic conditional update chống bán trùng ghế, và hàng đợi ảo để hạ tải khi mở bán vé đột biến.",
    },
    {
      slug: "payment-idempotency-ledger-reconciliation",
      title: "Payment: idempotency, ledger & reconciliation",
      minutes: 55,
      summary: "Idempotency key kiểm tra atomic để không trừ tiền hai lần, double-entry ledger, và đối soát với PSP.",
    },
  ],
  labs: [
    {
      id: "geo-query-comparison-1m-points",
      title: "1 triệu điểm: quét toàn bộ vs geohash vs PostGIS ST_DWithin",
      description: "Sinh 1 triệu vị trí tài xế giả lập trong Postgres, đo thời gian tìm K tài xế gần nhất bằng ba cách: quét toàn bộ, tự lọc theo geohash, và `ST_DWithin` với GiST index.",
      steps: [
        "Vào Postgres của `sd-playground`, bật extension: `docker compose exec postgres psql -U app -d app -c \"CREATE EXTENSION IF NOT EXISTS postgis;\"`",
        "Tạo bảng `driver_locations(id bigserial primary key, driver_id text, lng double precision, lat double precision, geom geography(Point, 4326), geohash text, updated_at timestamptz)` và sinh 1.000.000 điểm ngẫu nhiên quanh một thành phố (vd bằng `generate_series` + `random()` cho lng/lat trong bán kính ~30km, tính `geom` bằng `ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography`)",
        "Cách 1 — quét toàn bộ: chạy `SELECT driver_id, ST_Distance(geom, :point) AS d FROM driver_locations ORDER BY d LIMIT 10;` KHÔNG có index không gian, ghi lại `EXPLAIN (ANALYZE, BUFFERS)` và tổng thời gian",
        "Cách 2 — geohash tự lọc: thêm cột `geohash` (dùng thư viện `ngeohash` ở Node hoặc hàm PL/pgSQL), tạo `CREATE INDEX ON driver_locations (geohash);`, query theo `geohash LIKE 'prefix%'` cộng thêm 8 prefix ô lân cận, rồi mới tính khoảng cách chính xác trên tập nhỏ — so sánh thời gian và giải thích vì sao vẫn cần bước lọc lại bằng khoảng cách thật",
        "Cách 3 — PostGIS GiST: `CREATE INDEX driver_locations_geom_gist ON driver_locations USING GIST (geom);`, chạy `SELECT driver_id, ST_Distance(geom, :point) AS d FROM driver_locations WHERE ST_DWithin(geom, :point, 3000) ORDER BY geom <-> :point LIMIT 10;`, xem `EXPLAIN ANALYZE` có `Index Scan using driver_locations_geom_gist` không",
        "Lập bảng so sánh 3 cách theo: thời gian truy vấn (ms), có dùng index không, độ chính xác (có bỏ sót điểm nào không), và độ phức tạp cài đặt — kết luận PostGIS + GiST phù hợp khi nào so với tự làm geohash",
      ],
    },
    {
      id: "reproduce-fix-double-booking",
      title: "Tái hiện double-booking rồi sửa bằng conditional update + TTL",
      description: "1.000 request cùng tranh 10 ghế; trước tiên tái hiện double-booking bằng check-then-write ở app, sau đó sửa bằng atomic conditional update và giữ chỗ có TTL.",
      steps: [
        "Tạo bảng `seats(id int primary key, event_id int, status text default 'available', held_by text, hold_expires_at timestamptz)`, chèn 10 dòng cho `event_id = 1`",
        "Viết endpoint buggy `POST /events/:id/book-naive`: `SELECT status FROM seats WHERE ...` rồi nếu 'available' mới `UPDATE ... SET status='booked'` — chạy `k6` với 1000 VU gọi cùng lúc, đếm số dòng `status='booked'` so với số ghế (10) và số bản ghi booking được tạo ra — chỉ ra số vé vượt quá số ghế",
        "Sửa bằng atomic conditional update: `UPDATE seats SET status='held', held_by=:userId, hold_expires_at=now()+interval '2 minutes' WHERE id=:seatId AND status='available'`, kiểm tra `rowCount`; chạy lại k6 và xác nhận đúng 10 request thành công, còn lại nhận 409",
        "Thêm bước chốt: `POST /events/:id/confirm` chạy `UPDATE seats SET status='booked' WHERE id=:seatId AND status='held' AND held_by=:userId`; mô phỏng một vài user bỏ ngang (không gọi confirm)",
        "Viết job TTL sweeper chạy mỗi ~10s: `UPDATE seats SET status='available', held_by=NULL WHERE status='held' AND hold_expires_at < now()`; chứng minh ghế bị bỏ ngang được trả lại mà không cần restart service",
        "Ghi lại kết quả trước/sau vào báo cáo: số ghế bị bán trùng (phải về 0), p95 latency của endpoint giữ chỗ, và tỉ lệ request nhận 409 dưới tải cao",
      ],
    },
    {
      id: "design-doc-uber-ticketmaster-or-payment",
      title: "Design doc: chọn 1 trong 3 hệ thống (Uber-like, Ticketmaster-like, payment)",
      description: "Bấm giờ 45–60 phút, viết design doc đầy đủ theo Phụ lục A cho một trong ba hệ thống, rồi tự đối chiếu với các bài học và lab đã làm.",
      steps: [
        "Chọn một hệ thống: (a) proximity/dispatch kiểu Uber cho một thành phố 5 triệu dân, (b) booking vé kiểu Ticketmaster cho một sự kiện 50.000 vé mở bán cùng lúc, hoặc (c) payment system có ledger cho một sàn thương mại điện tử",
        "Bấm giờ 45–60 phút, viết mục 1–2 (Requirements + Ước lượng có số cụ thể, vd DAU, QPS đỉnh lúc mở bán/giờ cao điểm, storage) KHÔNG xem lại tài liệu",
        "Viết mục 3–5 (API, Data model, High-level design) — với Uber-like: quyết định geospatial index dùng gì; với Ticketmaster-like: seat hold + waiting room; với payment: idempotency key + ledger schema",
        "Viết mục 6 (Deep dive 2–3 điểm khó nhất) và mục 7 (bảng Trade-off & alternatives considered) — nêu rõ chọn gì, bỏ gì, khi nào đổi ý",
        "Viết mục 8 (Bottleneck, failure mode & mở rộng): điều gì sập trước tiên khi tải gấp 10, và cách mở rộng",
        "Đối chiếu bản viết với nội dung 4 bài học + 2 lab đã làm trong module: đánh dấu chỗ nào bạn đã bỏ sót (vd quên TTL sweeper, quên neighbor cell, quên atomic check idempotency key) và sửa lại",
      ],
    },
  ],
  deliverable:
    "Thư mục `sd18/` gồm: bảng so sánh thời gian truy vấn 3 cách tìm tài xế gần nhất trên 1M điểm, transcript demo double-booking (trước/sau khi sửa) kèm số liệu k6, và 1 design doc đầy đủ theo Phụ lục A cho một trong ba hệ thống (Uber-like, Ticketmaster-like, hoặc payment).",
  successCriteria:
    "Giải thích được vì sao geohash cần check ô lân cận còn PostGIS GiST thì không phải tự làm việc đó; demo 0 ghế bị bán trùng dưới 1000 request đồng thời; chỉ ra chính xác dòng code/transaction nào đảm bảo idempotency key được kiểm tra atomic với việc charge, và double-entry ledger cân bằng ở đâu trong luồng thanh toán.",
  resources: [
    { title: "PostGIS docs — ST_DWithin", url: "https://postgis.net/docs/ST_DWithin.html", kind: "doc" },
    { title: "PostGIS Workshop — Spatial Indexing (GiST)", url: "https://postgis.net/workshops/postgis-intro/indexing.html", kind: "doc" },
    { title: "Uber H3 — Hexagonal hierarchical spatial index", url: "https://h3geo.org/docs/", kind: "doc" },
    { title: "Stripe API docs — Idempotent requests", url: "https://stripe.com/docs/api/idempotent_requests", kind: "doc" },
    { title: "PostgreSQL docs — Explicit Locking", url: "https://www.postgresql.org/docs/current/explicit-locking.html", kind: "doc" },
    { title: "System Design Interview Vol. 2 (Alex Xu) — proximity & payment chapters, ByteByteGo", url: "https://bytebytego.com/", kind: "book" },
    { title: "Hello Interview — system design breakdowns (Uber, Ticketmaster)", url: "https://www.hellointerview.com/", kind: "course" },
    { title: "The System Design Primer (donnemartin, GitHub)", url: "https://github.com/donnemartin/system-design-primer", kind: "course" },
  ],
  quiz: [
    {
      id: "geohash-boundary-neighbor-cells",
      question: "App dùng geohash 7 ký tự để tìm tài xế gần nhất, chỉ query đúng cell chứa vị trí rider. QA báo cáo: có tài xế cách rider 8 mét nhưng không xuất hiện trong kết quả. Nguyên nhân hợp lý nhất?",
      options: [
        "Geohash chỉ hoạt động đúng ở khu vực gần xích đạo",
        "Tài xế đó chưa cập nhật vị trí đủ mới",
        "Tài xế nằm ở ô geohash liền kề — geohash có biên cứng, phải query cả 8 ô lân cận (khối 3×3) chứ không chỉ 1 ô",
        "Cần tăng độ dài geohash lên 9 ký tự để hết lỗi này",
      ],
      answerIndex: 2,
      explanation: "Geohash chia không gian thành lưới ô có biên rõ ràng: hai điểm cách nhau vài mét có thể rơi vào hai ô khác nhau nếu nằm sát biên. Query đúng 1 ô luôn có nguy cơ bỏ sót — phải kiểm tra thêm 8 ô lân cận. Tăng độ dài geohash làm ô nhỏ hơn, biên nhiều hơn, vấn đề còn nặng hơn.",
    },
    {
      id: "postgis-gist-vs-full-scan",
      question: "Bảng `driver_locations` có 1 triệu dòng. Câu query `SELECT * FROM driver_locations WHERE ST_DWithin(geom, :point, 2000) ORDER BY geom <-> :point LIMIT 10` chạy nhanh dù không có `WHERE driver_id = ...` nào để lọc trước. Vì sao?",
      options: [
        "GiST index trên cột `geom` cho phép Postgres nhảy thẳng tới các trang chứa điểm trong vùng bán kính, không cần đọc toàn bộ 1 triệu dòng",
        "PostGIS tự động cache toàn bộ bảng vào RAM",
        "`ST_DWithin` luôn nhanh bất kể có index hay không vì được tính gần đúng",
        "Vì bảng có primary key nên mọi query đều nhanh",
      ],
      answerIndex: 0,
      explanation: "Giống mục lục sách chia theo chương thay vì phải đọc từng trang: GiST index trên geometry/geography cho phép Postgres chỉ động tới các trang có khả năng chứa điểm trong bán kính, giống B-tree nhưng cho dữ liệu không gian. Không có index này, `ST_DWithin` vẫn đúng nhưng phải tính khoảng cách cho mọi dòng — sequential scan.",
    },
    {
      id: "h3-quadtree-vs-geohash-density",
      question: "Ứng dụng giao đồ ăn hoạt động ở cả trung tâm thành phố (mật độ tài xế rất cao) và ngoại ô (mật độ thấp). Geohash độ dài cố định gây ra vấn đề gì, và H3/quadtree giải quyết thế nào?",
      options: [
        "Geohash không hỗ trợ toạ độ âm nên không dùng được ở Nam bán cầu",
        "H3/quadtree chỉ nhanh hơn geohash về mặt lý thuyết, thực tế không khác biệt",
        "Không có vấn đề gì — geohash độ dài cố định phù hợp mọi mật độ",
        "Ô cố định khiến trung tâm thành phố có quá nhiều điểm trong 1 ô (phải lọc lại nhiều) còn ngoại ô lại quá thưa; H3 (resolution biến đổi) và quadtree (chia ô động theo mật độ) cho phép ô nhỏ hơn ở chỗ đông và lớn hơn ở chỗ thưa",
      ],
      answerIndex: 3,
      explanation: "Geohash với độ dài ký tự cố định tạo ra ô kích thước đều nhau bất kể mật độ điểm. Quadtree chia nhỏ ô khi có nhiều điểm (giống chia lại khu phố khi quá đông) và H3 cho phép chọn resolution phù hợp theo nhu cầu — cả hai xử lý tốt hơn dữ liệu phân bố không đều.",
    },
    {
      id: "high-frequency-location-writes",
      question: "Tài xế đẩy vị trí GPS mỗi 3 giây. Một dev đề xuất ghi thẳng mỗi ping vào bảng `driver_locations` trên Postgres primary (bảng cũng được matching service đọc liên tục). Rủi ro chính là gì?",
      options: [
        "Ghi tần suất cao (hàng trăm nghìn UPDATE/giây ở quy mô lớn) cạnh tranh I/O và lock với các read query matching liên tục trên cùng bảng/index, làm read latency tăng vọt — nên tách vị trí 'mới nhất' vào store riêng (Redis/in-memory) và đẩy lịch sử sang pipeline khác nếu cần",
        "Postgres không hỗ trợ kiểu dữ liệu toạ độ",
        "GPS ping không có ý nghĩa nếu tài xế đứng yên",
        "UPDATE luôn nhanh hơn INSERT nên không có vấn đề gì",
      ],
      answerIndex: 0,
      explanation: "Ghi 'vị trí mới nhất' là workload ghi đè liên tục trên ít dòng nhưng tần suất cực cao — cạnh tranh trực tiếp với read path matching trên cùng index không gian. Tách thành một store tối ưu cho ghi/đọc theo key (Redis GEO, in-memory) giữ đường ghi nóng tách khỏi hệ thống nghiệp vụ chính; lịch sử đầy đủ (nếu cần cho phân tích) đi qua pipeline riêng, không chặn đường nóng.",
    },
    {
      id: "matching-race-double-assign-driver",
      question: "Hai rider ở gần nhau cùng được matching service gợi ý tài xế d2 (do query trùng thời điểm). Cả hai request 'assign driver d2' gần như đồng thời. Cách nào chống được việc d2 bị gán cho cả hai chuyến?",
      options: [
        "Tăng tần suất cập nhật vị trí tài xế lên mỗi 1 giây",
        "Cho cả hai rider cùng đi chung xe d2",
        "Gán bằng conditional update kiểu `UPDATE drivers SET status='assigned', trip_id=:id WHERE id=:driverId AND status='available'` — request thứ hai nhận 0 dòng khớp, y hệt kỹ thuật chống double-booking ghế",
        "Chỉ gợi ý mỗi tài xế cho đúng 1 rider mỗi ngày",
      ],
      answerIndex: 2,
      explanation: "Đây chính là bài toán 'tài nguyên có hạn, nhiều bên tranh' xuất hiện lại: gán tài xế và giữ ghế sự kiện dùng chung một kỹ thuật — atomic conditional update theo trạng thái hiện tại, không phải kiểm tra rồi ghi ở tầng app.",
    },
    {
      id: "double-booking-fix-is-atomic-not-more-validation",
      question: "Sau khi phát hiện double-booking, một dev đề xuất: 'thêm một bước kiểm tra nữa ở app trước khi UPDATE, và log lại mọi lần đặt để dễ điều tra'. Đánh giá đề xuất này?",
      options: [
        "Đúng hướng — kiểm tra càng nhiều lần càng an toàn",
        "Chỉ cần thêm log là đủ, không cần sửa logic",
        "Vấn đề chỉ xảy ra khi có đúng 2 request nên thêm kiểm tra là đủ",
        "Không giải quyết gốc rễ: hai request vẫn có thể cùng đọc 'available' trước khi bên nào ghi xong (race condition), bất kể thêm bao nhiêu bước kiểm tra ở app; cần làm cho việc kiểm tra-và-ghi atomic ở tầng database (`WHERE status='available'`, unique constraint, hoặc `FOR UPDATE`)",
      ],
      answerIndex: 3,
      explanation: "Thêm kiểm tra ở tầng app không thu hẹp được khoảng thời gian giữa đọc và ghi (race window) — hai request vẫn có thể chen vào giữa. Phải chuyển điều kiện kiểm tra vào chính câu ghi (atomic) hoặc dùng khoá tường minh.",
    },
    {
      id: "virtual-waiting-room-purpose",
      question: "Sự kiện mở bán 50.000 vé, 2 triệu người cùng bấm 'mua vé' trong 10 giây đầu. Virtual waiting room (hàng đợi ảo) giải quyết vấn đề gì mà atomic conditional update một mình không đủ?",
      options: [
        "Giới hạn số request được vào tầng booking cùng lúc (cấp token theo hàng, admit dần) để tránh sập database và app dưới tải đỉnh — atomic update vẫn cần ở bước giữ ghế cho những request đã được admit",
        "Thay thế hoàn toàn nhu cầu atomic update ở bước giữ ghế",
        "Tăng tốc độ query database bằng cách cache toàn bộ ghế",
        "Ngăn một người mua nhiều hơn giới hạn vé cho phép",
      ],
      answerIndex: 0,
      explanation: "Waiting room và atomic update giải hai vấn đề khác nhau: waiting room hạ tải đỉnh (chỉ 2 triệu người cùng vào cùng lúc gây sập trước khi kịp chạm tới ghế nào), còn atomic conditional update chống double-booking cho những request đã được admit vào. Giới hạn vé/người là một ràng buộc nghiệp vụ riêng, thường kiểm tra ở bước xác nhận đơn.",
    },
    {
      id: "payment-retry-naive-double-charge",
      question: "Client gọi `POST /charge`, mạng chậm khiến response bị mất dù PSP đã charge thành công. Client tự động retry request y hệt. Không có gì để server nhận ra đây là request lặp lại. Hậu quả và cách phòng ngừa đúng?",
      options: [
        "Không sao vì PSP tự động phát hiện giao dịch trùng theo số thẻ",
        "Khách bị trừ tiền hai lần; cần idempotency key ổn định do client sinh, giữ nguyên qua các lần retry, để server nhận ra và bỏ qua request trùng",
        "Chỉ cần giảm timeout của client xuống để tránh retry",
        "Vấn đề chỉ xảy ra với thẻ tín dụng, không xảy ra với ví điện tử",
      ],
      answerIndex: 1,
      explanation: "Timeout không có nghĩa là request thất bại — nó có thể đã thành công phía server, chỉ response bị mất. Client không thể phân biệt hai trường hợp này nên sẽ retry cả hai. Chỉ có idempotency key (do client giữ nguyên qua các lần gọi) mới cho server nhận diện được request đã xử lý.",
    },
    {
      id: "idempotency-key-must-be-atomic-with-charge",
      question: "Server code: (1) `SELECT * FROM idempotency_keys WHERE key = :k`, nếu không thấy thì (2) gọi PSP charge, rồi (3) `INSERT INTO idempotency_keys ...`. Hai request cùng key gửi gần như đồng thời (client retry rất nhanh). Vấn đề?",
      options: [
        "Không có vấn đề gì vì đã kiểm tra key trước khi charge",
        "Chỉ cần thêm `ORDER BY` vào câu SELECT",
        "Cả hai request đều không thấy key ở bước (1) (chưa ai INSERT xong) nên cả hai đều đi tới bước (2) gọi PSP — vẫn double charge; cần INSERT (với unique constraint) atomic với việc ghi nhận ý định charge, trong cùng transaction, trước khi gọi PSP",
        "PSP sẽ tự chặn request thứ hai vì cùng số tiền",
      ],
      answerIndex: 2,
      explanation: "Check-rồi-insert giống hệt lost update kiểu 'check-then-act': khoảng trống giữa SELECT và INSERT là race window. Phải làm INSERT (unique constraint trên `key`) atomic — nếu conflict, coi như request trùng, không gọi PSP nữa; trạng thái 'processing' ngăn cả trường hợp request thứ hai đến giữa lúc request đầu đang chạy.",
    },
    {
      id: "double-entry-ledger-reconciliation-purpose",
      question: "Vì sao hệ thống thanh toán ghi mỗi giao dịch thành một cặp Nợ/Có (double-entry) vào nhiều tài khoản (ví rider, clearing, ví tài xế, doanh thu) thay vì chỉ một dòng `payments(amount, status)`?",
      options: [
        "Double-entry chỉ là quy ước lịch sử, không còn cần thiết với hệ thống hiện đại",
        "Mỗi đồng tiền di chuyển đều có nguồn đi và nơi đến rõ ràng; tổng Nợ luôn bằng tổng Có ở mọi thời điểm, nên một phép cộng đơn giản (đối soát) phát hiện được thiếu sót hoặc lỗi ghi sổ mà không cần dò từng dòng code, đồng thời tạo dấu vết audit đầy đủ",
        "Chỉ để tương thích với kế toán truyền thống, không có lợi ích kỹ thuật",
        "Vì database không hỗ trợ lưu số dư trực tiếp",
      ],
      answerIndex: 1,
      explanation: "Một dòng `payments(amount, status)` không nói được tiền đi đâu và không tự phát hiện được sai lệch. Double-entry buộc mỗi giao dịch cân bằng theo cấu trúc, nên nếu một tài khoản trung gian (như `platform_clearing`) không trở về 0 sau khi cộng hết Nợ/Có, đó là tín hiệu có dòng bị thiếu hoặc sai — đúng là cơ chế đối soát và audit.",
    },
  ],
};
