import type { ModuleDefinition } from "@/content/content-types";

export const b07TestingBackendModule: ModuleDefinition = {
  id: "b07",
  slug: "b07-testing-backend",
  phaseId: "b-phase-1",
  order: 7,
  weeks: "Tuần 9–10",
  title: "Testing backend",
  emoji: "🧪",
  eli5Summary:
    "Từ B01 tới B06, `taskflow-api` đã có auth, phân quyền, và CRUD thật trên Postgres — nhưng chưa có ai 'kiểm tra chất lượng' tự động. Module này lắp một dây chuyền kiểm tra: test nhanh cho từng linh kiện nhỏ, test chậm hơn cho cả dây chuyền lắp ráp, và một cách để mỗi lần thử không để lại rác trong kho — để từ B08 trở đi, bạn refactor mà không phải hồi hộp đoán xem có vỡ gì không.",
  objectives: [
    "Phân bổ đúng tỉ lệ unit/integration/e2e cho một backend API (không phải web UI)",
    "Cấu hình một database Postgres riêng cho test, tách biệt hoàn toàn khỏi DB dev",
    "Phân biệt dependency nào 'nằm ngoài tầm kiểm soát' cần mock, và vì sao KHÔNG mock database",
    "Viết integration test bọc mỗi test case trong một transaction rồi rollback, giữ test độc lập mà không cần migrate lại schema mỗi lần",
    "Đọc một con số coverage đúng cách — biết khi nào 100% coverage vẫn là một bộ test vô dụng",
  ],
  lessons: [
    {
      slug: "test-pyramid-backend",
      title: "Kim tự tháp test cho backend",
      minutes: 40,
      summary: "Không phải mọi thứ đáng test giống nhau — phân bổ unit/integration/e2e đúng tỉ lệ cho một REST API.",
    },
    {
      slug: "isolated-test-database-strategy",
      title: "Database riêng cho test",
      minutes: 40,
      summary: "Vì sao test không bao giờ được chạm vào DB dev, và cách dựng một DB test sạch trong cùng container Postgres.",
    },
    {
      slug: "mocking-true-externals-not-db",
      title: "Mock đúng thứ: external thật, không phải DB",
      minutes: 35,
      summary: "Mock là để né thứ ngoài tầm kiểm soát của bạn — Postgres không phải là thứ đó.",
    },
    {
      slug: "transaction-rollback-per-test",
      title: "Transaction rollback sau mỗi test",
      minutes: 45,
      summary: "BEGIN trước mỗi test, ROLLBACK sau mỗi test — test nhanh và sạch mà không cần migrate lại schema.",
    },
  ],
  labs: [
    {
      id: "vitest-isolated-test-database-setup",
      title: "Cấu hình Vitest + database test riêng",
      description: "Dựng `vitest.config.mts`, một database Postgres riêng (`taskflow_test`, cùng container `postgres` — không thêm service mới), và `tests/setup.ts` quản lý transaction rollback theo từng test.",
      steps: [
        "Tạo `vitest.config.mts` ở root `taskflow-api` với `test: { setupFiles: ['./tests/setup.ts'], fileParallelism: false }` — tắt chạy song song giữa các file test vì tất cả cùng dùng một database test và một connection duy nhất",
        "Tạo database test trong CÙNG container `postgres` của mục 3 curriculum (không thêm service mới): `docker compose exec postgres psql -U taskflow -c 'CREATE DATABASE taskflow_test'`",
        "Thêm `TEST_DATABASE_URL=postgres://taskflow:taskflow@postgres:5432/taskflow_test` vào `.env.test`, migrate schema vào đó: `DATABASE_URL=$TEST_DATABASE_URL pnpm drizzle-kit migrate`",
        "Viết `tests/setup.ts`: mở một connection Postgres riêng với `postgres(testUrl, { max: 1 })` (chỉ 1 connection — bắt buộc để `BEGIN`/`ROLLBACK` áp đúng lên các query của cùng một test), `beforeEach` chạy `BEGIN`, `afterEach` chạy `ROLLBACK`, export `testDb` (Drizzle instance dùng connection đó)",
        "Thêm script `\"test\": \"vitest run\"` vào `package.json`, chạy `pnpm test` với một test rỗng (`expect(1).toBe(1)`) để xác nhận setup không lỗi kết nối trước khi viết test thật",
      ],
    },
    {
      id: "auth-project-task-integration-flow-test",
      title: "Integration test: register → login → tạo project → tạo task",
      description: "Một test duy nhất đi qua toàn bộ luồng thật của B02–B06: đăng ký, đăng nhập, tạo project, tạo task — qua Fastify thật và Postgres test thật, không mock tầng nào ở giữa.",
      steps: [
        "Tạo `tests/auth-project-task-flow.test.ts`, dùng `buildApp()` từ `src/app.ts` (B01) cùng `app.inject()` của Fastify thay vì mở cổng HTTP thật",
        "Bước 1: `app.inject({ method: 'POST', url: '/api/v1/auth/register', payload: { email, password, name } })`, assert status `201`",
        "Bước 2: login bằng đúng email/password vừa đăng ký qua `/api/v1/auth/login`, lấy `accessToken` từ response body",
        "Bước 3–4: dùng `accessToken` trong header `Authorization: Bearer ...` gọi `POST /api/v1/projects` rồi `POST /api/v1/projects/:id/tasks`, assert `201` và đúng field trả về",
        "Assert thêm bằng cách query thẳng `testDb` (không qua API) để xác nhận task thật sự nằm trong Postgres test — không chỉ 'API trả 201 nhưng có thể chẳng ghi gì'",
      ],
    },
    {
      id: "cross-tenant-rbac-rejection-test",
      title: "Integration test: chặn RBAC xuyên tổ chức (B06)",
      description: "Chứng minh bằng test thật rằng user của organization A không thể đọc hay sửa dữ liệu của organization B — đúng lỗ hổng IDOR mà B06 phải chặn.",
      steps: [
        "Trong `tests/rbac-cross-tenant.test.ts`, dựng 2 user thuộc 2 organization khác nhau (đăng ký + login qua API thật như lab 2) để có 2 `accessToken` độc lập",
        "User của organization A tạo 1 project qua `POST /api/v1/projects`, lấy `projectId`",
        "Dùng `accessToken` của organization B gọi `DELETE /api/v1/projects/:projectId` (project thuộc A) — assert response `403` hoặc `404` theo đúng middleware `requireRole`/lọc `organization_id` của B06, tuyệt đối không phải `200`",
        "Test thêm chiều đọc: user B gọi `GET /api/v1/projects/:projectId/tasks` của project A, assert cũng bị chặn — chứng minh rò rỉ đọc dữ liệu (IDOR) bị chặn, không chỉ hành động ghi",
        "Chạy `pnpm test` cho xanh, rồi cố tình xoá dòng kiểm tra `organization_id` trong route đó và chạy lại — xác nhận đúng test này (và chỉ nó) chuyển đỏ, chứng minh test thật sự bảo vệ được logic đó",
      ],
    },
    {
      id: "due-date-calculator-unit-test",
      title: "Unit test cho hàm thuần: tính hạn chót task",
      description: "Một hàm logic thuần, không đụng DB hay HTTP — kiểu test nhanh nhất và rẻ nhất trong kim tự tháp.",
      steps: [
        "Viết hàm thuần `calculateDueDate` trong `src/lib/calculate-due-date.ts`: nhận `createdAt: Date` và `priority: 'low' | 'medium' | 'high'`, trả về `Date` hạn chót (`high` +1 ngày, `medium` +3 ngày, `low` +7 ngày) — không gọi `new Date()` bên trong, nhận `createdAt` làm tham số để test xác định được kết quả",
        "Viết `tests/calculate-due-date.test.ts` — KHÔNG import `app.ts`/`testDb`, vì test này không cần Fastify hay Postgres chạy",
        "Test đủ 3 nhánh `priority`, cộng 1 test biên: `createdAt` là cuối tháng (`2026-01-31`) cộng ngày phải tràn đúng sang tháng sau, không lệch múi giờ",
        "Chạy riêng file này bằng `pnpm vitest run tests/calculate-due-date.test.ts` — phải xong trong vài mili-giây, không cần `docker compose up`",
        "So sánh thời gian chạy với lab 2/3 (integration) bằng `pnpm test -- --reporter=verbose` để thấy rõ chênh lệch tốc độ giữa hai tầng của kim tự tháp",
      ],
    },
  ],
  deliverable:
    "`taskflow-api` có `vitest.config.mts`, database `taskflow_test` riêng, `tests/setup.ts` với transaction rollback per-test, integration test cho luồng auth→project→task và cho RBAC xuyên tổ chức (B06), cùng 1 unit test cho `calculateDueDate`.",
  successCriteria:
    "`pnpm test` chạy độc lập với thứ tự file, không phụ thuộc dữ liệu để lại từ lần chạy trước; xoá 1 dòng kiểm tra `organization_id` ở route B06 phải làm ít nhất 1 test đỏ; `pnpm test -- --coverage` chạy được và bạn giải thích được vì sao % coverage một mình không nói lên chất lượng.",
  resources: [
    { title: "Vitest — Getting Started", url: "https://vitest.dev/guide/", kind: "doc" },
    { title: "Martin Fowler — TestPyramid", url: "https://martinfowler.com/bliki/TestPyramid.html", kind: "doc" },
    { title: "Kent C. Dodds — Write tests. Not too many. Mostly integration.", url: "https://kentcdodds.com/blog/write-tests", kind: "doc" },
    { title: "Google Testing Blog — Just Say No to More End-to-End Tests", url: "https://testing.googleblog.com/2015/04/just-say-no-to-more-end-to-end-tests.html", kind: "doc" },
    { title: "Fastify docs — Testing", url: "https://fastify.dev/docs/latest/Guides/Testing/", kind: "doc" },
    { title: "Drizzle ORM docs — Transactions", url: "https://orm.drizzle.team/docs/transactions", kind: "doc" },
    { title: "postgres (porsager) — driver GitHub README", url: "https://github.com/porsager/postgres", kind: "doc" },
  ],
  quiz: [
    {
      id: "why-not-mostly-e2e-backend",
      question: "Vì sao một backend API như `taskflow-api` không nên viết phần lớn test dạng e2e (dựng cả stack Docker, gọi HTTP thật từ ngoài)?",
      options: [
        "Vì e2e test không bao giờ phát hiện được bug",
        "Vì e2e test chậm, dễ flaky (phụ thuộc network/timing thật) và khó biết chính xác lớp nào gây lỗi khi nó đỏ — chi phí bảo trì cao so với lợi ích với mỗi test thêm",
        "Vì Vitest không hỗ trợ chạy e2e test",
        "Vì e2e test yêu cầu viết bằng ngôn ngữ khác TypeScript",
      ],
      answerIndex: 1,
      explanation: "Không phải e2e vô dụng — nó cần thiết ở số lượng nhỏ để xác nhận cả hệ thống lắp ráp đúng. Nhưng nó chậm và mơ hồ khi đỏ (lỗi ở network, ở DB, hay ở logic?), nên kim tự tháp đặt phần lớn test ở tầng integration/unit nơi lỗi dễ khoanh vùng hơn nhiều.",
    },
    {
      id: "integration-vs-unit-what-catches-idor",
      question: "Loại test nào trong kim tự tháp có khả năng bắt được lỗi 'quên lọc `organization_id`' (IDOR) của B06?",
      options: [
        "Unit test cho `calculateDueDate` — vì nó test logic",
        "Integration test gọi thật route `DELETE /projects/:id` bằng token của tổ chức khác, qua Fastify + Postgres thật",
        "Không loại test nào bắt được, phải đọc code bằng mắt",
        "Chỉ e2e test mới bắt được lỗi loại này",
      ],
      answerIndex: 1,
      explanation: "IDOR là lỗi ở cách các lớp (route, middleware quyền, query DB) phối hợp với nhau — đúng thứ integration test được sinh ra để bắt. Unit test cho một hàm thuần không hề biết tới route hay DB nên không thể phát hiện loại lỗi này.",
    },
    {
      id: "shared-dev-db-pollution",
      question: "Một dev trỏ `DATABASE_URL` của test thẳng vào Postgres dev (không tạo DB riêng) cho nhanh. Vài ngày sau, test `đăng ký user` bắt đầu báo lỗi `email đã tồn tại` dù chưa từng đổi code. Nguyên nhân nhiều khả năng nhất?",
      options: [
        "Postgres bị lỗi ngẫu nhiên",
        "Vitest tự động cache kết quả test cũ",
        "Các lần chạy test trước đã insert user với email cố định vào DB dev thật và không bị xoá — lần chạy sau đụng unique constraint với dữ liệu 'rác' đó",
        "Drizzle ORM giới hạn số lần insert mỗi ngày",
      ],
      answerIndex: 2,
      explanation: "Đây chính là 'test pollution': test ghi dữ liệu thật vào một DB không được dọn giữa các lần chạy, nên lần chạy sau va phải dữ liệu do chính nó (hoặc CI trước đó) để lại. Dùng DB test riêng + rollback per-test (lesson 2 và 4) là cách tránh triệt để.",
    },
    {
      id: "why-not-mock-database",
      question: "Vì sao lesson này khuyên KHÔNG mock Postgres trong integration test, dù mock DB có vẻ giúp test chạy nhanh hơn và không cần Docker?",
      options: [
        "Vì Vitest không hỗ trợ mock module cho `postgres`",
        "Vì hành vi thật của DB (unique constraint, foreign key, transaction, thứ tự lock) chính là một phần logic đang cần được kiểm chứng — mock DB nghĩa là bạn chỉ test cái mock tự bịa ra, không test code thật",
        "Vì mock DB làm coverage report hiển thị sai số dòng",
        "Vì mock chỉ dùng được với REST API, không dùng được với Postgres",
      ],
      answerIndex: 1,
      explanation: "Một mock luôn hành xử đúng như bạn lập trình cho nó — kể cả khi bạn lập trình sai. Nếu mock 'quên' rằng cột `email` có unique constraint, test sẽ pass dù code thật sẽ crash khi chạy với Postgres thật. DB không phải 'external ngoài tầm kiểm soát' — nó là một phần hành vi của chính hệ thống bạn.",
    },
    {
      id: "true-external-to-mock",
      question: "Theo nguyên tắc 'chỉ mock thứ genuinely ngoài tầm kiểm soát', dependency nào dưới đây HỢP LÝ NHẤT để mock trong test?",
      options: [
        "Bảng `projects` trong Postgres test",
        "Hàm `calculateDueDate` (thuần, không I/O)",
        "Một cổng thanh toán (payment gateway) hoặc dịch vụ gửi email bên thứ ba — có phí thật, rate limit, và độ trễ mạng không kiểm soát được",
        "Route `POST /api/v1/projects` của chính `taskflow-api`",
      ],
      answerIndex: 2,
      explanation: "Payment gateway/email provider là dịch vụ ngoài, gọi thật sẽ tốn tiền/gửi email thật/không xác định (mạng, rate limit) — đúng định nghĩa 'genuinely outside your control'. DB, route, và hàm thuần đều là code/hạ tầng do chính hệ thống kiểm soát, nên test bằng bản thật (hoặc bản test riêng) chứ không mock.",
      recallPrompt: "Theo nguyên tắc 'chỉ mock thứ genuinely ngoài tầm kiểm soát', vì sao một payment gateway hay email provider bên thứ ba là ứng viên hợp lý để mock, còn Postgres, route nội bộ và hàm thuần thì không?",
    },
    {
      id: "coverage-100-percent-meaningless",
      question: "Một PR có `pnpm test -- --coverage` báo 100% line coverage cho route `DELETE /projects/:id`, nhưng file test chỉ có `expect(response.statusCode).not.toBeUndefined()`. Nhận định nào đúng?",
      options: [
        "100% coverage là bằng chứng đủ để merge an toàn",
        "Coverage 100% chỉ nói dòng code đó ĐÃ ĐƯỢC CHẠY qua ít nhất một lần khi test — không nói gì về việc kết quả có ĐÚNG hay không; assertion yếu này có thể pass kể cả khi route trả sai status code",
        "Coverage 100% có nghĩa là không còn bug nào trong route đó",
        "Coverage tool chắc chắn bị lỗi vì assertion quá đơn giản",
      ],
      answerIndex: 1,
      explanation: "Coverage đo 'code có được thực thi không', không đo 'code có làm đúng việc không'. Một test với assertion vô nghĩa (`not.toBeUndefined()` gần như luôn đúng) vẫn đạt 100% coverage nhưng không bắt được bug thật — 70% coverage với assertion chặt (đúng status code, đúng dữ liệu, đúng lỗi RBAC) có giá trị hơn nhiều.",
    },
    {
      id: "beforeeach-begin-aftereach-rollback",
      question: "Trong pattern transaction-rollback-per-test, vì sao `beforeEach`/`afterEach` phải dùng CHUNG một connection Postgres duy nhất (`max: 1`) thay vì connection pool bình thường?",
      options: [
        "Để tiết kiệm tiền hosting Postgres",
        "Vì `BEGIN` và `ROLLBACK` là lệnh áp lên một connection/session cụ thể — nếu mỗi query trong test lấy một connection khác nhau từ pool, chúng sẽ không nằm trong cùng transaction, nên rollback không dọn hết dữ liệu đã ghi",
        "Vì Drizzle ORM chỉ hỗ trợ 1 connection",
        "Vì Vitest giới hạn số connection database mỗi file test",
      ],
      answerIndex: 1,
      explanation: "Transaction gắn với session/connection. Nếu `testDb` được cấp phát từ một pool nhiều connection, request A của test có thể chạy trên connection 1 (đã BEGIN) còn request B chạy trên connection 2 (chưa BEGIN) — dữ liệu của request B sẽ bị COMMIT thật và không bị ROLLBACK cùng phần còn lại.",
    },
    {
      id: "nested-transaction-gotcha",
      question: "Route tạo task của `taskflow-api` tự gọi `db.transaction()` bên trong (để ghi `tasks` và `activity_logs` cùng lúc, từ B04) khi đang chạy dưới transaction rollback-per-test của B07. Điều gì cần cẩn thận?",
      options: [
        "Không có gì cần lo, mọi transaction lồng nhau luôn tự động an toàn với mọi driver và mọi cấu hình",
        "`db.transaction()` lồng bên trong thường chỉ tạo SAVEPOINT nên vẫn ổn, NHƯNG nếu code (hoặc trigger) có `COMMIT` tường minh hoặc constraint kiểu `DEFERRABLE ... ON COMMIT`, transaction ngoài cùng của test có thể bị commit sớm ngoài ý muốn — khiến `ROLLBACK` ở `afterEach` không còn gì để rollback",
        "Nested transaction luôn làm test chạy nhanh hơn",
        "Postgres sẽ tự động từ chối mọi transaction lồng nhau",
      ],
      answerIndex: 1,
      explanation: "Đây là caveat quan trọng của pattern: transaction lồng qua SAVEPOINT thường vô hại, nhưng bất kỳ đường nào khiến transaction ngoài bị COMMIT thật (COMMIT tường minh, một số hành vi ON COMMIT của constraint hoãn) sẽ phá vỡ giả định 'mọi thứ sẽ bị xoá sạch sau ROLLBACK' — dữ liệu rò rỉ sang test sau.",
    },
    {
      id: "unit-test-due-date-no-db",
      question: "Vì sao test cho `calculateDueDate` KHÔNG nên import `testDb` hay `buildApp()`, dù kỹ thuật vẫn chạy được nếu import?",
      options: [
        "Vì TypeScript sẽ báo lỗi nếu import cả hai trong cùng file",
        "Vì hàm đó không đọc/ghi DB hay HTTP — kéo theo `testDb`/Fastify là phụ thuộc không cần thiết, làm test chậm hơn và mơ hồ hơn về việc nó thật sự đang kiểm tra cái gì",
        "Vì `calculateDueDate` không thể export được từ module khác",
        "Vì Vitest cấm dùng 2 loại test khác nhau trong cùng file",
      ],
      answerIndex: 1,
      explanation: "Một hàm thuần (pure function) không có lý do gì để phụ thuộc vào DB hay HTTP server khi test — thêm phụ thuộc đó chỉ làm test chậm hơn (phải chờ Postgres) và khó đọc hơn (không rõ đang test logic tính ngày hay đang test kết nối DB). Giữ ranh giới rõ giữa unit và integration test.",
    },
    {
      id: "test-would-catch-regression",
      question: "Một PR sau này (B08+) vô tình xoá điều kiện `WHERE organization_id = $1` khỏi query `DELETE /projects/:id`. Test nào ở B07 sẽ chuyển đỏ và cảnh báo trước khi merge?",
      options: [
        "`tests/calculate-due-date.test.ts` — vì nó test logic ngày tháng",
        "`tests/rbac-cross-tenant.test.ts` — vì nó gọi đúng kịch bản 'user tổ chức B xoá project của tổ chức A' và assert phải bị `403`/`404`",
        "Không test nào bắt được, phải chờ báo cáo từ user thật",
        "`tests/auth-project-task-flow.test.ts` — vì nó test toàn bộ luồng đăng ký",
      ],
      answerIndex: 1,
      explanation: "Đây chính là lý do lab 3 tồn tại: một test cố tình mô phỏng đúng kịch bản tấn công xuyên tổ chức. Test luồng 'happy path' (auth-project-task-flow) hay unit test hạn chót không hề chạm tới đường code bị xoá điều kiện, nên chúng vẫn xanh dù lỗ hổng bảo mật đã xuất hiện.",
    },
  ],
};
