import type { ModuleDefinition } from "@/content/content-types";

export const b02HttpRestApiFastifyModule: ModuleDefinition = {
  id: "b02",
  slug: "b02-http-rest-api-fastify",
  phaseId: "b-phase-0",
  order: 2,
  weeks: "Tuần 2",
  title: "HTTP & REST API với Fastify",
  emoji: "🚦",
  eli5Summary:
    "HTTP giống như quy trình gửi thư ở bưu điện: có loại thư khác nhau (GET lấy thư, POST gửi thư mới), và mỗi lần gửi bưu điện đều trả một 'biên nhận' (status code) nói rõ chuyện gì đã xảy ra. Module này dạy bạn viết đúng quy trình đó bằng Fastify cho `taskflow-api`.",
  objectives: [
    "Chọn đúng HTTP method và status code cho từng tình huống CRUD (200/201/204/400/404/409)",
    "Tổ chức route bằng Fastify plugin thay vì dồn hết vào 1 file",
    "Giải thích được encapsulation của Fastify và khi nào cần `fastify-plugin` để phá nó có chủ đích",
    "Dùng đúng lifecycle hook (`onRequest`, `preValidation`, `preHandler`, `onSend`) cho logging và các việc chạy trước/sau handler",
    "Đặt tên resource REST đúng chuẩn, biết khi nào lồng resource và khi nào để phẳng",
    "Kiểm chứng API bằng `curl` thay vì đoán mò status code",
  ],
  lessons: [
    {
      slug: "http-methods-status-codes",
      title: "HTTP method & status code đúng nghĩa",
      minutes: 30,
      summary: "Biên nhận bưu điện: mỗi status code kể một câu chuyện khác nhau về chuyện gì đã xảy ra với request.",
    },
    {
      slug: "fastify-routing-plugins",
      title: "Fastify routing & plugin encapsulation",
      minutes: 40,
      summary: "Mỗi plugin là một 'phòng ban' riêng — chia nhỏ route mà không đá lẫn nhau.",
    },
    {
      slug: "fastify-lifecycle-hooks",
      title: "Request lifecycle & hook",
      minutes: 35,
      summary: "Request đi qua một dây chuyền trạm kiểm soát trước khi tới tay handler.",
    },
    {
      slug: "rest-resource-naming-nested-resources",
      title: "Đặt tên resource REST & nested resource",
      minutes: 30,
      summary: "URL là địa chỉ nhà — phải nói đúng thứ đang ở trong đó và ai là con của ai.",
    },
  ],
  labs: [
    {
      id: "in-memory-project-crud",
      title: "CRUD `projects` in-memory đúng chuẩn REST",
      description: "Dựng plugin `projectRoutes` cho `taskflow-api`, dùng `Map` để lưu project, trả đúng status code cho mọi case.",
      steps: [
        "Tạo `src/store.ts` export `projects: Map<string, Project>` và `tasks: Map<string, Task>` dùng chung toàn app",
        "Tạo `src/routes/projects.ts` là một Fastify plugin, đăng ký với prefix `/api/v1/projects` trong `src/app.ts`",
        "Viết `GET /` (danh sách), `GET /:id` (404 nếu không có), `POST /` (400 nếu thiếu `name`, 201 kèm header `Location` khi thành công)",
        "Viết `PATCH /:id` (404 nếu không có id) và `DELETE /:id` (409 nếu project còn task, 204 nếu xoá được)",
        "Chạy `pnpm dev`, gọi thử từng endpoint bằng `curl` và ghi lại status code thực tế nhận được",
      ],
    },
    {
      id: "nested-task-routes-logging-hook",
      title: "Nested routes cho `tasks` + hook log request",
      description: "Thêm plugin `taskRoutes` lồng dưới project, và một hook ghi log method/path/status/thời gian xử lý cho mọi request.",
      steps: [
        "Tạo `src/routes/tasks.ts`: `GET /api/v1/projects/:projectId/tasks` và `POST /api/v1/projects/:projectId/tasks` (404 nếu `projectId` không tồn tại)",
        "Thêm route phẳng `GET /api/v1/tasks/:id` và `PATCH /api/v1/tasks/:id` để sửa `status`/`assigneeId` mà không cần biết lại `projectId`",
        "Tạo `src/plugins/request-logger.ts`, đăng ký `fastify.addHook('onRequest', ...)` gắn `request.startTime`",
        "Đăng ký `fastify.addHook('onResponse', ...)` tính thời gian xử lý và `fastify.log.info` ra `method`, `url`, `statusCode`, `durationMs`",
        "Đăng ký `request-logger` ở `app.ts` (mức root) và xác nhận log xuất hiện cho cả route `projects` lẫn `tasks`",
      ],
    },
    {
      id: "curl-status-code-verification",
      title: "Xác nhận status code bằng curl",
      description: "Viết một loạt lệnh `curl` chứng minh mọi case (thành công/thiếu field/không tìm thấy/xung đột) trả đúng status code.",
      steps: [
        "`curl -i -X POST .../projects -d '{\"organizationId\":\"org_1\",\"name\":\"Website Revamp\"}'` — xác nhận `201` và header `Location`",
        "`curl -i -X POST .../projects -d '{\"organizationId\":\"org_1\"}'` (thiếu `name`) — xác nhận `400`",
        "`curl -i .../projects/khong-ton-tai` — xác nhận `404`",
        "Tạo 1 task trong project vừa tạo, sau đó `curl -i -X DELETE .../projects/:id` — xác nhận `409` vì project còn task",
        "Xoá task đó trước, gọi lại `DELETE .../projects/:id` — xác nhận lần này trả `204` và body rỗng",
        "Ghi toàn bộ 5 lệnh + status code thực tế vào `learnings.md` của tuần này",
      ],
    },
  ],
  deliverable:
    "`taskflow-api` có plugin `projectRoutes` + `taskRoutes` dưới `/api/v1`, CRUD in-memory đúng REST convention, hook log request, và một danh sách lệnh `curl` chứng minh status code đúng cho từng case.",
  successCriteria:
    "Mọi endpoint (kể cả case lỗi) trả đúng status code; route được tổ chức theo plugin, không dồn vào 1 file; log request xuất hiện đầy đủ cho mọi request nhờ hook, không phải code lặp lại trong từng handler.",
  resources: [
    { title: "Fastify docs — Routes", url: "https://fastify.dev/docs/latest/Reference/Routes/", kind: "doc" },
    { title: "Fastify docs — Hooks", url: "https://fastify.dev/docs/latest/Reference/Hooks/", kind: "doc" },
    { title: "Fastify docs — Plugins", url: "https://fastify.dev/docs/latest/Reference/Plugins/", kind: "doc" },
    { title: "fastify-plugin (phá encapsulation có chủ đích)", url: "https://github.com/fastify/fastify-plugin", kind: "tool" },
    { title: "MDN — HTTP response status codes", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status", kind: "doc" },
    { title: "MDN — HTTP request methods", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods", kind: "doc" },
    { title: "REST API Tutorial — Resource Naming", url: "https://restfulapi.net/resource-naming/", kind: "doc" },
  ],
  quiz: [
    {
      id: "create-success-status",
      question: "`POST /api/v1/projects` với body hợp lệ tạo project thành công. Status code chuẩn nên trả là gì?",
      options: ["201 Created", "200 OK", "202 Accepted", "204 No Content"],
      answerIndex: 0,
      explanation: "201 Created báo rõ 'đã tạo resource mới' — nên đi kèm header Location trỏ tới resource vừa tạo. 200 hợp lý hơn cho GET/PATCH, không phải tạo mới.",
    },
    {
      id: "delete-success-status",
      question: "`DELETE /api/v1/projects/:id` xoá thành công, không còn gì để trả về client. Status code phù hợp nhất?",
      options: ["200 OK với body rỗng", "202 Accepted", "204 No Content", "410 Gone"],
      answerIndex: 2,
      explanation: "204 No Content nghĩa là 'thành công, cố tình không có body'. Trả 200 với body rỗng vẫn đúng nhưng gây hiểu nhầm là có dữ liệu; 410 dùng cho resource đã từng tồn tại rồi bị xoá vĩnh viễn theo thiết kế, không phải case thông thường này.",
    },
    {
      id: "missing-field-status",
      question: "Client gửi `POST /api/v1/projects` nhưng thiếu field `name` bắt buộc. Nên trả status nào?",
      options: ["500 Internal Server Error", "404 Not Found", "409 Conflict", "400 Bad Request"],
      answerIndex: 3,
      explanation: "Lỗi do request sai hình thức từ phía client → 4xx, cụ thể 400. 500 chỉ dùng khi server lỗi ngoài ý muốn; 404/409 không liên quan tới việc thiếu field.",
    },
    {
      id: "not-found-vs-conflict",
      question: "`DELETE /api/v1/projects/:id` khi project đó vẫn còn task bên trong nên trả status nào, và vì sao KHÔNG phải 404?",
      options: [
        "409, vì project tồn tại thật nhưng thao tác xoá vi phạm ràng buộc trạng thái (còn task)",
        "404, vì project 'không hợp lệ để xoá' cũng coi như không tồn tại",
        "400, vì client gửi request sai cú pháp",
        "204, vì server tự động huỷ thao tác nên coi như thành công",
      ],
      answerIndex: 0,
      explanation: "404 dành cho 'resource không tồn tại'. Ở đây project tồn tại thật — vấn đề là trạng thái hiện tại (còn task) xung đột với thao tác xoá → đúng nghĩa 409 Conflict.",
    },
    {
      id: "fastify-plugin-scope",
      question: "Trong `projectRoutes`, bạn `fastify.decorate('assertProjectExists', fn)`. Từ `taskRoutes` (đăng ký bằng `app.register` riêng), gọi `fastify.assertProjectExists` sẽ ra sao?",
      options: [
        "Gọi được bình thường vì cùng một `app`",
        "Gọi được nhưng chạy chậm hơn",
        "Chỉ lỗi nếu hai plugin có cùng prefix",
        "Lỗi `decorator not found` vì mỗi lần `register` tạo một encapsulation context riêng",
      ],
      answerIndex: 3,
      explanation: "Fastify tạo child context mới cho mỗi `register`. Decorator khai báo trong context con chỉ tồn tại ở context đó và các context CON của nó, không lộ sang context anh em.",
    },
    {
      id: "fastify-plugin-fp",
      question: "Vì sao `storePlugin` (decorate `fastify.store`) cần bọc bằng `fp()` từ package `fastify-plugin` để cả `projectRoutes` lẫn `taskRoutes` cùng dùng được?",
      options: [
        "`fp()` làm plugin chạy nhanh hơn",
        "`fp()` tự động thêm route GET/POST/PATCH/DELETE",
        "`fp()` báo Fastify: 'đừng tạo context con mới cho plugin này' — decorator sẽ gắn thẳng lên context cha, lộ ra mọi context con phía dưới",
        "`fp()` chỉ cần thiết khi dùng TypeScript",
      ],
      answerIndex: 2,
      explanation: "`fastify-plugin` đánh dấu plugin là 'không encapsulate' — nó chạy trong context của cha thay vì tạo context riêng, nên decorator nó thêm vào lộ ra cho mọi anh em phía sau.",
    },
    {
      id: "hook-order",
      question: "Một request `POST /api/v1/tasks` đi qua các hook theo thứ tự nào (rút gọn, bỏ qua preParsing/preSerialization)?",
      options: [
        "onRequest → preValidation → preHandler → handler → onSend",
        "handler → onRequest → preValidation → preHandler → onSend",
        "preHandler → onRequest → handler → preValidation → onSend",
        "onSend → onRequest → preHandler → preValidation → handler",
      ],
      answerIndex: 0,
      explanation: "Đúng thứ tự dây chuyền: request thô vào (onRequest) → trước khi validate (preValidation) → sau validate, trước handler (preHandler) → route logic (handler) → trước khi gửi response (onSend).",
    },
    {
      id: "logging-hook-choice",
      question: "Bạn muốn log `statusCode` và thời gian xử lý SAU KHI response đã rời server, không chặn việc gửi response. Hook nào hợp lý nhất?",
      options: ["onRequest", "onResponse", "preValidation", "preHandler"],
      answerIndex: 1,
      explanation: "`onResponse` chạy sau khi response đã được gửi đi, phù hợp để log mà không ảnh hưởng tới thời gian phản hồi cho client. `onRequest`/`preHandler`/`preValidation` đều chạy trước khi có statusCode cuối cùng.",
    },
    {
      id: "nested-resource-naming",
      question: "Endpoint nào đặt tên đúng chuẩn REST cho 'lấy tất cả task của project X'?",
      options: [
        "GET /api/v1/getTasksByProject?id=X",
        "POST /api/v1/tasks/list",
        "GET /api/v1/projects/X/tasks",
        "GET /api/v1/task_list/X",
      ],
      answerIndex: 2,
      explanation: "REST dùng danh từ số nhiều, không dùng động từ trong URL (getTasksByProject sai), và thể hiện quan hệ cha-con bằng nested resource: /projects/:id/tasks.",
    },
    {
      id: "flat-vs-nested-choice",
      question: "Vì sao `PATCH /api/v1/tasks/:id` (route phẳng) hợp lý hơn `PATCH /api/v1/projects/:projectId/tasks/:id` để đổi `status` của một task?",
      options: [
        "Vì route phẳng luôn nhanh hơn route lồng",
        "Vì Fastify không hỗ trợ 2 tham số động trong 1 route",
        "Vì route lồng chỉ dùng được cho GET",
        "Vì `id` của task đã đủ định danh duy nhất — không cần biết lại `projectId` để sửa đúng resource",
      ],
      answerIndex: 3,
      explanation: "Nested resource hợp lý khi con LUÔN cần cha để xác định phạm vi (tạo mới, liệt kê). Khi đã có `id` duy nhất của resource, route phẳng đơn giản hơn và tránh phải đồng bộ `projectId` không cần thiết.",
    },
  ],
};
