import type { ModuleDefinition } from "@/content/content-types";

export const m15ObservabilityModule: ModuleDefinition = {
  id: "m15",
  slug: "m15-observability",
  phaseId: "phase-5",
  order: 15,
  weeks: "Tuần 24",
  title: "Observability",
  emoji: "🔭",
  eli5Summary:
    "Hệ thống production giống một chiếc xe đang chạy đường dài: bạn cần đồng hồ táp-lô (metrics), sổ nhật ký chuyến đi (logs) và bản đồ GPS lộ trình (traces). Module này dạy bạn gắn đủ ba thứ đó để khi xe kêu lạ, bạn biết ngay hỏng ở đâu thay vì đoán mò.",
  objectives: [
    "Phân biệt monitoring và observability; biết khi nào dùng metrics, logs hay traces",
    "Chọn đúng tín hiệu để theo dõi bằng Four Golden Signals, RED và USE",
    "Cài kube-prometheus-stack, viết PromQL với rate(), histogram_quantile() và recording rules",
    "Thiết kế alert có ý nghĩa và cấu hình Alertmanager routing, grouping, silence, inhibition",
    "Thu thập log tập trung bằng Grafana Alloy/Fluent Bit vào Loki hoặc CloudWatch",
    "Instrument service bằng OpenTelemetry và liên kết log ↔ trace bằng trace ID",
  ],
  lessons: [
    { slug: "monitoring-vs-observability", title: "Monitoring vs Observability & 3 trụ cột", minutes: 35, summary: "Táp-lô, sổ nhật ký và GPS: mỗi loại dữ liệu trả lời một câu hỏi khác nhau." },
    { slug: "golden-signals-red-use", title: "Golden Signals, RED & USE", minutes: 35, summary: "Đo cái gì trước tiên — cho service và cho tài nguyên." },
    { slug: "prometheus-promql", title: "Prometheus & PromQL", minutes: 50, summary: "Pull model, exporters, rate() và kube-prometheus-stack." },
    { slug: "grafana-alertmanager", title: "Grafana dashboards & Alertmanager", minutes: 45, summary: "Từ biểu đồ tới tin nhắn Slack: pending, firing, grouping, silence." },
    { slug: "logs-pipeline-loki", title: "Log tập trung: Loki, Fluent Bit & CloudWatch", minutes: 40, summary: "Gom log từ hàng trăm pod về một nơi và truy vấn bằng label." },
    { slug: "opentelemetry-tracing", title: "Distributed tracing với OpenTelemetry", minutes: 50, summary: "Theo dấu một request qua nhiều service bằng span và trace ID." },
  ],
  labs: [
    {
      id: "kube-prometheus-red-dashboard",
      title: "kube-prometheus-stack & dashboard RED",
      description: "Cài bộ Prometheus + Grafana + Alertmanager lên cluster, cho app mẫu expose /metrics và dựng dashboard RED cho API.",
      steps: [
        "Tạo cluster local bằng `kind create cluster --name obs` (hoặc dùng EKS từ M13)",
        "`helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && helm repo update`",
        "`helm install monitoring prometheus-community/kube-prometheus-stack -n monitoring --create-namespace`",
        "Deploy app mẫu có endpoint `/metrics` (vd dùng thư viện `prom-client` cho Node hoặc `prometheus_client` cho Python) với counter `http_requests_total` và histogram `http_request_duration_seconds`",
        "Tạo `ServiceMonitor` có label `release: monitoring` trỏ tới Service của app; kiểm tra target UP ở `kubectl -n monitoring port-forward svc/monitoring-kube-prometheus-prometheus 9090`",
        "Trong Grafana (`kubectl -n monitoring port-forward svc/monitoring-grafana 3000:80`) tạo dashboard 3 panel: Rate `sum(rate(http_requests_total[5m]))`, Errors (tỉ lệ 5xx), Duration p95 bằng `histogram_quantile(0.95, ...)`",
        "Tạo recording rule `job:http_requests:rate5m` bằng `PrometheusRule` và dùng lại trong dashboard",
      ],
    },
    {
      id: "otel-tempo-trace-log-correlation",
      title: "OpenTelemetry → Tempo, liên kết log ↔ trace",
      description: "Instrument API bằng OpenTelemetry SDK, gửi trace qua OTel Collector vào Tempo, và in trace ID vào log để nhảy qua lại trong Grafana.",
      steps: [
        "Cài Tempo và Loki bằng Helm chart `grafana/tempo` và `grafana/loki` (chế độ single binary cho lab)",
        "Deploy OpenTelemetry Collector với receiver `otlp` (gRPC 4317, HTTP 4318) và exporter `otlp` trỏ tới Tempo",
        "Thêm auto-instrumentation vào API (vd `@opentelemetry/auto-instrumentations-node` hoặc `opentelemetry-instrument` cho Python), đặt `OTEL_SERVICE_NAME` và `OTEL_EXPORTER_OTLP_ENDPOINT`",
        "Gọi API vài lần, mở Grafana → Explore → Tempo, tìm trace theo `service.name` và xem waterfall span",
        "Cấu hình logger in `trace_id` vào mỗi dòng log JSON; gom log vào Loki bằng Grafana Alloy",
        "Cấu hình data source Loki với derived field (regex `trace_id`) để bấm từ log nhảy sang trace trong Tempo",
      ],
    },
    {
      id: "slack-alerting-error-latency",
      title: "Alert error rate & p95 latency → Slack",
      description: "Viết PrometheusRule cho error rate > 5% trong 5 phút và p95 latency > 500ms, định tuyến qua Alertmanager tới Slack/Discord/email.",
      steps: [
        "Viết `PrometheusRule` alert `HighErrorRate`: tỉ lệ 5xx trên tổng request trong `[5m]` lớn hơn `0.05`, `for: 5m`, label `severity: page`",
        "Viết alert `HighLatencyP95`: `histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m]))) > 0.5`, `for: 10m`",
        "Tạo Slack Incoming Webhook (hoặc Discord webhook/email SMTP) và lưu URL vào Kubernetes Secret, không commit vào Git",
        "Cấu hình Alertmanager receiver + route theo `severity`, `group_by: [alertname, service]`, `repeat_interval: 4h`",
        "Gây lỗi có chủ đích (endpoint trả 500 hoặc thêm `sleep`) bằng `hey`/`k6`, quan sát alert đi từ Pending → Firing → Slack",
        "Tạo silence bằng `amtool silence add alertname=HighLatencyP95 --duration=1h --comment='maintenance'` và xác nhận không còn thông báo",
      ],
    },
  ],
  deliverable: "Repo chứa Helm values, ServiceMonitor, PrometheusRule, cấu hình Alertmanager/OTel Collector/Alloy và file JSON dashboard RED; README có ảnh chụp dashboard, trace waterfall và alert Slack.",
  successCriteria: "Từ một alert trên Slack, trong 5 phút bạn mở dashboard → tìm trace chậm → nhảy sang log đúng request đó và chỉ ra service gây lỗi.",
  resources: [
    { title: "Prometheus documentation", url: "https://prometheus.io/docs/introduction/overview/", kind: "doc" },
    { title: "kube-prometheus-stack Helm chart", url: "https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack", kind: "tool" },
    { title: "Google SRE Book — Monitoring Distributed Systems (Four Golden Signals)", url: "https://sre.google/sre-book/monitoring-distributed-systems/", kind: "book" },
    { title: "OpenTelemetry documentation", url: "https://opentelemetry.io/docs/", kind: "doc" },
    { title: "Grafana Loki documentation", url: "https://grafana.com/docs/loki/latest/", kind: "doc" },
    { title: "PromLabs PromQL Cheat Sheet", url: "https://promlabs.com/promql-cheat-sheet/", kind: "practice" },
    { title: "Amazon CloudWatch Container Insights", url: "https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html", kind: "doc" },
  ],
  quiz: [
    {
      id: "pillar-choice-slow-request",
      question: "Người dùng báo: 'Thanh toán thỉnh thoảng mất 8 giây'. Dashboard p95 vẫn bình thường. Dữ liệu nào giúp bạn tìm ra service nào làm chậm đúng request đó?",
      options: ["Metrics CPU của node", "Traces của các request chậm", "Số lượng pod đang chạy", "Uptime check từ bên ngoài"],
      answerIndex: 1,
      explanation: "Trace là 'GPS lộ trình' của từng request: nó cho thấy request đã dừng lâu ở service nào. Metrics là táp-lô tổng hợp, dễ che mất vài request lẻ chậm.",
    },
    {
      id: "red-vs-use",
      question: "Bạn cần dashboard cho một REST API và một dashboard khác cho các node EC2. Phương pháp nào hợp lý?",
      options: ["USE cho API, RED cho node", "RED cho cả hai", "RED cho API, USE cho node", "Chỉ cần đo CPU cho cả hai"],
      answerIndex: 2,
      explanation: "RED (Rate, Errors, Duration) nhìn từ góc khách hàng của service. USE (Utilization, Saturation, Errors) nhìn vào 'máy móc' — CPU, RAM, disk, network.",
    },
    {
      id: "counter-rate",
      question: "`http_requests_total` là counter. Vì sao vẽ trực tiếp giá trị của nó lên Grafana gần như vô dụng, và nên dùng gì?",
      options: [
        "Counter chỉ tăng nên đường luôn đi lên; dùng `rate(http_requests_total[5m])` để có số request/giây",
        "Counter bị reset mỗi phút; dùng `sum()`",
        "Counter là chuỗi string; dùng `count()`",
        "Không sao cả, vẽ trực tiếp là chuẩn",
      ],
      answerIndex: 0,
      explanation: "Counter giống đồng hồ công-tơ-mét: tổng quãng đường luôn tăng. Thứ bạn cần là tốc độ — rate() tính độ tăng mỗi giây và tự xử lý khi counter reset lúc pod restart.",
    },
    {
      id: "pull-model-target-down",
      question: "Pod app bị crash. Prometheus (pull model) phát hiện điều này thế nào?",
      options: [
        "App gửi tin nhắn 'tôi chết rồi' tới Prometheus",
        "Prometheus không thể biết",
        "Grafana báo cho Prometheus",
        "Lần scrape tiếp theo thất bại, metric `up` của target về 0",
      ],
      answerIndex: 3,
      explanation: "Với pull model, Prometheus chủ động đi 'thu tiền điện' từng nhà. Nhà nào không mở cửa thì `up == 0` — một tín hiệu miễn phí để alert.",
    },
    {
      id: "alert-for-duration",
      question: "Alert có `for: 5m`. Error rate vượt ngưỡng trong 2 phút rồi trở lại bình thường. Điều gì xảy ra?",
      options: [
        "Alert gửi ngay tới Slack",
        "Alert ở trạng thái Pending rồi quay về Inactive, không gửi thông báo",
        "Alertmanager tạo silence tự động",
        "Alert firing trong đúng 5 phút",
      ],
      answerIndex: 1,
      explanation: "`for` là thời gian 'kiên nhẫn quan sát': điều kiện phải đúng liên tục đủ 5 phút mới chuyển Firing. Nhờ vậy on-call không bị đánh thức vì một cú giật ngắn.",
    },
    {
      id: "alertmanager-grouping",
      question: "Một node chết làm 40 pod cùng firing alert. Tính năng nào của Alertmanager giúp on-call nhận 1 thông báo thay vì 40?",
      options: ["Grouping (`group_by`)", "Recording rules", "Scrape interval", "Retention"],
      answerIndex: 0,
      explanation: "Grouping gom các alert giống nhau thành một 'bưu kiện'. Inhibition còn có thể tắt alert con khi alert 'node down' đang firing.",
    },
    {
      id: "loki-labels-cardinality",
      question: "Đồng nghiệp muốn thêm `user_id` làm label trong Loki để dễ tìm log. Vì sao đây là ý tưởng tồi?",
      options: [
        "Loki không hỗ trợ label",
        "user_id là dữ liệu nhạy cảm nên Loki sẽ từ chối",
        "Mỗi giá trị label tạo một stream riêng — hàng triệu user làm bùng nổ cardinality, Loki chậm và tốn kém",
        "Label chỉ dùng được cho metrics",
      ],
      answerIndex: 2,
      explanation: "Loki chỉ đánh chỉ mục label, không đánh chỉ mục nội dung. Label nên ít giá trị (namespace, app, level); user_id hãy lọc trong nội dung bằng `|=` hoặc `| json`.",
    },
    {
      id: "trace-context-propagation",
      question: "Service A gọi service B qua HTTP nhưng trong Tempo, hai span nằm ở hai trace khác nhau. Nguyên nhân khả dĩ nhất?",
      options: [
        "Tempo bị đầy ổ đĩa",
        "Header `traceparent` (W3C Trace Context) không được truyền từ A sang B",
        "Service B chạy ngôn ngữ khác",
        "Prometheus chưa scrape service B",
      ],
      answerIndex: 1,
      explanation: "Trace ID phải 'đi theo' request như mã vận đơn dán trên kiện hàng. Nếu HTTP client không inject header `traceparent`, service B sẽ mở một trace mới.",
    },
    {
      id: "otel-collector-role",
      question: "Vì sao nên gửi telemetry qua OpenTelemetry Collector thay vì cho app gửi thẳng vào Tempo/Datadog?",
      options: [
        "Collector bắt buộc phải có, app không gửi thẳng được",
        "Collector làm app chạy nhanh hơn gấp đôi",
        "Collector thay thế hoàn toàn Prometheus",
        "Collector tách app khỏi backend: đổi vendor, thêm sampling, batching, lọc dữ liệu nhạy cảm mà không sửa code",
      ],
      answerIndex: 3,
      explanation: "Collector giống bưu cục trung chuyển: app chỉ cần gửi OTLP tới một chỗ, còn chuyển đi đâu, gom lô, lọc gì là việc cấu hình của bưu cục.",
    },
    {
      id: "histogram-quantile-p95",
      question: "Bạn muốn p95 latency của toàn bộ API từ histogram. Câu PromQL nào đúng?",
      options: [
        "`avg(http_request_duration_seconds_bucket)`",
        "`max(rate(http_request_duration_seconds_count[5m]))`",
        "`histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))`",
        "`quantile(0.95, http_requests_total)`",
      ],
      answerIndex: 2,
      explanation: "Lấy rate của các bucket, cộng theo `le` (giữ ranh giới bucket), rồi histogram_quantile ước lượng p95. Trung bình che mất các request chậm.",
    },
  ],
};
