import type { ModuleDefinition } from "@/content/content-types";

export const m06AwsCoreIamModule: ModuleDefinition = {
  id: "m06",
  slug: "m06-aws-core-iam",
  phaseId: "phase-2",
  order: 6,
  weeks: "Tuần 10",
  title: "Cloud Fundamentals & AWS Core / IAM",
  emoji: "☁️",
  eli5Summary:
    "Cloud giống như thuê bếp thay vì tự xây bếp: bạn chỉ trả tiền cho phần mình dùng. Nhưng chìa khoá bếp thì bạn phải tự giữ — module này dạy bạn khoá tài khoản AWS cho chắc, phát đúng thẻ ra vào cho đúng người, và gắn chuông báo khi hoá đơn tăng.",
  objectives: [
    "Phân biệt IaaS, PaaS, FaaS, SaaS và chỉ ra phần trách nhiệm của mình trong shared responsibility model",
    "Chọn region, thiết kế triển khai multi-AZ và giải thích vai trò của edge location",
    "Viết IAM policy least privilege, phân biệt identity-based và resource-based, debug AccessDenied bằng policy evaluation logic",
    "Khoá root account, dùng IAM Identity Center, thiết lập AWS Budgets và CloudTrail",
    "Dùng AWS CLI v2 với SSO profile và cấu hình GitHub Actions truy cập AWS bằng OIDC role",
  ],
  lessons: [
    { slug: "cloud-service-models", title: "Cloud là gì: IaaS, PaaS, SaaS & trách nhiệm chung", minutes: 35, summary: "Tự nấu, mua gói hay ra quán — và vì sao dữ liệu luôn là việc của bạn." },
    { slug: "regions-availability-zones", title: "Region, Availability Zone & edge location", minutes: 30, summary: "Thành phố, kho ở các quận và cửa hàng đầu ngõ của AWS." },
    { slug: "iam-identities-and-policies", title: "IAM: user, group, role & policy", minutes: 45, summary: "Hệ thống thẻ từ khách sạn: ai là ai, được mở cửa nào." },
    { slug: "iam-policy-evaluation", title: "Policy evaluation logic & least privilege", minutes: 40, summary: "Explicit deny thắng tất cả, mặc định là KHÔNG — và cách debug AccessDenied." },
    { slug: "secure-account-and-billing", title: "Khoá tài khoản: MFA, Identity Center, Budgets, CloudTrail", minutes: 45, summary: "Thay ổ khoá, lắp chuông báo điện và camera cho căn nhà AWS mới." },
    { slug: "aws-cli-and-github-oidc", title: "AWS CLI v2, profile & GitHub Actions OIDC", minutes: 45, summary: "Credential tạm thời cho laptop và pipeline — không còn access key dài hạn." },
  ],
  labs: [
    {
      id: "lock-root-identity-center",
      title: "Khoá root & tạo admin qua IAM Identity Center",
      description: "Đưa account về trạng thái an toàn: root có MFA, không access key, người dùng hằng ngày đăng nhập qua SSO.",
      steps: [
        "Đăng nhập root, bật MFA (passkey/security key hoặc app authenticator) trong Security credentials",
        "Xoá mọi access key của root nếu có; kiểm tra `aws iam get-account-summary` cho thấy `AccountAccessKeysPresent` = 0",
        "Bật IAM Identity Center (tạo AWS Organization nếu được hỏi), chọn region cho Identity Center",
        "Tạo user cho bản thân, bật MFA, tạo permission set `AdministratorAccess` và gán vào account",
        "Trên laptop: `aws configure sso`, rồi `aws sso login --profile dev-admin`",
        "Xác nhận `aws sts get-caller-identity --profile dev-admin` trả về ARN dạng `assumed-role/AWSReservedSSO_...`; từ nay không đăng nhập root nữa",
      ],
    },
    {
      id: "budget-alerts",
      title: "Cảnh báo chi phí $10 và $25",
      description: "Tạo hai AWS Budget gửi email để phát hiện sớm tài nguyên quên tắt.",
      steps: [
        "Viết `budget.json` (Amount 10, USD, MONTHLY, COST) và `notifications.json` (ACTUAL > 80%, FORECASTED > 100%, subscriber EMAIL)",
        "`aws budgets create-budget --account-id <ACCOUNT_ID> --budget file://budget.json --notifications-with-subscribers file://notifications.json`",
        "Lặp lại với budget 25 USD",
        "Kiểm tra bằng `aws budgets describe-budgets --account-id <ACCOUNT_ID>` và xác nhận email subscription",
        "Mở Cost Explorer, lọc theo Service và Region để làm quen nơi tìm \"thủ phạm\" chi phí",
      ],
    },
    {
      id: "least-privilege-s3-policy",
      title: "Policy tối thiểu cho một S3 bucket",
      description: "Viết policy chỉ cho đọc/ghi một bucket và chứng minh nó không cho làm gì khác.",
      steps: [
        "Tạo bucket lab: `aws s3 mb s3://<ten-ban>-lab-bucket`",
        "Viết policy: `s3:ListBucket` trên ARN bucket, `s3:GetObject` + `s3:PutObject` trên ARN `bucket/*`",
        "Gắn policy cho một role hoặc user thử nghiệm (`aws iam put-user-policy ...`)",
        "Kiểm chứng bằng IAM Policy Simulator hoặc `aws iam simulate-principal-policy` với `s3:GetObject`, `s3:PutObject`, `s3:DeleteObject`",
        "Xác nhận: Get/Put = allowed, Delete và bucket khác = implicitDeny; thử thật bằng `aws s3 cp` và `aws s3 rm`",
      ],
    },
    {
      id: "github-actions-oidc-role",
      title: "GitHub Actions → AWS bằng OIDC role",
      description: "Thay access key trong GitHub Secrets bằng role được assume qua OIDC, chỉ cho nhánh main.",
      steps: [
        "Tạo OIDC provider: `aws iam create-open-id-connect-provider --url https://token.actions.githubusercontent.com --client-id-list sts.amazonaws.com`",
        "Tạo role `github-deploy` với trust policy kiểm tra `aud = sts.amazonaws.com` và `sub = repo:<org>/<repo>:ref:refs/heads/main`",
        "Gắn policy S3 tối thiểu từ lab trước cho role",
        "Viết workflow có `permissions: id-token: write` và bước `aws-actions/configure-aws-credentials` với `role-to-assume`",
        "Push lên main: job chạy `aws sts get-caller-identity` thành công; mở PR để thấy assume role bị từ chối",
        "Xoá mọi `AWS_ACCESS_KEY_ID` / `AWS_SECRET_ACCESS_KEY` còn sót trong GitHub Secrets và IAM",
      ],
    },
  ],
  deliverable:
    "Tài khoản AWS an toàn: root có MFA và không access key, admin qua IAM Identity Center, 2 budget alert, CloudTrail trail, policy S3 least privilege và workflow GitHub Actions dùng OIDC role (lưu cấu hình + README trong repo).",
  successCriteria:
    "Không còn access key dài hạn nào (kể cả trong GitHub Secrets); tự giải thích được vì sao một request bị AccessDenied bằng policy evaluation logic; nhận được email budget khi thử hạ ngưỡng.",
  resources: [
    { title: "AWS Cloud Practitioner Essentials (Skill Builder, miễn phí)", url: "https://aws.amazon.com/training/digital/aws-cloud-practitioner-essentials/", kind: "course" },
    { title: "IAM User Guide", url: "https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction.html", kind: "doc" },
    { title: "Policy evaluation logic", url: "https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html", kind: "doc" },
    { title: "Security best practices in IAM", url: "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html", kind: "doc" },
    { title: "Shared Responsibility Model", url: "https://aws.amazon.com/compliance/shared-responsibility-model/", kind: "doc" },
    { title: "AWS CLI: cấu hình IAM Identity Center (SSO)", url: "https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html", kind: "doc" },
    { title: "GitHub Docs: Configuring OpenID Connect in AWS", url: "https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services", kind: "doc" },
    { title: "IAM Policy Simulator", url: "https://policysim.aws.amazon.com/", kind: "tool" },
  ],
  quiz: [
    {
      id: "shared-responsibility-ec2",
      question: "Một lỗ hổng nghiêm trọng được công bố trong kernel Linux. Công ty chạy app trên EC2 (Amazon Linux). Ai chịu trách nhiệm vá?",
      options: ["AWS, vì AWS cung cấp AMI", "Khách hàng, vì OS trên EC2 thuộc phần 'security IN the cloud'", "AWS vá hypervisor, nên OS tự an toàn", "Không ai, vì EC2 được cách ly"],
      answerIndex: 1,
      explanation: "EC2 là IaaS — thuê bếp có sẵn nhưng nấu nướng là việc của bạn. AWS lo phần cứng và hypervisor; OS, package, app trên instance do khách hàng vá.",
    },
    {
      id: "multi-az-design",
      question: "Yêu cầu: web app phải tiếp tục phục vụ nếu một datacenter gặp sự cố, chi phí hợp lý. Thiết kế nào phù hợp nhất?",
      options: [
        "1 EC2 lớn hơn trong một AZ",
        "Triển khai song song ở 2 region với DNS failover",
        "ALB + Auto Scaling Group trải trên ít nhất 2 AZ trong một region",
        "Chụp snapshot EBS mỗi giờ",
      ],
      answerIndex: 2,
      explanation: "Như có kho ở nhiều quận: multi-AZ chịu được mất một AZ với chi phí vừa phải. Multi-region đắt và phức tạp hơn yêu cầu; snapshot chỉ giúp khôi phục, không giữ app chạy liên tục.",
    },
    {
      id: "cloudfront-acm-region",
      question: "Bạn muốn gắn certificate ACM cho một CloudFront distribution. Certificate phải được tạo ở đâu?",
      options: ["us-east-1 (N. Virginia)", "Region gần người dùng nhất", "Cùng region với origin ALB", "Bất kỳ region nào, ACM là global"],
      answerIndex: 0,
      explanation: "CloudFront là dịch vụ global chạy ở edge; nó chỉ dùng certificate ACM tạo ở us-east-1. Certificate cho ALB thì phải ở cùng region với ALB.",
    },
    {
      id: "role-vs-user-for-ec2",
      question: "Một developer lưu access key của IAM user vào file cấu hình trên EC2 để app đọc S3. Cách thay thế an toàn nhất?",
      options: [
        "Mã hoá file chứa access key",
        "Xoay vòng access key mỗi 90 ngày",
        "Chuyển access key vào biến môi trường",
        "Gắn IAM role vào EC2 qua instance profile và bỏ access key",
      ],
      answerIndex: 3,
      explanation: "Như khách sạn phát thẻ tạm ở lễ tân: role cho credential tạm thời tự xoay vòng qua metadata service. Mã hoá hay đổi chỗ để key không loại bỏ được credential dài hạn.",
    },
    {
      id: "explicit-deny-wins",
      question: "User thuộc group có AdministratorAccess, nhưng một policy khác gắn vào user có Deny cho s3:DeleteBucket. User gọi DeleteBucket. Kết quả?",
      options: ["Allow, vì AdministratorAccess cho mọi quyền", "Deny, vì explicit Deny luôn thắng Allow", "Tuỳ policy nào được gắn sau", "Allow nếu user có MFA"],
      answerIndex: 1,
      explanation: "Tờ giấy 'cấm vào phòng máy' thắng mọi tờ giấy cho phép. Thứ tự gắn policy không quan trọng — Deny khớp là kết thúc.",
    },
    {
      id: "s3-arn-bucket-vs-object",
      question: "Policy cho phép s3:GetObject và s3:ListBucket với Resource là arn:aws:s3:::reports/*. Lệnh `aws s3 ls s3://reports` báo AccessDenied. Vì sao?",
      options: [
        "Cần thêm s3:ListAllMyBuckets",
        "ListBucket áp dụng lên ARN của bucket (arn:aws:s3:::reports), không phải bucket/*",
        "Bucket phải bật public access",
        "Policy phải có Principal",
      ],
      answerIndex: 1,
      explanation: "ListBucket là hành động trên 'căn phòng' (bucket), GetObject là trên 'đồ trong phòng' (object). Cần hai Resource khác nhau. Identity policy thì không có Principal.",
    },
    {
      id: "scp-does-not-grant",
      question: "Account member trong Organization có SCP cho phép `s3:*`. Một IAM role mới tạo không gắn policy nào gọi s3:ListBucket. Kết quả?",
      options: ["Allow, vì SCP cho phép", "Allow, vì role mới có quyền đọc mặc định", "Implicit deny, vì SCP chỉ đặt trần quyền, không cấp quyền", "Explicit deny từ SCP"],
      answerIndex: 2,
      explanation: "SCP như nội quy toà nhà: nó giới hạn, không phát thẻ. Role vẫn cần identity policy (hoặc resource policy) có Allow.",
    },
    {
      id: "root-account-protection",
      question: "Việc nào nên làm NGAY sau khi tạo account AWS mới?",
      options: [
        "Tạo access key cho root để dùng với CLI",
        "Bật MFA cho root, không tạo root access key, tạo danh tính riêng cho công việc hằng ngày",
        "Chia sẻ mật khẩu root cho cả team để tiện hỗ trợ",
        "Tắt CloudTrail để tiết kiệm chi phí",
      ],
      answerIndex: 1,
      explanation: "Thay ổ khoá trước khi dọn vào: chìa gốc cất két kèm khoá vân tay, người trong nhà dùng thẻ riêng (Identity Center).",
    },
    {
      id: "budgets-behavior",
      question: "Bạn nhận email AWS Budgets báo chi phí dự báo vượt 25 USD. Bước tiếp theo hợp lý nhất?",
      options: [
        "Chờ, vì Budgets sẽ tự dừng tài nguyên khi vượt ngưỡng",
        "Xoá budget để hết nhận email",
        "Tăng ngưỡng lên 100 USD",
        "Mở Cost Explorer lọc theo service/region để tìm tài nguyên gây chi phí rồi dọn",
      ],
      answerIndex: 3,
      explanation: "Budgets là chuông báo, không phải cầu dao. Cost Explorer giúp tìm 'thủ phạm' như NAT Gateway hay EC2 quên tắt ở region khác.",
    },
    {
      id: "cloudtrail-investigation",
      question: "Một Security Group production bị mở cổng 22 cho 0.0.0.0/0 tối qua. Dịch vụ nào cho biết ai đã làm và từ IP nào?",
      options: ["CloudWatch Metrics", "AWS Budgets", "AWS CloudTrail", "Trusted Advisor"],
      answerIndex: 2,
      explanation: "CloudTrail là camera ở cửa: ghi lại lời gọi AuthorizeSecurityGroupIngress kèm danh tính, thời gian, IP nguồn.",
    },
    {
      id: "github-oidc-permission",
      question: "Workflow dùng `aws-actions/configure-aws-credentials` với role-to-assume nhưng báo không lấy được credential; trust policy đã đúng. Thiếu gì nhiều khả năng nhất?",
      options: [
        "`permissions: id-token: write` trong workflow",
        "Secret AWS_SECRET_ACCESS_KEY",
        "Thumbprint của GitHub trong trust policy",
        "Quyền AdministratorAccess cho role",
      ],
      answerIndex: 0,
      explanation: "Không có id-token: write thì GitHub không in 'vé gửi xe' (JWT) cho job, nên chẳng có gì để đổi lấy credential tạm từ STS. OIDC không cần secret access key.",
    },
  ],
};
