import type { ModuleDefinition } from "@/content/content-types";

export const b03ValidationErrorHandlingApiDesignModule: ModuleDefinition = {
  id: "b03",
  slug: "b03-validation-error-handling-api-design",
  phaseId: "b-phase-0",
  order: 3,
  weeks: "Tuần 3–4",
  title: "Validation, Error Handling & API Design chuẩn",
  emoji: "🛂",
  eli5Summary:
    "B02 xây được cửa vào (route) nhưng chưa có bảo vệ đứng gác — ai đưa gì vào cũng nhận. Module này lắp một trạm kiểm tra hộ chiếu (Zod) trước cửa, một tổng đài xử lý sự cố (error handler) trả lời luôn theo một mẫu câu, và một tấm bản đồ tự động cập nhật (OpenAPI) cho khách tham quan.",
  objectives: [
    "Viết Zod schema validate body/query/params và gắn vào route Fastify",
    "Viết `setErrorHandler` tập trung trả đúng format lỗi chuẩn của cả course",
    "Giải thích vì sao cursor pagination không bị lệch khi dữ liệu thay đổi giữa các trang, còn offset thì có",
    "Thêm cursor pagination cho endpoint danh sách (`GET /api/v1/tasks`)",
    "Giải thích idempotency key kiểm tra trước khi thực thi side effect, không phải sau",
    "Tự sinh tài liệu OpenAPI từ đúng schema Zod đang dùng để validate (một nguồn sự thật duy nhất)",
  ],
  lessons: [
    {
      slug: "zod-schema-validation-fastify",
      title: "Zod schema & tích hợp Fastify",
      minutes: 40,
      summary: "Trạm kiểm tra hộ chiếu trước cửa route: Zod parse body/query/params trước khi handler chạy.",
    },
    {
      slug: "centralized-error-handling",
      title: "Error handling tập trung & format lỗi chuẩn",
      minutes: 40,
      summary: "Một tổng đài duy nhất bắt mọi loại lỗi và trả lời theo đúng một mẫu câu.",
    },
    {
      slug: "cursor-based-pagination",
      title: "Cursor pagination cho danh sách",
      minutes: 40,
      summary: "Đánh dấu trang bằng 'người cuối cùng đã phục vụ', không phải đếm số thứ tự.",
    },
    {
      slug: "openapi-auto-generation",
      title: "Tự sinh OpenAPI bằng @fastify/swagger",
      minutes: 35,
      summary: "Tấm bản đồ /docs tự vẽ lại mỗi khi schema Zod đổi — không cần viết tay hai lần.",
    },
  ],
  labs: [
    {
      id: "them-zod-schema-validation",
      title: "Thêm Zod schema cho toàn bộ route B02",
      description: "Validate body/query/params của `projects` và `tasks` bằng Zod, gắn vào Fastify qua type provider.",
      steps: [
        "Cài `zod` và `fastify-type-provider-zod`: `pnpm add zod fastify-type-provider-zod`",
        "Trong `src/app.ts`, gọi `.setValidatorCompiler(validatorCompiler)` và `.setSerializerCompiler(serializerCompiler)`, rồi `.withTypeProvider<ZodTypeProvider>()`",
        "Tạo `src/schemas/project.schema.ts` với `createProjectBodySchema` (`name` bắt buộc, tối thiểu 1 ký tự) bằng `z.object`",
        "Tạo `src/schemas/task.schema.ts` với `createTaskBodySchema` (`title` bắt buộc, `status` enum `['todo','in_progress','done']` mặc định `'todo'`) và `taskParamsSchema` (`id` phải là `z.string().uuid()`)",
        "Gắn từng schema vào đúng route tương ứng qua field `schema: { body, params, querystring }` trong `fastify.post/get/patch`",
        "Gửi `curl` với body thiếu `title` và với `id` không phải UUID, xác nhận Fastify tự trả `400` trước khi vào tới handler (chưa đúng format lỗi cuối cùng — sẽ sửa ở lab 2)",
      ],
    },
    {
      id: "viet-centralized-error-handler",
      title: "Viết centralized error handler",
      description: "Một `setErrorHandler` duy nhất bắt mọi lỗi (Zod, lỗi nghiệp vụ tự định nghĩa, lỗi không lường trước) và trả đúng format chuẩn của course.",
      steps: [
        "Tạo `src/errors/app-error.ts` export class `AppError extends Error` có `statusCode`, `code`, và optional `details`",
        "Tạo các subclass tiện dùng: `NotFoundError` (404, `NOT_FOUND`), `ConflictError` (409, `CONFLICT`)",
        "Trong `src/app.ts`, gọi `fastify.setErrorHandler((error, request, reply) => { ... })`",
        "Trong handler: nếu `error.code === 'FST_ERR_VALIDATION'` hoặc `error instanceof ZodError` → trả `422` với `code: 'VALIDATION_ERROR'` và `details` là mảng lỗi từng field",
        "Nếu `error instanceof AppError` → trả đúng `error.statusCode` với `error.code`",
        "Còn lại (lỗi không lường trước) → log bằng `request.log.error(error)` rồi trả `500` với `code: 'INTERNAL_ERROR'`, KHÔNG lộ `error.message` gốc ra response",
        "Sửa route `GET /api/v1/projects/:id` ném `NotFoundError` khi không tìm thấy thay vì tự trả JSON lỗi tay; kiểm tra `curl` trả đúng format `{ \"error\": { \"code\", \"message\", \"details\" } }` cho cả 3 trường hợp",
      ],
    },
    {
      id: "cursor-pagination-va-openapi-docs",
      title: "Cursor pagination cho GET /tasks + expose /docs",
      description: "Thêm phân trang kiểu cursor cho danh sách task, rồi tự sinh OpenAPI docs từ đúng schema đang validate.",
      steps: [
        "Thêm `querystring` schema cho `GET /api/v1/tasks`: `cursor` (optional string), `limit` (optional number, mặc định 20, tối đa 100)",
        "Sort in-memory tasks theo `createdAt` giảm dần; giải mã `cursor` (base64 của `createdAt` bản ghi cuối trang trước) để lọc `createdAt < cursor đã giải mã`",
        "Lấy đúng `limit` bản ghi, mã hoá `createdAt` của bản ghi cuối cùng trong trang thành `cursor` mới cho `meta.cursor`",
        "Trả đúng shape chuẩn: `{ data: [...], meta: { cursor: \"...\" } }`, `meta.cursor` là `null` khi hết dữ liệu",
        "Cài `@fastify/swagger` và `@fastify/swagger-ui`: `pnpm add @fastify/swagger @fastify/swagger-ui`",
        "Đăng ký 2 plugin đó trong `src/app.ts`, dùng `jsonSchemaTransform` từ `fastify-type-provider-zod` để convert Zod schema đã gắn ở route sang OpenAPI — KHÔNG viết OpenAPI spec tay riêng",
        "Mở `http://localhost:3000/docs`, xác nhận thấy đủ route `projects`/`tasks` với đúng request/response schema như Zod đang validate",
      ],
    },
  ],
  deliverable:
    "`taskflow-api` với toàn bộ route B02 có Zod validation, một `setErrorHandler` trả đúng format `{ error: { code, message, details } }`, `GET /api/v1/tasks` hỗ trợ cursor pagination, và `/docs` hiển thị OpenAPI tự sinh từ cùng schema.",
  successCriteria:
    "Gửi input sai kiểu/thiếu field luôn nhận `422` đúng format chuẩn; gọi `GET /api/v1/tasks?limit=2` nhiều lần bằng `meta.cursor` trả về không trùng, không thiếu; `/docs` hiển thị đúng toàn bộ route không cần sửa tay.",
  resources: [
    { title: "Zod docs", url: "https://zod.dev/", kind: "doc" },
    { title: "Fastify docs — Validation and Serialization", url: "https://fastify.dev/docs/latest/Reference/Validation-and-Serialization/", kind: "doc" },
    { title: "fastify-type-provider-zod (GitHub)", url: "https://github.com/turkerdev/fastify-type-provider-zod", kind: "tool" },
    { title: "@fastify/swagger (GitHub)", url: "https://github.com/fastify/fastify-swagger", kind: "tool" },
    { title: "Google AIP-158 — Pagination", url: "https://google.aip.dev/158", kind: "doc" },
    { title: "Stripe API docs — Idempotent Requests", url: "https://docs.stripe.com/api/idempotent_requests", kind: "doc" },
  ],
  quiz: [
    {
      id: "zod-validation-timing",
      question: "Client gửi `POST /api/v1/tasks` với body thiếu `title`. Với Zod schema đã gắn vào route, chuyện gì xảy ra trước tiên?",
      options: [
        "Fastify chạy validator compiler, request bị chặn trước khi vào handler",
        "Handler vẫn chạy, `title` nhận giá trị `undefined`",
        "Request được lưu tạm rồi validate sau khi response",
        "Zod chỉ cảnh báo ở log, không chặn request",
      ],
      answerIndex: 0,
      explanation: "Zod schema gắn vào route qua `withTypeProvider` chạy ở bước validate của Fastify — trước handler. Handler chỉ chạy khi request đã hợp lệ.",
    },
    {
      id: "error-format-shape",
      question: "Theo quy ước cố định của `taskflow-api`, response lỗi validation phải có shape nào?",
      options: [
        "`{ message: \"...\", status: 422 }`",
        "`{ errors: [\"...\"] }`",
        "`{ error: { code: \"VALIDATION_ERROR\", message: \"...\", details: [...] } }`",
        "`{ success: false, data: null }`",
      ],
      answerIndex: 2,
      explanation: "Format lỗi chốt từ mục 3 curriculum, dùng xuyên suốt 19 module: object `error` bọc `code`/`message`/`details`. Tự đổi shape ở module sau sẽ phá mọi client đã tích hợp.",
    },
    {
      id: "error-handler-catch-all",
      question: "Vì sao nên có một `setErrorHandler` DUY NHẤT thay vì mỗi route tự try/catch và trả JSON lỗi riêng?",
      options: [
        "Vì Fastify không cho phép try/catch trong handler",
        "Vì try/catch làm chậm response",
        "Vì centralized handler chạy song song với handler chính nên nhanh hơn",
        "Vì tập trung một chỗ đảm bảo mọi lỗi (kể cả lỗi chưa lường trước) đều ra đúng một format, không route nào 'quên'",
      ],
      answerIndex: 3,
      explanation: "Mỗi route tự xử lý lỗi rất dễ có route quên/viết sai format. Một `setErrorHandler` ở tầng app đảm bảo tính nhất quán, kể cả lỗi runtime không ai ngờ tới.",
    },
    {
      id: "internal-error-leak",
      question: "Một query Postgres lỗi bất ngờ (chưa được `AppError` bọc) rơi vào `setErrorHandler`. Response nên làm gì?",
      options: [
        "Log lỗi đầy đủ ở server, trả client `500` với message chung chung và `code: \"INTERNAL_ERROR\"`",
        "Trả nguyên `error.message` và `error.stack` ra client để debug nhanh",
        "Trả `200` kèm `data: null` để tránh client bị lỗi",
        "Bỏ qua, không trả response gì cả",
      ],
      answerIndex: 0,
      explanation: "Lộ `error.message`/`stack` ra ngoài có thể rò thông tin nội bộ (tên bảng, câu query). Log đầy đủ ở server (có `requestId` để tra sau), client chỉ nhận thông báo chung.",
    },
    {
      id: "offset-pagination-drift",
      question: "Đang phân trang `GET /tasks?offset=3&limit=3` bằng offset. Giữa lúc lấy trang 1 và trang 2, có 1 task MỚI được tạo và chèn lên đầu danh sách (sort theo mới nhất). Điều gì có thể xảy ra ở trang 2?",
      options: [
        "Không ảnh hưởng gì vì offset luôn đếm từ đầu danh sách hiện tại",
        "Trang 2 sẽ tự động bỏ qua task mới đó",
        "Trang 2 có thể trả trùng lại 1 task đã thấy ở trang 1, vì mọi thứ bị đẩy lùi 1 vị trí",
        "Server sẽ trả lỗi 409 Conflict",
      ],
      answerIndex: 2,
      explanation: "Offset đếm theo VỊ TRÍ tuyệt đối. Khi có bản ghi mới chèn lên đầu, toàn bộ danh sách dịch xuống 1 bậc — offset=3 giờ trỏ vào bản ghi đã hiện ở trang 1, gây trùng lặp.",
    },
    {
      id: "cursor-pagination-resilience",
      question: "Vì sao cursor pagination (dùng `createdAt` của bản ghi cuối trang trước làm cursor) không bị lỗi trùng/thiếu như offset khi có insert/delete giữa các trang?",
      options: [
        "Vì cursor pagination luôn cache toàn bộ kết quả từ trang đầu",
        "Vì cursor pagination không cho phép ai insert dữ liệu mới trong lúc phân trang",
        "Vì cursor luôn giới hạn đúng 20 bản ghi mỗi trang",
        "Vì cursor mã hoá VỊ TRÍ TƯƠNG ĐỐI so với một bản ghi cụ thể ('lấy các bản ghi cũ hơn X'), không phụ thuộc số thứ tự tuyệt đối nào đang bị thay đổi",
      ],
      answerIndex: 3,
      explanation: "Cursor neo vào một bản ghi đã biết ('createdAt < cursor'). Dù có thêm/xoá bản ghi khác, điều kiện lọc tương đối đó vẫn đúng — khác hẳn offset đếm theo số thứ tự tuyệt đối.",
    },
    {
      id: "pagination-response-shape",
      question: "Response thành công cho `GET /api/v1/tasks` (danh sách) phải theo shape nào của course?",
      options: [
        "`{ data: [...], meta: { cursor: \"...\" } }`",
        "`[{ ...task }, { ...task }]` — mảng trần",
        "`{ results: [...], page: 2, total: 40 }`",
        "`{ tasks: [...], hasMore: true }`",
      ],
      answerIndex: 0,
      explanation: "Quy ước API của `taskflow-api` (mục 3) cố định: danh sách trả `data` + `meta.cursor`, không dùng offset/`page`/`total`.",
    },
    {
      id: "idempotency-key-timing",
      question: "Client gửi `POST /api/v1/tasks` kèm `Idempotency-Key: abc123` hai lần liên tiếp (do mất mạng, client retry). Server nên kiểm tra key này ở đâu?",
      options: [
        "Sau khi đã tạo task xong, để log lại là request trùng",
        "Không cần kiểm tra, Postgres tự chống trùng bằng `id` uuid",
        "Trước khi thực thi side effect (tạo task) — nếu key đã thấy trước đó, trả lại đúng kết quả lần đầu, không tạo task thứ hai",
        "Chỉ cần kiểm tra ở tầng client, server không cần biết",
      ],
      answerIndex: 2,
      explanation: "Idempotency key phải được tra TRƯỚC khi thực thi side effect. Kiểm tra sau thì task thứ hai đã lỡ được tạo rồi — mất hết ý nghĩa chống trùng.",
    },
    {
      id: "openapi-source-of-truth",
      question: "Vì sao `/docs` (OpenAPI) nên được sinh từ CHÍNH schema Zod đang dùng để validate, thay vì viết một file OpenAPI riêng bằng tay?",
      options: [
        "Vì viết tay OpenAPI nhanh hơn và không ai cần maintain 2 chỗ",
        "Vì Fastify không hỗ trợ viết OpenAPI bằng tay",
        "Vì OpenAPI viết tay không hiển thị được trên Swagger UI",
        "Vì viết 2 nơi (schema validate + spec doc riêng) rất dễ lệch nhau khi 1 trong 2 được sửa mà quên sửa chỗ còn lại",
      ],
      answerIndex: 3,
      explanation: "Một nguồn sự thật duy nhất (Zod schema) tránh tình trạng doc nói một đằng, code validate một nẻo — lỗi rất phổ biến khi 2 định nghĩa tách rời nhau.",
    },
    {
      id: "status-code-choice",
      question: "Request đúng cấu trúc JSON nhưng `status` gửi giá trị `\"archived\"` (không nằm trong enum `todo/in_progress/done`). Status code phù hợp nhất là gì?",
      options: ["400 Bad Request", "422 Unprocessable Entity", "404 Not Found", "409 Conflict"],
      answerIndex: 1,
      explanation: "422 dành cho request có cú pháp đúng (JSON hợp lệ) nhưng dữ liệu ngữ nghĩa sai (giá trị không thuộc enum cho phép) — đúng như Zod trả về khi `.enum()` không khớp.",
    },
  ],
};
