import type { ModuleDefinition } from "@/content/content-types";

export const m16SrePracticesModule: ModuleDefinition = {
  id: "m16",
  slug: "m16-sre-practices",
  phaseId: "phase-5",
  order: 16,
  weeks: "Tuần 25",
  title: "SRE Practices",
  emoji: "🛟",
  eli5Summary:
    "Quán pizza hứa 'giao trong 30 phút'. SRE là cách biến lời hứa đó thành con số đo được, cho phép trễ một chút có kiểm soát (error budget), và khi trễ thật thì xử lý bình tĩnh, rút kinh nghiệm mà không đổ lỗi cho shipper.",
  objectives: [
    "Định nghĩa SLI, SLO, SLA đúng cách từ góc nhìn người dùng",
    "Tính error budget và áp dụng error budget policy để cân bằng tốc độ ra tính năng với độ ổn định",
    "Viết alert theo SLO bằng multi-window, multi-burn-rate thay cho ngưỡng cố định",
    "Nhận diện toil, ưu tiên tự động hoá và lập kế hoạch capacity cơ bản",
    "Điều phối incident với vai trò rõ ràng, viết runbook và blameless postmortem",
    "Chạy chaos experiment và game day có kiểm soát bằng Chaos Mesh hoặc AWS FIS",
  ],
  lessons: [
    { slug: "sli-slo-sla", title: "SLI, SLO & SLA", minutes: 40, summary: "Lời hứa giao pizza 30 phút: đo gì, hứa bao nhiêu, đền gì." },
    { slug: "error-budget-policy", title: "Error budget & error budget policy", minutes: 35, summary: "Quỹ 'được phép hỏng' — tiêu hết thì dừng tính năng, sửa độ ổn định." },
    { slug: "slo-burn-rate-alerting", title: "Alert theo SLO: multi-window, multi-burn-rate", minutes: 45, summary: "Báo động theo tốc độ đốt ngân sách lỗi thay vì ngưỡng CPU." },
    { slug: "toil-automation-capacity", title: "Toil, tự động hoá & capacity planning", minutes: 35, summary: "Việc tay chân lặp lại là nợ — nhận diện, đo và loại bỏ." },
    { slug: "incident-management-postmortem", title: "Incident management, runbook & postmortem", minutes: 45, summary: "Ai chỉ huy, ai liên lạc, sửa thế nào và học gì mà không đổ lỗi." },
    { slug: "chaos-engineering-game-day", title: "Chaos engineering & game day", minutes: 40, summary: "Chủ động gây lỗi có kiểm soát để tìm điểm yếu trước khách hàng." },
  ],
  labs: [
    {
      id: "define-slos-error-budget-dashboard",
      title: "Định nghĩa 2 SLO & dashboard error budget",
      description: "Viết SLO availability 99.5% và latency p95 dưới 300ms cho app mẫu từ M15, tạo recording rule, burn-rate alert và dashboard error budget.",
      steps: [
        "Viết tài liệu SLO (`slo.md`): SLI availability = request không 5xx / tổng request; SLI latency = tỉ lệ request nhanh hơn 300ms; cửa sổ 30 ngày",
        "Kiểm tra histogram có bucket `le=\"0.3\"`; nếu chưa có, thêm bucket 0.3 vào `http_request_duration_seconds` của app",
        "Tạo `PrometheusRule` recording rule `sli:availability:ratio_rate5m`, `ratio_rate30m`, `ratio_rate1h`, `ratio_rate6h` (hoặc sinh bằng Sloth/Pyrra)",
        "Thêm alert burn rate: page khi 1h và 5m cùng vượt `14.4 * 0.005`; ticket khi 6h và 30m vượt `6 * 0.005`",
        "Tạo dashboard Grafana: SLI hiện tại, % error budget còn lại trong 30 ngày, burn rate 1h/6h",
        "Chạy `hey -z 5m -c 20 http://localhost:8080/fail` để đốt budget có chủ đích và xác nhận alert firing đúng như tính toán",
      ],
    },
    {
      id: "write-runbooks-critical-alerts",
      title: "Viết runbook cho 3 alert quan trọng",
      description: "Mỗi alert page phải có runbook: triệu chứng, cách xác nhận, cách giảm thiểu, cách escalate.",
      steps: [
        "Chọn 3 alert: `CheckoutErrorBudgetBurnFast`, `HighLatencyP95`, `KubePodCrashLooping`",
        "Mỗi runbook theo template: Ý nghĩa → Tác động người dùng → Chẩn đoán (lệnh `kubectl`, PromQL, link dashboard) → Giảm thiểu (rollback, scale) → Escalate",
        "Ghi lệnh copy-paste được, ví dụ `kubectl -n shop rollout undo deploy/checkout` và `kubectl -n shop rollout status deploy/checkout`",
        "Thêm annotation `runbook_url` vào từng alert trong `PrometheusRule` trỏ tới file runbook trong Git",
        "Nhờ một người chưa biết hệ thống làm theo runbook trong môi trường lab; sửa mọi chỗ họ bị kẹt",
      ],
    },
    {
      id: "game-day-chaos-mesh-postmortem",
      title: "Game day với Chaos Mesh & viết postmortem",
      description: "Lên kế hoạch, gây lỗi có kiểm soát (kill pod, inject latency), xử lý theo runbook và viết blameless postmortem.",
      steps: [
        "Cài Chaos Mesh: `helm repo add chaos-mesh https://charts.chaos-mesh.org` rồi `helm install chaos-mesh chaos-mesh/chaos-mesh -n chaos-mesh --create-namespace`",
        "Viết kế hoạch game day: steady-state hypothesis (SLI availability ≥ 99.5% trong lúc thí nghiệm), phạm vi (namespace `shop`), điều kiện dừng khẩn cấp",
        "Thí nghiệm 1: `PodChaos` action `pod-kill` mode `one` cho `app: checkout` — quan sát replica và PodDisruptionBudget",
        "Thí nghiệm 2: `NetworkChaos` action `delay` latency `500ms` cho `app: payments` trong 10 phút — quan sát p95, timeout và retry",
        "Một người đóng vai on-call chỉ được dùng dashboard + runbook để phát hiện và giảm thiểu; người khác ghi timeline",
        "Xoá thí nghiệm bằng `kubectl delete podchaos,networkchaos -n shop --all` và xác nhận hệ thống hồi phục",
        "Viết postmortem blameless: tóm tắt, tác động, timeline, nguyên nhân gốc, điều làm tốt, action items có owner và hạn",
      ],
    },
  ],
  deliverable: "Repo chứa tài liệu SLO, PrometheusRule (recording + burn-rate alert), JSON dashboard error budget, 3 runbook, manifest Chaos Mesh và một postmortem hoàn chỉnh từ game day.",
  successCriteria: "Giải thích được vì sao chọn 99.5% chứ không phải 99.99%; alert burn rate firing đúng khi đốt budget có chủ đích; người khác làm theo runbook xử lý được sự cố giả lập mà không cần hỏi bạn.",
  resources: [
    { title: "Site Reliability Engineering (Google, miễn phí)", url: "https://sre.google/sre-book/table-of-contents/", kind: "book" },
    { title: "The Site Reliability Workbook — Alerting on SLOs", url: "https://sre.google/workbook/alerting-on-slos/", kind: "book" },
    { title: "The Site Reliability Workbook — Error Budget Policy", url: "https://sre.google/workbook/error-budget-policy/", kind: "book" },
    { title: "PagerDuty Incident Response Documentation", url: "https://response.pagerduty.com/", kind: "doc" },
    { title: "Chaos Mesh documentation", url: "https://chaos-mesh.org/docs/", kind: "doc" },
    { title: "AWS Fault Injection Service", url: "https://docs.aws.amazon.com/fis/latest/userguide/what-is.html", kind: "doc" },
    { title: "Sloth — sinh Prometheus SLO rules", url: "https://sloth.dev/", kind: "tool" },
  ],
  quiz: [
    {
      id: "sli-user-centric",
      question: "Team đề xuất SLI cho checkout là 'CPU trung bình của pod dưới 70%'. Vì sao đây là SLI kém?",
      options: [
        "CPU không đo được bằng Prometheus",
        "CPU là chỉ số nội bộ, không phản ánh trực tiếp trải nghiệm người dùng như tỉ lệ request thành công hay độ trễ",
        "SLI phải luôn là số tiền",
        "70% quá thấp, phải là 90%",
      ],
      answerIndex: 1,
      explanation: "Khách đặt pizza không quan tâm bếp nóng bao nhiêu độ — họ quan tâm pizza tới đúng giờ và không bị sai món. SLI tốt đo từ góc nhìn người dùng.",
    },
    {
      id: "slo-vs-sla-strictness",
      question: "Công ty ký SLA 99.9% với khách hàng. SLO nội bộ nên đặt thế nào?",
      options: ["Bằng đúng 99.9%", "Thấp hơn, 99.5%, để team đỡ áp lực", "Chặt hơn SLA một chút, vd 99.95%, để có vùng đệm trước khi phải bồi thường", "Không cần SLO khi đã có SLA"],
      answerIndex: 2,
      explanation: "SLA là lời hứa có đền tiền; SLO là mục tiêu nội bộ chặt hơn để bạn thấy nguy cơ và kịp sửa trước khi vi phạm hợp đồng.",
    },
    {
      id: "error-budget-minutes",
      question: "SLO availability 99.9% trong cửa sổ 30 ngày tương ứng với khoảng bao nhiêu phút 'được phép hỏng'?",
      options: ["~43 phút", "~4 phút", "~7 giờ", "~432 phút"],
      answerIndex: 0,
      explanation: "30 ngày = 43.200 phút; 0,1% của 43.200 ≈ 43,2 phút. Mỗi số 9 thêm vào chia quỹ này cho 10.",
    },
    {
      id: "error-budget-exhausted",
      question: "Giữa tháng, dịch vụ đã tiêu 120% error budget. Theo error budget policy điển hình, việc nào hợp lý?",
      options: [
        "Tăng tốc ra tính năng để bù",
        "Hạ SLO xuống cho vừa với thực tế ngay lập tức",
        "Không làm gì, chờ sang tháng",
        "Tạm dừng release tính năng không khẩn cấp, ưu tiên các việc cải thiện độ tin cậy cho tới khi budget hồi phục",
      ],
      answerIndex: 3,
      explanation: "Quỹ 'được phép trễ' đã tiêu hết: shipper phải tập trung giao đúng giờ trước khi quán mở thêm món mới. Policy được thống nhất trước nên không cần cãi nhau lúc sự cố.",
    },
    {
      id: "burn-rate-meaning",
      question: "Burn rate = 14.4 trong 1 giờ với SLO cửa sổ 30 ngày nghĩa là gì?",
      options: [
        "14,4% request đang lỗi",
        "Đang tiêu error budget nhanh gấp 14,4 lần mức 'vừa đủ hết đúng 30 ngày' — 1 giờ như vậy đốt ~2% budget tháng",
        "Còn 14,4 giờ trước khi hết budget",
        "SLO đã bị vi phạm 14,4 lần",
      ],
      answerIndex: 1,
      explanation: "Burn rate 1 = hết budget đúng cuối cửa sổ. 14,4 × 1h / 720h = 2% budget. Giữ tốc độ đó thì budget cạn sau khoảng 2 ngày.",
    },
    {
      id: "short-window-purpose",
      question: "Vì sao alert burn rate dùng thêm cửa sổ ngắn (5m) bên cạnh cửa sổ dài (1h)?",
      options: [
        "Để alert tắt nhanh sau khi sự cố đã được khắc phục, tránh tiếp tục page vì dữ liệu cũ trong cửa sổ 1h",
        "Để tăng số lượng alert",
        "Vì Prometheus không tính được cửa sổ 1h",
        "Để thay thế hoàn toàn cửa sổ dài",
      ],
      answerIndex: 0,
      explanation: "Cửa sổ dài xác nhận 'đốt đủ nhiều để đáng page'; cửa sổ ngắn xác nhận 'vẫn đang đốt ngay lúc này'. Hết cháy thì cửa sổ ngắn về bình thường và alert resolved.",
    },
    {
      id: "toil-identification",
      question: "Việc nào dưới đây là toil điển hình?",
      options: [
        "Thiết kế kiến trúc multi-region mới",
        "Viết postmortem cho sự cố tuần trước",
        "Mỗi sáng SSH vào server xoá log cũ bằng tay vì disk đầy, số lần tăng theo số server",
        "Review code của đồng nghiệp",
      ],
      answerIndex: 2,
      explanation: "Toil: thủ công, lặp lại, tự động hoá được, không để lại giá trị lâu dài và tăng tuyến tính theo quy mô. Giải pháp: log rotation + retention tự động.",
      recallPrompt: "Việc SSH vào từng server mỗi sáng để xoá log cũ bằng tay, số lần tăng theo số server, là ví dụ điển hình của khái niệm gì trong SRE, và vì sao?",
    },
    {
      id: "incident-commander-role",
      question: "Trong một sự cố SEV1, incident commander (IC) nên làm gì?",
      options: [
        "Tự gõ lệnh sửa lỗi nhanh nhất có thể",
        "Điều phối: phân vai, quyết định hướng xử lý, đảm bảo có người cập nhật stakeholder — không tự sa vào debug",
        "Tìm xem ai đã deploy gây lỗi để kỷ luật",
        "Viết postmortem ngay trong lúc sự cố đang diễn ra",
      ],
      answerIndex: 1,
      explanation: "IC giống chỉ huy đội cứu hoả: không cầm vòi nước mà giữ bức tranh tổng, phân việc và ra quyết định. Người sửa lỗi là ops/tech lead.",
    },
    {
      id: "blameless-postmortem",
      question: "Kỹ sư chạy nhầm lệnh xoá bảng trên production. Postmortem blameless nên tập trung vào điều gì?",
      options: [
        "Vì sao hệ thống cho phép một lệnh thủ công xoá dữ liệu production mà không có bảo vệ, và cần thay đổi gì",
        "Tên kỹ sư và mức kỷ luật",
        "Không cần postmortem vì đó là lỗi cá nhân",
        "Cấm kỹ sư đó truy cập production vĩnh viễn",
      ],
      answerIndex: 0,
      explanation: "Blameless không có nghĩa là không có trách nhiệm — mà là sửa hệ thống để lỗi con người không thành thảm hoạ: quyền tối thiểu, xác nhận hai bước, backup đã kiểm thử.",
    },
    {
      id: "chaos-steady-state",
      question: "Trước khi chạy chaos experiment kill pod trên staging, bước quan trọng nhất là gì?",
      options: [
        "Chạy thẳng trên production cho thật",
        "Tắt hết alert để không bị làm phiền",
        "Kill toàn bộ pod cùng lúc cho nhanh",
        "Định nghĩa steady-state hypothesis đo được (vd SLI giữ ≥ 99.5%) và điều kiện dừng khẩn cấp",
      ],
      answerIndex: 3,
      explanation: "Chaos engineering là thí nghiệm khoa học: có giả thuyết, phạm vi nhỏ (blast radius), và nút dừng. Không có giả thuyết thì chỉ là phá hoại.",
    },
  ],
};
