import type { ModuleDefinition } from "@/content/content-types";

export const m10TerraformModule: ModuleDefinition = {
  id: "m10",
  slug: "m10-terraform",
  phaseId: "phase-3",
  order: 10,
  weeks: "Tuần 16–17",
  title: "Terraform",
  emoji: "🏗️",
  eli5Summary:
    "Thay vì dặn thợ từng câu trên Console, bạn đưa cho Terraform một bản vẽ hạ tầng. Terraform so bản vẽ với thực tế, báo giá trước (plan), bạn duyệt rồi nó mới thi công (apply) — và ghi tất cả vào một cuốn sổ chung có khoá.",
  objectives: [
    "Giải thích IaC declarative khác imperative thế nào và vì sao idempotency quan trọng",
    "Viết HCL với provider, resource, data source, variable, output, locals, for_each",
    "Đọc plan thành thạo, nhận ra thay đổi nguy hiểm (-/+ và -) trước khi apply",
    "Thiết lập remote state trên S3 có versioning, mã hoá và locking",
    "Tổ chức module dùng chung cho nhiều môi trường dev/staging",
    "Dựng pipeline plan-trên-PR, apply-khi-merge qua OIDC và xử lý drift, import, moved",
  ],
  lessons: [
    { slug: "iac-declarative-mindset", title: "IaC: bản vẽ thay vì mệnh lệnh", minutes: 30, summary: "Declarative vs imperative, idempotency, Terraform so với CloudFormation, CDK, Pulumi, OpenTofu." },
    { slug: "terraform-core-workflow", title: "init → plan → apply → destroy", minutes: 40, summary: "Vòng đời chuẩn và cách đọc ký hiệu +, ~, -/+, - trong plan." },
    { slug: "hcl-building-blocks", title: "HCL: các khối xây dựng", minutes: 50, summary: "Provider, resource, data, variable, locals, output, count vs for_each, dynamic block, lifecycle." },
    { slug: "state-remote-backend", title: "State, remote backend & locking", minutes: 45, summary: "Sổ kiểm kê của Terraform, S3 backend với use_lockfile và các lệnh state." },
    { slug: "modules-environments", title: "Module & nhiều môi trường", minutes: 45, summary: "Một bộ module cho dev/staging/prod: thư mục theo env, workspaces, Terragrunt." },
    { slug: "terraform-ci-drift-import", title: "CI/CD, drift, import & moved", minutes: 50, summary: "Plan trên PR, apply qua OIDC, tflint/checkov, phát hiện drift và refactor an toàn." },
  ],
  labs: [
    {
      id: "terraform-modules-checkpoint2",
      title: "Dựng lại Checkpoint 2 bằng module tự viết",
      description: "Viết module vpc, alb-asg, rds và dùng chúng để dựng môi trường dev và staging giống kiến trúc Checkpoint 2.",
      steps: [
        "Tạo cấu trúc `infra/modules/{vpc,alb-asg,rds}` và `infra/envs/{dev,staging}`",
        "Module `vpc`: VPC, public/private subnet dùng `for_each` theo AZ, IGW, NAT (biến `single_nat`), route table; output `vpc_id`, `public_subnet_ids`, `private_subnet_ids`",
        "Module `alb-asg`: ALB, target group có health check, launch template, ASG trong private subnet; output `alb_dns_name`",
        "Module `rds`: DB subnet group, security group chỉ nhận từ SG của app, `manage_master_user_password = true`",
        "Trong `envs/dev/main.tf` gọi 3 module, truyền output của `vpc` vào `alb-asg` và `rds`",
        "Chạy `terraform fmt -recursive`, `terraform validate`, `terraform plan -out=tfplan` rồi `terraform apply tfplan`",
        "Kiểm tra `curl http://$(terraform output -raw alb_dns_name)/health` trả 200; lặp lại cho `envs/staging` với tfvars khác",
        "Tiêu chí đạt: `terraform destroy` rồi `terraform apply` lại, app chạy mà không chỉnh tay bước nào",
      ],
    },
    {
      id: "s3-remote-state-locking",
      title: "Remote state trên S3 có locking",
      description: "Tạo bucket state an toàn và chuyển state của các môi trường lên S3 với native locking.",
      steps: [
        "Thư mục `bootstrap/`: tạo S3 bucket với versioning, SSE, public access block và `prevent_destroy`",
        "Thêm `backend \"s3\"` với `key = \"dev/terraform.tfstate\"`, `encrypt = true`, `use_lockfile = true` (cần Terraform bản hỗ trợ, kiểm tra tài liệu)",
        "Chạy `terraform init -migrate-state` và xác nhận file state xuất hiện bằng `aws s3 ls`",
        "Mở 2 terminal, chạy `terraform apply` cùng lúc và quan sát lỗi `Error acquiring the state lock`",
        "Thêm `*.tfstate*` và `.terraform/` vào `.gitignore`; commit `.terraform.lock.hcl`",
      ],
    },
    {
      id: "github-actions-terraform-pipeline",
      title: "Pipeline plan trên PR, apply khi merge",
      description: "Tự động hoá Terraform bằng GitHub Actions với OIDC, lint, scan bảo mật và environment approval.",
      steps: [
        "Tạo 2 IAM role cho GitHub OIDC: `gha-terraform-plan` (chỉ đọc) và `gha-terraform-apply` (trust giới hạn `environment:dev`)",
        "Viết workflow chạy `terraform fmt -check`, `validate`, `tflint`, `checkov -d .` và `terraform plan` khi có `pull_request`",
        "Comment kết quả plan vào PR (`gh pr comment --body-file plan.txt`)",
        "Job apply chạy khi push lên `main`, dùng `environment: dev` có required reviewers",
        "Bật branch protection: bắt buộc CI xanh và 1 approve trước khi merge",
        "Mở một PR thêm security group mở cổng 22 ra `0.0.0.0/0` và xác nhận checkov chặn",
      ],
    },
    {
      id: "terraform-drift-detection",
      title: "Tạo drift và xử lý",
      description: "Cố tình sửa tay trên Console, phát hiện bằng plan và chọn cách xử lý phù hợp.",
      steps: [
        "Trên Console, sửa tag của VPC và thêm một rule vào security group do Terraform quản lý",
        "Chạy `terraform plan -detailed-exitcode` và ghi lại exit code (2) cùng phần `Objects have changed outside of Terraform`",
        "Với tag: `terraform apply` để đưa về như code; với rule SG hợp lý: cập nhật code cho khớp",
        "Tạo tay một S3 bucket rồi đưa vào Terraform bằng block `import` và `terraform plan -generate-config-out=generated.tf`",
        "Thêm workflow `schedule` chạy plan hằng đêm và báo khi exit code bằng 2",
      ],
    },
  ],
  deliverable:
    "Repo `infra/` gồm modules vpc, alb-asg, rds; envs dev và staging với remote state S3 có locking; workflow GitHub Actions plan trên PR và apply khi merge qua OIDC; README mô tả cách xử lý drift.",
  successCriteria:
    "`terraform destroy` rồi `apply` lại → app hoạt động mà không chỉnh tay bước nào; mọi thay đổi hạ tầng đi qua PR có plan được review.",
  resources: [
    { title: "Terraform Tutorials — AWS Get Started", url: "https://developer.hashicorp.com/terraform/tutorials/aws-get-started", kind: "course" },
    { title: "Terraform Language Documentation", url: "https://developer.hashicorp.com/terraform/language", kind: "doc" },
    { title: "Backend Type: s3", url: "https://developer.hashicorp.com/terraform/language/backend/s3", kind: "doc" },
    { title: "AWS Provider trên Terraform Registry", url: "https://registry.terraform.io/providers/hashicorp/aws/latest/docs", kind: "doc" },
    { title: "terraform-aws-modules (module cộng đồng)", url: "https://github.com/terraform-aws-modules", kind: "tool" },
    { title: "Terraform: Up & Running (Yevgeniy Brikman)", url: "https://www.terraformupandrunning.com/", kind: "book" },
    { title: "OpenTofu Documentation", url: "https://opentofu.org/docs/", kind: "doc" },
    { title: "Checkov — quét bảo mật IaC", url: "https://www.checkov.io/", kind: "tool" },
  ],
  quiz: [
    {
      id: "declarative-rerun",
      question: "Script bash gọi `aws ec2 run-instances` 3 lần được chạy lại lần hai. Terraform khai báo `count = 3` cũng được apply lại lần hai. Kết quả khác nhau thế nào?",
      options: [
        "Cả hai đều có 6 instance",
        "Script tạo thêm 3 (thành 6); Terraform báo No changes (vẫn 3)",
        "Script báo lỗi trùng tên; Terraform tạo thêm 3",
        "Cả hai đều giữ nguyên 3 instance",
      ],
      answerIndex: 1,
      explanation: "Script là mệnh lệnh từng bước nên làm lại từ đầu. Terraform là bản vẽ: so với thực tế thấy đã đủ 3 nên không làm gì (idempotent).",
    },
    {
      id: "plan-replacement-symbol",
      question: "Trong plan, ký hiệu nào đòi hỏi bạn dừng lại kiểm tra kỹ nhất với một database đang chứa dữ liệu?",
      options: ["`+`", "`~`", "`<=`", "`-/+`"],
      answerIndex: 3,
      explanation: "`-/+` nghĩa là xoá rồi tạo lại — như báo giá ghi 'đập nhà kho xây lại'. Dữ liệu có thể mất. `~` sửa tại chỗ, `<=` chỉ đọc data source.",
    },
    {
      id: "data-vs-resource",
      question: "Team network đã tạo sẵn VPC dùng chung (không do stack của bạn quản lý). Bạn cần VPC ID để tạo subnet. Nên làm gì?",
      options: [
        "Dùng `data \"aws_vpc\"` lọc theo tag để đọc VPC có sẵn",
        "Khai báo `resource \"aws_vpc\"` với cùng CIDR",
        "Import VPC đó vào state của bạn",
        "Hardcode VPC ID trong mọi resource",
      ],
      answerIndex: 0,
      explanation: "Data source là 'hỏi bếp có sẵn gì' mà không nhận quyền quản lý. Import sẽ khiến hai stack cùng quản lý một VPC — destroy của bạn có thể xoá VPC của team khác.",
    },
    {
      id: "count-index-shift",
      question: "`aws_iam_user.dev` dùng `count = length(var.users)` với danh sách `[\"an\", \"binh\", \"chi\"]`. Bạn xoá \"an\". Plan có khả năng làm gì?",
      options: [
        "Chỉ xoá user an",
        "Không thay đổi gì vì Terraform tự nhận ra",
        "Đổi tên/thay thế user ở index 0 và 1, xoá index 2 — ảnh hưởng cả binh và chi",
        "Báo lỗi vì count không cho phép giảm",
      ],
      answerIndex: 2,
      explanation: "count đánh số ghế theo thứ tự: một người rời đi, mọi người phía sau bị dồn ghế. Dùng `for_each = toset(var.users)` để địa chỉ gắn theo tên.",
    },
    {
      id: "state-in-git",
      question: "Vì sao không nên commit `terraform.tfstate` vào Git?",
      options: [
        "Vì Git không lưu được file JSON",
        "Vì state có thể chứa secret dạng rõ và Git không có cơ chế lock khi nhiều người apply",
        "Vì Terraform sẽ từ chối đọc state trong thư mục Git",
        "Vì state quá nặng, luôn trên 100 MB",
      ],
      answerIndex: 1,
      explanation: "Sổ kiểm kê chứa cả 'mã két' (mật khẩu DB) và cần một chìa khoá duy nhất khi ghi. Remote backend S3 có mã hoá, versioning và locking.",
    },
    {
      id: "s3-native-locking",
      question: "Với các bản Terraform hỗ trợ native S3 locking, cấu hình nào thay thế cho việc tạo bảng DynamoDB làm khoá?",
      options: ["`encrypt = true`", "`use_lockfile = true`", "`versioning = true`", "`lock_table = \"s3\"`"],
      answerIndex: 1,
      explanation: "`use_lockfile = true` tạo file `.tflock` trong chính bucket bằng conditional write. `encrypt` chỉ mã hoá state, versioning cấu hình trên bucket.",
    },
    {
      id: "force-unlock-danger",
      question: "Job CI apply bị huỷ giữa chừng, lần chạy sau báo `Error acquiring the state lock`. Cách xử lý an toàn là gì?",
      options: [
        "Xác nhận không còn tiến trình apply nào chạy, rồi `terraform force-unlock <LOCK_ID>`",
        "Luôn chạy `terraform apply -lock=false` từ nay về sau",
        "Xoá file state trên S3",
        "Tạo bucket state mới",
      ],
      answerIndex: 0,
      explanation: "Khoá kẹt vì người giữ chìa đã 'bỏ về' mà không trả. Chỉ gỡ khi chắc chắn không ai đang ghi — nếu không sẽ gây ghi đè state.",
    },
    {
      id: "environments-isolation",
      question: "Công ty muốn chắc chắn một lỗi khi apply staging không bao giờ đụng tới prod. Thiết kế nào giúp nhất?",
      options: [
        "Một state chung cho cả staging và prod",
        "Dùng count để bật/tắt tài nguyên prod",
        "Copy-paste code staging sang prod",
        "Module dùng chung, mỗi env một thư mục với backend key và IAM role riêng",
      ],
      answerIndex: 3,
      explanation: "Mỗi toà nhà có sổ và chìa khoá riêng: state tách biệt giới hạn 'bán kính nổ', role riêng ngăn credentials staging ghi vào prod.",
    },
    {
      id: "drift-detailed-exitcode",
      question: "Job drift chạy hằng đêm cần biết có khác biệt giữa code và thực tế hay không. Lệnh nào phù hợp?",
      options: [
        "`terraform validate`",
        "`terraform fmt -check`",
        "`terraform plan -detailed-exitcode` và báo động khi exit code là 2",
        "`terraform output`",
      ],
      answerIndex: 2,
      explanation: "Như kiểm két đột xuất: `-detailed-exitcode` trả 0 khi khớp, 2 khi có thay đổi, 1 khi lỗi. validate và fmt không hề hỏi AWS thực tế.",
    },
    {
      id: "moved-block-refactor",
      question: "Bạn đổi tên `resource \"aws_lb\" \"main\"` thành `resource \"aws_lb\" \"public\"`. Làm sao để plan không xoá rồi tạo lại ALB?",
      options: [
        "Không thể, đổi tên luôn tạo lại tài nguyên",
        "Thêm block `moved` với `from = aws_lb.main` và `to = aws_lb.public`",
        "Thêm `prevent_destroy = true`",
        "Chạy `terraform state rm aws_lb.main`",
      ],
      answerIndex: 1,
      explanation: "ALB không đổi, chỉ đổi 'số trang trong sổ'. `moved` ghi chú chuyển mục; `prevent_destroy` chỉ làm plan báo lỗi, còn `state rm` làm Terraform quên ALB và tạo cái mới.",
    },
    {
      id: "oidc-ci-credentials",
      question: "Cách nào an toàn nhất để GitHub Actions chạy `terraform apply` trên AWS?",
      options: [
        "Lưu access key của IAM user admin vào GitHub Secrets",
        "Commit file `~/.aws/credentials` vào repo private",
        "Chạy apply từ laptop của trưởng nhóm rồi push state",
        "OIDC assume role quyền hẹp, trust policy giới hạn theo repo và environment",
      ],
      answerIndex: 3,
      explanation: "OIDC cấp credentials tạm thời mỗi lần chạy, không có key sống lâu để lộ. Giống thủ quỹ chỉ nhận quyền chi sau khi đề nghị đã được ký duyệt.",
    },
  ],
};
