import type { ModuleDefinition } from "@/content/content-types";

export const m12KubernetesCoreModule: ModuleDefinition = {
  id: "m12",
  slug: "m12-kubernetes-core",
  phaseId: "phase-4",
  order: 12,
  weeks: "Tuần 19–20",
  title: "Kubernetes Core",
  emoji: "☸️",
  eli5Summary:
    "Nếu container là những thùng hàng, Kubernetes là ban quản lý cảng: bạn chỉ nói 'tôi muốn luôn có 3 thùng loại A đang hoạt động', ban quản lý tự xếp chỗ, thay thùng hỏng và chỉ đường cho khách. Module này dạy bạn ra lệnh cho ban quản lý đó — và sửa khi có chuyện.",
  objectives: [
    "Giải thích vai trò từng thành phần control plane và node, và điều gì xảy ra khi chạy `kubectl apply`",
    "Deploy app bằng Deployment, rolling update và rollback an toàn",
    "Mở app ra ngoài bằng Service, DNS nội bộ và Gateway API/Ingress",
    "Cấu hình ConfigMap, Secret, probes, requests/limits, HPA và PodDisruptionBudget",
    "Chạy database bằng StatefulSet + PVC, điều khiển scheduling bằng affinity và taints",
    "Khoá quyền bằng RBAC/NetworkPolicy và tự chẩn đoán CrashLoopBackOff, ImagePullBackOff, Pending",
  ],
  lessons: [
    { slug: "kubernetes-architecture", title: "Vì sao cần Kubernetes & kiến trúc cluster", minutes: 45, summary: "Ban quản lý cảng: control plane ra quyết định, node làm việc, etcd giữ sổ cái." },
    { slug: "pods-deployments-workloads", title: "Pod, Deployment & các loại workload", minutes: 50, summary: "Khai báo trạng thái mong muốn, để controller tự sửa và cập nhật cuốn chiếu." },
    { slug: "services-ingress-gateway-api", title: "Service, DNS, Ingress & Gateway API", minutes: 50, summary: "Địa chỉ cố định cho những pod luôn thay đổi, và cổng vào cho người dùng bên ngoài." },
    { slug: "config-probes-resources-autoscaling", title: "Config, probes, resources & HPA", minutes: 55, summary: "Cấu hình tách khỏi image, khám sức khoẻ định kỳ, khẩu phần CPU/RAM và tự co giãn." },
    { slug: "storage-statefulsets-scheduling", title: "Storage, StatefulSet & scheduling", minutes: 50, summary: "Dữ liệu sống sót khi pod chết, và cách chọn node cho pod." },
    { slug: "rbac-networkpolicy-troubleshooting", title: "RBAC, NetworkPolicy & troubleshooting", minutes: 55, summary: "Ai được làm gì, pod nào được gọi pod nào — và quy trình bắt bệnh pod." },
  ],
  labs: [
    {
      id: "kind-cluster-full-app",
      title: "Cluster kind 3 node + app mẫu đầy đủ",
      description: "Dựng cluster local nhiều node và deploy frontend, API, Postgres (StatefulSet + PVC).",
      steps: [
        "Viết `kind-config.yaml` gồm 1 `control-plane` và 2 `worker`, chạy `kind create cluster --name lab --config kind-config.yaml`",
        "Kiểm tra `kubectl get nodes -o wide` thấy 3 node `Ready`; tạo namespace `kubectl create namespace shop` và `kubens shop`",
        "Tạo Secret `postgres-auth` bằng `kubectl create secret generic` (không commit giá trị thật vào Git)",
        "Deploy Postgres bằng StatefulSet có `volumeClaimTemplates` + headless Service; kiểm tra `kubectl get pvc` ở trạng thái `Bound`",
        "Deploy API và frontend bằng Deployment (3 replicas) + Service ClusterIP; đọc cấu hình từ ConfigMap",
        "Xoá pod `postgres-0` và xác nhận dữ liệu vẫn còn sau khi pod được tạo lại",
      ],
    },
    {
      id: "probes-resources-hpa",
      title: "Probes, requests/limits & HPA",
      description: "Làm app 'biết tự khai báo sức khoẻ', có khẩu phần tài nguyên và tự scale khi tải tăng.",
      steps: [
        "Thêm `startupProbe`, `readinessProbe`, `livenessProbe` cho API; cố tình làm readiness fail và xem `kubectl get endpointslices`",
        "Đặt `resources.requests` và `resources.limits`, kiểm tra QoS bằng `kubectl get pod <pod> -o jsonpath='{.status.qosClass}'`",
        "Cài metrics-server (trên kind cần thêm cờ `--kubelet-insecure-tls`), kiểm tra `kubectl top pods`",
        "Tạo HPA `autoscaling/v2` target CPU 60%, min 2 max 10",
        "Load test bằng `kubectl run load --image=busybox -- /bin/sh -c 'while true; do wget -q -O- http://api; done'` và theo dõi `kubectl get hpa -w`",
        "Thêm PodDisruptionBudget `minAvailable: 1` và thử `kubectl drain` một worker node",
      ],
    },
    {
      id: "gateway-api-routing",
      title: "Gateway API: / → frontend, /api → API",
      description: "Đưa traffic từ ngoài vào cluster bằng Gateway + HTTPRoute (có thể so sánh với Ingress).",
      steps: [
        "Cài Gateway API CRDs (standard channel) bằng `kubectl apply --server-side -f` file `standard-install.yaml` từ release chính thức",
        "Cài một implementation (ví dụ Envoy Gateway qua Helm) và dùng `cloud-provider-kind` để Service LoadBalancer có IP trên kind",
        "Tạo `Gateway` listener HTTP cổng 80 và `HTTPRoute` với 2 rule: `PathPrefix /api` → Service `api`, `PathPrefix /` → Service `frontend`",
        "Kiểm tra `kubectl get gateway,httproute` thấy `PROGRAMMED True`, rồi `curl http://<gateway-ip>/api/health`",
        "Bonus: viết Ingress tương đương và ghi lại khác biệt về phân quyền (GatewayClass/Gateway/Route)",
      ],
    },
    {
      id: "rbac-networkpolicy",
      title: "RBAC & NetworkPolicy",
      description: "ServiceAccount chỉ được đọc pod trong 1 namespace; chỉ API được gọi database.",
      steps: [
        "Tạo ServiceAccount `pod-reader`, Role cho verbs `get`,`list` trên `pods` trong namespace `shop`, và RoleBinding",
        "Kiểm chứng: `kubectl auth can-i list pods -n shop --as=system:serviceaccount:shop:pod-reader` → yes; `delete pods` → no",
        "Tạo NetworkPolicy default-deny ingress cho namespace `shop`",
        "Thêm NetworkPolicy cho phép pod có label `app: api` gọi `app: postgres` cổng 5432 (và cho phép frontend → api)",
        "Kiểm chứng bằng `kubectl exec` từ pod frontend: `nc -zv postgres 5432` phải timeout, từ pod api phải thành công",
      ],
    },
    {
      id: "break-and-fix",
      title: "Break & fix: 10 bài tự gây lỗi",
      description: "Tự làm hỏng cluster theo 10 kịch bản rồi chẩn đoán chỉ bằng kubectl — kỹ năng số 1 cho CKA và trực on-call.",
      steps: [
        "Sai tên image (`ImagePullBackOff`), sai command (`CrashLoopBackOff`), thiếu Secret (`CreateContainerConfigError`)",
        "Service selector không khớp label pod (endpoints rỗng), sai `targetPort`",
        "Memory limit quá thấp (`OOMKilled`), request CPU vượt khả năng node (`Pending`)",
        "Taint node mà pod không có toleration, `nodeSelector` sai label, PVC với StorageClass không tồn tại",
        "Mỗi bài: ghi triệu chứng, lệnh chẩn đoán (`kubectl describe`, `kubectl logs --previous`, `kubectl get events --sort-by=.lastTimestamp`) và cách sửa vào `BREAK-FIX.md`",
      ],
    },
  ],
  deliverable:
    "Repo Git chứa manifest app mẫu (frontend, API, Postgres) chạy trên kind 3 node: probes, requests/limits, HPA, PDB, Gateway API route, RBAC, NetworkPolicy, kèm `BREAK-FIX.md` ghi 10 bài chẩn đoán.",
  successCriteria:
    "Xoá pod bất kỳ app vẫn phục vụ; HPA scale khi load test; tự chẩn đoán CrashLoopBackOff, ImagePullBackOff, Pending chỉ bằng kubectl describe/logs/events trong vòng 10 phút.",
  resources: [
    { title: "Kubernetes Docs — Concepts", url: "https://kubernetes.io/docs/concepts/", kind: "doc" },
    { title: "Kubernetes Docs — Tasks", url: "https://kubernetes.io/docs/tasks/", kind: "doc" },
    { title: "kubectl Quick Reference", url: "https://kubernetes.io/docs/reference/kubectl/quick-reference/", kind: "doc" },
    { title: "Gateway API — tài liệu chính thức", url: "https://gateway-api.sigs.k8s.io/", kind: "doc" },
    { title: "kind — Kubernetes in Docker", url: "https://kind.sigs.k8s.io/", kind: "tool" },
    { title: "k9s — terminal UI cho Kubernetes", url: "https://k9scli.io/", kind: "tool" },
    { title: "Kubernetes The Hard Way (Kelsey Hightower)", url: "https://github.com/kelseyhightower/kubernetes-the-hard-way", kind: "practice" },
    { title: "KodeKloud — CKA Certification Course", url: "https://kodekloud.com/courses/cka-certification-course-certified-kubernetes-administrator", kind: "course" },
  ],
  quiz: [
    {
      id: "etcd-only-apiserver",
      question: "Thành phần nào là thành phần DUY NHẤT đọc/ghi trực tiếp vào etcd?",
      options: ["kube-scheduler", "kubelet", "kube-apiserver", "kube-controller-manager"],
      answerIndex: 2,
      explanation: "etcd là sổ cái của cảng, chỉ quầy lễ tân (API server) được mở sổ. Scheduler, controller, kubelet đều đi qua API server.",
    },
    {
      id: "pod-deleted-recreated",
      question: "Bạn `kubectl delete pod web-7d4b9-abcde` của một Deployment 3 replicas. Vài giây sau lại có 3 pod. Vì sao?",
      options: [
        "kubelet tự khởi động lại pod đã xoá",
        "ReplicaSet controller thấy thực tế (2) khác mong muốn (3) nên tạo pod mới",
        "Lệnh delete bị bỏ qua vì pod đang chạy",
        "etcd khôi phục bản sao lưu của pod",
      ],
      answerIndex: 1,
      explanation: "Vòng lặp reconcile: controller liên tục so 'sổ kế hoạch' với thực tế. Muốn giảm số pod thật sự, hãy sửa `replicas` của Deployment.",
    },
    {
      id: "rolling-update-zero-downtime",
      question: "Deployment 4 replicas với `maxSurge: 1`, `maxUnavailable: 0`. Trong rolling update, điều gì đúng?",
      options: [
        "Có lúc chỉ còn 3 pod sẵn sàng phục vụ",
        "Tất cả pod cũ bị xoá trước rồi mới tạo pod mới",
        "Số pod có thể lên tối đa 5, và luôn có ít nhất 4 pod sẵn sàng",
        "Rolling update không dùng ReplicaSet mới",
      ],
      answerIndex: 2,
      explanation: "maxSurge 1 cho phép 'thêm 1 người' trước khi 'cho 1 người nghỉ'; maxUnavailable 0 nghĩa là không bao giờ thiếu người đứng quầy.",
    },
    {
      id: "service-selector-mismatch",
      question: "Service `api` tồn tại, pod đang Running và Ready, nhưng `curl http://api` bị từ chối kết nối. `kubectl get endpointslices -l kubernetes.io/service-name=api` không có địa chỉ nào. Nguyên nhân khả dĩ nhất?",
      options: [
        "selector của Service không khớp label của pod",
        "CoreDNS bị lỗi",
        "Pod thiếu livenessProbe",
        "Namespace chưa có ResourceQuota",
      ],
      answerIndex: 0,
      explanation: "Service như tổng đài tìm nhân viên theo 'bảng tên' (label). Sai bảng tên → danh bạ rỗng, dù nhân viên vẫn đang làm việc.",
    },
    {
      id: "readiness-vs-liveness-db",
      question: "Database dùng chung bị down 2 phút. Bạn muốn pod API tạm ngừng nhận traffic nhưng KHÔNG bị restart. Nên kiểm tra kết nối DB ở probe nào?",
      options: ["livenessProbe", "startupProbe", "Không probe nào, dùng HPA", "readinessProbe"],
      answerIndex: 3,
      explanation: "Readiness = 'đang mở quầy hay tạm đóng'. Liveness fail thì kubelet restart container — nếu check DB ở liveness, mọi pod sẽ restart hàng loạt mà chẳng sửa được DB.",
    },
    {
      id: "oomkilled-exit-137",
      question: "`kubectl describe pod` hiện `Last State: Terminated, Reason: OOMKilled, Exit Code: 137`. Việc nên làm đầu tiên?",
      options: [
        "Tăng CPU limit",
        "Xem mức RAM thực tế (`kubectl top pod`), tăng memory limit hoặc sửa rò rỉ bộ nhớ",
        "Thêm readinessProbe",
        "Đổi imagePullPolicy thành Always",
      ],
      answerIndex: 1,
      explanation: "Vượt khẩu phần RAM thì kernel 'đuổi' container (137 = 128 + SIGKILL 9). CPU vượt limit chỉ bị bóp chậm (throttle), không bị giết.",
    },
    {
      id: "pending-taint",
      question: "Pod ở `Pending`, events: `0/3 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 2 Insufficient memory`. Hướng xử lý hợp lý?",
      options: [
        "Giảm memory request của pod hoặc thêm node/RAM cho worker",
        "Restart kubelet trên control-plane",
        "Xoá taint trên mọi node trong production",
        "Đổi Service sang NodePort",
      ],
      answerIndex: 0,
      explanation: "Scheduler lọc node: control-plane bị 'biển cấm' (taint), 2 worker không đủ chỗ trống theo request. Pod cần chỗ ngồi vừa, không phải gỡ biển cấm bừa bãi.",
    },
    {
      id: "statefulset-pvc-identity",
      question: "Vì sao Postgres nên chạy bằng StatefulSet với `volumeClaimTemplates` thay vì Deployment?",
      options: [
        "StatefulSet chạy nhanh hơn Deployment",
        "Deployment không hỗ trợ container image của Postgres",
        "Mỗi pod có tên cố định (postgres-0) và luôn gắn lại đúng PVC của mình khi được tạo lại",
        "StatefulSet tự động backup dữ liệu",
      ],
      answerIndex: 2,
      explanation: "Như phòng khách sạn có số cố định và tủ đồ riêng: postgres-0 quay lại vẫn mở đúng tủ `data-postgres-0`. StatefulSet không backup hộ bạn.",
    },
    {
      id: "rbac-role-namespace",
      question: "ServiceAccount có RoleBinding tới Role `pod-reader` trong namespace `shop`. Nó chạy `kubectl get pods -n payments`. Kết quả?",
      options: [
        "Thành công vì Role cho phép get pods",
        "Bị từ chối (Forbidden) vì Role và RoleBinding chỉ có hiệu lực trong namespace `shop`",
        "Thành công nhưng danh sách rỗng",
        "Lỗi vì ServiceAccount không dùng được kubectl",
      ],
      answerIndex: 1,
      explanation: "Role là thẻ ra vào của MỘT toà nhà. Muốn quyền trên nhiều namespace thì dùng ClusterRole + RoleBinding ở từng namespace, hoặc ClusterRoleBinding.",
    },
    {
      id: "networkpolicy-default-deny",
      question: "Namespace `shop` có NetworkPolicy chọn mọi pod với `policyTypes: [Ingress]` và không có rule `ingress` nào. Hệ quả?",
      options: [
        "Không có tác dụng vì thiếu rule",
        "Chặn mọi traffic đi ra từ pod",
        "Chặn cả truy cập kubectl vào namespace",
        "Mọi traffic đi vào các pod trong namespace bị chặn, trừ khi policy khác cho phép",
      ],
      answerIndex: 3,
      explanation: "Đây là 'default deny ingress' — khoá hết cửa rồi mở từng cửa bằng policy khác. NetworkPolicy chỉ lo traffic mạng giữa pod, không liên quan RBAC/kubectl.",
    },
    {
      id: "gateway-api-roles",
      question: "So với Ingress, điểm mạnh chính của Gateway API là gì?",
      options: [
        "Tách vai trò: hạ tầng quản lý GatewayClass/Gateway, team app tự viết HTTPRoute; hỗ trợ header matching, traffic splitting chuẩn hoá",
        "Gateway API không cần controller nào",
        "Gateway API chỉ dùng được trên AWS",
        "Gateway API thay thế Service ClusterIP",
      ],
      answerIndex: 0,
      explanation: "Như toà nhà: ban quản lý lắp cổng (Gateway), mỗi công ty thuê tự treo biển chỉ đường (Route). Vẫn cần một implementation (controller) và vẫn trỏ về Service.",
    },
    {
      id: "crashloop-previous-logs",
      question: "Pod ở `CrashLoopBackOff`, `kubectl logs web-abc` trống vì container vừa khởi động lại. Lệnh nào xem log của lần chạy bị crash?",
      options: ["kubectl describe node", "kubectl logs web-abc --previous", "kubectl get events -A --watch-only", "kubectl top pod web-abc"],
      answerIndex: 1,
      explanation: "`--previous` đọc 'biên bản' của container trước khi bị restart — nơi thường có stack trace hoặc lỗi thiếu biến môi trường.",
    },
  ],
};
