import type { ModuleDefinition } from "@/content/content-types";

export const m04DockerContainersModule: ModuleDefinition = {
  id: "m04",
  slug: "m04-docker-containers",
  phaseId: "phase-1",
  order: 4,
  weeks: "Tuần 5–6",
  title: "Docker & Containers",
  emoji: "🐳",
  eli5Summary:
    "Container giống thùng hàng tiêu chuẩn trên tàu biển: bạn đóng gói app cùng mọi thứ nó cần vào một thùng, và thùng đó chạy giống hệt nhau trên laptop, server hay cloud. Module này dạy bạn đóng thùng gọn nhẹ, an toàn và cho nhiều thùng làm việc cùng nhau.",
  objectives: [
    "Giải thích khác biệt giữa container và VM, vai trò của namespaces và cgroups",
    "Viết Dockerfile tận dụng build cache, multi-stage build, chạy non-root",
    "Chọn đúng network, volume hay bind mount cho từng tình huống",
    "Chạy app nhiều service bằng Docker Compose với healthcheck và thứ tự khởi động đúng",
    "Tag image theo git SHA/semver, push lên GHCR/ECR và quét lỗ hổng bằng Trivy",
  ],
  lessons: [
    { slug: "container-vs-vm", title: "Container vs VM", minutes: 35, summary: "Căn hộ chung cư và nhà phố riêng: chung móng (kernel) hay mỗi nhà một móng." },
    { slug: "images-layers-build-cache", title: "Image, layer & build cache", minutes: 40, summary: "Image là chồng lớp chỉ-đọc; sắp xếp Dockerfile đúng để build lại trong vài giây." },
    { slug: "dockerfile-best-practices", title: "Viết Dockerfile chuẩn production", minutes: 45, summary: "Multi-stage build, pin version, non-root user, HEALTHCHECK — image nhỏ và an toàn." },
    { slug: "networking-volumes", title: "Networking & lưu trữ dữ liệu", minutes: 40, summary: "Container gọi nhau bằng tên, mở port ra ngoài, và giữ dữ liệu sống sót khi container bị xoá." },
    { slug: "docker-compose-multi-service", title: "Docker Compose cho app nhiều service", minutes: 45, summary: "Một file compose.yaml khởi động cả frontend, API, Postgres, Redis đúng thứ tự." },
    { slug: "registry-tagging-security", title: "Registry, tagging & quét bảo mật", minutes: 40, summary: "Dán nhãn image bằng git SHA, đẩy lên GHCR/ECR và soi lỗ hổng bằng Trivy." },
  ],
  labs: [
    {
      id: "multi-stage-api-image",
      title: "Dockerfile multi-stage cho API",
      description: "Viết Dockerfile cho API mẫu, so sánh kích thước image trước và sau multi-stage (mục tiêu giảm ≥ 50%).",
      steps: [
        "Viết Dockerfile một stage đơn giản (`FROM node:22`), build với tag `api:single` và ghi lại kích thước bằng `docker images api`",
        "Thêm `.dockerignore` loại `node_modules`, `.git`, `.env`, `dist`",
        "Chuyển sang multi-stage: stage `build` chạy `npm ci && npm run build`, stage runtime `FROM node:22-alpine` chỉ `COPY --from=build` phần cần chạy",
        "Cài chỉ production dependency (`npm ci --omit=dev`), thêm `USER node` và `HEALTHCHECK`",
        "Build tag `api:multi`, so sánh bằng `docker images api` — kích thước phải giảm ≥ 50%",
        "Kiểm tra non-root: `docker run --rm api:multi id` phải không trả về `uid=0(root)`",
        "Chạy `hadolint Dockerfile` và sửa các cảnh báo",
      ],
    },
    {
      id: "compose-full-stack",
      title: "Full stack bằng Docker Compose",
      description: "Viết compose.yaml chạy frontend, API, Postgres, Redis với healthcheck, volume và env file.",
      steps: [
        "Tạo `compose.yaml` với 4 service: `frontend`, `api`, `db` (postgres:17-alpine), `redis` (redis:7-alpine)",
        "Thêm `healthcheck` cho `db` (`pg_isready`) và `redis` (`redis-cli ping`); `api` dùng `depends_on` với `condition: service_healthy`",
        "Khai báo named volume `pgdata` gắn vào `/var/lib/postgresql/data`; đưa mật khẩu vào file `.env` (có trong `.gitignore`)",
        "Chạy `docker compose up -d --wait` và xác nhận mọi service `healthy` bằng `docker compose ps`",
        "Thử `docker compose down` rồi `up` lại: dữ liệu Postgres vẫn còn; `docker compose down -v` thì mất — ghi lại vì sao",
        "Clone repo sang thư mục khác (hoặc máy khác), chạy `docker compose up` và app hoạt động không cần cài gì thêm ngoài Docker",
      ],
    },
    {
      id: "trivy-scan-fix",
      title: "Quét image bằng Trivy và sửa lỗi CRITICAL",
      description: "Tìm và xử lý lỗ hổng trong image trước khi đưa lên registry.",
      steps: [
        "Cài Trivy và chạy `trivy image --severity HIGH,CRITICAL api:multi`",
        "So sánh với image một stage: `trivy image --severity CRITICAL api:single` — đếm số lỗ hổng chênh lệch",
        "Sửa lỗi CRITICAL: nâng base image lên bản vá mới nhất, cập nhật package có `Fixed Version`",
        "Chạy lại với `--exit-code 1 --ignore-unfixed --severity CRITICAL` cho tới khi lệnh trả về exit code 0",
        "Kiểm tra secret lọt vào image: `trivy image --scanners secret api:multi`",
      ],
    },
    {
      id: "push-ghcr-git-sha",
      title: "Push image lên GHCR với tag = git SHA",
      description: "Đặt tên image đúng chuẩn registry và đẩy lên GitHub Container Registry.",
      steps: [
        "Tạo Personal Access Token (classic) có scope `write:packages`, đăng nhập: `echo $CR_PAT | docker login ghcr.io -u <user> --password-stdin`",
        "Lấy SHA ngắn: `GIT_SHA=$(git rev-parse --short HEAD)`",
        "Tag image: `docker tag api:multi ghcr.io/<user>/api:sha-$GIT_SHA`",
        "Push: `docker push ghcr.io/<user>/api:sha-$GIT_SHA` và ghi lại digest `sha256:...` được in ra",
        "Xoá image local, pull lại bằng digest `docker pull ghcr.io/<user>/api@sha256:...` để chắc chắn đúng bản đã push",
      ],
    },
  ],
  deliverable: "Repo app mẫu có Dockerfile multi-stage cho từng service, `.dockerignore`, `compose.yaml` chạy app 3-tier (frontend, API, Postgres + Redis) và README hướng dẫn chạy.",
  successCriteria: "`docker compose up` là chạy toàn bộ app trên máy mới; mọi image của bạn chạy non-root; Trivy không còn lỗi CRITICAL có bản vá.",
  resources: [
    { title: "Docker Docs — Get started", url: "https://docs.docker.com/get-started/", kind: "doc" },
    { title: "Docker Docs — Building best practices", url: "https://docs.docker.com/build/building/best-practices/", kind: "doc" },
    { title: "Docker Compose documentation", url: "https://docs.docker.com/compose/", kind: "doc" },
    { title: "Trivy documentation", url: "https://trivy.dev/", kind: "tool" },
    { title: "GitHub Container Registry (GHCR)", url: "https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry", kind: "doc" },
    { title: "Docker Deep Dive (Nigel Poulton)", url: "https://nigelpoulton.com/books/", kind: "book" },
    { title: "Hadolint — lint Dockerfile", url: "https://github.com/hadolint/hadolint", kind: "tool" },
    { title: "dive — soi từng layer của image", url: "https://github.com/wagoodman/dive", kind: "tool" },
  ],
  quiz: [
    {
      id: "container-shares-kernel",
      question: "Vì sao một container khởi động nhanh hơn nhiều so với một VM?",
      options: [
        "Vì container dùng ổ SSD còn VM dùng HDD",
        "Vì container dùng chung kernel của máy host, không phải boot cả một hệ điều hành riêng",
        "Vì container không có tiến trình nào chạy bên trong",
        "Vì container luôn được viết bằng Go",
      ],
      answerIndex: 1,
      explanation: "Căn hộ chung cư dùng chung móng nhà (kernel); dọn vào là ở ngay. VM là nhà phố riêng, phải xây móng (boot guest OS) trước.",
    },
    {
      id: "cgroups-memory-limit",
      question: "Một container ăn hết RAM làm cả server chậm. Cơ chế Linux nào giúp giới hạn RAM cho container?",
      options: ["namespaces", "cgroups", "overlayfs", "iptables"],
      answerIndex: 1,
      explanation: "namespaces là 'bức tường' che tầm nhìn; cgroups là 'đồng hồ điện nước' giới hạn tài nguyên. `docker run --memory 256m` dùng cgroups.",
    },
    {
      id: "cache-order-package-json",
      question: "Dockerfile có `COPY . .` rồi mới `RUN npm ci`. Mỗi lần sửa 1 dòng code, build lại mất 2 phút. Cách sửa tốt nhất?",
      options: [
        "Thêm `--no-cache` vào lệnh build",
        "Đổi base image sang ubuntu",
        "`COPY package*.json ./` và `RUN npm ci` trước, rồi mới `COPY . .`",
        "Gộp mọi lệnh vào một dòng RUN duy nhất",
      ],
      answerIndex: 2,
      explanation: "Layer nào thay đổi thì mọi layer phía trên phải làm lại. Đặt thứ ít đổi (dependency) ở dưới, code hay đổi ở trên — như ninh nước dùng phở trước, rau thơm cho sau cùng.",
    },
    {
      id: "multi-stage-purpose",
      question: "Lợi ích chính của multi-stage build là gì?",
      options: [
        "Image cuối chỉ chứa thứ cần để chạy, không kèm compiler, dev dependency, source",
        "Build chạy song song trên nhiều máy",
        "Tự động quét lỗ hổng bảo mật",
        "Cho phép container chạy không cần kernel",
      ],
      answerIndex: 0,
      explanation: "Nấu trong bếp lớn đầy dụng cụ (stage build) rồi chỉ mang hộp cơm (artifact) đi giao. Image nhỏ hơn cũng có ít lỗ hổng hơn.",
    },
    {
      id: "named-volume-survives",
      question: "Bạn chạy Postgres trong container không gắn volume, rồi `docker rm -f db` và chạy lại. Dữ liệu thế nào?",
      options: [
        "Vẫn còn, Docker tự backup",
        "Còn nếu dùng tag latest",
        "Mất, vì dữ liệu nằm trong writable layer của container đã bị xoá",
        "Chuyển sang thư mục /tmp của host",
      ],
      answerIndex: 2,
      explanation: "Đồ để trong căn hộ thuê sẽ mất khi trả phòng. Muốn giữ phải gửi vào kho của ban quản lý — named volume.",
    },
    {
      id: "container-dns-by-name",
      question: "Trong Compose, service `api` nên kết nối Postgres bằng địa chỉ nào?",
      options: ["localhost:5432", "db:5432 (tên service)", "IP của container db xem bằng docker inspect", "host.docker.internal:5432"],
      answerIndex: 1,
      explanation: "Trong mạng do Compose tạo, Docker có DNS nội bộ: gọi theo tên service như gọi theo số căn hộ. `localhost` bên trong container là chính container đó. IP container thay đổi mỗi lần tạo lại.",
    },
    {
      id: "depends-on-healthy",
      question: "API crash lúc `docker compose up` vì Postgres chưa sẵn sàng dù đã có `depends_on: [db]`. Sửa thế nào?",
      options: [
        "Thêm healthcheck cho db và dùng `depends_on` với `condition: service_healthy`",
        "Đổi thứ tự service trong file compose.yaml",
        "Thêm `sleep 60` vào Dockerfile của Postgres",
        "Xoá depends_on đi",
      ],
      answerIndex: 0,
      explanation: "depends_on dạng ngắn chỉ đợi container db 'đã tới cửa' (started), không đợi 'đầu bếp nói sẵn sàng'. Healthcheck + service_healthy mới đợi đúng. App vẫn nên có retry.",
    },
    {
      id: "tag-latest-production",
      question: "Vì sao không nên deploy production bằng tag `latest`?",
      options: [
        "Registry không cho pull tag latest",
        "latest luôn là bản cũ nhất",
        "latest chạy chậm hơn",
        "latest là nhãn có thể bị gán lại, không biết chính xác bản nào đang chạy và khó rollback",
      ],
      answerIndex: 3,
      explanation: "Tag là nhãn dán có thể bóc ra dán lại. Git SHA (hoặc digest) như mã vạch cố định: biết chính xác code nào đang chạy và quay về bản trước dễ dàng.",
    },
    {
      id: "secret-in-image-layer",
      question: "Dockerfile có `COPY .env .` rồi dòng sau `RUN rm .env`. Secret đã an toàn chưa?",
      options: [
        "An toàn, vì file đã bị xoá",
        "Chưa: file vẫn nằm trong layer tạo bởi COPY, ai pull image cũng lấy ra được",
        "An toàn nếu image là private",
        "An toàn nếu dùng alpine",
      ],
      answerIndex: 1,
      explanation: "Layer là chồng lớp chỉ-đọc: lớp trên 'che' file chứ không xoá khỏi lớp dưới. Truyền secret lúc chạy (env, secret manager) hoặc dùng `RUN --mount=type=secret` khi build.",
    },
    {
      id: "trivy-exit-code-pipeline",
      question: "Muốn pipeline dừng lại khi image có lỗ hổng CRITICAL, dùng lệnh Trivy nào?",
      options: [
        "`trivy image myapp:sha`",
        "`trivy image --format json myapp:sha`",
        "`trivy image --severity CRITICAL --exit-code 1 myapp:sha`",
        "`trivy fs --list-all-pkgs .`",
      ],
      answerIndex: 2,
      explanation: "Máy soi hành lý phải 'hú còi' thì mới chặn được: `--exit-code 1` làm lệnh thất bại khi tìm thấy lỗi mức đã chọn, CI thấy exit code khác 0 là dừng.",
    },
  ],
};
