import type { ModuleDefinition } from "@/content/content-types";

export const sd15CaseNewsFeedNotificationModule: ModuleDefinition = {
  id: "sd15",
  slug: "sd15-case-news-feed-notification",
  phaseId: "sd-phase-4",
  order: 15,
  weeks: "Tuần 19",
  title: "Case: News feed & notification system",
  emoji: "📰",
  eli5Summary:
    "Một tài khoản 200 người theo dõi thì người đưa thư (hệ thống) rảnh rỗi bỏ thư vào từng hộp khi có tin mới. Một celebrity 50 triệu người theo dõi thì người đưa thư đó phải photocopy 50 triệu bản trong vài giây — không ai làm nổi. Module này dạy bạn khi nào bỏ thư tận nhà (push), khi nào để người đọc tự ra bảng tin lấy (pull), và cách gửi thông báo đa kênh mà không gửi trùng.",
  objectives: [
    "Ước lượng quy mô news feed (DAU, QPS đọc/ghi, storage) và bảo vệ được các con số đó bằng giả định rõ ràng",
    "So sánh fan-out-on-write (push), fan-out-on-read (pull) và hybrid; tính được chi phí ghi bùng nổ khi follower tăng và giải thích vì sao celebrity phải dùng pull",
    "Thiết kế data model timeline (ID + hydrate, không lưu trùng nội dung) và luồng đọc feed merge giữa push và pull",
    "Thiết kế notification system đa kênh (push/email/SMS) với preference filtering, idempotency và retry + DLQ, nối lại pattern outbox/idempotent consumer ở SD07",
    "Viết design doc theo template chuẩn (Phụ lục A) cho cả hai hệ thống, nêu rõ bottleneck và trade-off",
  ],
  lessons: [
    {
      slug: "yeu-cau-uoc-luong-fan-out",
      title: "Yêu cầu, ước lượng & fan-out push/pull/hybrid",
      minutes: 50,
      summary: "Người đưa thư vs bảng tin chung cư: định nghĩa bài toán, ước lượng quy mô, và vì sao celebrity làm push sụp đổ.",
    },
    {
      slug: "luu-doc-timeline",
      title: "Lưu & đọc timeline",
      minutes: 45,
      summary: "Tủ đồ cá nhân ở trường học: lưu ID thay vì nội dung, hydrate khi đọc, và trộn thêm bài của celebrity lúc đọc.",
    },
    {
      slug: "notification-da-kenh-idempotency",
      title: "Notification system: đa kênh, idempotency & retry",
      minutes: 50,
      summary: "Trực tổng đài đa kênh: lọc theo preference, không gửi trùng, retry có giới hạn và DLQ khi provider lỗi.",
    },
  ],
  labs: [
    {
      id: "redis-sorted-set-fanout-celebrity-cliff",
      title: "Prototype fan-out-on-write bằng Redis sorted set & celebrity cliff",
      description: "Dựng fan-out-on-write trên Redis trong sd-playground, tạo một tài khoản follower giả lập quy mô lớn để đo chi phí ghi, rồi chuyển sang hybrid.",
      steps: [
        "Trong `sd-playground`, chạy `docker compose up -d redis` rồi seed follower giả lập: `redis-cli SADD followers:normal-user user:1 user:2 ... user:200` (200 phần tử) và `redis-cli SADD followers:celebrity` với một vòng lặp script sinh 50.000 id (`for i in $(seq 1 50000); do redis-cli SADD followers:celebrity user:$i >/dev/null; done` hoặc dùng pipeline cho nhanh)",
        "Viết `src/scripts/fanout-on-write.ts`: khi có `postId` mới, đọc `SMEMBERS followers:<author>` rồi `ZADD timeline:<followerId> <postId> <timestampScore>` cho từng follower, đo `Date.now()` trước/sau vòng lặp",
        "Chạy script cho `normal-user` (200 follower) và ghi lại thời gian; chạy lại cho `celebrity` (50.000 follower) và so sánh — quan sát chi phí tăng gần tuyến tính theo số follower, đây chính là fan-out cost cliff",
        "Thử fan-out-on-read cho celebrity: bỏ qua vòng lặp ZADD, thay vào đó khi một follower gọi `GET /feed`, script đọc trực tiếp `ZREVRANGE posts:celebrity 0 4` (K bài mới nhất) và merge vào kết quả — đo độ trễ thêm cho một lần đọc, so với việc phải chờ fan-out ghi xong",
        "Đặt ngưỡng celebrity (vd `FOLLOWER_THRESHOLD=10000`): nếu `SCARD followers:<author> >= FOLLOWER_THRESHOLD` thì bỏ qua fan-out-on-write và đánh dấu tài khoản là `celebrity` trong Postgres/Redis (`SET account:<id>:celebrity 1`)",
        "Ghi lại bảng so sánh thời gian fan-out ở 200 / 5.000 / 50.000 follower và giải thích bằng số liệu vì sao ngưỡng hybrid là cần thiết",
      ],
    },
    {
      id: "design-doc-news-feed-500m-dau",
      title: "Design doc: News feed cho 500 triệu DAU",
      description: "Điền đầy đủ template Phụ lục A cho hệ thống news feed, dùng lại số liệu ước lượng đã tính ở Lesson 1.",
      steps: [
        "Mục 1 Requirements: liệt kê functional (đăng bài, follow/unfollow, xem feed theo thời gian gần nhất, phân trang) và non-functional có số (latency p99 đọc feed, availability, độ tươi tối đa của bài mới); ghi rõ out of scope (ranking bằng ML, ads)",
        "Mục 2 Ước lượng: điền bảng DAU / QPS đọc-ghi trung bình & đỉnh / storage 5 năm, dùng cách làm tròn ở Phụ lục B và nêu rõ giả định (số bài trung bình/ngày, follower trung bình, tỉ lệ đọc/ghi)",
        "Mục 3 API: liệt kê `POST /posts`, `GET /feed?cursor=&limit=`, `POST /follow`, `DELETE /follow/{id}` kèm request/response tối thiểu",
        "Mục 4 Data model: bảng `posts` (Postgres, nguồn sự thật), `follows` (đồ thị follow), `timeline:{userId}` (Redis ZSET), và giải thích vì sao chọn Postgres cho post gốc, Redis cho timeline",
        "Mục 5 High-level design: vẽ sơ đồ Post Service → Fanout Worker → Redis timeline ⟷ Feed Service ⟷ Redis post cache, kèm Follow Graph Service",
        "Mục 6 Deep dive: chọn 2–3 điểm khó nhất (ngưỡng celebrity, merge pull lúc đọc, hydrate + cache miss) và trình bày cách giải quyết",
        "Mục 7 Trade-off & alternatives: bảng push vs pull vs hybrid, và chronological vs ranking (khái niệm) — nêu khi nào đổi ý",
        "Mục 8 Bottleneck, failure modes & mở rộng: hot key khi celebrity được pull nhiều, timeline phình to (cần trim), multi-region replicate Redis timeline",
      ],
    },
    {
      id: "design-doc-notification-system-retry-dlq",
      title: "Design doc: Notification system có retry, DLQ, preference & idempotency",
      description: "Điền template Phụ lục A cho hệ thống notification đa kênh, nối lại outbox/idempotent consumer đã làm ở SD07.",
      steps: [
        "Mục 1 Requirements: functional (thông báo like/comment/follow qua push/email/SMS, user bật/tắt từng kênh, đánh dấu đã đọc) và non-functional (không gửi trùng, độ trễ chấp nhận được, không bắt buộc thứ tự nghiêm ngặt)",
        "Mục 2 Ước lượng: số sự kiện cần thông báo/ngày, hệ số fan-out theo loại sự kiện (1 like = 1 người nhận, 1 bài viral = hàng triệu người xem nhưng không phải ai cũng được thông báo), QPS dispatch theo kênh",
        "Mục 3 API: `GET/PUT /users/{id}/notification-preferences`, `GET /notifications?cursor=`, `POST /notifications/{id}/read`",
        "Mục 4 Data model: bảng `notifications`, `user_preferences` (bật/tắt theo kênh × loại sự kiện), `dispatch_dedup(consumer, message_id)` — giải thích lại vì sao cần unique constraint như ở SD07",
        "Mục 5 High-level design: vẽ Event source (outbox) → topic `notifications` → Notification Worker → filter preference → 3 adapter (push/email/SMS) → provider ngoài",
        "Mục 6 Deep dive: thiết kế idempotency key (`hash(event_id, user_id, channel)`), retry có backoff + jitter tối đa N lần rồi DLQ, và cơ chế gộp thông báo (batching) khi một bài viral tạo hàng triệu sự kiện cùng lúc",
        "Mục 7 Trade-off & alternatives: một topic chung cho 3 kênh vs topic riêng từng kênh; gọi provider đồng bộ trong consumer vs thêm một lớp queue nữa",
        "Mục 8 Bottleneck, failure modes & mở rộng: provider 1 kênh outage (DLQ đầy), notification storm từ bài viral, kế hoạch replay DLQ sau khi sửa lỗi",
      ],
    },
  ],
  deliverable:
    "Prototype fan-out-on-write/on-read trên Redis (sd-playground) đo được chi phí theo follower count, kèm 2 design doc (Phụ lục A): news feed 500M DAU và notification system có retry/DLQ/preference/idempotency.",
  successCriteria:
    "Giải thích được bằng số liệu vì sao một tài khoản nhiều follower (celebrity) cần chuyển từ push sang pull, thiết kế được luồng notification không gửi trùng khi mọi thành phần có thể crash hoặc retry, và bảo vệ được các lựa chọn trong design doc trước câu hỏi 'khi nào bạn đổi ý'.",
  resources: [
    { title: "ByteByteGo (Alex Xu) — Design a News Feed System", url: "https://bytebytego.com/courses/system-design-interview/design-a-news-feed-system", kind: "course" },
    { title: "Hello Interview — Design Facebook's News Feed (problem breakdown)", url: "https://www.hellointerview.com/learn/system-design/problem-breakdowns/fb-news-feed", kind: "doc" },
    { title: "X (Twitter) Engineering blog — kiến trúc timeline, khái niệm fan-out", url: "https://blog.x.com/engineering/en_us", kind: "doc" },
    { title: "system-design-primer (GitHub) — case study & pattern tham khảo", url: "https://github.com/donnemartin/system-design-primer", kind: "doc" },
    { title: "microservices.io — Pattern: Idempotent consumer (nối lại SD07)", url: "https://microservices.io/patterns/communication-style/idempotent-consumer.html", kind: "doc" },
    { title: "Redpanda documentation (rpk, topic, consumer group) — dùng lại cho hàng đợi notification", url: "https://docs.redpanda.com/", kind: "tool" },
  ],
  quiz: [
    {
      id: "push-write-amplification",
      question:
        "Một celebrity có 50 triệu follower đăng 1 bài. Hệ thống dùng fan-out-on-write và cụm ghi được cỡ 100.000 lần ghi/giây. Fan-out bài này mất khoảng bao lâu, và điều đó có chấp nhận được không?",
      options: [
        "Cỡ 500 giây (~8 phút) — quá lâu để chờ mọi follower thấy bài, đây là dấu hiệu cần chuyển sang pull cho tài khoản này",
        "Cỡ 0,5 giây — hoàn toàn chấp nhận được cho mọi quy mô",
        "Không tính được vì Redis luôn ghi tức thời",
        "Cỡ 50 giây và luôn ổn vì fan-out chạy nền, không ảnh hưởng gì",
      ],
      answerIndex: 0,
      explanation: "50.000.000 / 100.000 = 500 giây. Đây là ví dụ về write amplification: chi phí ghi tăng tuyến tính theo follower, và ở quy mô celebrity nó vượt ngưỡng chấp nhận được — lý do hybrid tồn tại.",
    },
    {
      id: "pull-cost-independent-of-followers",
      question: "Vì sao pull (fan-out-on-read) lại phù hợp cho celebrity dù họ có 50 triệu follower?",
      options: [
        "Vì pull miễn phí hoàn toàn, không tốn tài nguyên gì",
        "Vì Redis không hỗ trợ ghi nhiều key cùng lúc",
        "Vì follower của celebrity thường không online",
        "Vì chi phí đọc bài mới nhất của MỘT tài khoản (celebrity) khi cần là O(1), không phụ thuộc vào tài khoản đó có bao nhiêu follower",
      ],
      answerIndex: 3,
      explanation: "Push tốn theo số follower của người ĐĂNG bài. Pull cho một tài khoản chỉ là một lần lấy bài mới nhất của chính tài khoản đó — không nhân với số follower. Đó là lý do celebrity nên dùng pull thay vì push.",
    },
    {
      id: "pull-cost-for-reader-following-many",
      question: "Một user bình thường (không phải celebrity) follow 2.000 người. Nếu toàn bộ hệ thống dùng thuần pull, chi phí đọc feed của user này thay đổi thế nào so với push?",
      options: [
        "Không đổi gì vì pull luôn nhanh hơn push",
        "Đắt hơn ở lúc đọc: mỗi lần mở feed phải merge dữ liệu từ 2.000 nguồn (followee), càng follow nhiều càng chậm",
        "Rẻ hơn vì không cần ghi timeline khi có bài mới",
        "Đắt hơn ở lúc ghi vì Redis phải ZADD 2.000 lần",
      ],
      answerIndex: 1,
      explanation: "Pull thuần chuyển chi phí từ ghi sang đọc: người đọc phải merge bài từ tất cả người họ follow. Follow càng nhiều thì đọc càng chậm — đây là lý do pull không phù hợp làm mặc định cho MỌI user, chỉ hợp cho account có follower cực lớn.",
    },
    {
      id: "why-hybrid-is-standard-answer",
      question: "Trong phỏng vấn, vì sao 'hybrid: push cho user thường, pull cho celebrity' được coi là câu trả lời chuẩn hơn là chọn thuần push hoặc thuần pull?",
      options: [
        "Vì nó cân bằng đúng bài toán: đa số tài khoản follower ít nên push giữ đọc rẻ, còn thiểu số celebrity dùng pull để tránh cliff ghi — mỗi nhóm dùng chiến lược khớp với đặc điểm của nó",
        "Vì hybrid dùng ít Redis hơn nên rẻ hơn về hạ tầng",
        "Vì thuần push hay thuần pull đều không thể cài đặt được trên Redis",
        "Vì hybrid không cần ngưỡng follower, hệ thống tự động chọn",
      ],
      answerIndex: 0,
      explanation: "Hybrid không phải 'an toàn cho chắc' — nó khớp chiến lược với phân bố thực tế: phần lớn tài khoản follower nhỏ (push rẻ, đọc nhanh), số ít celebrity follower khổng lồ (push sẽ vỡ, nên pull). Vẫn cần một ngưỡng rõ ràng để phân loại.",
    },
    {
      id: "timeline-store-id-not-full-copy",
      question: "Vì sao timeline (`timeline:{userId}`) nên lưu `postId` thay vì lưu toàn bộ nội dung bài viết cho từng follower?",
      options: [
        "Vì Redis ZSET không cho phép lưu chuỗi dài",
        "Vì hydrate luôn nhanh hơn đọc trực tiếp nội dung",
        "Vì ID giúp ranking chính xác hơn nội dung",
        "Vì lưu ID rẻ hơn nhiều lần (50 triệu follower × nội dung đầy đủ tốn storage khổng lồ) và khi tác giả sửa/xoá bài chỉ cần cập nhật một nơi (post store), không phải phát lại cho từng follower",
      ],
      answerIndex: 3,
      explanation: "Lưu full content nhân theo follower là lãng phí storage khủng khiếp và làm sửa/xoá bài trở thành bài toán fan-out lần hai. Lưu ID rồi hydrate (batch lookup) tách rời 'thứ tự đọc' khỏi 'nội dung', giữ post store là nguồn sự thật duy nhất.",
    },
    {
      id: "hydrate-batch-cost",
      question: "Feed Service lấy được 20 postId từ `ZREVRANGE` rồi phải lấy nội dung để trả về client. Cách nào hợp lý nhất?",
      options: [
        "Gọi tuần tự 20 lần `GET post:{id}` tới Redis, mỗi lần một round trip riêng",
        "Batch một lần bằng `MGET`/pipeline cho cả 20 key, cache miss thì query Postgres theo `WHERE id IN (...)` rồi nạp lại cache",
        "Bỏ qua hydrate, trả thẳng 20 postId cho client tự gọi API lấy từng bài",
        "Luôn đọc thẳng Postgres, không cần cache vì chỉ có 20 bài",
      ],
      answerIndex: 1,
      explanation: "Round-trip tuần tự nhân độ trễ mạng lên 20 lần. Batch (pipeline/MGET, hoặc IN-query khi cache miss) là cách chuẩn để hydrate — vẫn giữ Redis làm lớp cache nhanh và Postgres làm nguồn sự thật khi miss.",
    },
    {
      id: "notification-idempotency-key-design",
      question: "Notification Worker cần đảm bảo không gửi trùng thông báo khi event bị đọc lại (rebalance, retry). Idempotency key nên được tính từ gì?",
      options: [
        "Offset của message trong Redpanda",
        "Timestamp hiện tại lúc gửi",
        "`hash(event_id, user_id, channel)` — ổn định với cùng một sự kiện, cùng người nhận, cùng kênh, bất kể đọc lại bao nhiêu lần",
        "Nội dung văn bản của thông báo",
      ],
      answerIndex: 2,
      explanation: "Giống bài học idempotent consumer ở SD07: offset đổi khi message được produce lại, hash nội dung thì hai thông báo hợp lệ giống nhau bị coi là trùng. `event_id` (từ outbox) ổn định tại nguồn — kết hợp `user_id` và `channel` vì một event có thể gửi tới nhiều người qua nhiều kênh.",
    },
    {
      id: "preference-filter-before-dispatch",
      question: "User đã tắt kênh SMS trong preference nhưng vẫn nhận được SMS thông báo. Lỗi nhiều khả năng nằm ở đâu?",
      options: [
        "Notification Worker không tra `user_preferences` trước khi dispatch, hoặc tra sai thời điểm (dispatch trước, lọc sau)",
        "SMS provider tự động gửi bất chấp preference",
        "Redpanda gửi trùng message tới cả 3 kênh",
        "Đây là hành vi đúng, preference chỉ áp dụng cho push/email",
      ],
      answerIndex: 0,
      explanation: "Lọc theo preference phải xảy ra TRƯỚC khi dispatch tới adapter, không phải sau. Nếu Worker gửi trước rồi mới kiểm tra, hoặc cache preference cũ, user tắt kênh vẫn bị gửi.",
    },
    {
      id: "retry-backoff-then-dlq",
      question: "Email adapter gọi provider bị timeout liên tục do provider đang bảo trì. Cách xử lý đúng nhất trong Notification Worker?",
      options: [
        "Retry vô hạn lần cho tới khi provider hoạt động lại",
        "Bỏ qua thông báo đó vĩnh viễn, không log gì",
        "Retry có giới hạn (vd 3 lần) với backoff tăng dần + jitter; hết retry thì đẩy sang DLQ kèm metadata lỗi, alert on-call, các kênh/user khác không bị ảnh hưởng",
        "Dừng toàn bộ Notification Worker (cả push và SMS) cho tới khi email provider hồi phục",
      ],
      answerIndex: 2,
      explanation: "Giống DLQ ở SD07: retry vô hạn làm nghẽn cả pipeline giống poison message, còn dừng toàn bộ worker vì lỗi của một kênh là quá mức cần thiết. Retry có giới hạn + DLQ cô lập đúng phần hỏng, các kênh khác vẫn chạy.",
    },
    {
      id: "notification-storm-batching",
      question: "Một bài viral nhận 2 triệu lượt like trong 10 phút, mỗi like tạo một event 'X đã thích bài viết của bạn' gửi cho cùng một tác giả. Vấn đề chính và hướng xử lý?",
      options: [
        "Không có vấn đề gì, cứ gửi tuần tự 2 triệu thông báo cho tác giả là được",
        "Chuyển toàn bộ event này sang gửi SMS để đảm bảo không mất",
        "Tăng gấp đôi số lần retry để đảm bảo không có like nào bị bỏ sót",
        "Notification storm cho một user — nên gộp (batch) thành một thông báo dạng '2.000 người vừa thích bài viết của bạn' trong một khoảng thời gian, thay vì gửi từng cái riêng",
      ],
      answerIndex: 3,
      explanation: "Gửi 2 triệu thông báo riêng lẻ vừa spam người dùng vừa tốn tài nguyên dispatch. Batching/debounce theo cửa sổ thời gian là cách chuẩn để xử lý notification storm — đánh đổi độ trễ thông báo lấy trải nghiệm và tải hệ thống hợp lý hơn.",
    },
  ],
};
