import type { ModuleDefinition } from "@/content/content-types";

export const b15SecurityForBackendModule: ModuleDefinition = {
  id: "b15",
  slug: "b15-security-for-backend",
  phaseId: "b-phase-3",
  order: 15,
  weeks: "Tuần 19",
  title: "Security cho backend",
  emoji: "🛡️",
  eli5Summary:
    "Nhà đã xây xong — có CRUD, cửa an toàn (auth), sổ phân quyền (RBAC), kho đồ (upload), việc vặt chạy nền (job), tủ lạnh trữ đồ (cache), chuông cửa (realtime) — nhưng cửa sổ chưa khoá, chưa lắp camera, và có tờ giấy dán mật khẩu wifi ngay cửa ra vào. Module này không xây thêm phòng nào cả — nó đi khoá từng cửa sổ, lắp chuông báo động, và dọn sạch những tờ giấy dán mật khẩu trước khi mời khách (production) vào ở.",
  objectives: [
    "Rà OWASP Top 10 (2021) lên đúng từng phần của `taskflow-api` đã build, phân biệt rủi ro đã được B04/B05/B06 xử lý và rủi ro cần vá thêm ở module này",
    "Thêm rate limiting theo scope (chặt cho `/auth/login`, lỏng hơn cho toàn API) để giảm brute-force & abuse, hiểu rõ giới hạn của rate limit theo IP",
    "Cấu hình `@fastify/helmet` và CORS đúng cách — allowlist origin cụ thể, không dùng `*` khi request có cookie/bearer token",
    "Quản lý secret an toàn: không hard-code, dùng `.env`, tránh secret rò trong log lỗi/stack trace",
    "Đọc report `pnpm audit` thật và xử lý hoặc document ít nhất một lỗ hổng dependency thực tế",
    "Viết test chứng minh Drizzle (parameterized query) chặn được payload injection cổ điển",
  ],
  lessons: [
    {
      slug: "owasp-top10-taskflow-api",
      title: "OWASP Top 10 áp cho taskflow-api",
      minutes: 40,
      summary: "Rà từng hạng mục OWASP Top 10 lên đúng những gì taskflow-api đã có — cái nào B04/B05/B06 lo rồi, cái nào module này phải vá.",
    },
    {
      slug: "rate-limiting-brute-force-abuse",
      title: "Rate limiting: chặn brute-force & abuse",
      minutes: 40,
      summary: "Một xô nước có hạn mức cho từng IP/route — login bị giới hạn chặt, toàn API giới hạn lỏng hơn.",
    },
    {
      slug: "security-headers-and-cors",
      title: "Security header & CORS đúng cách",
      minutes: 40,
      summary: "helmet dựng hàng rào header mặc định; CORS quyết định trình duyệt nào được phép gọi taskflow-api kèm cookie.",
    },
    {
      slug: "secrets-and-dependency-vulnerabilities",
      title: "Quản lý secret & lỗ hổng dependency",
      minutes: 35,
      summary: "Secret không được nằm trong code hay log lỗi; dependency cần được quét định kỳ bằng pnpm audit.",
    },
  ],
  labs: [
    {
      id: "rate-limit-login-and-global",
      title: "Rate limit riêng cho /auth/login + giới hạn chung toàn API",
      description: "Cài `@fastify/rate-limit`, áp ngưỡng chặt cho `/auth/login` (chống brute-force) và ngưỡng lỏng hơn cho toàn bộ `/api/v1` (chống abuse).",
      steps: [
        "Cài `@fastify/rate-limit`: `pnpm add @fastify/rate-limit`",
        "Đăng ký plugin global trong `src/app.ts` với ngưỡng lỏng: `max: 100, timeWindow: '1 minute'`, áp cho toàn bộ `/api/v1`",
        "Trong route `POST /api/v1/auth/login`, override cấu hình rate limit ở route-level (`config: { rateLimit: { max: 5, timeWindow: '1 minute' } }`) — chặt hơn nhiều vì đây là mục tiêu brute-force",
        "Dùng `errorResponseBuilder` để khi vượt ngưỡng, response trả đúng format lỗi chuẩn `{ error: { code: 'RATE_LIMITED', message: '...' } }` thay vì format mặc định của plugin",
        "Test thủ công: gọi `/auth/login` sai mật khẩu 6 lần liên tiếp bằng `curl` trong vòng 1 phút, xác nhận 5 lần đầu trả `401`, lần thứ 6 trả `429`",
      ],
    },
    {
      id: "helmet-and-cors-allowlist",
      title: "Thêm @fastify/helmet + CORS allowlist",
      description: "Bật security header mặc định và cấu hình CORS chỉ cho phép đúng origin frontend, hỗ trợ credentials cho cookie refresh token.",
      steps: [
        "Cài `@fastify/helmet` và `@fastify/cors`: `pnpm add @fastify/helmet @fastify/cors`",
        "Đăng ký `@fastify/helmet` trong `src/app.ts` trước các route khác, dùng cấu hình mặc định (đủ cho API JSON, không cần cấu hình CSP phức tạp của trang HTML)",
        "Đăng ký `@fastify/cors` với `origin: env.ALLOWED_ORIGINS.split(',')` (đọc từ biến môi trường, ví dụ `http://localhost:5173`) và `credentials: true` — KHÔNG dùng `origin: '*'` vì `/auth/refresh` gửi cookie `httpOnly` (B05)",
        "Thêm biến `ALLOWED_ORIGINS` vào `.env.example`",
        "Test bằng `curl -H 'Origin: http://evil.example' -X OPTIONS ...`: xác nhận response không có header `Access-Control-Allow-Origin` khớp origin lạ; lặp lại với origin hợp lệ trong allowlist, xác nhận header xuất hiện đúng",
      ],
    },
    {
      id: "pnpm-audit-fix-vulnerability",
      title: "Chạy pnpm audit và xử lý ít nhất 1 lỗ hổng thật",
      description: "Quét dependency thật của taskflow-api, đọc report, và thực sự sửa hoặc document một finding — không bịa CVE.",
      steps: [
        "Chạy `pnpm audit` trong thư mục `taskflow-api`, đọc toàn bộ output (severity, package, patched version)",
        "Với mỗi finding mức `high`/`critical`: kiểm tra có bản cập nhật vá được không (`pnpm update <package>`), cập nhật rồi chạy lại `pnpm test` để chắc không vỡ gì",
        "Với finding mức `low`/`moderate` chưa có bản vá ngay (thường là transitive dependency), ghi vào `SECURITY.md` ở gốc repo: tên gói, mức độ, lý do chấp nhận rủi ro tạm thời — thay vì im lặng bỏ qua",
        "Chạy lại `pnpm audit` sau khi sửa, xác nhận không còn finding mức `high`/`critical` chưa xử lý",
        "Commit `pnpm-lock.yaml` đã cập nhật cùng `SECURITY.md`",
      ],
    },
    {
      id: "sqli-parameterized-query-test",
      title: "Test injection: xác nhận Drizzle chặn được SQLi",
      description: "Viết test Vitest gửi payload injection cổ điển vào một trường text (ví dụ `task.title`), chứng minh parameterized query của Drizzle không bị khai thác.",
      steps: [
        "Chọn một trường text nhận input tự do — ví dụ `title` của `POST /api/v1/projects/:projectId/tasks`",
        "Viết test gửi payload `\"'; DROP TABLE tasks; --\"` làm giá trị `title`, gọi endpoint thật qua `app.inject()`",
        "Assert response trả `201` (tạo task thành công) và bảng `tasks` trong DB vẫn còn nguyên — đếm số dòng trước/sau không bị mất bất thường, bảng chưa bị xoá",
        "Assert task vừa tạo có `title` đúng bằng chuỗi payload gốc (bao gồm cả dấu `'` và `;`) — chứng minh nó được lưu như DỮ LIỆU, không phải được THỰC THI như câu lệnh SQL",
        "Chạy `pnpm test` — test injection phải xanh; ghi chú trong test: nếu handler dùng `sql.raw()` nối chuỗi input trực tiếp thay vì Drizzle query builder, test này phải đỏ ngay",
      ],
    },
  ],
  deliverable:
    "`taskflow-api` có rate limit theo scope (login chặt, toàn API lỏng), `@fastify/helmet` + CORS allowlist, `SECURITY.md` ghi lại các finding từ `pnpm audit` đã xử lý, và test Vitest xác nhận Drizzle chặn được payload injection.",
  successCriteria:
    "Đăng nhập sai liên tục bị `429` sau đúng ngưỡng cấu hình; request CORS từ origin lạ không nhận được header `Access-Control-Allow-Origin` khớp; `pnpm audit` không còn lỗ hổng mức high/critical chưa xử lý; `pnpm test` xanh, gồm cả test injection.",
  resources: [
    { title: "OWASP Top 10 (2021)", url: "https://owasp.org/Top10/", kind: "doc" },
    { title: "OWASP Cheat Sheet Series", url: "https://cheatsheetseries.owasp.org/", kind: "doc" },
    { title: "OWASP Secrets Management Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html", kind: "doc" },
    { title: "@fastify/rate-limit (GitHub)", url: "https://github.com/fastify/fastify-rate-limit", kind: "doc" },
    { title: "@fastify/helmet (GitHub)", url: "https://github.com/fastify/fastify-helmet", kind: "doc" },
    { title: "pnpm docs — pnpm audit", url: "https://pnpm.io/cli/audit", kind: "doc" },
  ],
  quiz: [
    {
      id: "rate-limit-scope-login-vs-global",
      question: "taskflow-api áp rate limit riêng cho `/auth/login` (chặt hơn) và một ngưỡng chung cho toàn API (lỏng hơn). Vì sao cần ngưỡng RIÊNG cho login thay vì chỉ dùng ngưỡng chung?",
      options: [
        "Vì route login trả response nặng nhất nên cần giới hạn",
        "Vì Fastify không hỗ trợ áp rate limit toàn cục",
        "Vì login là mục tiêu brute-force mật khẩu — ngưỡng chung (ví dụ 100 request/phút) vẫn đủ để thử hàng chục mật khẩu; cần một ngưỡng riêng thấp hơn hẳn cho đúng endpoint nhạy cảm này",
        "Vì login luôn được cache nên không cần rate limit",
      ],
      answerIndex: 2,
      explanation: "Ngưỡng chung được đặt để chặn abuse trên toàn API (ví dụ scraping), còn login cần một ngưỡng nhỏ hơn nhiều vì mỗi request là một lần thử mật khẩu — 100 request/phút vẫn quá rộng rãi cho một kẻ brute-force.",
    },
    {
      id: "rate-limit-ip-rotation-bypass",
      question: "Kẻ tấn công rotate qua hàng trăm IP khác nhau để brute-force `/auth/login`, mỗi IP chỉ gửi vài request. Rate limit theo IP có chặn được hoàn toàn không?",
      options: [
        "Có, rate limit theo IP luôn chặn được mọi kiểu brute-force",
        "Có, vì `@fastify/rate-limit` tự động phát hiện và gộp các IP rotation lại",
        "Không liên quan, vì rate limit chỉ áp dụng cho response chứ không áp dụng cho request",
        "Không hoàn toàn — rate limit theo IP là MỘT lớp phòng thủ; kẻ tấn công rotate IP có thể lách qua. Cần kết hợp thêm biện pháp khác (khoá tài khoản tạm thời, CAPTCHA) thay vì chỉ dựa vào IP",
      ],
      answerIndex: 3,
      explanation: "Rate limit theo IP không phải giải pháp đầy đủ chống brute-force — nó là một lớp phòng thủ trong nhiều lớp. Attacker có botnet hoặc proxy pool rotate IP vẫn có thể lách qua nếu đó là biện pháp DUY NHẤT.",
    },
    {
      id: "rate-limit-nat-false-positive",
      question: "Sau khi bật rate limit theo IP cho toàn API, nhiều nhân viên công ty (ngồi sau cùng một NAT/proxy công ty) báo bị `429` dù mỗi người chỉ gọi API vài lần. Nguyên nhân nhiều khả năng nhất?",
      options: [
        "Nhiều user khác nhau chia sẻ chung một IP công cộng (NAT) nên request của họ bị cộng dồn vào cùng một bucket rate limit theo IP",
        "Rate limit đang tính nhầm theo email thay vì IP",
        "`@fastify/rate-limit` chỉ hoạt động đúng với địa chỉ IPv6",
        "Đây là lỗi của Redis, không liên quan tới cấu hình rate limit",
      ],
      answerIndex: 0,
      explanation: "Đây chính là hạn chế thực tế của rate limit theo IP: nhiều thiết bị/người dùng đứng sau cùng một NAT hoặc proxy công ty dùng chung một địa chỉ IP công cộng, nên bị tính chung vào một bucket — false positive cho người dùng hợp lệ.",
    },
    {
      id: "cors-wildcard-with-credentials",
      question: "taskflow-api dùng cookie `httpOnly` để lưu refresh token (từ B05). Một dev cấu hình CORS `origin: '*'` cho \"dễ dùng\", đồng thời set `credentials: true`. Điều gì xảy ra?",
      options: [
        "Hoạt động bình thường, `*` cho phép mọi origin gửi kèm cookie",
        "Trình duyệt TỪ CHỐI gửi/nhận response — theo CORS spec, `Access-Control-Allow-Origin: *` không tương thích với `credentials: true`; phải khai một origin cụ thể trong allowlist",
        "Server tự động đổi `*` thành origin thật khi phát hiện có cookie",
        "Chỉ ảnh hưởng tới Safari, các trình duyệt khác vẫn hoạt động bình thường",
      ],
      answerIndex: 1,
      explanation: "Theo đặc tả CORS, khi request có `credentials` (cookie, `Authorization` kèm session), server không được trả `Access-Control-Allow-Origin: *` — trình duyệt sẽ chặn response. Server phải phản hồi đúng origin cụ thể của request, lấy từ một allowlist đã kiểm tra.",
    },
    {
      id: "cors-preflight-purpose",
      question: "Trình duyệt tự động gửi request `OPTIONS` trước khi thực hiện `DELETE /api/v1/projects/:id` từ một origin khác. Request OPTIONS (preflight) này để làm gì?",
      options: [
        "Là request thật sự sẽ xoá project, chỉ đổi tên method để né rate limit",
        "Là cơ chế cache tĩnh của trình duyệt, không liên quan tới bảo mật",
        "Preflight — trình duyệt hỏi trước server \"origin/method/header này có được phép không\"; nếu server không trả header cho phép, request thật (`DELETE`) sẽ không được trình duyệt gửi tiếp",
        "Chỉ xảy ra khi server trả lỗi `500` ở lần gọi trước",
      ],
      answerIndex: 2,
      explanation: "Preflight là bước trình duyệt tự thêm vào cho các request \"không đơn giản\" (method như DELETE/PUT, header tuỳ chỉnh...) để hỏi server trước xem origin/method/header đó có được cho phép hay không, trước khi thật sự gửi request có thể gây side-effect.",
    },
    {
      id: "helmet-purpose",
      question: "`@fastify/helmet` chủ yếu làm gì cho `taskflow-api`?",
      options: [
        "Mã hoá toàn bộ nội dung response body",
        "Tự động thêm các HTTP response header giúp giảm thiểu một số lớp tấn công phổ biến ở phía trình duyệt (ví dụ chống MIME-sniffing) — không thay thế cho việc validate input hay authorization đúng cách",
        "Thay thế hoàn toàn chức năng của `@fastify/rate-limit`",
        "Tăng tốc độ response nhờ nén gzip tự động",
      ],
      answerIndex: 1,
      explanation: "helmet chỉ set các response header an toàn (một lớp phòng thủ bổ sung ở phía client/trình duyệt) — nó không kiểm tra input, không xác thực, không thay thế cho các lớp bảo mật khác đã xây ở B05/B06.",
    },
    {
      id: "injection-already-mitigated-drizzle",
      question: "taskflow-api dùng Drizzle ORM (từ B04) cho mọi câu query. Một dev vẫn lo lắng về SQL injection khi cho phép user nhập text tự do vào `task.title`. Đánh giá nào đúng?",
      options: [
        "Vì Drizzle build câu lệnh bằng parameterized query (giá trị truyền qua placeholder, không nối chuỗi trực tiếp vào SQL) nên một payload như `'; DROP TABLE tasks; --` chỉ được lưu như một chuỗi text bình thường, không thực thi được — rủi ro injection cổ điển đã được giảm thiểu từ B04, module này chỉ viết TEST xác nhận lại",
        "Drizzle không liên quan gì tới injection, cần cài thêm thư viện chống injection riêng",
        "Cần tắt Drizzle và tự viết raw SQL để kiểm soát injection tốt hơn",
        "Chỉ an toàn nếu chuỗi input có độ dài dưới 255 ký tự",
      ],
      answerIndex: 0,
      explanation: "Đây chính là lý do curriculum nối B15 với B04: injection cổ điển đã được giảm thiểu từ khi chọn Drizzle (parameterized query) làm ORM. B15 không cần \"thêm chống injection\" — nó viết test để CHỨNG MINH điều đó bằng thực nghiệm, thay vì chỉ tin suông.",
    },
    {
      id: "secrets-leak-in-error-log",
      question: "Một lỗi kết nối Postgres bị log ra kèm nguyên chuỗi `postgres://taskflow:taskflow@postgres:5432/taskflow`. Rủi ro chính là gì và nên sửa thế nào?",
      options: [
        "Không có rủi ro vì log chỉ nhân viên nội bộ xem được",
        "Rủi ro duy nhất là dòng log quá dài, làm chậm hệ thống log",
        "Chỉ cần đổi tên biến môi trường sang tên khác là an toàn hơn",
        "Log chứa mật khẩu DB dạng plaintext trong connection string — nếu log được đẩy sang dịch vụ log tập trung, backup, hay lộ qua công cụ bên thứ ba, mật khẩu bị lộ theo; nên redact secret trước khi log lỗi (chỉ log host/tên DB, không log cả connection string)",
      ],
      answerIndex: 3,
      explanation: "Log thường được lưu lâu dài, sao lưu, và có thể được gửi tới dịch vụ log tập trung (bên thứ ba) — bất kỳ secret nào lọt vào log coi như đã bị lộ ra ngoài phạm vi kiểm soát ban đầu. Cấu hình `redact` ở logger (pino) để loại bỏ secret trước khi ghi log.",
    },
    {
      id: "pnpm-audit-workflow",
      question: "Sau khi chạy `pnpm audit`, một dev thấy vài finding mức \"low\" nằm trong dependency không dùng trực tiếp (transitive) và chưa có bản vá. Cách xử lý hợp lý nhất?",
      options: [
        "Bỏ qua toàn bộ report vì `pnpm audit` chỉ mang tính tham khảo, không cần quan tâm",
        "Ưu tiên xử lý ngay các finding mức high/critical trước (cập nhật version, hoặc dùng bản vá nếu có); với finding low/transitive chưa có bản vá, ghi rõ vào `SECURITY.md` lý do chấp nhận rủi ro tạm thời — thay vì im lặng bỏ qua",
        "Xoá toàn bộ `node_modules` và cài lại là đủ để hết mọi lỗ hổng",
        "Luôn phải downgrade Node.js xuống bản cũ hơn để né lỗ hổng",
      ],
      answerIndex: 1,
      explanation: "`pnpm audit` là điểm khởi đầu của một quy trình, không phải checklist tick-cho-xong. Mức nghiêm trọng cao cần xử lý ngay; mức thấp/transitive chưa có bản vá thì ghi nhận có ý thức (document) thay vì lờ đi — đúng tinh thần \"đọc lỗi thật\" của cả course.",
    },
    {
      id: "rate-limit-threshold-tradeoff",
      question: "Ngưỡng rate limit cho `/auth/login` được đặt quá thấp (ví dụ 3 lần/giờ). Trade-off nào xuất hiện?",
      options: [
        "Không có trade-off nào — ngưỡng càng thấp thì càng an toàn tuyệt đối, không đánh đổi gì",
        "Server sẽ tốn nhiều RAM hơn khi ngưỡng được đặt thấp",
        "Người dùng thật gõ sai mật khẩu vài lần (quên mật khẩu, gõ nhầm bàn phím) sẽ bị khoá không đăng nhập được trong cả cửa sổ thời gian đó — cần cân bằng giữa việc chặn brute-force và trải nghiệm người dùng hợp lệ, không đặt ngưỡng tuỳ tiện",
        "Ngưỡng rate limit thấp làm tăng nguy cơ SQL injection",
      ],
      answerIndex: 2,
      explanation: "Rate limiting luôn là một đánh đổi: ngưỡng càng chặt càng an toàn trước brute-force nhưng càng dễ khoá nhầm người dùng thật. Đây là lý do rate limit chỉ nên là MỘT lớp phòng thủ, không phải lớp duy nhất — kết hợp thêm cảnh báo, CAPTCHA, hoặc thông báo email khi có nhiều lần đăng nhập sai.",
    },
  ],
};
