import type { ModuleDefinition } from "@/content/content-types";

export const b04DatabaseOrmDrizzlePostgresqlModule: ModuleDefinition = {
  id: "b04",
  slug: "b04-database-orm-drizzle-postgresql",
  phaseId: "b-phase-1",
  order: 4,
  weeks: "Tuần 5–6",
  title: "Database & ORM: Drizzle + PostgreSQL",
  emoji: "🗄️",
  eli5Summary:
    "Ba module trước, `taskflow-api` ghi nhớ dữ liệu bằng một cái `Map` trong RAM — giống ghi chú dán trên bảng trắng, tắt máy là mất hết. Module này xây một 'nhà kho' thật (Postgres) và thuê một 'thư ký' (Drizzle ORM) biết đọc tiếng TypeScript để cất — lấy đồ đúng ô, đúng kệ, và không bao giờ làm mất hàng khi cúp điện giữa chừng.",
  objectives: [
    "Định nghĩa schema Postgres bằng `pgTable` của Drizzle, đúng tên bảng/cột theo spec taskflow-api",
    "Sinh và áp migration bằng `drizzle-kit generate`/`push`/`migrate`, phân biệt khi nào dùng cái nào",
    "Khai báo quan hệ 1-n bằng foreign key và `relations()`, hiểu vì sao n-n cần bảng trung gian",
    "Bọc nhiều thao tác ghi trong `db.transaction` và giải thích chính xác cơ chế rollback khi lỗi",
    "Nhận diện N+1 query trong code thật và sửa bằng Drizzle relational query API (`with`)",
    "Cấu hình connection pool hợp lý cho driver `postgres` và giải thích đánh đổi của `max`",
  ],
  lessons: [
    {
      slug: "dinh-nghia-schema-drizzle-pgtable",
      title: "Định nghĩa schema với Drizzle & pgTable",
      minutes: 45,
      summary: "Biến 4 bảng trong spec taskflow-api thành code TypeScript thật, và nối driver `postgres` với connection pool.",
    },
    {
      slug: "migration-drizzle-kit-generate-push-migrate",
      title: "Migration: generate, push & migrate",
      minutes: 40,
      summary: "Từ file schema.ts ra file SQL migration thật, và khi nào dùng push thay vì generate+migrate.",
    },
    {
      slug: "quan-he-khoa-ngoai-relations",
      title: "Quan hệ 1-n, n-n & khai báo relations()",
      minutes: 40,
      summary: "Foreign key nối 4 bảng thành chuỗi org → project → task → comment, và vì sao n-n cần bảng nối.",
    },
    {
      slug: "transaction-db-transaction-rollback",
      title: "Transaction & rollback với db.transaction",
      minutes: 40,
      summary: "Tạo task và ghi log trong cùng một 'chuyến đi' — hỏng giữa đường thì trả lại nguyên trạng.",
    },
    {
      slug: "n-cong-1-query-relational-query-api",
      title: "N+1 query & relational query API",
      minutes: 45,
      summary: "Vòng lặp vô tình bắn N query, và cách gọi `with` một lần để Drizzle gộp lại.",
    },
  ],
  labs: [
    {
      id: "define-drizzle-schema",
      title: "Định nghĩa schema Drizzle cho 4 bảng",
      description: "Viết `src/db/schema.ts` đúng theo spec taskflow-api: organizations, projects, tasks, comments.",
      steps: [
        "Cài dependency nếu chưa có: `pnpm add drizzle-orm postgres` và `pnpm add -D drizzle-kit`",
        "Tạo `src/db/schema.ts`, khai báo `organizations` bằng `pgTable` với `id uuid` mặc định `defaultRandom()`, `name`, `slug` unique, `created_at`",
        "Khai báo `projects` với `organization_id` tham chiếu `organizations.id` bằng `.references()`",
        "Khai báo `tasks` với `project_id` tham chiếu `projects.id`, cột `status` giới hạn 3 giá trị, `assignee_id uuid` **không** có `.references()` (chưa có bảng `users`)",
        "Khai báo `comments` với `task_id` tham chiếu `tasks.id`, `author_id uuid` cũng chưa có FK",
        "Thêm `relations()` cho cả 4 bảng để dùng được relational query ở lab sau",
        "Tạo `src/db/client.ts` khởi tạo `postgres(DATABASE_URL, { max: 10 })` và `drizzle(client, { schema })`",
      ],
    },
    {
      id: "drizzle-kit-generate-push",
      title: "Sinh migration & áp vào Postgres bằng drizzle-kit",
      description: "Tạo `drizzle.config.ts`, sinh file SQL migration, và áp schema vào container `postgres` đang chạy.",
      steps: [
        "Tạo `drizzle.config.ts` ở root với `schema`, `out: \"./drizzle\"`, `dialect: \"postgresql\"`, `dbCredentials.url`",
        "Chạy `npx drizzle-kit generate` — đọc kỹ file `.sql` sinh ra trong `drizzle/`, xác nhận đúng 4 bảng + FK",
        "Đảm bảo `docker compose up -d postgres` đang chạy, container dùng đúng user/db `taskflow`/`taskflow`",
        "Áp migration bằng `npx drizzle-kit migrate` (chạy đúng file `.sql` đã generate, phù hợp CI/production)",
        "Thử `npx drizzle-kit push` trên một thay đổi nhỏ (ví dụ thêm cột) để thấy nó áp thẳng không qua file — chỉ dùng cho local dev",
        "Kiểm tra bằng `docker compose exec postgres psql -U taskflow -d taskflow -c '\\dt'` thấy đủ 4 bảng",
      ],
    },
    {
      id: "rewrite-routes-drizzle",
      title: "Chuyển route B02/B03 từ Map sang Drizzle",
      description: "Xoá in-memory `Map`, nối toàn bộ route `projects`/`tasks` với Postgres thật qua Drizzle.",
      steps: [
        "Trong `src/routes/projects.ts`, thay `projectsMap.set(...)` bằng `db.insert(projects).values({...}).returning()`",
        "Thay `projectsMap.get(id)` bằng `db.query.projects.findFirst({ where: eq(projects.id, id) })`",
        "Trong `src/routes/tasks.ts`, chuyển `GET /projects/:id/tasks` sang `db.query.tasks.findMany({ where: eq(tasks.projectId, id) })`, giữ nguyên cursor pagination đã có từ B03",
        "Chuyển `PATCH`/`DELETE` task sang `db.update(tasks).set({...}).where(eq(tasks.id, id))` và `db.delete(tasks).where(...)`",
        "Xoá hẳn file định nghĩa `Map` in-memory, xác nhận không còn import nào trỏ tới nó",
        "Chạy lại toàn bộ request `curl` từ B02/B03, xác nhận status code và response shape không đổi — chỉ nguồn dữ liệu đổi",
      ],
    },
    {
      id: "transaction-task-plus-log",
      title: "Transaction: tạo task + ghi log, rollback khi lỗi",
      description: "Viết một transaction ghi 2 bảng, cố tình cho lỗi giữa chừng để chứng minh cả 2 write đều bị huỷ.",
      steps: [
        "Viết hàm `createTaskWithLog(input, { forceFailure })` dùng `db.transaction(async (tx) => {...})`",
        "Bên trong: `tx.insert(tasks)` trước, `.returning()` lấy `id` vừa tạo",
        "Tiếp theo `tx.insert(comments)` ghi một dòng \"log\" hệ thống dùng chính `task.id` vừa tạo (author_id dùng UUID giả vì chưa có bảng `users`)",
        "Nếu `forceFailure` là `true`, `throw new Error(...)` ngay sau 2 lệnh insert — không `catch` bên trong transaction",
        "Gọi hàm với `forceFailure: true`, bắt lỗi ở tầng route, trả `500`",
        "Query lại `SELECT * FROM tasks` và `SELECT * FROM comments` — xác nhận **không** có dòng nào của lần gọi lỗi đó, chỉ transaction thành công (`forceFailure: false`) mới để lại dữ liệu",
      ],
    },
  ],
  deliverable:
    "`taskflow-api` với `src/db/schema.ts` (4 bảng đúng spec), migration đã áp vào Postgres qua volume, toàn bộ route B02/B03 đọc/ghi Postgres thật (không còn Map), và hàm `createTaskWithLog` có transaction rollback chứng minh được.",
  successCriteria:
    "Restart container `postgres` (không xoá volume) — dữ liệu vẫn còn nguyên; gọi `createTaskWithLog` với lỗi giả lập không để lại task hay comment mồ côi nào trong DB.",
  resources: [
    { title: "Drizzle ORM docs — Overview", url: "https://orm.drizzle.team/docs/overview", kind: "doc" },
    { title: "Drizzle ORM docs — Drizzle Kit (migrations)", url: "https://orm.drizzle.team/docs/kit-overview", kind: "doc" },
    { title: "Drizzle ORM docs — Transactions", url: "https://orm.drizzle.team/docs/transactions", kind: "doc" },
    { title: "Drizzle ORM docs — Relational Queries (RQB)", url: "https://orm.drizzle.team/docs/rqb", kind: "doc" },
    { title: "PostgreSQL docs — Transactions", url: "https://www.postgresql.org/docs/current/tutorial-transactions.html", kind: "doc" },
    { title: "postgres (porsager) — driver GitHub README", url: "https://github.com/porsager/postgres", kind: "doc" },
  ],
  quiz: [
    {
      id: "pgtable-purpose",
      question: "Trong `export const tasks = pgTable(\"tasks\", { id: uuid(\"id\").primaryKey(), ... })`, `pgTable` dùng để làm gì?",
      options: [
        "Định nghĩa cấu trúc bảng bằng TypeScript, dùng để sinh SQL và để code truy vấn có type an toàn",
        "Chạy migration lên Postgres ngay lập tức",
        "Tạo một bảng tạm chỉ tồn tại trong RAM",
        "Kết nối tới Postgres container",
      ],
      answerIndex: 0,
      explanation: "`pgTable` chỉ là khai báo schema bằng code (giống bản vẽ kệ hàng) — nó chưa chạm tới DB. `drizzle-kit generate`/`push` mới thật sự tạo bảng.",
    },
    {
      id: "assignee-no-fk",
      question: "Vì sao cột `tasks.assignee_id` trong module này là `uuid` thường, không có `.references()`?",
      options: [
        "Vì Drizzle không hỗ trợ foreign key cho cột nullable",
        "Vì assignee luôn là chính người tạo task nên không cần tham chiếu",
        "Vì foreign key làm chậm query `SELECT`",
        "Vì bảng `users` chưa tồn tại — nó được tạo ở B05, module này chỉ để chỗ cho cột đó",
      ],
      answerIndex: 3,
      explanation: "Spec taskflow-api tạo `users`/`memberships` ở B05. B04 chỉ tạo organizations/projects/tasks/comments, nên assignee_id/author_id tạm là uuid trơn, FK sẽ thêm bằng migration ở B05.",
    },
    {
      id: "generate-vs-push",
      question: "Team đã có pipeline CI chạy migration khi merge vào `main`. Nên dùng lệnh nào để thay đổi schema production, thay vì `drizzle-kit push`?",
      options: [
        "`drizzle-kit push` vẫn luôn là lựa chọn tốt nhất cho mọi môi trường",
        "`drizzle-kit studio` vì nó tự động deploy",
        "`drizzle-kit generate` để sinh file `.sql` versioned, review trong PR, rồi `drizzle-kit migrate` áp đúng file đó trong CI",
        "Sửa trực tiếp bằng `psql` cho nhanh, khỏi cần Drizzle",
      ],
      answerIndex: 2,
      explanation: "`push` áp thẳng schema hiện tại vào DB, tiện cho local dev nhưng không để lại lịch sử. Production/CI cần file migration versioned để review và chạy lại được — đó là việc của `generate` + `migrate`.",
    },
    {
      id: "relations-vs-fk",
      question: "Trong Drizzle, `.references(() => organizations.id)` trên cột và hàm `relations(projects, ({ one }) => ({...}))` khác nhau ở điểm nào?",
      options: [
        "Chúng làm cùng một việc, viết cái nào cũng được, không cần cả hai",
        "`.references()` tạo ràng buộc foreign key thật ở tầng DB; `relations()` chỉ mô tả cho Drizzle biết cách join khi dùng relational query API (`with`), không tạo constraint",
        "`relations()` mới là thứ tạo foreign key, `.references()` chỉ để đặt tên cột",
        "`.references()` dùng cho n-n, `relations()` dùng cho 1-n",
      ],
      answerIndex: 1,
      explanation: "Hai thứ phục vụ hai tầng khác nhau: `.references()` ảnh hưởng tới SQL migration (constraint thật), còn `relations()` chỉ là metadata giúp `db.query.x.findMany({ with: {...} })` biết join bảng nào.",
    },
    {
      id: "many-to-many-join-table",
      question: "Nếu sau này taskflow-api cần quan hệ n-n thật (ví dụ nhiều `tags` gắn vào nhiều `tasks`), cách làm đúng với Postgres/Drizzle là gì?",
      options: [
        "Thêm một mảng `tag_ids` kiểu `text[]` vào bảng `tasks`",
        "Thêm `tags_id` vào `tasks` và `task_id` vào `tags`, tham chiếu chéo nhau",
        "Tạo bảng trung gian (join table) như `task_tags (task_id fk, tag_id fk)` với khoá chính kết hợp cả hai cột",
        "Không thể làm n-n trong quan hệ, phải tách thành 2 request riêng ở tầng ứng dụng",
      ],
      answerIndex: 2,
      explanation: "n-n luôn cần bảng nối vì một hàng ở bảng A có thể khớp nhiều hàng ở bảng B và ngược lại — không cột đơn nào biểu diễn được điều đó. `memberships` ở B05 là ví dụ thật của pattern này (user ↔ organization).",
    },
    {
      id: "transaction-throw-rollback",
      question: "Bên trong `db.transaction(async (tx) => { await tx.insert(tasks)...; throw new Error(\"boom\"); })`, chuyện gì xảy ra với dòng `tasks` vừa insert?",
      options: [
        "Drizzle tự động rollback toàn bộ thay đổi trong transaction đó — dòng `tasks` biến mất như chưa từng insert",
        "Vẫn được lưu vào DB vì `insert` đã chạy xong trước khi throw",
        "Phải gọi `tx.rollback()` thủ công thì mới huỷ được",
        "Chỉ rollback nếu lỗi là `SyntaxError`, các lỗi khác thì giữ nguyên",
      ],
      answerIndex: 0,
      explanation: "Ném lỗi (throw) bên trong callback của `db.transaction` khiến Drizzle tự rollback toàn bộ — không cần gọi rollback thủ công. Đây là lý do transaction an toàn để nhóm nhiều write lại với nhau.",
    },
    {
      id: "tx-vs-db-inside-transaction",
      question: "Trong transaction, vì sao phải dùng `tx.insert(...)` thay vì `db.insert(...)` cho các câu lệnh bên trong callback?",
      options: [
        "Không có khác biệt, chỉ là quy ước đặt tên biến",
        "`db.insert` chậm hơn `tx.insert` vì phải mở connection mới mỗi lần",
        "`tx` chỉ dùng được cho `SELECT`, không dùng được cho `INSERT`",
        "`tx` chạy trên cùng một connection/transaction đang mở; dùng nhầm `db` sẽ chạy trên connection khác, ngoài transaction, nên không rollback cùng được",
      ],
      answerIndex: 3,
      explanation: "`tx` là 'phiên bản' của `db` bị khoá vào đúng transaction đang chạy. Lỡ gọi `db.insert` bên trong sẽ thoát ra ngoài transaction đó — insert sẽ commit ngay lập tức, không rollback được nữa dù transaction cha thất bại.",
    },
    {
      id: "n-plus-one-spotting",
      question:
        "Route lấy toàn bộ task bằng `db.select().from(tasks)`, rồi lặp `for (const task of allTasks)` và bên trong vòng lặp gọi thêm `db.select().from(comments).where(eq(comments.taskId, task.id))` cho từng task. Đoạn code này có vấn đề gì?",
      options: [
        "Không có vấn đề gì, đây là cách viết chuẩn của Drizzle",
        "Đây là N+1 query: 1 query lấy tasks, cộng thêm N query (mỗi task một query) để lấy comments — chậm dần khi N tăng",
        "Vấn đề là thiếu `await` ở dòng đầu tiên",
        "Vấn đề là `comments` phải được insert trước `tasks`",
      ],
      answerIndex: 1,
      explanation: "Vòng lặp gọi query cho từng phần tử là dấu hiệu kinh điển của N+1. Với 200 task, đoạn này bắn 201 query xuống Postgres thay vì 1-2 query.",
    },
    {
      id: "relational-query-fix",
      question: "Cách sửa N+1 ở câu trên bằng Drizzle relational query API là gì?",
      options: [
        "Thêm `Promise.all()` bọc quanh vòng lặp cho chạy song song",
        "Chuyển toàn bộ sang raw SQL viết tay để kiểm soát số query",
        "`await db.query.tasks.findMany({ with: { comments: true } })` — Drizzle gộp việc lấy comments thành một (hoặc rất ít) query, không lặp theo từng task",
        "Cache toàn bộ bảng `comments` vào bộ nhớ khi app khởi động",
      ],
      answerIndex: 2,
      explanation: "`Promise.all()` vẫn chạy N query, chỉ chạy song song thay vì tuần tự — không giải quyết gốc rễ. `with` trong relational query API mới thực sự gộp lại theo lô, đúng tinh thần Drizzle thiết kế.",
    },
    {
      id: "pool-max-tradeoff",
      question: "`postgres(DATABASE_URL, { max: 10 })` — nếu tăng `max` lên 500 cho một `taskflow-api` chạy dạng server dài hạn (không phải serverless), điều gì đáng lo nhất?",
      options: [
        "500 connection từ một instance có thể cộng dồn với các instance khác và vượt `max_connections` cấu hình của Postgres, làm connection mới bị từ chối — không phải cứ tăng `max` là nhanh hơn tuyến tính",
        "Không có gì đáng lo, `max` càng cao càng nhanh, luôn nên đặt tối đa",
        "`max` chỉ ảnh hưởng tới Redis, không liên quan tới Postgres",
        "`max: 500` sẽ khiến Drizzle tự động bật thêm replica",
      ],
      answerIndex: 0,
      explanation: "Pool lớn hữu ích khi có nhiều request đồng thời thật sự cần connection riêng, nhưng Postgres có giới hạn `max_connections` toàn instance. Con số 'đúng' phụ thuộc tải thực tế và số instance — không có một giá trị max phổ quát, cần đo và cân đối, không phải càng cao càng tốt.",
    },
  ],
};
