import type { ModuleDefinition } from "@/content/content-types";

export const m09AwsWellArchitectedCostModule: ModuleDefinition = {
  id: "m09",
  slug: "m09-aws-well-architected-cost",
  phaseId: "phase-2",
  order: 9,
  weeks: "Tuần 14–15",
  title: "Well-Architected, HA/DR & Cost Optimization",
  emoji: "🧭",
  eli5Summary:
    "Xây xong nhà thì phải tự hỏi: nhà có chắc không (reliability), có an toàn không (security), có tốn điện quá không (cost)? Module này dạy bạn dùng danh sách kiểm tra 6 trụ cột của AWS, lên kế hoạch cho ngày 'cháy nhà' (DR), và cắt giảm hoá đơn AWS mà không đánh đổi độ ổn định. Kết thúc bằng Checkpoint 2: dựng một app HA thật trên AWS và ôn thi chứng chỉ SAA.",
  objectives: [
    "Áp dụng 6 trụ cột Well-Architected để tự review một kiến trúc",
    "Phân biệt chính xác HA, fault tolerance và disaster recovery; định nghĩa RTO/RPO",
    "Chọn đúng chiến lược DR (backup & restore, pilot light, warm standby, active-active) theo yêu cầu và ngân sách",
    "Áp dụng right-sizing, Savings Plans/Spot và tagging strategy để tối ưu chi phí",
    "Đọc CloudWatch metrics/logs và cấu hình alarm dẫn tới hành động tự động",
    "Dựng một app HA hoàn chỉnh trên AWS và tự đánh giá sẵn sàng cho kỳ thi AWS SAA",
  ],
  lessons: [
    { slug: "well-architected-six-pillars", title: "Well-Architected Framework: 6 trụ cột", minutes: 40, summary: "Danh sách kiểm tra kiến trúc: vận hành, bảo mật, độ tin cậy, hiệu năng, chi phí, bền vững." },
    { slug: "ha-fault-tolerance-dr-rto-rpo", title: "HA vs Fault Tolerance vs DR, RTO/RPO", minutes: 40, summary: "Ba mức chuẩn bị cho sự cố, và hai con số đo mức chấp nhận được." },
    { slug: "dr-strategies-backup-pilot-warm-active", title: "4 chiến lược Disaster Recovery", minutes: 45, summary: "Backup & restore, pilot light, warm standby, active-active — đánh đổi chi phí vs RTO/RPO." },
    { slug: "cost-optimization-tagging", title: "Tối ưu chi phí & tagging strategy", minutes: 45, summary: "Right-sizing, Savings Plans, Spot, và gắn tag để biết tiền đi đâu." },
    { slug: "cloudwatch-metrics-logs-alarms", title: "CloudWatch: metrics, logs, alarms", minutes: 40, summary: "Cảm biến, camera và chuông báo của hạ tầng AWS." },
  ],
  labs: [
    {
      id: "architecture-diagram-well-architected-review",
      title: "Vẽ kiến trúc & tự review bằng Well-Architected Tool",
      description: "Vẽ sơ đồ kiến trúc app hiện tại và chạy review chính thức để tìm rủi ro theo 6 trụ cột.",
      steps: [
        "Vẽ sơ đồ kiến trúc app (draw.io, Excalidraw hoặc diagrams-as-code như Python `diagrams`) gồm VPC, subnet, ALB, ASG, RDS, ElastiCache, S3",
        "Tạo workload trong Well-Architected Tool: `aws wellarchitected create-workload --workload-name ... --lenses wellarchitected --aws-regions ap-southeast-1`",
        "Trả lời bộ câu hỏi cho ít nhất 3 trụ cột: Reliability, Security, Cost Optimization",
        "Liệt kê toàn bộ High Risk Issue được công cụ chỉ ra: `aws wellarchitected list-answers --workload-id <id> --lens-alias wellarchitected --query \"AnswerSummaries[?Risk=='HIGH']\"`",
        "Với mỗi HRI, viết 1–2 câu giải pháp cụ thể (sửa ngay hoặc ghi nhận rủi ro chấp nhận được và lý do)",
      ],
    },
    {
      id: "dr-plan-rto-rpo-restore-drill",
      title: "Viết DR plan và đo RTO/RPO thật",
      description: "Đặt mục tiêu RTO/RPO, thử restore RDS từ snapshot và đo thời gian thực tế so với mục tiêu.",
      steps: [
        "Viết DR plan ngắn: RTO/RPO mục tiêu, chiến lược DR chọn (vd Backup & Restore), lý do chọn",
        "Bấm giờ bắt đầu: `date -u +%T`",
        "Restore RDS từ snapshot gần nhất: `aws rds restore-db-instance-from-db-snapshot --db-instance-identifier app-db-dr-test --db-snapshot-identifier <snapshot-id> --db-subnet-group-name app-db-subnets --no-publicly-accessible`",
        "Theo dõi tới khi trạng thái `available`, ghi lại thời gian đã mất — đây là RTO thực đo được",
        "So sánh RTO/RPO thực đo với mục tiêu ban đầu, ghi vào DR plan; nếu lệch nhiều, điều chỉnh chiến lược hoặc mục tiêu",
        "Xoá instance test: `aws rds delete-db-instance --db-instance-identifier app-db-dr-test --skip-final-snapshot`",
      ],
    },
    {
      id: "tagging-cost-explorer",
      title: "Gắn tag chuẩn & xem chi phí theo tag",
      description: "Áp tag project/env/owner cho toàn bộ resource, kích hoạt cost allocation tag và đọc báo cáo Cost Explorer.",
      steps: [
        "Liệt kê resource chưa có tag: `aws resourcegroupstaggingapi get-resources --tag-filters Key=project`",
        "Gắn tag `project`, `env`, `owner` cho mọi EC2, RDS, S3, EBS liên quan bằng `aws ec2 create-tags` (hoặc theo dịch vụ tương ứng)",
        "Kích hoạt các tag này làm cost allocation tag trong Billing Console (hoặc `aws ce update-cost-allocation-tags-status` nếu dùng CLI)",
        "Sau khi tag được kích hoạt (có thể mất tới 24 giờ để lên báo cáo), truy vấn chi phí theo tag: `aws ce get-cost-and-usage --time-period Start=...,End=... --granularity MONTHLY --metrics UnblendedCost --group-by Type=TAG,Key=project`",
        "Tạo AWS Budget cảnh báo 80% ngưỡng $10/tháng cho project, gửi email khi vượt",
      ],
    },
    {
      id: "checkpoint-2-ha-app-saa-review",
      title: "✅ Checkpoint 2 + Ôn AWS SAA",
      description:
        "Dựng app mẫu chạy HA đầy đủ trên AWS (CloudFront → ALB → ASG private → RDS Multi-AZ + ElastiCache + S3, CI/CD qua OIDC, CloudWatch alarms), rồi ôn luyện và tự đánh giá sẵn sàng thi AWS Certified Solutions Architect – Associate.",
      steps: [
        "Ghép lại toàn bộ hạ tầng từ M06–M09: VPC 2 AZ, ALB public + ASG private phía sau, RDS Multi-AZ và ElastiCache trong private subnet, S3 cho file người dùng",
        "Đặt CloudFront phía trước ALB (HTTPS bằng ACM) để có CDN + edge cache cho asset tĩnh",
        "Cấu hình CI/CD pipeline (GitHub Actions) deploy qua OIDC role — không dùng access key tĩnh (ôn lại M06)",
        "Tạo CloudWatch alarm cho CPU ASG, độ trễ ALB (TargetResponseTime) và số connection RDS; nối vào SNS gửi email",
        "Tắt 1 AZ (terminate toàn bộ instance ở 1 AZ hoặc force failover RDS) và xác nhận app vẫn phục vụ — đúng tiêu chí đạt Checkpoint 2",
        "Chụp ảnh màn hình/console mọi cấu hình quan trọng và ghi chú kiến trúc trước khi xoá resource (NAT Gateway, RDS, ALB tính tiền theo giờ)",
        "Làm Tutorials Dojo practice exam AWS SAA tới khi đạt ≥ 80% ổn định qua nhiều lần thi thử, sau đó đăng ký thi thật (kiểm tra mã đề thi hiện hành trên trang AWS Certification trước khi đăng ký)",
      ],
    },
  ],
  deliverable:
    "App HA hoàn chỉnh trên AWS (CloudFront → ALB → ASG private → RDS Multi-AZ + ElastiCache + S3, CI/CD qua OIDC, CloudWatch alarms) kèm tài liệu kiến trúc, DR plan có RTO/RPO đo thực tế, và kết quả Well-Architected review.",
  successCriteria:
    "Tắt 1 AZ mà app vẫn phục vụ được; mọi resource có tag project/env/owner; DR plan có số liệu RTO/RPO đo thật (không chỉ lý thuyết); đạt ổn định ≥ 80% trên đề thi thử AWS SAA trước khi đăng ký thi thật; đã xoá sạch resource tính phí theo giờ sau khi hoàn thành.",
  resources: [
    { title: "AWS Well-Architected Framework", url: "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html", kind: "doc" },
    { title: "AWS Well-Architected Tool", url: "https://docs.aws.amazon.com/wellarchitected/latest/userguide/intro.html", kind: "tool" },
    { title: "Disaster Recovery of Workloads on AWS (Whitepaper)", url: "https://docs.aws.amazon.com/whitepapers/latest/disaster-recovery-workloads-on-aws/disaster-recovery-workloads-on-aws.html", kind: "doc" },
    { title: "AWS Cost Optimization", url: "https://aws.amazon.com/aws-cost-management/aws-cost-optimization/", kind: "doc" },
    { title: "Amazon CloudWatch User Guide", url: "https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/WhatIsCloudWatch.html", kind: "doc" },
    { title: "AWS Skill Builder — AWS Certified Solutions Architect - Associate", url: "https://skillbuilder.aws/exam-prep/solutions-architect-associate", kind: "course" },
    { title: "Tutorials Dojo — AWS SAA-C03 Practice Exams", url: "https://tutorialsdojo.com/courses/aws-certified-solutions-architect-associate-practice-exams/", kind: "practice" },
    { title: "AWS Certification — Solutions Architect Associate (kiểm tra mã đề hiện hành)", url: "https://aws.amazon.com/certification/certified-solutions-architect-associate/", kind: "doc" },
  ],
  quiz: [
    {
      id: "well-architected-pillar-mapping",
      question: "Review kiến trúc phát hiện: security group mở SSH cho 0.0.0.0/0. Đây là rủi ro thuộc trụ cột nào của Well-Architected?",
      options: ["Cost Optimization", "Performance Efficiency", "Security", "Sustainability"],
      answerIndex: 2,
      explanation: "Mở cổng quản trị cho toàn Internet là lỗ hổng bảo mật — vi phạm nguyên tắc phòng thủ nhiều lớp và least privilege của trụ cột Security.",
    },
    {
      id: "ha-vs-fault-tolerant",
      question: "ASG có min=1, max=3, khi instance duy nhất crash thì ASG mất khoảng 3 phút để khởi động instance mới, app gián đoạn trong lúc đó. Đây là ví dụ của điều gì?",
      options: [
        "Fault tolerance hoàn chỉnh",
        "High availability (tự phục hồi nhưng có gián đoạn ngắn), không phải fault tolerant",
        "Disaster recovery",
        "Multi-site active-active",
      ],
      answerIndex: 1,
      explanation: "Fault tolerant nghĩa là không ai nhận ra có lỗi (cần ≥ 2 instance chạy song song). Ở đây có gián đoạn 3 phút trước khi phục hồi — đó là HA (tự phục hồi), chưa phải fault tolerant.",
    },
    {
      id: "rto-rpo-definition",
      question: "Business đặt ra: 'Downtime tối đa 30 phút, chấp nhận mất dữ liệu tối đa 5 phút gần nhất.' Đây tương ứng với cặp giá trị nào?",
      options: ["RPO=30 phút, RTO=5 phút", "RTO=30 phút, RPO=5 phút", "SLA=30 phút, không có RPO", "RTO=RPO=35 phút"],
      answerIndex: 1,
      explanation: "'Downtime tối đa' đo thời gian phục hồi dịch vụ = RTO. 'Mất dữ liệu tối đa' đo khoảng dữ liệu có thể mất = RPO. RTO=30, RPO=5.",
    },
    {
      id: "dr-strategy-budget-constrained",
      question: "Team nhỏ, ngân sách hạn chế, app nội bộ ít quan trọng, chấp nhận downtime vài giờ nếu region chính gặp sự cố lớn. Chiến lược DR phù hợp nhất?",
      options: ["Multi-site active-active", "Warm standby", "Pilot light", "Backup & Restore"],
      answerIndex: 3,
      explanation: "Với RTO chấp nhận vài giờ và ngân sách hạn chế, Backup & Restore (rẻ nhất, không chạy gì sẵn ở region DR) là đủ. Các chiến lược khác tốn thêm chi phí chạy sẵn ở region thứ hai không cần thiết.",
    },
    {
      id: "dr-strategy-fast-rto",
      question: "Sàn giao dịch cần RTO gần như bằng 0 khi 1 region gặp sự cố, chấp nhận chi phí cao để đạt được điều đó. Chiến lược nào đáp ứng?",
      options: ["Backup & Restore", "Pilot light", "Multi-site active-active", "Chỉ cần Multi-AZ trong 1 region"],
      answerIndex: 2,
      explanation: "Multi-AZ chỉ bảo vệ trong 1 region, không chống được sự cố cả region. RTO gần 0 khi mất cả region cần multi-site active-active — cả 2 region cùng phục vụ traffic thật song song.",
    },
    {
      id: "read-replica-not-dr",
      question: "Team tin rằng 'đã có RDS read replica ở region khác nên không cần lo DR nữa'. Nhận định này thiếu sót gì?",
      options: [
        "Không thiếu gì, read replica đã đủ cho mọi tình huống DR",
        "Read replica chỉ đồng bộ dữ liệu; cần có runbook promote thủ công + kế hoạch chuyển traffic (DNS, app config) mới thực sự là DR hoàn chỉnh",
        "Read replica tự động trở thành primary khi cần",
        "Read replica không hoạt động được ở region khác",
      ],
      answerIndex: 1,
      explanation: "Read replica cross-region là một phần của pilot light/warm standby, nhưng chưa phải DR đầy đủ — vẫn cần quy trình promote thủ công, chuyển đổi routing/config, và (quan trọng) đã được test thật.",
    },
    {
      id: "right-sizing-evidence",
      question: "Trước khi đổi EC2 từ m5.2xlarge xuống t4g.large để tiết kiệm chi phí, bước nào nên làm trước?",
      options: [
        "Đổi ngay, xem sao rồi tính tiếp",
        "Đo CPU/RAM thực tế qua CloudWatch (kèm CloudWatch Agent nếu cần RAM) trong ít nhất 1–2 tuần bao gồm giờ cao điểm",
        "Chỉ cần hỏi ý kiến đồng nghiệp",
        "Mua Reserved Instance cho instance mới trước khi đổi",
      ],
      answerIndex: 1,
      explanation: "Right-sizing dựa trên dữ liệu tải thật, không phải đoán. Đo đủ lâu (bao gồm giờ cao điểm) trước khi hạ cấp, tránh downgrade rồi mới phát hiện thiếu tài nguyên lúc tải cao.",
    },
    {
      id: "spot-instance-suitability",
      question: "Đâu là khối lượng công việc PHÙ HỢP NHẤT để chạy trên Spot Instances?",
      options: [
        "RDS primary database đang phục vụ giao dịch thanh toán",
        "Worker xử lý message từ SQS, có thể retry khi bị ngắt",
        "EC2 chạy bastion host duy nhất cho SSH",
        "ASG chính phục vụ traffic web thời gian thực không chịu được gián đoạn",
      ],
      answerIndex: 1,
      explanation: "Spot có thể bị AWS thu hồi bất cứ lúc nào (cảnh báo ngắn ~2 phút). Worker đọc từ SQS là stateless và chịu được retry — nếu bị ngắt, message quay lại queue và job khác xử lý tiếp.",
    },
    {
      id: "tagging-cost-explorer-benefit",
      question: "Lợi ích chính của việc gắn tag project/env/owner nhất quán cho mọi resource là gì?",
      options: [
        "Giúp resource chạy nhanh hơn",
        "Tự động giảm giá AWS",
        "Cho phép lọc và phân bổ chi phí theo dự án/môi trường/người sở hữu trên Cost Explorer",
        "Bắt buộc để bật Multi-AZ",
      ],
      answerIndex: 2,
      explanation: "Tag (sau khi kích hoạt làm cost allocation tag) là cách chính để trả lời 'ai/dự án nào đang tốn tiền' trên Cost Explorer — không ảnh hưởng hiệu năng hay giá dịch vụ.",
    },
    {
      id: "cloudwatch-alarm-evaluation-periods",
      question: "Alarm CPU > 80% với evaluation-periods=1 (chỉ 1 chu kỳ) hay báo động giả do một đợt tăng CPU thoáng qua vài giây. Cách sửa hợp lý?",
      options: [
        "Xoá alarm vì CloudWatch không đáng tin",
        "Tăng evaluation-periods lên vài chu kỳ liên tiếp (vd 3) để lọc nhiễu ngắn hạn",
        "Hạ threshold xuống 50%",
        "Chuyển sang theo dõi bằng mắt thường thay vì alarm",
      ],
      answerIndex: 1,
      explanation: "Yêu cầu vượt ngưỡng qua NHIỀU chu kỳ liên tiếp (không chỉ 1) giúp alarm chỉ báo khi vấn đề thực sự kéo dài, giảm báo động giả và alert fatigue.",
    },
    {
      id: "insufficient-data-alarm-state",
      question: "Một CloudWatch alarm hiển thị trạng thái INSUFFICIENT_DATA. Điều này có nghĩa gì?",
      options: [
        "Metric đang vượt ngưỡng nghiêm trọng",
        "Alarm đang ở trạng thái bình thường, không có vấn đề gì",
        "Chưa có đủ datapoint để so sánh với ngưỡng — thường do resource mới tạo, đã dừng, hoặc metric chưa đủ chu kỳ dữ liệu",
        "Alarm đã bị xoá",
      ],
      answerIndex: 2,
      explanation: "INSUFFICIENT_DATA khác với OK và ALARM — nó nghĩa là CloudWatch chưa có đủ dữ liệu để đánh giá, không phải là một khẳng định về tình trạng tốt hay xấu của hệ thống.",
    },
  ],
};
