import type { MDXContent } from "mdx/types";

type LessonLoader = (lessonSlug: string) => Promise<{ default: MDXContent }>;

/**
 * One loader per registered module. Each import template is scoped to a single module folder,
 * so the bundler only compiles MDX of registered modules — a half-written module elsewhere
 * cannot break the build. Keep in sync with `curriculum-registry.ts`.
 */
export const lessonContentLoaders: Record<string, LessonLoader> = {
  "m01-linux-shell": (lessonSlug) => import(`./modules/m01-linux-shell/lessons/${lessonSlug}.mdx`),
  "m02-networking": (lessonSlug) => import(`./modules/m02-networking/lessons/${lessonSlug}.mdx`),
  "m03-devops-mindset-git": (lessonSlug) => import(`./modules/m03-devops-mindset-git/lessons/${lessonSlug}.mdx`),
  "m04-docker-containers": (lessonSlug) => import(`./modules/m04-docker-containers/lessons/${lessonSlug}.mdx`),
  "m05-cicd-github-actions": (lessonSlug) => import(`./modules/m05-cicd-github-actions/lessons/${lessonSlug}.mdx`),
  "m06-aws-core-iam": (lessonSlug) => import(`./modules/m06-aws-core-iam/lessons/${lessonSlug}.mdx`),
  "m07-aws-networking-compute": (lessonSlug) => import(`./modules/m07-aws-networking-compute/lessons/${lessonSlug}.mdx`),
  "m08-aws-storage-database-serverless": (lessonSlug) => import(`./modules/m08-aws-storage-database-serverless/lessons/${lessonSlug}.mdx`),
  "m10-terraform": (lessonSlug) => import(`./modules/m10-terraform/lessons/${lessonSlug}.mdx`),
  "m12-kubernetes-core": (lessonSlug) => import(`./modules/m12-kubernetes-core/lessons/${lessonSlug}.mdx`),
  "m15-observability": (lessonSlug) => import(`./modules/m15-observability/lessons/${lessonSlug}.mdx`),
  "m09-aws-well-architected-cost": (lessonSlug) => import(`./modules/m09-aws-well-architected-cost/lessons/${lessonSlug}.mdx`),
  "m11-ansible-packer": (lessonSlug) => import(`./modules/m11-ansible-packer/lessons/${lessonSlug}.mdx`),
  "m13-kubernetes-production-eks": (lessonSlug) => import(`./modules/m13-kubernetes-production-eks/lessons/${lessonSlug}.mdx`),
  "m14-gitops-argocd": (lessonSlug) => import(`./modules/m14-gitops-argocd/lessons/${lessonSlug}.mdx`),
  "m16-sre-practices": (lessonSlug) => import(`./modules/m16-sre-practices/lessons/${lessonSlug}.mdx`),
  "m17-devsecops": (lessonSlug) => import(`./modules/m17-devsecops/lessons/${lessonSlug}.mdx`),
  "sd05-database-fundamentals": (lessonSlug) => import(`./modules/sd05-database-fundamentals/lessons/${lessonSlug}.mdx`),
  "sd07-async-messaging": (lessonSlug) => import(`./modules/sd07-async-messaging/lessons/${lessonSlug}.mdx`),
  "sd06-scaling-databases": (lessonSlug) => import(`./modules/sd06-scaling-databases/lessons/${lessonSlug}.mdx`),
  "sd01-system-design-mindset": (lessonSlug) => import(`./modules/sd01-system-design-mindset/lessons/${lessonSlug}.mdx`),
  "sd02-networking-communication": (lessonSlug) => import(`./modules/sd02-networking-communication/lessons/${lessonSlug}.mdx`),
  "sd03-scaling-load-balancing": (lessonSlug) => import(`./modules/sd03-scaling-load-balancing/lessons/${lessonSlug}.mdx`),
  "sd04-caching-cdn": (lessonSlug) => import(`./modules/sd04-caching-cdn/lessons/${lessonSlug}.mdx`),
  "sd09-consistency-replication": (lessonSlug) => import(`./modules/sd09-consistency-replication/lessons/${lessonSlug}.mdx`),
  "sd08-storage-search": (lessonSlug) => import(`./modules/sd08-storage-search/lessons/${lessonSlug}.mdx`),
  "sd11-reliability-patterns": (lessonSlug) => import(`./modules/sd11-reliability-patterns/lessons/${lessonSlug}.mdx`),
  "sd12-microservices-api-design": (lessonSlug) => import(`./modules/sd12-microservices-api-design/lessons/${lessonSlug}.mdx`),
  "sd13-slo-capacity-multi-region": (lessonSlug) => import(`./modules/sd13-slo-capacity-multi-region/lessons/${lessonSlug}.mdx`),
  "sd10-consensus-coordination": (lessonSlug) => import(`./modules/sd10-consensus-coordination/lessons/${lessonSlug}.mdx`),
  "sd16-case-chat-presence": (lessonSlug) => import(`./modules/sd16-case-chat-presence/lessons/${lessonSlug}.mdx`),
  "sd14-case-url-shortener-rate-limiter": (lessonSlug) => import(`./modules/sd14-case-url-shortener-rate-limiter/lessons/${lessonSlug}.mdx`),
  "sd17-case-video-streaming-file-sync": (lessonSlug) => import(`./modules/sd17-case-video-streaming-file-sync/lessons/${lessonSlug}.mdx`),
  "sd15-case-news-feed-notification": (lessonSlug) => import(`./modules/sd15-case-news-feed-notification/lessons/${lessonSlug}.mdx`),
  "sd19-mock-interview-capstone": (lessonSlug) => import(`./modules/sd19-mock-interview-capstone/lessons/${lessonSlug}.mdx`),
  "sd18-case-proximity-booking-payment": (lessonSlug) => import(`./modules/sd18-case-proximity-booking-payment/lessons/${lessonSlug}.mdx`),
  "b01-nodejs-runtime-project-architecture": (lessonSlug) => import(`./modules/b01-nodejs-runtime-project-architecture/lessons/${lessonSlug}.mdx`),
  "b02-http-rest-api-fastify": (lessonSlug) => import(`./modules/b02-http-rest-api-fastify/lessons/${lessonSlug}.mdx`),
  "b05-authentication-jwt-refresh-token": (lessonSlug) => import(`./modules/b05-authentication-jwt-refresh-token/lessons/${lessonSlug}.mdx`),
  "b03-validation-error-handling-api-design": (lessonSlug) => import(`./modules/b03-validation-error-handling-api-design/lessons/${lessonSlug}.mdx`),
  "b04-database-orm-drizzle-postgresql": (lessonSlug) => import(`./modules/b04-database-orm-drizzle-postgresql/lessons/${lessonSlug}.mdx`),
  "b06-authorization-multi-tenant-rbac": (lessonSlug) => import(`./modules/b06-authorization-multi-tenant-rbac/lessons/${lessonSlug}.mdx`),
  "b08-file-upload-object-storage": (lessonSlug) => import(`./modules/b08-file-upload-object-storage/lessons/${lessonSlug}.mdx`),
  "b09-background-jobs-scheduling": (lessonSlug) => import(`./modules/b09-background-jobs-scheduling/lessons/${lessonSlug}.mdx`),
  "b07-testing-backend": (lessonSlug) => import(`./modules/b07-testing-backend/lessons/${lessonSlug}.mdx`),
};
