import type { ModuleDefinition } from "@/content/content-types";

export const m03DevopsMindsetGitModule: ModuleDefinition = {
  id: "m03",
  slug: "m03-devops-mindset-git",
  phaseId: "phase-0",
  order: 3,
  weeks: "Tuần 4",
  title: "DevOps mindset & Git workflow",
  emoji: "♾️",
  eli5Summary:
    "DevOps giống một nhà hàng nơi bếp và phục vụ là một đội: ra món mới từng phần nhỏ, nếm thử tự động trước khi bưng, và cùng nghe phản hồi của khách. Module này dạy cách nghĩ đó, cùng quy trình Git giúp mọi thay đổi đi vào 'bản chính' an toàn — và dựng app mẫu bạn dùng suốt khoá học.",
  objectives: [
    "Giải thích DevOps qua CALMS, Three Ways, vòng đời Plan → Monitor và đo bằng DORA metrics",
    "Thiết kế app theo The Twelve-Factor App: config qua env, stateless, log ra stdout, graceful shutdown",
    "So sánh trunk-based development với GitFlow và dùng feature flag để tách deploy khỏi release",
    "Vận hành quy trình PR với branch protection, CODEOWNERS, pre-commit hooks, Conventional Commits và semantic versioning",
    "Phân biệt DevOps, SRE và Platform Engineering; tính SLO và error budget",
  ],
  lessons: [
    { slug: "devops-culture-calms-dora", title: "DevOps là gì: CALMS & DORA metrics", minutes: 40, summary: "Bếp và phục vụ cùng một đội, đo tốc độ và ổn định bằng số liệu." },
    { slug: "twelve-factor-app", title: "The Twelve-Factor App", minutes: 45, summary: "Chuẩn hoá chuỗi quán phở để mở chi nhánh ở đâu cũng chạy." },
    { slug: "branching-strategies", title: "Branching: trunk-based vs GitFlow", minutes: 40, summary: "Viết chung một cuốn sách: bản nháp ngắn, ghép liên tục." },
    { slug: "pull-request-workflow-versioning", title: "PR workflow, branch protection & semver", minutes: 50, summary: "Quy trình duyệt bài trước khi lên báo, kèm số phát hành có ý nghĩa." },
    { slug: "devops-sre-platform-engineering", title: "DevOps vs SRE vs Platform Engineering", minutes: 40, summary: "Văn hoá, đội an toàn và đội hạ tầng của hãng xe buýt; SLO & error budget." },
  ],
  labs: [
    {
      id: "sample-app-repo",
      title: "App mẫu xuyên suốt: sample-app",
      description: "Tạo repo sample-app gồm frontend + API + PostgreSQL + Redis, cấu hình theo 12-factor. App này được đóng gói, deploy và giám sát ở các module sau.",
      steps: [
        "Tạo repo `sample-app` trên GitHub với cấu trúc `frontend/` (tĩnh hoặc React), `api/` (Node/Python/Go tuỳ bạn), `README.md`, `.gitignore` (có `.env`)",
        "API đọc toàn bộ cấu hình từ env (`PORT`, `DATABASE_URL`, `REDIS_URL`, `LOG_LEVEL`), fail fast khi thiếu; commit `.env.example`, không commit `.env`",
        "Viết một tính năng nhỏ dùng PostgreSQL (vd CRUD `todos`) và cache kết quả đọc bằng Redis",
        "Thêm endpoint `/healthz` (kiểm tra DB + Redis, trả 503 khi lỗi) và chừa route `/metrics` cho M15",
        "Log dạng JSON ra stdout; bắt `SIGTERM` để tắt êm (đóng server, DB, Redis)",
        "Chạy Postgres + Redis local bằng `docker run` (hoặc compose) và unit test chạy được bằng 1 lệnh, vd `npm test` / `pytest` / `go test ./...`",
        "README ghi rõ: yêu cầu, cách chạy local, biến môi trường, cách chạy test",
      ],
    },
    {
      id: "pre-commit-conventional-commits",
      title: "Pre-commit hooks & Conventional Commits",
      description: "Chuẩn hoá chất lượng trước khi code rời máy dev.",
      steps: [
        "Thêm `.editorconfig` (charset, indent, `insert_final_newline = true`)",
        "Tạo `.pre-commit-config.yaml` với `pre-commit-hooks`, `gitleaks` và `conventional-pre-commit` (stage `commit-msg`)",
        "`pre-commit install && pre-commit install --hook-type commit-msg`, rồi `pre-commit run --all-files` và sửa hết lỗi",
        "Thử commit message sai chuẩn và một file chứa chuỗi giống AWS access key giả để thấy hook chặn",
        "Ghi quy ước commit (`feat`, `fix`, `docs`, `chore`, `!` cho breaking change) vào `CONTRIBUTING.md`",
      ],
    },
    {
      id: "branch-protection-pr-flow",
      title: "Branch protection, CODEOWNERS & quy trình PR",
      description: "Bảo vệ main để mọi thay đổi đi qua PR, CI xanh và review.",
      steps: [
        "Thêm workflow CI tối thiểu `.github/workflows/ci.yml` chạy lint + test trên `pull_request` (job tên `test`)",
        "Thêm `.github/CODEOWNERS` và `.github/pull_request_template.md`",
        "Bật branch protection hoặc ruleset cho `main`: bắt buộc PR, ≥1 approval, review từ Code Owners, status check `test`, chặn force push, áp dụng cho cả admin",
        "Thử `git push origin main` trực tiếp và xác nhận bị từ chối",
        "Mở một PR cố tình làm test fail (`gh pr create --fill`), thấy nút merge bị khoá; sửa, push lại, merge bằng `gh pr merge --squash --delete-branch`",
        "Tạo tag release đầu tiên `v0.1.0` (hoặc cấu hình release-please) và ghi changelog",
      ],
    },
    {
      id: "slo-dora-baseline",
      title: "Baseline DORA & SLO cho sample-app",
      description: "Viết một trang ngắn định nghĩa cách đo tốc độ và độ tin cậy của app — dùng lại ở M05 và M15–M16.",
      steps: [
        "Trong `docs/slo.md`, định nghĩa SLI availability (vd % request `/api/*` không trả 5xx) và SLO (vd 99,5%/30 ngày)",
        "Tính error budget theo phút và theo số request, viết error budget policy 3 mức (còn nhiều / sắp cạn / hết)",
        "Ghi cách đo 4 DORA metrics cho repo (tag release, `gh pr list --state merged --json createdAt,mergedAt`, số lần revert)",
        "Ghi số liệu baseline hiện tại (dù còn thô) để so sánh sau khi có CI/CD",
      ],
    },
  ],
  deliverable: "Repo `sample-app` (frontend + API + PostgreSQL + Redis) cấu hình qua env, có `/healthz`, unit test chạy bằng 1 lệnh, README, `.editorconfig`, pre-commit hooks, CODEOWNERS và branch protection trên `main`.",
  successCriteria: "App chạy local, test pass, repo có quy trình PR rõ ràng: không push thẳng được vào main, PR cần CI xanh và approval mới merge.",
  resources: [
    { title: "The Twelve-Factor App", url: "https://12factor.net/", kind: "doc" },
    { title: "DORA — research & four key metrics", url: "https://dora.dev/", kind: "doc" },
    { title: "Conventional Commits 1.0.0", url: "https://www.conventionalcommits.org/en/v1.0.0/", kind: "doc" },
    { title: "Semantic Versioning 2.0.0", url: "https://semver.org/", kind: "doc" },
    { title: "Trunk Based Development", url: "https://trunkbaseddevelopment.com/", kind: "doc" },
    { title: "GitHub Docs — About protected branches", url: "https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches", kind: "doc" },
    { title: "Google — Site Reliability Engineering book (đọc miễn phí)", url: "https://sre.google/sre-book/table-of-contents/", kind: "book" },
    { title: "roadmap.sh — DevOps roadmap", url: "https://roadmap.sh/devops", kind: "course" },
  ],
  quiz: [
    {
      id: "devops-definition",
      question: "Công ty đổi tên team Ops thành 'team DevOps', dev vẫn build xong gửi file zip cho team này deploy hàng tháng. Nhận định nào đúng?",
      options: [
        "Đã áp dụng DevOps vì có team mang tên DevOps",
        "Chỉ cần mua thêm công cụ CI/CD là đủ",
        "Chưa phải DevOps: bức tường giữa Dev và Ops vẫn còn, lô thay đổi lớn và phản hồi chậm",
        "DevOps chỉ áp dụng cho công ty lớn",
      ],
      answerIndex: 2,
      explanation: "Bếp vẫn 'ném món qua ô cửa' cho phục vụ, chỉ là đổi tên người đứng ô cửa. DevOps là văn hoá chung trách nhiệm, lô nhỏ và phản hồi nhanh, không phải tên phòng ban.",
    },
    {
      id: "dora-stability",
      question: "Metric DORA nào đo độ ổn định khi thay đổi lên production?",
      options: ["Change failure rate", "Deployment frequency", "Lead time for changes", "Số dòng code mỗi tuần"],
      answerIndex: 0,
      explanation: "Change failure rate (và thời gian khôi phục) thuộc nhóm stability. Deployment frequency và lead time thuộc nhóm throughput. Số dòng code không phải DORA metric.",
    },
    {
      id: "twelve-factor-config",
      question: "App cần kết nối DB khác nhau ở staging và production. Cách làm đúng theo 12-factor?",
      options: [
        "Tạo 2 nhánh Git: staging và production với URL khác nhau",
        "Đọc `DATABASE_URL` từ biến môi trường, mỗi môi trường đặt giá trị riêng",
        "Viết `if (env === 'production')` trong code",
        "Build 2 image khác nhau có URL hard-code",
      ],
      answerIndex: 1,
      explanation: "Factor III: config nằm trên 'tờ cấu hình dán ở bếp', không sửa công thức. Cùng một artifact chạy mọi môi trường, chỉ khác env.",
    },
    {
      id: "twelve-factor-sigterm",
      question: "Kubernetes gửi SIGTERM trước khi xoá pod. App nhận là chết ngay, người dùng thấy lỗi mỗi lần deploy. Cần áp dụng factor nào?",
      options: ["Factor I Codebase", "Factor II Dependencies", "Factor X Dev/prod parity", "Factor IX Disposability: bắt SIGTERM, ngừng nhận request mới, xử lý nốt rồi thoát"],
      answerIndex: 3,
      explanation: "Như quán đóng cửa phải phục vụ nốt khách đang ăn rồi mới tắt đèn. Graceful shutdown giúp deploy không làm rớt request.",
    },
    {
      id: "trunk-feature-flag",
      question: "Vì sao feature flag là mảnh ghép quan trọng của trunk-based development?",
      options: [
        "Cho phép merge code tính năng chưa hoàn thiện vào main thường xuyên mà người dùng chưa thấy",
        "Thay thế hoàn toàn cho unit test",
        "Giúp không cần code review",
        "Làm app chạy nhanh hơn",
      ],
      answerIndex: 0,
      explanation: "Như dán giấy 'chưa in' lên chương viết dở: đoạn văn đã ghép vào bản chính nhưng chưa phát hành. Deploy tách khỏi release.",
    },
    {
      id: "gitflow-fit",
      question: "Trường hợp nào GitFlow (có release/hotfix branch) hợp lý hơn trunk-based?",
      options: [
        "Web SaaS deploy nhiều lần mỗi ngày",
        "Landing page marketing",
        "Thư viện/phần mềm on-premise phải duy trì song song nhiều version đã phát hành",
        "Team muốn giảm lead time tối đa",
      ],
      answerIndex: 2,
      explanation: "Khi khách dùng nhiều 'số báo' khác nhau cùng lúc và cần vá riêng từng số, release/hotfix branch có ích. Web app deploy liên tục thì các nghi thức này làm chậm dòng chảy.",
    },
    {
      id: "required-check",
      question: "Branch protection yêu cầu approval nhưng không bắt buộc status check. Rủi ro là gì?",
      options: [
        "Không ai push được vào main",
        "PR có thể được merge dù CI đang đỏ, lỗi lọt vào main",
        "CODEOWNERS bị vô hiệu hoá",
        "Không tạo được tag release",
      ],
      answerIndex: 1,
      explanation: "Biên tập viên đã ký nhưng máy kiểm tra chính tả báo lỗi mà máy in vẫn in. Bật 'Require status checks to pass' để CI đỏ thì nút merge bị khoá.",
    },
    {
      id: "semver-breaking",
      question: "Bạn đổi tên field `user_name` thành `username` trong response API public. Commit message và version phù hợp (từ v1.8.3)?",
      options: [
        "`fix: rename field` → v1.8.4",
        "`chore: rename field` → không release",
        "`feat: rename field` → v1.9.0",
        "`feat(api)!: rename user_name to username` → v2.0.0",
      ],
      answerIndex: 3,
      explanation: "Client đang đọc `user_name` sẽ vỡ — đó là breaking change, phải đánh dấu `!` hoặc BREAKING CHANGE để tăng MAJOR và báo cho mọi người biết.",
    },
    {
      id: "precommit-not-enough",
      question: "Team đã có pre-commit hook quét secret. Vì sao vẫn nên chạy lại kiểm tra đó trong CI?",
      options: [
        "Vì hook chạy trên máy dev có thể chưa được cài hoặc bị bỏ qua bằng `--no-verify`",
        "Vì pre-commit không hỗ trợ Git",
        "Vì CI chạy nhanh hơn máy dev",
        "Không cần, chạy hai lần là lãng phí",
      ],
      answerIndex: 0,
      explanation: "Hook là máy kiểm tra ở bàn phóng viên — tiện nhưng tắt được. CI là cổng bắt buộc của toà soạn mà ai cũng phải đi qua.",
    },
    {
      id: "error-budget-decision",
      question: "SLO 99,9%/30 ngày (budget ≈ 43 phút). Hết tuần 2 mới dùng 5 phút. Product muốn release tính năng lớn. Theo SRE, quyết định hợp lý?",
      options: [
        "Cấm release cho tới cuối tháng để giữ 100%",
        "Hạ SLO xuống 99% để có thêm budget",
        "Còn nhiều error budget nên có thể release (kèm canary/rollback), chấp nhận rủi ro hợp lý",
        "Nâng SLO lên 99,99% vì đang làm tốt",
      ],
      answerIndex: 2,
      explanation: "Ngân sách được phép trễ còn gần như nguyên — đây chính là lúc nên dùng nó để đổi mới. Error budget là để tiêu hợp lý, không phải để để dành.",
    },
    {
      id: "platform-vs-sre",
      question: "Team X xây template tạo service mới có sẵn Dockerfile, pipeline CI/CD, dashboard và alert để các team sản phẩm tự dùng. Đây đặc trưng nhất cho hướng nào?",
      options: ["Platform Engineering (golden path, platform as a product)", "SRE (đặt SLO, error budget)", "GitFlow", "QA thủ công"],
      answerIndex: 0,
      explanation: "Đội xây bến bãi và làm xe mẫu: cung cấp con đường trải sẵn để developer nội bộ tự phục vụ. SRE tập trung vào mức tin cậy đo bằng SLO.",
    },
  ],
};
