import type { ModuleDefinition } from "@/content/content-types";

export const sd06ScalingDatabasesModule: ModuleDefinition = {
  id: "sd06",
  slug: "sd06-scaling-databases",
  phaseId: "sd-phase-1",
  order: 6,
  weeks: "Tuần 8",
  title: "Scale database: replication, sharding & consistent hashing",
  emoji: "🗄️",
  eli5Summary:
    "Một cuốn sổ bán hàng không đủ cho cả chuỗi cửa hàng: ta photo sổ gửi các chi nhánh để nhiều người cùng tra (replication), rồi chia sổ thành nhiều quyển theo một quy tắc để ghi song song (sharding). Cái giá là bản photo luôn tới trễ một chút, và chọn sai quy tắc chia thì một quyển bị viết kín trong khi quyển khác trống trơn.",
  objectives: [
    "Giải thích leader-follower replication qua WAL, phân biệt sync và async, đo replication lag trên Postgres",
    "Thiết kế routing đọc/ghi có xử lý read-your-writes và nói rõ dữ liệu có thể mất khi failover với async replication",
    "Tính giới hạn connection và chọn đúng chế độ PgBouncer, biết tính năng nào hỏng ở transaction pooling",
    "So sánh range, hash và directory sharding; chọn shard key theo access pattern và chỉ ra query phải scatter-gather",
    "Tự viết consistent hashing có virtual nodes và đo số key phải di chuyển so với `hash mod N`",
    "Nhận diện hot key/hot partition và chọn cách xử lý (cache, salting, tách partition) cùng chiến lược rebalancing",
  ],
  lessons: [
    { slug: "replication-and-replication-lag", title: "Replication & replication lag", minutes: 45, summary: "Primary ghi sổ WAL, replica chép lại — nhanh nhưng luôn trễ một nhịp." },
    { slug: "read-replicas-and-failover", title: "Read replica, read-your-writes & failover", minutes: 45, summary: "Chuyển đọc sang replica mà user không thấy dữ liệu cũ, và failover mà biết mình có thể mất gì." },
    { slug: "connection-pooling-pgbouncer", title: "Connection pooling với PgBouncer", minutes: 35, summary: "Hàng trăm client dùng chung vài chục connection — và những tính năng bị hỏng nếu chọn sai mode." },
    { slug: "sharding-and-shard-key", title: "Sharding & chọn shard key", minutes: 50, summary: "Range, hash, directory — shard key quyết định query nào rẻ, query nào phải hỏi mọi shard." },
    { slug: "consistent-hashing-virtual-nodes", title: "Consistent hashing & virtual nodes", minutes: 45, summary: "Thêm một node mà chỉ phải dời một phần nhỏ dữ liệu, thay vì xáo trộn gần hết." },
    { slug: "hot-keys-and-rebalancing", title: "Hot key, hot partition & rebalancing", minutes: 40, summary: "Khi một key nổi tiếng đè bẹp một shard, và cách dời dữ liệu khi hệ thống đang chạy." },
  ],
  labs: [
    {
      id: "postgres-streaming-replica",
      title: "Postgres primary + streaming replica, quan sát lag",
      description: "Thêm service `postgres-replica` vào sd-playground bằng `pg_basebackup -R`, rồi tự tay tạo và đo replication lag.",
      steps: [
        "Tạo `db/10-replication.sh` (mount vào `/docker-entrypoint-initdb.d/`): `CREATE ROLE replicator WITH REPLICATION LOGIN PASSWORD 'replicator'` và thêm `host replication replicator all scram-sha-256` vào `$PGDATA/pg_hba.conf`",
        "Script init chỉ chạy khi volume rỗng: với playground, `docker compose down -v` rồi `docker compose up -d postgres` (lệnh này xoá dữ liệu — không làm trên môi trường thật)",
        "Thêm service `postgres-replica` (`postgres:17`, `user: postgres`, port `5433:5432`) có entrypoint chạy `pg_basebackup -h postgres -U replicator -D /var/lib/postgresql/data -R -X stream -C -S replica1` khi thư mục data rỗng rồi `exec postgres`",
        "`docker compose up -d postgres-replica`; trên replica chạy `SELECT pg_is_in_recovery();` phải ra `t`",
        "Trên primary: `SELECT client_addr, state, sync_state, replay_lag FROM pg_stat_replication;` — thấy 1 dòng `streaming` / `async`",
        "Tạo lag có kiểm soát: trên replica `SELECT pg_wal_replay_pause();`, ghi 1 dòng ở primary, đọc ngay ở replica (chưa thấy), so `pg_current_wal_lsn()` với `pg_last_wal_replay_lsn()`, rồi `SELECT pg_wal_replay_resume();`",
        "Tạo tải ghi: `docker compose exec postgres pgbench -i -s 10 -U app app` rồi `pgbench -c 8 -T 60 -U app app`; ở terminal khác theo dõi `pg_wal_lsn_diff(pg_current_wal_lsn(), replay_lsn)` bằng `\\watch 1`",
      ],
    },
    {
      id: "read-your-writes-routing",
      title: "Routing đọc/ghi có read-your-writes",
      description: "App ghi vào primary, đọc từ replica, nhưng user vừa ghi thì đọc từ primary trong vài giây.",
      steps: [
        "Trong `app`, tạo 2 `pg.Pool`: `DATABASE_URL` trỏ `postgres`, `REPLICA_URL` trỏ `postgres-replica`",
        "Endpoint `PUT /users/:id/avatar` ghi vào primary rồi `SET rw:<id> 1 EX 5` trong Redis",
        "Endpoint `GET /users/:id` đọc replica, trừ khi `EXISTS rw:<id>` trả về 1 thì đọc primary",
        "Pause replay trên replica (`SELECT pg_wal_replay_pause();`), gọi `curl -X PUT` rồi `curl` GET: bật sticky thấy avatar mới, tắt sticky thấy avatar cũ",
        "Viết `k6/read-your-writes.js`: mỗi VU PUT rồi GET ngay, dùng `Rate` metric đếm tỉ lệ đọc cũ khi bật/tắt sticky; nhớ `pg_wal_replay_resume()` sau khi đo",
      ],
    },
    {
      id: "consistent-hashing-typescript",
      title: "Tự viết consistent hashing có virtual nodes",
      description: "Viết hash ring bằng TypeScript, đo % key phải di chuyển khi thêm/bớt node so với `hash mod N`.",
      steps: [
        "Tạo `ring.ts`: hàm `hash32` dùng `createHash(\"md5\")` lấy 4 byte đầu, class `HashRing` có `add`, `remove`, `get` (mảng điểm đã sort + binary search)",
        "Sinh 100.000 key `user:<i>`, gán cho 4 node bằng `hash mod N` và bằng ring (100 vnode/node)",
        "Thêm node thứ 5, đếm % key đổi node cho mỗi cách bằng `npx tsx ring.ts` — kỳ vọng cỡ 80% với `mod N`, cỡ 20% với ring",
        "Đổi số vnode 1 → 10 → 100 → 500, in số key mỗi node và tỉ lệ `max/avg` để thấy vnode làm phân bố đều hơn",
        "Xoá 1 node và kiểm chứng: chỉ các key từng thuộc node đó bị chuyển đi, key khác giữ nguyên",
      ],
    },
    {
      id: "chat-messages-shard-key",
      title: "Chọn shard key cho bảng `messages` của app chat",
      description: "Design doc ngắn theo Phụ lục A: ước lượng, access pattern, so sánh shard key và bảng trade-off.",
      steps: [
        "Ước lượng với giả định ghi rõ: 10M DAU × 40 tin/ngày ⇒ 400M tin/ngày ≈ 4.000 ghi/s trung bình (÷10⁵ s), peak 2–3×; ~1KB/tin (kèm index) ⇒ cỡ 400GB/ngày",
        "Liệt kê access pattern: gửi tin, 50 tin mới nhất của channel, cuộn lịch sử cũ, tất cả tin của 1 user, xoá 1 tin",
        "So sánh 3 shard key `created_at` (range), `hash(message_id)`, `(channel_id, bucket)`: mỗi access pattern đi 1 shard hay phải scatter-gather",
        "Chọn 1 key và viết bảng `| Quyết định | Chọn | Bỏ | Vì sao | Khi nào đổi ý |`",
        "Viết mục failure modes: channel cực lớn (hot partition), resharding từ 16 lên 32 shard, và query 'tin của user' giải quyết bằng gì (bảng index riêng, search)",
      ],
    },
  ],
  deliverable:
    "Repo sd-playground có `postgres` + `postgres-replica` chạy streaming replication kèm ghi chú đo lag, endpoint read-your-writes, `ring.ts` consistent hashing có số đo so với `mod N`, và design doc chọn shard key cho `messages`.",
  successCriteria:
    "Giải thích được vì sao shard key sai rất khó sửa, cách xử lý read-your-writes với replica, và dữ liệu nào có thể mất khi failover với async replication.",
  resources: [
    { title: "PostgreSQL docs — Log-Shipping Standby Servers (streaming replication)", url: "https://www.postgresql.org/docs/current/warm-standby.html", kind: "doc" },
    { title: "PostgreSQL docs — pg_basebackup", url: "https://www.postgresql.org/docs/current/app-pgbasebackup.html", kind: "doc" },
    { title: "PostgreSQL docs — Monitoring stats (pg_stat_replication)", url: "https://www.postgresql.org/docs/current/monitoring-stats.html", kind: "doc" },
    { title: "PgBouncer — pooling modes & SQL feature map", url: "https://www.pgbouncer.org/features.html", kind: "doc" },
    { title: "Designing Data-Intensive Applications (Kleppmann) — ch.5 Replication, ch.6 Partitioning", url: "https://dataintensive.net/", kind: "book" },
    { title: "Amazon's Dynamo (Werner Vogels, bài + paper)", url: "https://www.allthingsdistributed.com/2007/10/amazons_dynamo.html", kind: "doc" },
    { title: "Discord Engineering — How Discord Stores Billions of Messages", url: "https://discord.com/blog/how-discord-stores-billions-of-messages", kind: "doc" },
    { title: "Discord Engineering — How Discord Stores Trillions of Messages", url: "https://discord.com/blog/how-discord-stores-trillions-of-messages", kind: "doc" },
  ],
  quiz: [
    {
      id: "stale-avatar-after-update",
      question: "User đổi avatar, bấm reload thì vẫn thấy avatar cũ, vài giây sau mới đúng. App ghi vào primary và đọc từ replica (async). Nguyên nhân hợp lý nhất?",
      options: [
        "Transaction ghi avatar đã bị rollback",
        "Replica chưa replay tới đoạn WAL chứa thay đổi — replication lag gây vi phạm read-your-writes",
        "Index trên bảng users bị hỏng",
        "Primary ghi WAL chậm nên commit chưa xong",
      ],
      answerIndex: 1,
      explanation: "Giống chi nhánh chưa nhận được trang sổ photo từ quán gốc: quán gốc đã ghi xong (commit OK) nhưng bản chép ở chi nhánh còn trễ. Đọc từ replica ngay sau khi ghi là thấy dữ liệu cũ.",
    },
    {
      id: "async-failover-lost-orders",
      question: "Primary chạy async replication bị chết, hệ thống tự promote replica. Sau đó vài đơn hàng mà khách đã nhận thông báo 'đặt thành công' biến mất. Vì sao?",
      options: [
        "Promote replica luôn xoá các transaction gần nhất để an toàn",
        "Replica bị lỗi đĩa",
        "Các đơn đó đã commit trên primary nhưng WAL chưa kịp tới replica trước khi primary chết",
        "App ghi nhầm vào replica",
      ],
      answerIndex: 2,
      explanation: "Với async, quán gốc đưa hoá đơn cho khách trước khi chi nhánh chép xong trang sổ. Quán gốc cháy thì những trang chưa chép mất theo — phó quản lý lên thay chỉ có bản sổ tới trang trước đó.",
    },
    {
      id: "sync-commit-still-stale",
      question: "Bạn bật synchronous replication với `synchronous_commit = on`. Ngay sau COMMIT, đọc từ replica đó đôi khi vẫn thấy dữ liệu cũ vài ms. Giải thích đúng?",
      options: [
        "`on` chỉ đợi replica flush WAL xuống đĩa, chưa đợi replay; muốn đọc thấy ngay cần `remote_apply`",
        "Sync replication không hoạt động với Docker",
        "Replica đang dùng isolation `SERIALIZABLE`",
        "Không thể xảy ra — sync thì replica luôn thấy ngay",
      ],
      answerIndex: 0,
      explanation: "Chi nhánh xác nhận 'đã nhận và cất trang sổ vào tủ' (flush) chứ chưa chắc đã chép vào sổ đang cho khách tra (replay). `remote_apply` bắt quán gốc đợi tới lúc chép xong mới báo OK — đổi lại ghi chậm hơn.",
    },
    {
      id: "read-your-writes-fix",
      question: "Cách nào xử lý read-your-writes hợp lý cho trang profile khi đọc chủ yếu từ replica async?",
      options: [
        "Tắt hẳn replica, mọi đọc đi primary",
        "Tăng `max_connections` trên replica",
        "Retry đọc replica 3 lần liên tiếp không chờ",
        "Sau khi user ghi, đọc dữ liệu của chính user đó từ primary trong vài giây (hoặc tới khi replica replay qua LSN của lần ghi)",
      ],
      answerIndex: 3,
      explanation: "Người vừa ghi sổ thì cho tra ở quán gốc thêm một lúc; khách khác vẫn tra ở chi nhánh. Chỉ phần đọc cần tươi mới đi primary nên vẫn giữ được lợi ích scale đọc.",
    },
    {
      id: "pgbouncer-transaction-mode-set",
      question: "Sau khi chuyển PgBouncer sang `pool_mode = transaction`, app bắt đầu đọc nhầm schema: nó chạy `SET search_path TO tenant_42` khi mở connection rồi query nhiều lần. Chuyện gì xảy ra?",
      options: [
        "PgBouncer chặn mọi câu `SET` nên query lỗi cú pháp",
        "`SET` ở mức session gắn với server connection cũ; transaction sau có thể chạy trên server connection khác không có setting đó",
        "Transaction mode làm Postgres bỏ qua search_path",
        "Do `max_client_conn` quá thấp",
      ],
      answerIndex: 1,
      explanation: "Như dặn giao dịch viên ở quầy 3 'nhớ tôi thuộc chi nhánh 42', lần sau số thứ tự đưa bạn sang quầy 7 — không ai nhớ lời dặn. Dùng `SET LOCAL` trong transaction hoặc ghi schema rõ trong query.",
    },
    {
      id: "range-shard-created-at",
      question: "Bảng `messages` shard theo range `created_at` (mỗi tháng một shard). Vấn đề nào gần như chắc chắn xảy ra?",
      options: [
        "Không query được theo thời gian",
        "Mọi ghi mới dồn vào shard tháng hiện tại, các shard cũ gần như nhàn rỗi",
        "Không thể thêm shard mới",
        "Mỗi query đều phải scatter-gather",
      ],
      answerIndex: 1,
      explanation: "Giống xếp hồ sơ theo ngày nộp: mọi người nộp hôm nay đều xếp hàng trước đúng một tủ. Range theo thời gian rất tốt cho quét theo khoảng nhưng tạo hot shard cho ghi.",
    },
    {
      id: "chat-shard-key-choice",
      question: "App chat: query nóng nhất là '50 tin mới nhất của một channel'. Shard key nào phù hợp nhất?",
      options: [
        "`hash(message_id)` — phân bố đều nhất",
        "`created_at` theo tháng",
        "`(channel_id, bucket thời gian)` — tin của một channel trong một khoảng nằm cùng partition",
        "`user_id` của người gửi",
      ],
      answerIndex: 2,
      explanation: "Chia tủ hồ sơ theo 'nhóm chat + đợt' thì lấy tin mới của một nhóm chỉ mở 1 ngăn. `hash(message_id)` đều nhưng bắt hỏi mọi tủ rồi gộp lại; bucket thời gian giữ cho mỗi ngăn không phình vô hạn.",
    },
    {
      id: "mod-n-add-node",
      question: "Cache cluster 4 node dùng `hash(key) mod N`. Thêm node thứ 5. Xấp xỉ bao nhiêu key đổi node, và nếu dùng consistent hashing thì sao?",
      options: [
        "`mod N`: cỡ 20%; consistent hashing: cỡ 80%",
        "Cả hai đều cỡ 20%",
        "`mod N`: 100%; consistent hashing: 0%",
        "`mod N`: cỡ 80% (4/5); consistent hashing: cỡ 20% (1/5) trung bình",
      ],
      answerIndex: 3,
      explanation: "`mod N` như chia lại khách cho shipper theo số nhà chia số shipper — thêm một người là gần như ai cũng đổi shipper (chỉ 1/(N+1) key giữ nguyên). Trên vòng tròn, shipper mới chỉ nhận bớt khách của hàng xóm, trung bình 1/(N+1) key.",
    },
    {
      id: "virtual-nodes-purpose",
      question: "Vì sao consistent hashing trong thực tế thường dùng virtual nodes (mỗi server nhiều điểm trên ring)?",
      options: [
        "Để phân bố key đều hơn và khi một node rời đi, tải của nó rải cho nhiều node thay vì dồn hết vào một node kế bên",
        "Để mã hoá key an toàn hơn",
        "Để không cần lưu danh sách node",
        "Để tránh phải hash key",
      ],
      answerIndex: 0,
      explanation: "Mỗi shipper nhận nhiều đoạn ngắn rải khắp vòng tròn thay vì một đoạn dài: chia khách đều hơn, và khi một shipper nghỉ thì khách của họ chia cho nhiều người. Vnode cũng cho phép server mạnh nhận nhiều điểm hơn.",
    },
    {
      id: "hot-key-salting-tradeoff",
      question: "Một livestream nổi tiếng làm key `stream:999:comments` nhận 60% lượt ghi của shard 2. Bạn salting thành `stream:999:comments#0..7`. Cái giá chính là gì?",
      options: [
        "Không có cái giá nào",
        "Ghi chậm hơn 8 lần",
        "Đọc toàn bộ comment phải fan-out 8 key rồi gộp, latency đọc phụ thuộc phần chậm nhất",
        "Mất tính durability",
      ],
      answerIndex: 2,
      explanation: "Mở 8 quầy cùng bán vé cho một concert thì hàng ghi được chia nhỏ, nhưng muốn biết tổng số vé đã bán phải hỏi cả 8 quầy. Chỉ salting key thật sự nóng, và cân nhắc thêm cache cho phía đọc.",
    },
  ],
};
