import type { ModuleDefinition } from "@/content/content-types";

export const m02NetworkingModule: ModuleDefinition = {
  id: "m02",
  slug: "m02-networking",
  phaseId: "phase-0",
  order: 2,
  weeks: "Tuần 3",
  title: "Networking cho DevOps",
  emoji: "🌐",
  eli5Summary:
    "Mỗi lần bạn mở một trang web là một chuyến giao hàng: tra địa chỉ (DNS), chạy qua cổng bảo vệ (firewall), qua lễ tân (load balancer), niêm phong phong bì (HTTPS) rồi mới tới tay người nhận (app). Module này dạy bạn đọc bản đồ chuyến hàng đó và tìm ra nó kẹt ở đâu.",
  objectives: [
    "Giải thích mô hình TCP/IP, khác biệt TCP vs UDP và vai trò của port",
    "Tính CIDR, chia subnet và phân biệt private/public IP, NAT",
    "Mô tả luồng DNS resolve, các loại record và ảnh hưởng của TTL",
    "Đọc HTTP request/response, status code và giải thích TLS handshake, certificate chain",
    "Cấu hình Nginx làm reverse proxy/load balancer có HTTPS",
    "Khoanh vùng lỗi mạng bằng dig, nc, ss, curl -v, tcpdump và cấu hình firewall cơ bản",
  ],
  lessons: [
    { slug: "tcp-ip-ports", title: "TCP/IP, TCP vs UDP & port", minutes: 40, summary: "Bưu kiện nhiều lớp gửi tới đúng toà nhà (IP) và đúng căn hộ (port)." },
    { slug: "ip-cidr-subnetting", title: "IP, CIDR, subnet & NAT", minutes: 45, summary: "Chia lô khu đô thị: tên đường, số nhà, đường nội bộ và cổng bảo vệ." },
    { slug: "dns-resolution", title: "DNS: từ tên miền tới IP", minutes: 40, summary: "Tổng đài viên đi hỏi qua root, TLD, authoritative và ghi sổ tay theo TTL." },
    { slug: "http-https-tls", title: "HTTP, HTTPS & TLS", minutes: 45, summary: "Bưu thiếp vs phong bì niêm phong có con dấu công chứng." },
    { slug: "load-balancer-reverse-proxy", title: "Load balancer & reverse proxy", minutes: 45, summary: "Lễ tân L4 nhìn số bàn, lễ tân L7 đọc order để chia khách." },
    { slug: "firewall-network-debugging", title: "Firewall & debug mạng", minutes: 50, summary: "Lần theo từng chặng của shipper để biết request chết ở đâu." },
  ],
  labs: [
    {
      id: "subnet-planning",
      title: "Tính tay subnet cho VPC",
      description: "Chia 10.0.0.0/16 thành 4 subnet public + 4 subnet private, lưu lại để dựng VPC ở M07.",
      steps: [
        "Tính số bit cần mượn để có 8 subnet bằng nhau từ `10.0.0.0/16` và suy ra prefix mới",
        "Viết bảng: tên subnet, CIDR, IP đầu, IP cuối, số IP dùng được trên AWS (trừ 5)",
        "Kiểm chứng bằng `python3 -c \"import ipaddress; print(list(ipaddress.ip_network('10.0.0.0/16').subnets(new_prefix=19)))\"`",
        "Phương án 2: public `/24` nhỏ, private `/20` lớn và chừa dải trống — kiểm tra không chồng lấn bằng `ipaddress.ip_network(...).overlaps(...)`",
        "Ghi quyết định (vì sao chọn kích thước này, AZ nào dùng subnet nào) vào `docs/network-plan.md` trong repo",
      ],
    },
    {
      id: "nginx-reverse-proxy-lb",
      title: "Nginx reverse proxy cân bằng tải 2 backend",
      description: "Dựng 2 app backend trên một VM và đặt Nginx phía trước chia tải round-robin.",
      steps: [
        "Cài Nginx: `sudo apt install -y nginx` và mở firewall `sudo ufw allow 'Nginx Full'`",
        "Chạy 2 backend trên `127.0.0.1:3001` và `127.0.0.1:3002` (app nhỏ trả về tên backend, hoặc `python3 -m http.server`)",
        "Viết block `upstream` với 2 server và `location /api/` dùng `proxy_pass` kèm các header `X-Forwarded-*`",
        "`sudo nginx -t && sudo systemctl reload nginx`, rồi gọi `curl` nhiều lần để thấy round-robin",
        "Tắt một backend, gọi lại và đọc `/var/log/nginx/error.log` để thấy Nginx bỏ qua backend hỏng",
        "Xác nhận backend chỉ listen `127.0.0.1` bằng `ss -tlnp` (không lộ ra ngoài)",
      ],
    },
    {
      id: "https-letsencrypt",
      title: "Gắn domain + HTTPS bằng Let's Encrypt",
      description: "Trỏ domain về VM, xin cert bằng certbot và ép HTTP chuyển sang HTTPS.",
      steps: [
        "Tạo A record (vd `app.<domain của bạn>`) trỏ về IP public của VM; kiểm tra bằng `dig +short`",
        "Mở port 80 và 443 ở firewall/Security Group (Let's Encrypt HTTP-01 cần port 80)",
        "`sudo certbot --nginx -d app.<domain>` và chọn redirect HTTP → HTTPS",
        "Kiểm tra: `curl -I http://app.<domain>` trả `301`, `curl -v https://app.<domain>` báo `SSL certificate verify ok`",
        "Xác nhận tự gia hạn: `systemctl list-timers | grep certbot` và `sudo certbot renew --dry-run`",
      ],
    },
    {
      id: "tcpdump-http-capture",
      title: "Bắt gói tin một request HTTP",
      description: "Dùng tcpdump quan sát handshake, dữ liệu và đóng kết nối của một request thật.",
      steps: [
        "Mở terminal 1 trên server: `sudo tcpdump -i any -nn -A 'tcp port 80'`",
        "Terminal 2: `curl http://127.0.0.1/` (hoặc gọi từ máy khác qua IP)",
        "Đánh dấu trong output các gói SYN `[S]`, SYN-ACK `[S.]`, ACK `[.]`, dữ liệu `[P.]`, FIN `[F.]`",
        "Lưu capture ra file bằng `-w http.pcap` và mở bằng Wireshark để xem từng tầng header",
        "Viết giải thích từng bước từ DNS lookup tới response cho lệnh `curl https://example.com` (tiêu chí đạt của module)",
      ],
    },
  ],
  deliverable: "VM chạy Nginx reverse proxy cân bằng tải cho 2 backend, có domain + HTTPS (redirect HTTP → HTTPS), kèm bảng subnet và ghi chú tcpdump trong repo.",
  successCriteria: "Giải thích được `curl https://example.com` từ DNS lookup, TCP handshake, TLS handshake tới HTTP response; tự khoanh vùng được lỗi timeout vs refused vs 502.",
  resources: [
    { title: "Cloudflare Learning Center — DNS, TLS, load balancing", url: "https://www.cloudflare.com/learning/", kind: "doc" },
    { title: "Julia Evans — Networking! ACK! (zine)", url: "https://wizardzines.com/zines/networking/", kind: "book" },
    { title: "MDN — HTTP overview, status codes, headers", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP", kind: "doc" },
    { title: "NGINX — Reverse proxy & HTTP load balancing guide", url: "https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/", kind: "doc" },
    { title: "Certbot — hướng dẫn theo web server & OS", url: "https://certbot.eff.org/instructions", kind: "tool" },
    { title: "How DNS works (truyện tranh)", url: "https://howdns.works/", kind: "course" },
    { title: "ss(8) man page", url: "https://man7.org/linux/man-pages/man8/ss.8.html", kind: "doc" },
    { title: "tcpdump man page", url: "https://www.tcpdump.org/manpages/tcpdump.1.html", kind: "doc" },
  ],
  quiz: [
    {
      id: "tcp-vs-udp-choice",
      question: "Dịch vụ nào dưới đây mặc định dùng UDP vì ưu tiên nhanh, chấp nhận tự xử lý mất gói ở ứng dụng?",
      options: ["SSH", "Truy vấn DNS thông thường", "Kết nối PostgreSQL", "HTTP/1.1"],
      answerIndex: 1,
      explanation: "DNS thường gửi một câu hỏi ngắn qua UDP 53 — như ném tờ rơi, mất thì client tự hỏi lại. SSH, Postgres, HTTP/1.1 cần kết nối tin cậy nên dùng TCP.",
      recallPrompt: "Vì sao DNS, streaming và game online thường dùng UDP thay vì TCP?",
    },
    {
      id: "bind-address",
      question: "Container Node.js log `listening on 127.0.0.1:3000`. Bạn đã map `-p 3000:3000` nhưng gọi từ host bị lỗi. Sửa thế nào?",
      options: ["Đổi sang port 443", "Mở thêm rule ufw cho port 3000", "Thêm A record cho container", "Cho app listen `0.0.0.0` bên trong container"],
      answerIndex: 3,
      explanation: "127.0.0.1 trong container là 'cửa trong nhà' của chính container. Traffic được forward vào interface của container nên app phải nghe 0.0.0.0 mới nhận được khách.",
    },
    {
      id: "cidr-size",
      question: "Team cần subnet AWS chứa khoảng 1.000 IP cho pod Kubernetes. Prefix nhỏ nhất (ít IP nhất) vẫn đủ là?",
      options: ["/22", "/23", "/24", "/21"],
      answerIndex: 0,
      explanation: "/22 = 1.024 địa chỉ, trừ 5 IP AWS giữ lại còn 1.019 — vừa đủ. /23 chỉ có 512. Mỗi lần prefix giảm 1, khu phố rộng gấp đôi.",
    },
    {
      id: "nat-direction",
      question: "EC2 trong private subnet đi qua NAT Gateway. Điều nào đúng?",
      options: [
        "Người ngoài Internet SSH thẳng được vào EC2 qua IP của NAT",
        "EC2 chủ động tải package từ Internet được, nhưng Internet không tự mở kết nối vào EC2 được",
        "EC2 nhận IP public riêng",
        "NAT Gateway thay thế cho Security Group",
      ],
      answerIndex: 1,
      explanation: "NAT như cổng bảo vệ khu đô thị: cư dân đi ra được, người ngoài chỉ thấy địa chỉ cổng và không tự vào được căn nhà nào.",
    },
    {
      id: "dns-ttl-migration",
      question: "Tuần sau bạn chuyển app sang load balancer mới. Record hiện có TTL 3600. Làm gì trước để giảm thời gian người dùng còn vào hệ thống cũ?",
      options: [
        "Hạ TTL xuống 60 từ trước ít nhất 1 giờ, rồi mới đổi record",
        "Xoá record rồi tạo lại",
        "Đổi record và tắt server cũ ngay",
        "Tăng TTL lên 86400 để DNS ổn định",
      ],
      answerIndex: 0,
      explanation: "Sổ tay của resolver được giữ tới 3600 giây. Hạ TTL trước (và chờ hết TTL cũ) thì khi đổi, mọi người cập nhật trong khoảng 1 phút.",
    },
    {
      id: "dig-vs-hosts",
      question: "`dig app.internal` ra `10.0.2.9` nhưng `curl http://app.internal` lại vào `127.0.0.1`. Nguyên nhân khả dĩ nhất?",
      options: ["Resolver bị lỗi cache", "Có dòng cho app.internal trong `/etc/hosts`", "curl không dùng DNS", "TTL đã hết hạn"],
      answerIndex: 1,
      explanation: "dig hỏi thẳng DNS và bỏ qua /etc/hosts; còn curl đi qua NSS nên đọc /etc/hosts trước. Dùng `getent hosts app.internal` để thấy đúng thứ ứng dụng thấy.",
    },
    {
      id: "tls-chain",
      question: "Trình duyệt vào HTTPS bình thường, nhưng một service Python gọi API báo `unable to get local issuer certificate`. Nghi ngờ đầu tiên?",
      options: ["Server chưa mở port 443", "DNS trỏ sai", "Server chỉ gửi leaf cert, thiếu intermediate (không dùng fullchain)", "Python không hỗ trợ TLS 1.3"],
      answerIndex: 2,
      explanation: "Con dấu công chứng phải nối liền: leaf ← intermediate ← root. Trình duyệt hay tự bù intermediate, còn client khác thì không. Cấu hình fullchain.pem.",
    },
    {
      id: "l4-vs-l7",
      question: "Bạn cần load balancer cho một cụm PostgreSQL read replica (giao thức TCP riêng, không phải HTTP). Chọn loại nào hợp lý?",
      options: ["L7 load balancer route theo path", "Forward proxy", "CDN", "L4 load balancer (vd NLB/HAProxy mode tcp)"],
      answerIndex: 3,
      explanation: "Lễ tân L7 chỉ đọc được 'order' HTTP. Postgres không nói HTTP nên cần lễ tân L4 chia theo IP:port.",
    },
    {
      id: "timeout-vs-refused",
      question: "`nc -vz 10.0.1.25 5432` báo lỗi ngay trong vài mili-giây: `Connection refused`. Điều nào đúng nhất?",
      options: [
        "Gói đã tới máy, nhưng không có process nào listen port 5432 (hoặc bị REJECT)",
        "Security Group đang DROP gói tin",
        "DNS không phân giải được",
        "Sai subnet mask",
      ],
      answerIndex: 0,
      explanation: "Refused = có người trả lời 'không ai ở nhà' (RST). DROP thì bác bảo vệ im lặng → bạn sẽ chờ tới timeout. Gọi bằng IP nên không liên quan DNS.",
    },
    {
      id: "502-meaning",
      question: "Sau khi deploy, Nginx trả `502 Bad Gateway`. Bước kiểm tra hợp lý đầu tiên?",
      options: ["Gia hạn certificate", "Xem `/var/log/nginx/error.log` và trạng thái app upstream (`systemctl status`, `ss -tlnp`)", "Đổi A record", "Mở thêm port 80 trên firewall"],
      answerIndex: 1,
      explanation: "502 nghĩa là khách đã tới lễ tân Nginx, nhưng lễ tân gọi vào bếp (upstream) không được. Log lỗi của Nginx sẽ nói rõ upstream nào và lỗi gì.",
    },
    {
      id: "docker-ufw",
      question: "Bạn `ufw deny 6379` nhưng Redis chạy bằng `docker run -p 6379:6379` vẫn bị quét thấy từ Internet. Vì sao?",
      options: [
        "ufw chỉ chặn UDP",
        "Redis tự mở firewall",
        "Docker chèn rule iptables riêng cho port publish, đi vòng qua rule của ufw",
        "Port dưới 10000 không chặn được",
      ],
      answerIndex: 2,
      explanation: "Docker mở 'cửa hông' không đi qua bàn bác bảo vệ ufw. Publish vào 127.0.0.1 hoặc chặn ở Security Group bên ngoài.",
    },
  ],
};
