import type { ModuleDefinition } from "@/content/content-types";

export const sd03ScalingLoadBalancingModule: ModuleDefinition = {
  id: "sd03",
  slug: "sd03-scaling-load-balancing",
  phaseId: "sd-phase-1",
  order: 3,
  weeks: "Tuần 4",
  title: "Scaling & load balancing",
  emoji: "⚖️",
  eli5Summary:
    "Quán phở đông khách thì có hai cách: mua nồi to hơn cho một đầu bếp, hoặc mở thêm quầy và thuê người đứng cửa dẫn khách tới quầy đang rảnh. Module này dạy bạn mở thêm quầy đúng cách: người dẫn khách chọn quầy ra sao, làm gì khi một quầy đóng cửa, và vì sao sổ order phải để chung chứ không nằm trong đầu từng đầu bếp.",
  objectives: [
    "So sánh vertical và horizontal scaling, biến một app có state thành stateless (session ra Redis)",
    "Phân biệt load balancer L4 và L7, reverse proxy và API gateway; chọn loại phù hợp tình huống",
    "Chọn thuật toán cân bằng tải (round robin, least connections, weighted, IP hash) dựa trên đặc điểm request",
    "Cấu hình passive health check, retry sang instance khác và connection draining trên Nginx",
    "Đọc số đo k6 để chỉ ra bottleneck tiếp theo sau khi scale app (CPU app hay connection DB)",
  ],
  lessons: [
    { slug: "vertical-horizontal-stateless", title: "Vertical vs horizontal scaling & app stateless", minutes: 40, summary: "Nồi to hơn hay thêm quầy? Và vì sao sổ order phải để chung." },
    { slug: "load-balancer-l4-l7", title: "Load balancer L4/L7, reverse proxy & API gateway", minutes: 40, summary: "Người dẫn khách chỉ nhìn số bàn, hay đọc cả tờ order rồi mới dẫn?" },
    { slug: "load-balancing-algorithms", title: "Thuật toán cân bằng tải", minutes: 35, summary: "Round robin, least_conn, weighted, IP hash — mỗi cách chia khách hợp với loại quán nào." },
    { slug: "health-check-failover", title: "Health check, failover & connection draining", minutes: 45, summary: "Quầy đóng cửa thì dẫn khách đi đâu, và cho quầy nghỉ mà không đuổi khách đang ăn." },
    { slug: "autoscaling-next-bottleneck", title: "Autoscaling & bottleneck tiếp theo", minutes: 35, summary: "Thêm quầy tự động theo lượng khách — cho tới khi bếp chung (database) quá tải." },
  ],
  labs: [
    {
      id: "nginx-round-robin-vs-least-conn",
      title: "3 instance sau Nginx: round robin → least_conn",
      description: "Scale service `app` lên 3 replica sau Nginx, đo throughput và p95 bằng k6 với hai thuật toán cân bằng tải.",
      steps: [
        "Trong `compose.yaml` của `sd-playground`, bỏ `ports` và `container_name` của service `app` (chỉ giữ `expose: [\"3000\"]`) để scale được nhiều replica",
        "Viết `nginx/default.conf` với `upstream app_backend { server app:3000; }` và thêm `add_header X-Upstream $upstream_addr always;` để thấy instance nào trả lời",
        "Chạy `docker compose up -d --scale app=3` rồi `docker compose exec nginx nginx -s reload` (Nginx chỉ resolve tên `app` lúc nạp cấu hình)",
        "Gọi `curl -s -D - -o /dev/null localhost:8080/api/work` vài lần, xác nhận `X-Upstream` xoay vòng qua 3 IP",
        "Chạy `k6 run k6/lb-test.js` với stages 50 → 500 VU trên endpoint `/api/slow` (5% request đốt CPU 300ms); ghi `http_reqs/s`, p95, `http_req_failed`",
        "Thêm `least_conn;` vào block `upstream`, reload Nginx, chạy lại k6 và điền bảng so sánh round robin vs least_conn (kèm cấu hình máy và số CPU của Docker VM)",
      ],
    },
    {
      id: "kill-instance-passive-health-check",
      title: "Kill một instance giữa lúc chạy k6",
      description: "Quan sát lỗi khi một instance chết, rồi dùng passive health check và retry của Nginx để giảm lỗi 5xx.",
      steps: [
        "Bản 'ngây thơ': trong `upstream` đặt `server app:3000 max_fails=0;`, trong `location` đặt `proxy_next_upstream off;` và `proxy_connect_timeout 1s;`, reload Nginx",
        "Chạy `k6 run k6/lb-test.js` ở 200 VU; sau 30 giây chạy `docker compose ps` rồi `docker kill <tên-container-app-2>`",
        "Ghi lại `http_req_failed` và p95 trong summary k6; xem `docker compose logs nginx | grep -c 'upstream'` để đếm lỗi upstream",
        "Bản cải thiện: `server app:3000 max_fails=3 fail_timeout=10s;` + `proxy_next_upstream error timeout http_502 http_503;` + `proxy_next_upstream_tries 2;`, reload và lặp lại kịch bản kill",
        "Viết 3–5 câu so sánh trước/sau; giải thích vì sao request `POST` không được retry mặc định (non-idempotent)",
      ],
    },
    {
      id: "session-in-redis",
      title: "Chuyển session in-memory sang Redis",
      description: "Chứng minh app stateless: user không bị đăng xuất khi request rơi vào instance khác hoặc khi một instance restart.",
      steps: [
        "Viết `/login` và `/me` lưu session trong một `Map` trong RAM; login bằng `curl -c jar.txt -X POST localhost:8080/login`, rồi gọi `curl -b jar.txt localhost:8080/me` 6 lần — ghi lại số lần nhận `401`",
        "Đổi sang lưu `sess:<id>` trong Redis với `redis.set(key, value, { EX: 1800 })`; rebuild bằng `docker compose up -d --build --scale app=3`",
        "Lặp lại 6 lần `curl -b jar.txt localhost:8080/me` — tất cả phải trả `200` dù `servedBy` khác nhau",
        "Kiểm tra session trong Redis: `docker compose exec redis redis-cli --scan --pattern 'sess:*'` và `redis-cli TTL sess:<id>`",
        "Restart toàn bộ app bằng `docker compose restart app` và xác nhận `/me` vẫn trả `200`",
      ],
    },
    {
      id: "find-next-bottleneck-design-note",
      title: "Tìm bottleneck tiếp theo & ghi chú thiết kế",
      description: "Scale app lên nhiều replica cho tới khi throughput ngừng tăng, chỉ ra thành phần nghẽn và viết design doc ngắn.",
      steps: [
        "Thêm endpoint `/api/orders` có query Postgres; mỗi instance dùng `pg.Pool` với `max: 10`",
        "Chạy k6 với `--scale app=1`, `2`, `4`, `6`; mỗi lần ghi throughput, p95 và `docker stats --no-stream` (CPU từng container)",
        "Trong lúc chạy tải, đếm connection: `docker compose exec postgres psql -U postgres -c \"SELECT count(*) FROM pg_stat_activity;\"` và so với `SHOW max_connections;`",
        "Vẽ bảng số instance → throughput; đánh dấu điểm throughput ngừng tăng và nguyên nhân (CPU app, CPU Postgres, hết connection, hay giới hạn CPU của Docker VM)",
        "Viết design doc 1 trang theo template Phụ lục A cho 'API đặt hàng chịu 5.000 RPS đỉnh': ước lượng số instance, số connection DB, bảng trade-off (sticky session vs Redis, L4 vs L7)",
      ],
    },
  ],
  deliverable: "Repo `sd-playground` có app stateless chạy 3+ replica sau Nginx (session trong Redis), cấu hình upstream có health check thụ động, cùng báo cáo k6 so sánh round robin/least_conn, kịch bản kill instance và bottleneck tiếp theo.",
  successCriteria: "Chỉ ra được bottleneck tiếp theo từ số đo k6 (CPU app hay connection DB) và giải thích được Nginx làm gì khi một instance chết giữa chừng.",
  resources: [
    { title: "NGINX docs — HTTP Load Balancing", url: "https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/", kind: "doc" },
    { title: "nginx — ngx_http_upstream_module (least_conn, max_fails, fail_timeout)", url: "https://nginx.org/en/docs/http/ngx_http_upstream_module.html", kind: "doc" },
    { title: "nginx — ngx_http_proxy_module (proxy_next_upstream)", url: "https://nginx.org/en/docs/http/ngx_http_proxy_module.html", kind: "doc" },
    { title: "AWS Elastic Load Balancing documentation", url: "https://docs.aws.amazon.com/elasticloadbalancing/", kind: "doc" },
    { title: "AWS Builders' Library — Implementing health checks", url: "https://aws.amazon.com/builders-library/implementing-health-checks/", kind: "doc" },
    { title: "Grafana k6 documentation", url: "https://grafana.com/docs/k6/latest/", kind: "tool" },
    { title: "The System Design Primer (donnemartin)", url: "https://github.com/donnemartin/system-design-primer", kind: "book" },
  ],
  quiz: [
    {
      id: "stateless-session",
      question: "App đang lưu session trong RAM của từng instance. Bạn scale từ 1 lên 3 instance sau load balancer round robin và user than bị đăng xuất liên tục. Cách sửa bền vững nhất là gì?",
      options: [
        "Tăng RAM cho mỗi instance",
        "Đưa session ra một store dùng chung như Redis để instance nào cũng đọc được",
        "Giảm về 1 instance cho chắc",
        "Đổi thuật toán sang least_conn",
      ],
      answerIndex: 1,
      explanation: "Sổ order phải để chung, không nằm trong đầu từng đầu bếp. Khi session ở Redis, mọi instance đều 'đọc được sổ' nên LB có thể gửi request tới bất kỳ đâu. least_conn không giải quyết việc session nằm sai chỗ.",
    },
    {
      id: "sticky-session-tradeoff",
      question: "Team đề xuất bật sticky session (cookie affinity) thay vì sửa code để app stateless. Rủi ro lớn nhất là gì?",
      options: [
        "Khi instance đó chết hoặc bị scale-in, user mất session; tải cũng dễ dồn lệch vào vài instance",
        "Sticky session làm TLS không hoạt động",
        "Sticky session bắt buộc phải dùng load balancer L4",
        "Không có rủi ro nào, sticky session luôn tốt hơn",
      ],
      answerIndex: 0,
      explanation: "Sticky giống việc khách luôn quay lại đúng một đầu bếp nhớ order trong đầu — đầu bếp nghỉ là order mất, và quầy có nhiều khách quen bị quá tải. Sticky là giải pháp tạm, không thay được stateless.",
    },
    {
      id: "l7-path-routing",
      question: "Bạn cần gửi `/api/*` tới pool app và `/static/*` tới pool khác, đồng thời thêm header `X-Request-Id`. Loại load balancer nào phù hợp?",
      options: ["L4 (TCP) load balancer", "DNS round robin", "L7 (HTTP) load balancer / reverse proxy", "Chỉ cần tăng số instance"],
      answerIndex: 2,
      explanation: "Người dẫn khách L7 đọc cả tờ order (path, header) nên dẫn đúng quầy theo món. L4 chỉ nhìn 'số bàn' (IP:port), không thấy path HTTP.",
    },
    {
      id: "l4-when",
      question: "Hệ thống game dùng giao thức TCP riêng (không phải HTTP), cần throughput rất cao và độ trễ thêm tối thiểu. Lựa chọn hợp lý là gì?",
      options: [
        "API gateway có xác thực JWT",
        "L4 load balancer (ví dụ AWS NLB hoặc Nginx `stream`)",
        "L7 load balancer định tuyến theo path",
        "CDN",
      ],
      answerIndex: 1,
      explanation: "L4 chỉ chuyển tiếp kết nối theo IP:port — không cần hiểu 'nội dung order' nên nhẹ và hợp với giao thức không phải HTTP. Đổi lại, không định tuyến theo path/header được.",
    },
    {
      id: "round-robin-uneven",
      question: "Endpoint export báo cáo có request mất 5 giây, xen lẫn request 20ms. Với round robin, một instance bị dồn nhiều request chậm và p95 tăng vọt. Nên đổi sang gì trước tiên?",
      options: ["least_conn", "ip_hash", "Tăng `fail_timeout`", "Tắt keepalive"],
      answerIndex: 0,
      explanation: "Round robin chia lượt đều như phát số thứ tự, bất kể quầy đó đang có bao nhiêu khách ngồi ăn lâu. least_conn dẫn khách tới quầy đang ít khách nhất nên hợp với request có thời lượng chênh lệch.",
    },
    {
      id: "weighted",
      question: "Pool có 2 máy 8 vCPU và 1 máy 2 vCPU (đang chờ thay). Cấu hình Nginx nào hợp lý?",
      options: [
        "Cho cả 3 `weight=1`",
        "Dùng `ip_hash` để chia đều",
        "Đánh dấu máy 2 vCPU là `backup`",
        "Máy 8 vCPU `weight=4`, máy 2 vCPU `weight=1`",
      ],
      answerIndex: 3,
      explanation: "Quầy to có 4 đầu bếp thì nhận nhiều khách hơn quầy 1 đầu bếp — weight theo năng lực. `backup` chỉ nhận tải khi mọi server chính chết nên lãng phí máy nhỏ.",
    },
    {
      id: "passive-health-check",
      question: "Với Nginx open source, `server app:3000 max_fails=3 fail_timeout=10s;` nghĩa là gì?",
      options: [
        "Nếu có 3 lần lỗi trong vòng 10 giây, server bị coi là không khả dụng trong 10 giây",
        "Nginx gửi request `/health` mỗi 3 giây, lỗi 10 lần thì loại server",
        "Server được retry tối đa 3 lần, mỗi lần chờ 10 giây",
        "Server được khởi động lại sau 10 giây",
      ],
      answerIndex: 0,
      explanation: "Đây là passive health check: người dẫn khách không đi kiểm tra quầy, mà đếm số khách bị quầy từ chối thật. 3 lần hỏng trong 10 giây thì tạm không dẫn khách tới quầy đó 10 giây. Active health check (`health_check`) là tính năng của NGINX Plus.",
    },
    {
      id: "deep-health-check",
      question: "Endpoint `/health` của mọi instance đều kiểm tra kết nối Postgres. Postgres chập chờn 20 giây. Chuyện gì dễ xảy ra nhất?",
      options: [
        "Không có gì, health check chỉ ảnh hưởng một instance",
        "Postgres tự phục hồi nhanh hơn",
        "Load balancer loại TẤT CẢ instance cùng lúc, toàn bộ hệ thống trả lỗi kể cả các endpoint không cần DB",
        "Chỉ request ghi bị lỗi",
      ],
      answerIndex: 2,
      explanation: "Nếu quầy nào cũng tự báo 'nghỉ' khi bếp chung trục trặc, người dẫn khách đóng cửa cả quán. Health check cho LB nên phản ánh sức khoẻ của chính instance; phụ thuộc dùng chung cần xử lý bằng timeout/degrade.",
    },
    {
      id: "connection-draining",
      question: "Khi deploy, container app nhận SIGTERM. Cách tắt đúng để không làm hỏng request đang chạy là gì?",
      options: [
        "Thoát ngay lập tức với `process.exit(0)`",
        "Gửi SIGKILL cho nhanh",
        "Tăng `max_fails` lên 100",
        "Ngừng nhận request mới, để LB ngừng gửi tới, hoàn tất request đang chạy rồi mới thoát",
      ],
      answerIndex: 3,
      explanation: "Connection draining giống quầy treo biển 'không nhận khách mới' nhưng vẫn phục vụ nốt khách đang ăn. Trên AWS là deregistration delay; trong Node là `fastify.close()` sau khi nhận SIGTERM, trong thời gian `stop_grace_period`.",
    },
    {
      id: "next-bottleneck",
      question: "Scale app từ 4 lên 12 instance nhưng throughput gần như không tăng, p95 tăng, CPU app chỉ 25%, Postgres báo `too many clients already`. Bottleneck là gì?",
      options: [
        "Load balancer thiếu CPU",
        "Thuật toán round robin",
        "Connection tới database: 12 instance × pool 10 = 120 connection, vượt `max_connections` mặc định 100",
        "Mạng giữa k6 và Nginx",
      ],
      answerIndex: 2,
      explanation: "Thêm quầy không giúp gì khi bếp chung chỉ có 100 bếp lửa. CPU app thấp + lỗi từ Postgres chỉ thẳng vào DB. Hướng xử lý: connection pooler (PgBouncer), giảm pool mỗi instance, cache, read replica (SD04–SD06).",
    },
  ],
};
