import type { ModuleDefinition } from "@/content/content-types";

export const m11AnsiblePackerModule: ModuleDefinition = {
  id: "m11",
  slug: "m11-ansible-packer",
  phaseId: "phase-3",
  order: 11,
  weeks: "Tuần 18",
  title: "Configuration Management: Ansible & Packer",
  emoji: "🧩",
  eli5Summary:
    "Terraform tạo ra căn nhà trống (server), nhưng ai lo bên trong nhà có điện nước, đồ đạc đúng chỗ? Ansible là quản lý cầm checklist ghé từng nhà kiểm tra/sửa; Packer là máy đúc khuôn để nhân bản một căn nhà mẫu đã chuẩn thành hàng loạt căn giống hệt nhau.",
  objectives: [
    "Phân biệt provisioning (Terraform) và configuration management (Ansible)",
    "So sánh mutable vs immutable infrastructure và hệ quả configuration drift",
    "Viết inventory, playbook, role Ansible và giải thích vì sao chúng idempotent",
    "Dùng handler, template Jinja2 và Ansible Vault đúng cách",
    "Build golden AMI bằng Packer + Ansible và nối vào launch template của Terraform",
    "Chọn đúng công cụ (Ansible / user data / golden image) theo từng tình huống",
  ],
  lessons: [
    { slug: "provisioning-vs-configuration-management", title: "Provisioning vs configuration management", minutes: 30, summary: "Terraform tạo tài nguyên, Ansible cấu hình bên trong; mutable vs immutable infrastructure." },
    { slug: "ansible-architecture-inventory-playbooks", title: "Kiến trúc Ansible: inventory & playbook", minutes: 45, summary: "Agentless qua SSH, static/dynamic inventory, playbook, và vì sao module idempotent." },
    { slug: "roles-handlers-templates-vault", title: "Role, handler, template & Vault", minutes: 45, summary: "Đóng gói task thành role tái sử dụng, notify handler đúng 1 lần, Jinja2 template, mã hoá secret." },
    { slug: "packer-golden-ami-pipeline", title: "Packer: build golden AMI", minutes: 45, summary: "Packer + Ansible provisioner tạo AMI, Terraform launch template dùng AMI mới, instance refresh." },
    { slug: "choosing-the-right-configuration-tool", title: "Chọn đúng công cụ: Ansible, user data hay image?", minutes: 30, summary: "Ma trận quyết định và cách ba công cụ phối hợp trong một hệ thống thật." },
  ],
  labs: [
    {
      id: "ansible-hardening-role",
      title: "Role Ansible cài & harden server",
      description: "Viết role hardening áp dụng cho fleet web: quản lý user, khoá SSH, firewall, fail2ban, node_exporter.",
      steps: [
        "Tạo dynamic inventory `inventory.aws_ec2.yml` lọc theo tag `Role=web`",
        "`ansible-galaxy init roles/hardening` rồi viết task: tạo user không phải root, đẩy SSH public key, đặt `PermitRootLogin no` + `PasswordAuthentication no` qua `lineinfile`, notify handler restart sshd",
        "Thêm task cài `ufw`, chỉ mở cổng 22 (giới hạn theo CIDR bastion), 80, 443",
        "Thêm task cài `fail2ban` với jail mặc định cho sshd",
        "Thêm task cài `node_exporter` chạy như systemd service (tham khảo M01 cho cấu trúc unit file)",
        "Đặt secret (nếu có) vào `group_vars/web/vault.yml` bằng `ansible-vault create`",
        "Chạy `ansible-playbook site.yml --check --diff` trước, review, rồi chạy thật; chạy lại lần 2 để xác nhận `changed=0`",
      ],
    },
    {
      id: "packer-golden-ami-terraform-launch-template",
      title: "Packer + Ansible build AMI, Terraform dùng AMI mới nhất",
      description: "Đóng gói role hardening ở lab trên thành golden AMI và nối vào launch template ASG từ M10.",
      steps: [
        "Viết `web.pkr.hcl` với `source \"amazon-ebs\"` trỏ tới AMI Ubuntu LTS mới nhất qua `source_ami_filter`",
        "Thêm `provisioner \"ansible\"` gọi lại đúng playbook/role đã viết ở lab 1",
        "Thêm `provisioner \"shell\"` dọn `cloud-init clean` và xoá `/etc/machine-id`",
        "`packer init && packer validate && packer build` — ghi lại AMI ID hoặc dùng tag `Pipeline=web` để tra cứu",
        "Trong module `alb-asg` (M10), thêm `data \"aws_ami\"` lọc theo tag để lấy AMI mới nhất, gán vào `aws_launch_template.image_id`",
        "`terraform plan` xác nhận launch template bị `-/+` do đổi `image_id`; `terraform apply` và theo dõi `aws autoscaling describe-instance-refreshes`",
      ],
    },
    {
      id: "terraform-associate-exam-prep",
      title: "(Tuỳ chọn) Ôn thi HashiCorp Terraform Associate",
      description: "Ôn tập nội dung M10–M11 để chuẩn bị cho kỳ thi chứng chỉ Terraform Associate.",
      steps: [
        "Liệt kê lại tự tay các khái niệm: state, backend, module, provisioner, workspace, drift",
        "Làm ít nhất 1 bộ đề thi thử (tham khảo tài liệu chính thức HashiCorp)",
        "Ghi lại 5 câu sai nhiều nhất và đọc lại phần tương ứng trong M10",
        "Kiểm tra mã đề và nội dung thi hiện hành trên trang HashiCorp trước khi đăng ký chính thức",
      ],
    },
  ],
  deliverable:
    "Role Ansible `hardening` (users, SSH, ufw, fail2ban, node_exporter) áp dụng được cho fleet web; pipeline Packer build golden AMI từ role đó; module `alb-asg` của Terraform tự lấy AMI mới nhất qua data source và rollout bằng instance refresh.",
  successCriteria:
    "Chạy playbook 2 lần liên tiếp, lần 2 báo `changed=0` trên mọi host; `packer build` ra AMI mới, `terraform apply` cập nhật launch template và ASG rollout không downtime kéo dài (health check pass trong lúc refresh).",
  resources: [
    { title: "Ansible Documentation", url: "https://docs.ansible.com/ansible/latest/", kind: "doc" },
    { title: "Ansible for DevOps (Jeff Geerling)", url: "https://www.ansiblefordevops.com/", kind: "book" },
    { title: "Packer — Amazon EBS Builder", url: "https://developer.hashicorp.com/packer/integrations/hashicorp/amazon/latest/components/builder/ebs", kind: "doc" },
    { title: "Packer Ansible Provisioner", url: "https://developer.hashicorp.com/packer/integrations/hashicorp/ansible/latest/components/provisioner/ansible", kind: "doc" },
    { title: "Ansible Vault", url: "https://docs.ansible.com/ansible/latest/vault_guide/index.html", kind: "doc" },
    { title: "amazon.aws.aws_ec2 dynamic inventory", url: "https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html", kind: "doc" },
    { title: "AWS Auto Scaling — Instance Refresh", url: "https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-instance-refresh.html", kind: "doc" },
    { title: "HashiCorp Certified: Terraform Associate", url: "https://developer.hashicorp.com/certifications/infrastructure-automation", kind: "course" },
  ],
  quiz: [
    {
      id: "provisioning-vs-config-mgmt",
      question: "Bạn vừa dùng Terraform tạo xong một EC2 trống. EC2 đó chưa cài gì cả. Công cụ nào phù hợp để cài Nginx và tạo user bên trong nó?",
      options: ["Chạy lại terraform apply với resource khác", "Ansible", "Sửa trực tiếp file state", "AWS CloudTrail"],
      answerIndex: 1,
      explanation: "Terraform chỉ biết 'tài nguyên nào tồn tại' (provisioning). Việc cài đặt, cấu hình bên trong hệ điều hành là configuration management — việc của Ansible.",
    },
    {
      id: "mutable-drift-scenario",
      question: "3 server trong cùng ASG trả response khác nhau vì một server từng bị SSH sửa tay để debug rồi quên trả lại. Hiện tượng này gọi là gì?",
      options: ["Idempotency", "Configuration drift", "State locking", "Instance refresh"],
      answerIndex: 1,
      explanation: "Các server 'lệch' nhau dần theo thời gian do sửa tay không đồng bộ — đúng định nghĩa configuration drift, rủi ro chính của mutable infrastructure.",
    },
    {
      id: "idempotent-rerun-changed-zero",
      question: "Chạy `ansible-playbook site.yml` lần đầu báo `changed=5`. Không ai sửa gì, bạn chạy lại ngay. Kết quả mong đợi là gì nếu playbook viết đúng chuẩn?",
      options: [
        "`changed=5` again vì phải chạy lại từ đầu",
        "`changed=0` vì mọi host đã ở đúng trạng thái mong muốn",
        "Lỗi vì package đã cài rồi",
        "`changed=10` vì Ansible cộng dồn",
      ],
      answerIndex: 1,
      explanation: "Đây là bản chất idempotent: mỗi module tự kiểm tra trạng thái trước khi hành động. Đã đúng rồi thì báo `ok`, không đụng gì thêm.",
    },
    {
      id: "command-module-not-idempotent",
      question: "Một task dùng `ansible.builtin.command: systemctl restart nginx` báo `changed` ở MỌI lần chạy dù không có gì đổi. Vì sao?",
      options: [
        "Vì nginx bị crash liên tục",
        "Vì module command không tự kiểm tra trạng thái hiện tại trước khi chạy lệnh tuỳ ý",
        "Vì thiếu inventory group",
        "Vì thiếu ansible_python_interpreter",
      ],
      answerIndex: 1,
      explanation: "command/shell không có logic 'so sánh trạng thái mong muốn với thực tế' như apt/service — nên luôn báo changed. Nên dùng module chuyên dụng hoặc handler.",
    },
    {
      id: "handler-fires-once",
      question: "4 task cùng `template` 4 file cấu hình khác nhau, cả 4 đều `notify: Restart nginx` và đều `changed` trong lần chạy này. Nginx bị restart bao nhiêu lần?",
      options: ["4 lần", "0 lần", "Đúng 1 lần, sau khi mọi task trong play chạy xong", "2 lần"],
      answerIndex: 2,
      explanation: "Ansible dedupe các notify trùng tên trong cùng một play — handler chỉ chạy đúng 1 lần ở cuối, dù được notify nhiều lần.",
    },
    {
      id: "vault-secret-storage",
      question: "Team cần lưu mật khẩu database trong repo Git để Ansible dùng, nhưng không muốn ai đọc được giá trị thật khi xem code. Cách nào đúng?",
      options: [
        "Ghi thẳng mật khẩu vào `group_vars/web/vars.yml`",
        "Lưu trong biến môi trường trên máy cá nhân của mỗi dev",
        "Dùng `ansible-vault create` để mã hoá file chứa mật khẩu rồi commit file đã mã hoá",
        "Gửi mật khẩu qua chat nội bộ mỗi khi cần dùng",
      ],
      answerIndex: 2,
      explanation: "Ansible Vault mã hoá AES256 nội dung file — an toàn để commit. File `.vault_pass.txt`/mật khẩu vault mới là thứ không được commit.",
    },
    {
      id: "packer-provisioner-role",
      question: "Trong pipeline Packer, vai trò của `provisioner \"ansible\"` là gì?",
      options: [
        "Tạo VPC cho instance tạm",
        "Chạy playbook để cấu hình máy tạm trước khi Packer chụp lại thành AMI",
        "Xoá AMI cũ không dùng nữa",
        "Đăng ký DNS cho instance mới",
      ],
      answerIndex: 1,
      explanation: "Provisioner chạy trên máy tạm Packer thuê để build — thường là gọi lại đúng playbook/role Ansible đã viết, sau đó Packer snapshot máy tạm thành AMI.",
    },
    {
      id: "terraform-consumes-new-ami",
      question: "Sau khi Packer build xong AMI mới, làm sao Terraform biết để dùng AMI đó cho launch template?",
      options: [
        "Terraform tự động dò AMI mới nhất mà không cần cấu hình gì",
        "Dùng `data \"aws_ami\"` với filter theo tên/tag, `most_recent = true`, rồi gán vào `image_id`",
        "Sửa tay AMI ID trong AWS Console",
        "Terraform và Packer dùng chung một state nên tự đồng bộ",
      ],
      answerIndex: 1,
      explanation: "Data source `aws_ami` đọc thông tin có sẵn (không tạo gì) để lấy AMI ID mới nhất theo tiêu chí lọc, rồi launch template tham chiếu tới ID đó.",
    },
    {
      id: "instance-refresh-502-brief",
      question: "Sau khi cập nhật launch template sang AMI mới và ASG bắt đầu instance refresh, ALB trả một vài lỗi 502 trong vài phút rồi hết. Đánh giá nào hợp lý nhất?",
      options: [
        "Chắc chắn là lỗi nghiêm trọng, phải rollback ngay lập tức",
        "Bình thường trong lúc rollout nếu ngắn hạn và tự hết khi instance mới pass health check; theo dõi `describe-instance-refreshes` để xác nhận",
        "Là dấu hiệu Ansible Vault sai mật khẩu",
        "Là dấu hiệu Terraform state bị hỏng",
      ],
      answerIndex: 1,
      explanation: "instance_refresh rút dần instance cũ trong khi instance mới đang khởi động/chưa healthy — gây gián đoạn ngắn là hành vi mong đợi, không phải lỗi build hay state.",
    },
    {
      id: "emergency-patch-tool-choice",
      question: "Lỗ hổng OpenSSL nghiêm trọng vừa công bố, cần vá NGAY trên 40 server đang chạy, trong khi build lại golden AMI mất 30 phút review. Nên làm gì trước?",
      options: [
        "Đợi merge xong mới vá",
        "Sửa user data của launch template, đợi ASG tự thay hết instance",
        "Chạy Ansible ad-hoc vá ngay trên fleet đang chạy, đồng thời mở PR cập nhật role để lần build AMI tới có sẵn bản vá",
        "Không cần làm gì vì hạ tầng đã immutable",
      ],
      answerIndex: 2,
      explanation: "Tình huống khẩn cấp trên fleet đang chạy là đúng chỗ dùng Ansible (nhanh, mutable). Vẫn phải đưa fix vào golden image, nếu không AMI lần build tới sẽ thiếu bản vá.",
    },
    {
      id: "userdata-vs-ansible-scope",
      question: "Điểm khác biệt quan trọng nhất giữa EC2 user data và Ansible playbook là gì?",
      options: [
        "User data chỉ chạy một lần lúc instance khởi động; Ansible có thể chạy lại nhiều lần trên instance đang sống",
        "User data mạnh hơn Ansible ở mọi khía cạnh",
        "Ansible chỉ chạy được trên AWS, user data chạy được mọi cloud",
        "Không có khác biệt, hai cái thay thế nhau hoàn toàn",
      ],
      answerIndex: 0,
      explanation: "User data giống 'tờ hướng dẫn ngày đầu đi làm' — chỉ đọc một lần lúc mới vào. Ansible có thể 'gọi điện dặn thêm việc' bất cứ lúc nào cho server đang chạy.",
    },
  ],
};
