import type { ModuleDefinition } from "@/content/content-types";

export const sd01SystemDesignMindsetModule: ModuleDefinition = {
  id: "sd01",
  slug: "sd01-system-design-mindset",
  phaseId: "sd-phase-0",
  order: 1,
  weeks: "Tuần 1–2",
  title: "Tư duy System Design & ước lượng",
  emoji: "📐",
  eli5Summary:
    "Kiến trúc sư không vẽ bản vẽ trước khi hỏi gia chủ nhà mấy người ở, ngân sách bao nhiêu. Module này dạy bạn hỏi đúng câu, nhẩm nhanh quy mô bằng vài phép nhân, và dựng một 'phòng thí nghiệm' nhỏ trên máy để tự đo thay vì đoán.",
  objectives: [
    "Áp dụng framework 4 bước (yêu cầu → ước lượng → high-level → đào sâu) cho mọi bài thiết kế",
    "Viết functional và non-functional requirements có con số cụ thể (latency p99, availability, durability)",
    "Ước lượng QPS trung bình/đỉnh, storage nhiều năm và băng thông bằng tính nhẩm, sai không quá 1 bậc",
    "Dùng latency numbers và bảng 'số 9' để phản biện một kiến trúc",
    "Nhận ra hệ thống đọc nhiều hay ghi nhiều và hệ quả lên kiến trúc",
    "Dựng sd-playground (Nginx, app Node/TypeScript, Postgres, Redis) và chạy k6 smoke test",
  ],
  lessons: [
    { slug: "system-design-thinking-framework", title: "Tư duy system design & framework 4 bước", minutes: 40, summary: "Không có đáp án đúng, chỉ có trade-off — và một quy trình cố định để đi tới đó." },
    { slug: "functional-nonfunctional-requirements", title: "Functional & non-functional requirements", minutes: 40, summary: "Hệ thống làm gì, và làm tốt tới mức nào — viết thành con số." },
    { slug: "back-of-the-envelope-estimation", title: "Ước lượng back-of-the-envelope", minutes: 50, summary: "Nhẩm QPS, storage, băng thông trong 5 phút với 10⁵ giây/ngày." },
    { slug: "latency-numbers-availability-nines", title: "Latency numbers & số 9 availability", minutes: 40, summary: "RAM, SSD, mạng chênh nhau hàng nghìn lần; mỗi số 9 thêm vào đắt gấp bội." },
    { slug: "read-write-ratio-sd-playground", title: "Read/write ratio & dựng sd-playground", minutes: 55, summary: "Đọc nhiều hay ghi nhiều quyết định kiến trúc — dựng playground để tự đo." },
  ],
  labs: [
    {
      id: "sd-playground-setup",
      title: "Dựng sd-playground & k6 smoke test",
      description: "Dựng playground dùng xuyên suốt course: app Fastify + Postgres + Redis sau Nginx, rồi chạy k6 smoke test.",
      steps: [
        "Tạo repo `sd-playground` với `app/` (Fastify + `pg` + `ioredis`), `db/init.sql`, `nginx/default.conf` và `docker-compose.yml` như bài học",
        "Thêm `healthcheck` cho Postgres (`pg_isready`) và `depends_on: condition: service_healthy` cho app",
        "`docker compose up -d --build` rồi `docker compose ps` — cả 4 service phải Up, Postgres (healthy)",
        "Kiểm tra từng tầng: `curl localhost:3000/health`, `curl localhost:8080/api/items/1`, `docker compose exec redis redis-cli PING`",
        "Viết `k6/smoke.js` (5 VU, 30s, threshold `http_req_failed` < 1% và p95 < 200ms) và chạy `k6 run k6/smoke.js`",
        "Ghi lại p95 và số request/giây vào `README.md` — đây là baseline cho các module sau",
      ],
    },
    {
      id: "estimate-three-systems",
      title: "Ước lượng cho 3 hệ thống",
      description: "Làm bảng ước lượng cho Twitter-like, URL shortener và chat 1-1: DAU, QPS đọc/ghi, storage 5 năm.",
      steps: [
        "Với mỗi hệ thống, viết giả định trước: DAU, số lần đọc/ghi mỗi user/ngày, kích thước trung bình mỗi bản ghi",
        "Tính QPS trung bình bằng quy tắc `1 ngày ≈ 10⁵ giây`, rồi QPS đỉnh với hệ số peak 2–3× (ghi rõ hệ số)",
        "Tính storage/ngày và storage 5 năm; ghi riêng phần media (ảnh/file) nếu có và hệ số replication (ví dụ ×3)",
        "Trình bày thành bảng `| Đại lượng | Giả định | Kết quả |` theo Phụ lục A cho cả 3 hệ thống",
        "Bấm giờ: làm lại 1 hệ thống bất kỳ trong 5 phút không nhìn ghi chú, so sánh với bản đầu — lệch không quá 1 bậc",
      ],
    },
    {
      id: "requirements-for-your-system",
      title: "Viết requirements cho hệ thống thật của bạn",
      description: "Chọn 1 hệ thống ở công ty hoặc side project, viết functional + NFR có con số và out of scope.",
      steps: [
        "Liệt kê 3–5 functional requirements quan trọng nhất dạng 'User có thể…'",
        "Viết NFR có số: latency p99 cho 2 API chính, availability mục tiêu, durability, mức consistency cho từng loại dữ liệu",
        "Ghi rõ out of scope (ít nhất 3 mục) và read/write ratio ước tính từ log hoặc metrics thật (ví dụ đếm GET vs POST trong access log)",
        "Với mỗi NFR, ghi 1 hệ quả kiến trúc (ví dụ 'p99 < 100ms ⇒ cần cache cho trang sản phẩm')",
        "Nhờ 1 đồng nghiệp đọc và đánh dấu chỗ nào còn mơ hồ; sửa lại cho tới khi mọi NFR đều đo được",
      ],
    },
    {
      id: "measure-latency-layers",
      title: "Tự đo latency từng tầng trong playground",
      description: "So sánh độ trễ Redis, Postgres và HTTP qua Nginx với bảng latency numbers.",
      steps: [
        "Đo Redis: `docker compose exec redis redis-cli --latency` trong ~10 giây, ghi lại avg",
        "Đo Postgres: trong `psql` bật `\\timing on`, chạy `SELECT * FROM items WHERE id = 1;` vài lần và `SELECT count(*) FROM items;`",
        "Đo HTTP: `curl -s -o /dev/null -w \"%{time_total}\\n\" localhost:8080/api/items/1` 5 lần; so với gọi thẳng `localhost:3000`",
        "Lập bảng thứ tự độ lớn (µs, ms) cho từng tầng và giải thích chênh lệch; ghi chú rằng Docker trên laptop không phản ánh production",
      ],
    },
  ],
  deliverable: "Repo sd-playground chạy được bằng `docker compose up` kèm kết quả k6 baseline, cùng bảng ước lượng cho 3 hệ thống và 1 bản requirements có NFR định lượng.",
  successCriteria: "Trong 5 phút ước lượng được QPS và storage của một hệ thống mới, sai không quá 1 bậc độ lớn; playground chạy được và có số p95 baseline.",
  resources: [
    { title: "The System Design Primer (donnemartin, GitHub)", url: "https://github.com/donnemartin/system-design-primer", kind: "course" },
    { title: "System Design Interview Vol. 1 (Alex Xu) — ch.1–3, ByteByteGo", url: "https://bytebytego.com/", kind: "book" },
    { title: "Latency Numbers Every Programmer Should Know", url: "https://gist.github.com/jboner/2841832", kind: "doc" },
    { title: "Hello Interview — System Design (delivery framework)", url: "https://www.hellointerview.com/", kind: "course" },
    { title: "Google SRE Book — Embracing Risk (availability & error budget)", url: "https://sre.google/sre-book/embracing-risk/", kind: "book" },
    { title: "Docker Compose docs", url: "https://docs.docker.com/compose/", kind: "tool" },
    { title: "Grafana k6 docs", url: "https://grafana.com/docs/k6/latest/", kind: "tool" },
  ],
  quiz: [
    {
      id: "clarify-before-drawing",
      question: "Interviewer nói: \"Thiết kế Instagram\". Việc đầu tiên nên làm là gì?",
      options: [
        "Vẽ ngay load balancer, app server và database",
        "Hỏi làm rõ tính năng chính, số user, tỉ lệ đọc/ghi và các NFR quan trọng",
        "Chọn Kafka + Cassandra vì chúng scale tốt",
        "Viết schema chi tiết cho bảng `posts`",
      ],
      answerIndex: 1,
      explanation: "Như kiến trúc sư phải hỏi gia chủ nhà mấy người ở trước khi vẽ: chưa biết quy mô và yêu cầu thì mọi hộp vẽ ra đều là đoán mò.",
    },
    {
      id: "identify-nfr",
      question: "Với URL shortener, yêu cầu nào là non-functional?",
      options: [
        "User rút gọn được một URL dài",
        "User xem được danh sách link đã tạo",
        "99% lượt redirect trả về trong vòng 50ms, availability 99,99%",
        "User đặt được alias tuỳ chỉnh",
      ],
      answerIndex: 2,
      explanation: "Functional là 'thực đơn có món gì'; non-functional là 'lên món nhanh cỡ nào, bao nhiêu khách, có được sai sót không'. Latency và availability thuộc nhóm sau.",
    },
    {
      id: "qps-estimate",
      question: "DAU 10 triệu, mỗi user trung bình 10 request/ngày. QPS trung bình cỡ bao nhiêu?",
      options: ["Cỡ 1.000 QPS", "Cỡ 100 QPS", "Cỡ 10.000 QPS", "Cỡ 100.000 QPS"],
      answerIndex: 0,
      explanation: "10M × 10 = 10⁸ request/ngày; chia 10⁵ giây/ngày ≈ 10³ QPS (chính xác ~1.160). Như ước bán phở: chỉ cần biết 1.000 hay 10.000 tô, không cần đúng từng tô.",
    },
    {
      id: "storage-five-years",
      question: "Hệ thống nhận 1 triệu bài viết/ngày, mỗi bài ~1 KB (chỉ text + metadata). Storage thô sau 5 năm cỡ bao nhiêu (chưa tính replication)?",
      options: ["Cỡ 18 GB", "Cỡ 180 GB", "Cỡ 18 TB", "Cỡ 1,8 TB"],
      answerIndex: 3,
      explanation: "10⁶ × 1 KB = 1 GB/ngày; × 365 × 5 ≈ 1.825 GB ≈ 1,8 TB. Nhớ nhân thêm hệ số replication (ví dụ ×3) và tách riêng media nếu có.",
    },
    {
      id: "design-for-peak",
      question: "QPS trung bình là 500. Vì sao vẫn phải thiết kế cho cỡ 1.000–1.500 QPS?",
      options: [
        "Vì k6 luôn đo sai 2–3 lần",
        "Vì lưu lượng dồn vào giờ cao điểm; hệ thống sập đúng lúc đông khách nhất nếu chỉ đủ cho mức trung bình",
        "Vì database luôn chậm gấp 3 lần app",
        "Vì QPS trung bình không bao gồm request ghi",
      ],
      answerIndex: 1,
      explanation: "Quán phở không đông đều cả ngày — 6–8 giờ sáng mới là lúc thiếu nồi. Hệ số peak 2–3× là giả định phổ biến, luôn nói rõ khi dùng.",
    },
    {
      id: "read-heavy-implication",
      question: "URL shortener có read:write cỡ 100:1. Hệ quả kiến trúc hợp lý nhất là gì?",
      options: [
        "Tối ưu đường đọc: cache, read replica, có thể CDN cho redirect",
        "Shard database theo write ngay từ ngày đầu",
        "Tỉ lệ đọc/ghi không ảnh hưởng kiến trúc",
        "Đưa mọi request đọc qua message queue",
      ],
      answerIndex: 0,
      explanation: "Như thư viện: rất nhiều người đọc, ít người viết sách mới — ta đầu tư vào quầy mượn sách (cache, replica) chứ không phải xưởng in.",
    },
    {
      id: "cross-region-latency",
      question: "App ở Singapore, database ở US East. Mỗi request chạy 5 query tuần tự, trang load mất cỡ 1 giây dù query nào cũng nhanh. Cách sửa hiệu quả nhất?",
      options: [
        "Tăng CPU cho app server",
        "Thêm index cho các bảng",
        "Đặt app và database cùng region, đồng thời gộp bớt round trip",
        "Đổi response từ JSON sang XML",
      ],
      answerIndex: 2,
      explanation: "Round trip xuyên Thái Bình Dương cỡ 200ms × 5 = 1 giây. Như mỗi món lại chạy ra chợ bên kia thành phố — dời bếp lại gần chợ, và đi chợ một lần mua đủ.",
    },
    {
      id: "availability-in-series",
      question: "Request phải đi qua app (99,9%) rồi database (99,9%), hai thành phần hỏng độc lập. Availability tổng cỡ bao nhiêu?",
      options: ["99,99%", "99,9%", "Cỡ 99,95%", "Cỡ 99,8%"],
      answerIndex: 3,
      explanation: "Nối tiếp thì nhân: 0,999 × 0,999 ≈ 0,998. Như cửa hàng chỉ mở khi cả chủ quán lẫn thợ bếp cùng có mặt — thêm một khâu bắt buộc là thêm một lý do phải đóng cửa.",
    },
    {
      id: "nines-downtime",
      question: "SLO 99,99% theo tháng cho phép downtime cỡ bao nhiêu mỗi tháng?",
      options: ["Cỡ 43 phút", "Cỡ 4,4 phút", "Cỡ 26 giây", "Cỡ 7 giờ"],
      answerIndex: 1,
      explanation: "Mỗi số 9 chia downtime cho 10: 99,9% ≈ 43,8 phút/tháng, 99,99% ≈ 4,4 phút. Cửa hàng '4 số 9' chỉ được đóng cửa vài phút mỗi tháng — không kịp gọi người sửa bằng tay.",
    },
    {
      id: "compose-startup-order",
      question: "`docker compose up` xong, app crash với lỗi `ECONNREFUSED postgres:5432` rồi tự hết khi chạy lại. Cách sửa đúng nhất trong playground?",
      options: [
        "Thêm `sleep 30` vào đầu Dockerfile của app",
        "Đổi `postgres` thành `localhost` trong `DATABASE_URL`",
        "Thêm `healthcheck` (`pg_isready`) cho Postgres và `depends_on` với `condition: service_healthy` cho app",
        "Bỏ `depends_on` để các container khởi động song song",
      ],
      answerIndex: 2,
      explanation: "Container 'đã chạy' chưa có nghĩa là Postgres 'sẵn sàng nhận khách'. Healthcheck giống bếp báo 'đã lên lửa' thì mới mở cửa đón khách. Trong container, `localhost` là chính container app, không phải Postgres.",
    },
  ],
};
