import type { ModuleDefinition } from "@/content/content-types";

export const b08FileUploadObjectStorageModule: ModuleDefinition = {
  id: "b08",
  slug: "b08-file-upload-object-storage",
  phaseId: "b-phase-2",
  order: 8,
  weeks: "Tuần 11",
  title: "File upload & object storage",
  emoji: "📎",
  eli5Summary:
    "Cho tới giờ, `taskflow-api` chưa hề đụng tới một file nào ngoài JSON. Module này cho phép người dùng đính kèm file vào task — nhưng thay vì bắt app server 'cõng' từng byte file đi qua nó như một trạm trung chuyển, server chỉ phát một 'phiếu gửi hàng đã ký sẵn' (presigned URL) rồi để client tự đem file thẳng tới kho hàng thật (MinIO, S3-compatible). App server chỉ kiểm tra giấy tờ, không bao giờ chạm vào kiện hàng.",
  objectives: [
    "Giải thích vì sao upload file production nên đi thẳng client → object storage thay vì qua app server, và đánh đổi của từng cách",
    "Thêm service `minio` vào `docker-compose.yml` đúng spec taskflow-api, cấu hình S3 client bằng `@aws-sdk/client-s3` với `forcePathStyle: true`",
    "Cài luồng presigned URL: cấp URL PUT có phạm vi giới hạn (đúng key, đúng thao tác, có hạn dùng) bằng `@aws-sdk/s3-request-presigner`",
    "Validate size/type từ metadata client khai báo trước khi cấp URL — và giải thích chính xác vì sao bước này cần thiết nhưng chưa đủ",
    "Viết endpoint confirm ghi bảng `attachments`, dùng `HeadObjectCommand` để xác thực lại thông tin thật từ storage thay vì tin lời khai của client",
    "Nhận diện vì sao kiểm tra nội dung file thật (virus scan) phải là bước bất đồng bộ — tiền đề cho B09",
  ],
  lessons: [
    {
      slug: "object-storage-vs-app-server-upload",
      title: "Object storage: upload qua app server vs. thẳng lên storage",
      minutes: 35,
      summary: "Vì sao bắt Fastify 'cõng' từng byte file là ý tưởng tồi ở quy mô production, và presigned URL giải quyết vấn đề đó thế nào.",
    },
    {
      slug: "presigned-url-request-sign-confirm-flow",
      title: "Luồng presigned URL: request → sign → PUT → confirm",
      minutes: 45,
      summary: "Từng bước một request đi từ `POST /presign` tới lúc file nằm trong MinIO và có một row trong bảng `attachments`.",
    },
    {
      slug: "validate-size-type-before-presigning",
      title: "Giới hạn size & type trước khi cấp presigned URL",
      minutes: 35,
      summary: "Chặn ở cổng vào bằng lời khai của client — hiệu quả nhưng không phải bức tường thành bất khả xâm phạm.",
    },
    {
      slug: "async-verification-after-upload",
      title: "Sau khi upload: HEAD check & virus-scan bất đồng bộ",
      minutes: 30,
      summary: "File đã nằm trong kho không có nghĩa là đáng tin — bước xác thực thật sự diễn ra sau, chạy nền (tiền đề B09).",
    },
  ],
  labs: [
    {
      id: "add-minio-service-and-attachments-schema",
      title: "Thêm service `minio` & bảng `attachments`",
      description: "Mở rộng `docker-compose.yml` với service `minio` (mục 3 curriculum), thêm bảng `attachments` vào schema Drizzle, và dựng S3 client dùng chung.",
      steps: [
        "Trong `docker-compose.yml`, thêm service `minio`: `image: minio/minio`, `command: server /data --console-address \":9001\"`, `ports: [\"9002:9000\", \"9003:9001\"]`, `environment: { MINIO_ROOT_USER: minioadmin, MINIO_ROOT_PASSWORD: minioadmin }`, volume `minio-data:/data` — đúng ports host:container ở mục 3 curriculum, không đổi",
        "Chạy `docker compose up -d minio`, mở console tại `http://localhost:9003` (đăng nhập `minioadmin`/`minioadmin`), tạo bucket tên `taskflow-attachments`",
        "Trong `src/db/schema.ts`, thêm bảng `attachments`: `id uuid pk default gen_random_uuid()`, `task_id uuid` fk `tasks.id`, `url text`, `filename text`, `size_bytes bigint` (mode `number`), `uploaded_by uuid` fk `users.id`, `created_at timestamptz default now()` — đúng tên cột ở mục 3 curriculum, `uploaded_by` là FK thật vì `users` đã tồn tại từ B05",
        "Sinh và chạy migration: `pnpm drizzle-kit generate` rồi `pnpm drizzle-kit migrate`; xác nhận bằng `docker compose exec postgres psql -U taskflow -c '\\d attachments'`",
        "Cài `@aws-sdk/client-s3` và `@aws-sdk/s3-request-presigner` (`pnpm add @aws-sdk/client-s3 @aws-sdk/s3-request-presigner`), thêm biến môi trường `MINIO_INTERNAL_ENDPOINT=http://minio:9000`, `MINIO_PUBLIC_ENDPOINT=http://localhost:9002`, `MINIO_ACCESS_KEY=minioadmin`, `MINIO_SECRET_KEY=minioadmin`, `MINIO_BUCKET=taskflow-attachments`",
        "Tạo `src/lib/s3-client.ts` khởi tạo hai `S3Client` — một trỏ `MINIO_INTERNAL_ENDPOINT` (dùng cho `HeadObjectCommand` gọi từ chính container `api`), một trỏ `MINIO_PUBLIC_ENDPOINT` (chỉ dùng để ký presigned URL cho client bên ngoài mạng Docker) — cả hai đều `forcePathStyle: true`",
      ],
    },
    {
      id: "presign-endpoint-with-validation",
      title: "Endpoint presign có validate size/type",
      description: "`POST /api/v1/tasks/:id/attachments/presign` — kiểm tra quyền, validate `filename`/`mimeType`/`sizeBytes` bằng Zod, từ chối trước khi tốn công ký URL.",
      steps: [
        "Định nghĩa hằng số `MAX_ATTACHMENT_SIZE_BYTES = 15 * 1024 * 1024` và `ALLOWED_ATTACHMENT_MIME_TYPES = [\"image/png\", \"image/jpeg\", \"application/pdf\"]` trong `src/routes/attachments.ts`",
        "Viết Zod schema `presignBodySchema` cho `{ filename: string, mimeType: string, sizeBytes: number }`",
        "Trong handler: `authenticate` trước, tìm `task` theo `:id` (404 nếu không có), join sang `projects` lấy `organization_id`, kiểm tra `memberships` có row của `request.user.sub` với `organization_id` đó (403 nếu không), validate body bằng Zod (400 `VALIDATION_ERROR` nếu sai kiểu)",
        "Nếu `sizeBytes > MAX_ATTACHMENT_SIZE_BYTES` hoặc `mimeType` không nằm trong `ALLOWED_ATTACHMENT_MIME_TYPES`, trả `400` với `error.code = \"VALIDATION_ERROR\"` và KHÔNG gọi tới S3 client — chặn trước khi tốn công ký URL",
        "Nếu hợp lệ: sinh key `tasks/${taskId}/${randomUUID()}-${filename}`, gọi `getSignedUrl(s3PresignClient, new PutObjectCommand({ Bucket, Key, ContentType: mimeType }), { expiresIn: 300 })`, trả về `{ uploadUrl, key, expiresAt }`",
        "Test thủ công bằng `curl`: một request với `sizeBytes` 20MB phải nhận `400`, một request hợp lệ phải nhận `200` kèm `uploadUrl`",
      ],
    },
    {
      id: "confirm-endpoint-and-e2e-test",
      title: "Endpoint confirm & test upload-then-confirm đầy đủ",
      description: "`POST /api/v1/tasks/:id/attachments/confirm` ghi bảng `attachments` sau khi xác thực lại object thật bằng `HeadObjectCommand`, cùng script curl chạy trọn luồng.",
      steps: [
        "Viết Zod schema `confirmBodySchema` cho `{ key: string, filename: string }` (không nhận lại `sizeBytes`/`mimeType` từ client ở bước này — sẽ lấy từ storage thật)",
        "Trong handler: gọi `HeadObjectCommand({ Bucket, Key: key })` bằng `s3InternalClient`; nếu object không tồn tại (lỗi `NotFound`), trả `404` — chứng minh file thật sự đã lên MinIO trước khi ghi DB",
        "Lấy `ContentLength` và `ContentType` THẬT từ response của `HeadObjectCommand` (không dùng lại giá trị client khai lúc presign), insert vào `attachments` với `url` dựng từ `MINIO_PUBLIC_ENDPOINT`, `size_bytes = ContentLength`, `uploaded_by = request.user.sub`",
        "Viết file `scripts/test-attachment-upload-flow.sh`: gọi `presign` lấy `uploadUrl`+`key` → `curl -X PUT --upload-file ./sample.pdf -H \"Content-Type: application/pdf\" \"$uploadUrl\"` → gọi `confirm` với `key` → `curl` lại `GET /api/v1/tasks/:id/attachments` để xác nhận row xuất hiện",
        "Viết test Vitest `attachments.test.ts`: gọi `confirm` với một `key` chưa từng được PUT lên MinIO, assert response `404` — chứng minh confirm không ghi DB dựa trên lời hứa suông",
        "Chạy `pnpm test` — test attachments phải xanh trước khi coi lab hoàn thành",
      ],
    },
  ],
  deliverable:
    "`taskflow-api` có service `minio` trong compose, bảng `attachments`, 2 endpoint `/api/v1/tasks/:id/attachments/{presign,confirm}` hoạt động thật với MinIO + Postgres, script curl chạy trọn luồng upload, và test Vitest chứng minh confirm từ chối object chưa tồn tại trên storage.",
  successCriteria:
    "Chạy script upload-then-confirm thành công: presign → PUT thẳng lên MinIO (app server không nhận byte file nào qua chính nó) → confirm ghi đúng row `attachments` với `size_bytes` lấy từ `HeadObjectCommand`, không phải từ lời khai client. Request presign với size/type sai bị từ chối `400` trước khi có URL nào được ký. `pnpm test` xanh.",
  resources: [
    { title: "MinIO Documentation", url: "https://min.io/docs/minio/linux/index.html", kind: "doc" },
    { title: "MinIO JavaScript Client API Reference", url: "https://min.io/docs/minio/linux/developers/javascript/minio-javascript-client-api-reference.html", kind: "doc" },
    { title: "AWS S3 User Guide — Uploading objects with presigned URLs", url: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html", kind: "doc" },
    { title: "@aws-sdk/client-s3 (npm)", url: "https://www.npmjs.com/package/@aws-sdk/client-s3", kind: "tool" },
    { title: "@aws-sdk/s3-request-presigner (npm)", url: "https://www.npmjs.com/package/@aws-sdk/s3-request-presigner", kind: "tool" },
    { title: "aws-sdk-js-v3 (GitHub)", url: "https://github.com/aws/aws-sdk-js-v3", kind: "doc" },
    { title: "OWASP File Upload Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html", kind: "doc" },
  ],
  quiz: [
    {
      id: "why-not-stream-through-app-server",
      question: "Vì sao `taskflow-api` dùng presigned URL thay vì để client upload file thẳng qua app server rồi server tự đẩy lên MinIO?",
      options: [
        "Vì Fastify không hỗ trợ nhận file upload (multipart)",
        "Vì MinIO chỉ nhận file từ client, không nhận từ server khác",
        "Vì presigned URL giúp byte file đi thẳng client → storage, app server không phải làm trạm trung chuyển tốn băng thông và bộ nhớ",
        "Vì presigned URL mã hoá file tốt hơn",
      ],
      answerIndex: 2,
      explanation: "App-server-mediated upload bắt Fastify nhận toàn bộ byte file rồi mới gửi tiếp lên storage — tốn băng thông kép, chiếm memory, khó scale với file lớn. Presigned URL để client PUT thẳng tới MinIO, app server chỉ ký giấy phép.",
    },
    {
      id: "presigned-url-scope-limited",
      question: "Một presigned PUT URL vừa được tạo cho object key `tasks/42/report.pdf`, hết hạn sau 5 phút. Điều gì đúng về URL này?",
      options: [
        "Chỉ hợp lệ cho đúng operation (PUT) và đúng key đã ký, và tự hết hiệu lực sau thời gian định trước — không phải một credential dùng chung",
        "Có thể dùng để PUT bất kỳ object nào trong bucket, không riêng key đó",
        "Có thể dùng để GET, PUT, DELETE bất kỳ lúc nào vì đã có chữ ký hợp lệ",
        "Không bao giờ hết hạn nếu bucket là public",
      ],
      answerIndex: 0,
      explanation: "Presigned URL ký cho đúng một thao tác (PUT), đúng một key, với thời hạn cụ thể — nó không phải access key hay session token dùng chung cho mọi hành động. Hết hạn là hết hiệu lực, không cần server chủ động thu hồi.",
    },
    {
      id: "size-check-necessary-not-sufficient",
      question: "Server đã từ chối cấp presigned URL nếu `sizeBytes` client khai báo lúc presign vượt 15MB. Điều này có đảm bảo file thật upload lên không vượt 15MB không?",
      options: [
        "Đủ, vì server đã kiểm tra trước khi cấp URL",
        "Đủ, vì MinIO tự động huỷ upload nếu file lớn hơn khai báo",
        "Không liên quan vì kiểm tra size chỉ để hiển thị UI",
        "Không đủ — presigned PUT URL (khác presigned POST kèm policy điều kiện) không tự chặn dung lượng thật lúc PUT, client vẫn có thể gửi file lớn hơn khai báo lên đúng URL đã ký",
      ],
      answerIndex: 3,
      explanation: "Presigned PUT chỉ ký chữ ký cho request PUT tới đúng key — nó không mang theo điều kiện ràng buộc Content-Length như presigned POST với policy. Validate lúc presign chỉ chặn được client 'khai đúng nhưng quá to', không chặn được client cố tình khai nhỏ rồi gửi file to.",
    },
    {
      id: "never-trust-extension-alone",
      question: "File client khai báo tên `avatar.png` và `mimeType: image/png`. Vì sao không nên chỉ dựa vào đuôi file hoặc `mimeType` client khai để kết luận đây thật sự là ảnh an toàn?",
      options: [
        "Vì Node.js không đọc được đuôi file .png",
        "Vì đuôi file và `Content-Type` đều do client tự đặt — một file thực chất khác hoàn toàn có thể đổi tên/khai lại để qua được bước kiểm tra này",
        "Vì .png là định dạng không tồn tại trong MinIO",
        "Vì việc này chỉ quan trọng khi file lớn hơn 1GB",
      ],
      answerIndex: 1,
      explanation: "Tên file và Content-Type client gửi lên là dữ liệu client tự khai, không phải sự thật được xác minh. Kiểm tra chúng chặn được người dùng vô ý (sai định dạng), không chặn được người cố tình giả mạo.",
    },
    {
      id: "head-object-after-confirm",
      question: "Sau khi client gọi endpoint confirm, vì sao server nên gọi `HeadObjectCommand` lên MinIO thay vì tin thẳng thông tin client gửi kèm request confirm?",
      options: [
        "Vì `HeadObjectCommand` chạy nhanh hơn `PutObjectCommand`",
        "Vì confirm endpoint bắt buộc phải gọi `HeadObjectCommand` mới hợp lệ theo chuẩn S3",
        "Vì `HeadObjectCommand` lấy thông tin thật (`ContentLength`, `ETag`) từ object đã lưu trong storage, không phụ thuộc lời khai của client — phát hiện được sai lệch giữa khai báo và thực tế, và chứng minh file thật sự tồn tại",
        "Vì `HeadObjectCommand` tự động xoá file nếu quá hạn",
      ],
      answerIndex: 2,
      explanation: "`HeadObjectCommand` hỏi thẳng storage 'object này có thật không, dung lượng bao nhiêu' — đây là nguồn sự thật (source of truth), khác với việc tin vào JSON client gửi kèm request confirm (có thể sai hoặc client chưa từng upload gì cả).",
    },
    {
      id: "async-scan-teaser-b09",
      question: "Virus-scan/kiểm tra nội dung file thật sự được xếp là bước bất đồng bộ, chạy SAU khi file đã lưu vào storage, thay vì chặn ngay lúc cấp presigned URL. Vì sao thiết kế vậy hợp lý?",
      options: [
        "Vì quét virus không quan trọng với file người dùng tải lên",
        "Vì MinIO tự động quét virus khi nhận PUT",
        "Vì async luôn nhanh hơn sync trong mọi trường hợp",
        "Vì quét nội dung thật cần đọc toàn bộ byte file (tốn CPU/thời gian) — lúc cấp presigned URL thì file CHƯA hề tồn tại để quét, nên bắt buộc phải làm sau khi file đã lên storage, và chạy nền để không chặn response của client",
      ],
      answerIndex: 3,
      explanation: "Lúc gọi `/presign`, chưa có byte file nào trong tay server — không có gì để quét. Việc quét chỉ có thể diễn ra sau khi file đã nằm trong MinIO, và vì tốn thời gian nên phải chạy nền (queue, nối B09) thay vì chặn request của client.",
    },
    {
      id: "forcepathstyle-minio",
      question: "Khi tạo `S3Client` trỏ tới MinIO bằng `@aws-sdk/client-s3`, vì sao cần set `forcePathStyle: true`?",
      options: [
        "Vì MinIO mặc định không hỗ trợ virtual-hosted-style (`bucket.endpoint.com/key`) như AWS S3 thật — phải dùng path-style (`endpoint.com/bucket/key`) để request tới đúng bucket",
        "Để tăng tốc độ upload",
        "Để mã hoá dữ liệu trước khi gửi",
        "Chỉ cần thiết khi chạy trên production, không cần ở local",
      ],
      answerIndex: 0,
      explanation: "AWS S3 thật hỗ trợ cả hai kiểu địa chỉ bucket, nhưng SDK v3 mặc định ưu tiên virtual-hosted-style — MinIO (và hầu hết S3-compatible storage tự host) không xử lý kiểu đó đúng, nên phải ép `forcePathStyle: true`.",
    },
    {
      id: "bucket-not-in-compose-before-b08",
      question: "Một learner đang ở B07 (trước khi học B08) thử gọi endpoint presign nhưng app báo lỗi không kết nối được MinIO. Nguyên nhân hợp lý nhất là gì?",
      options: [
        "MinIO chỉ hoạt động vào ban đêm",
        "Fastify 5 không tương thích với MinIO",
        "Service `minio` chỉ được thêm vào `docker-compose.yml` từ B08 — trước đó compose của `taskflow-api` chưa có service này nên không có gì để kết nối tới",
        "Cần license trả phí để dùng MinIO",
      ],
      answerIndex: 2,
      explanation: "Theo mục 3 curriculum, mỗi service chỉ xuất hiện trong compose từ đúng module giới thiệu nó — `minio` giới thiệu ở B08. Trước đó gọi endpoint liên quan tới nó chắc chắn lỗi kết nối vì service chưa tồn tại.",
    },
    {
      id: "presigned-url-expiry-purpose",
      question: "Presigned URL được cấu hình hết hạn sau 5 phút (`expiresIn: 300`). Mục đích chính của thời hạn ngắn này là gì?",
      options: [
        "Để giảm chi phí lưu trữ trên MinIO",
        "Để giới hạn cửa sổ thời gian một URL bị lộ (ví dụ lọt vào log, bị chia sẻ nhầm) còn có thể bị lợi dụng — hết hạn là tự vô hiệu, không cần server chủ động thu hồi",
        "Để buộc client phải nhập lại mật khẩu",
        "Vì MinIO giới hạn số request mỗi 5 phút",
      ],
      answerIndex: 1,
      explanation: "Presigned URL không thể bị 'revoke' giữa chừng như một session — cách duy nhất giới hạn rủi ro nếu nó bị lộ là cho nó tự hết hạn sớm. 5 phút vừa đủ cho một lần PUT bình thường, không đủ để bị khai thác lâu dài.",
    },
    {
      id: "attachments-fk-uploaded-by",
      question: "Vì sao đến B08, cột `uploaded_by` trong bảng `attachments` có thể là một foreign key thật tới `users.id`, dù `attachments` chỉ xuất hiện lần đầu trong domain model ở mục 3 curriculum (giới thiệu cùng lúc với B04)?",
      options: [
        "Vì MinIO yêu cầu bắt buộc phải có foreign key",
        "Vì `uploaded_by` không liên quan đến file upload",
        "Vì Drizzle không hỗ trợ FK tới bảng tạo sau",
        "Vì bảng `users` chỉ thật sự được tạo từ B05 (module authentication) — `attachments` được build ở B08, sau khi `users` đã tồn tại, nên FK thẳng vào `users.id` là hợp lệ ngay từ đầu",
      ],
      answerIndex: 3,
      explanation: "Domain model ở mục 3 liệt kê đủ 10 bảng nhưng từng bảng được BUILD (tạo migration thật) ở đúng module giới thiệu nó. `attachments` được tạo ở B08 — lúc này `users` (từ B05) đã tồn tại, nên không cần để `uploaded_by` là placeholder chờ FK sau như cách B04 từng để chỗ cho `users`/`memberships`.",
    },
  ],
};
