import type { ModuleDefinition } from "@/content/content-types";

export const m01LinuxShellModule: ModuleDefinition = {
  id: "m01",
  slug: "m01-linux-shell",
  phaseId: "phase-0",
  order: 1,
  weeks: "Tuần 1–2",
  title: "Linux & Shell Scripting",
  emoji: "🐧",
  eli5Summary:
    "Server trên cloud gần như đều chạy Linux — một ngôi nhà không có chuột, chỉ có bàn phím. Module này dạy bạn đi lại trong ngôi nhà đó, cấp chìa khoá cho đúng người, và viết 'kịch bản' để máy tự làm việc lặp lại.",
  objectives: [
    "Di chuyển và quản lý file trong cây thư mục Linux",
    "Hiểu và cấp quyền file đúng nguyên tắc (chmod, chown, sudo)",
    "Quản lý tiến trình và service bằng systemctl, journalctl",
    "Kết hợp lệnh bằng pipe để lọc, phân tích log",
    "Viết bash script an toàn và hẹn giờ chạy tự động",
    "Đăng nhập server bằng SSH key, tắt đăng nhập bằng mật khẩu",
  ],
  lessons: [
    { slug: "linux-filesystem", title: "Linux là gì & cây thư mục", minutes: 35, summary: "Toà chung cư Linux: mỗi thư mục là một khu có công dụng riêng." },
    { slug: "users-permissions", title: "User, group & quyền truy cập", minutes: 40, summary: "Ai được đọc, sửa, chạy file nào — và vì sao không nên dùng root." },
    { slug: "processes-systemd", title: "Tiến trình & systemd", minutes: 40, summary: "Quản lý nhà hàng systemd giữ cho các ứng dụng luôn chạy." },
    { slug: "pipes-text-processing", title: "Pipe & xử lý văn bản", minutes: 45, summary: "Nối các lệnh nhỏ thành dây chuyền phân tích log mạnh mẽ." },
    { slug: "bash-scripting-automation", title: "Bash script & tự động hoá", minutes: 50, summary: "Viết kịch bản an toàn và hẹn giờ cho máy tự chạy." },
    { slug: "ssh-remote-access", title: "SSH: điều khiển server từ xa", minutes: 35, summary: "Đăng nhập bằng cặp khoá thay vì mật khẩu." },
  ],
  labs: [
    {
      id: "harden-vm",
      title: "Dựng & bảo vệ một VM",
      description: "Tạo máy ảo Linux, tạo user riêng, đăng nhập bằng SSH key và khoá cửa root.",
      steps: [
        "Tạo VM Ubuntu LTS bằng Multipass (`multipass launch --name lab`) hoặc EC2 free tier",
        "Tạo user mới có quyền sudo: `adduser trung` và `usermod -aG sudo trung`",
        "Tạo SSH key trên laptop (`ssh-keygen -t ed25519`) và copy lên VM bằng `ssh-copy-id`",
        "Trong `/etc/ssh/sshd_config`: đặt `PasswordAuthentication no` và `PermitRootLogin no`, rồi `sudo systemctl reload ssh`",
        "Bật firewall: `sudo ufw allow OpenSSH && sudo ufw enable`",
        "Kiểm tra: mở terminal mới, SSH vào bằng key thành công; thử `ssh root@...` phải bị từ chối",
      ],
    },
    {
      id: "backup-script",
      title: "Script backup tự động",
      description: "Viết backup.sh nén thư mục, giữ 7 bản gần nhất, chạy mỗi đêm bằng systemd timer.",
      steps: [
        "Viết `backup.sh` với `set -euo pipefail`, nhận thư mục nguồn và đích làm tham số",
        "Kiểm tra thư mục nguồn tồn tại, báo lỗi ra stderr và `exit 1` nếu không",
        "Nén bằng `tar -czf` với tên file chứa ngày `$(date +%F)`",
        "Xoá các bản cũ, chỉ giữ 7 bản mới nhất",
        "Tạo `backup.service` (Type=oneshot) và `backup.timer` (OnCalendar=daily)",
        "Kích hoạt timer, kiểm tra bằng `systemctl list-timers` và `journalctl -u backup`",
        "Chạy ShellCheck trên script, sửa hết cảnh báo",
      ],
    },
    {
      id: "healthcheck-script",
      title: "Script kiểm tra sức khoẻ server",
      description: "Viết healthcheck.sh cảnh báo khi CPU, RAM hoặc ổ đĩa vượt ngưỡng.",
      steps: [
        "Lấy % disk đã dùng của `/` bằng `df` + `awk`",
        "Lấy % RAM đã dùng bằng `free` + `awk`",
        "Lấy load average từ `/proc/loadavg` và so với số CPU (`nproc`)",
        "Cho phép chỉnh ngưỡng qua biến môi trường (ví dụ `DISK_THRESHOLD=80`)",
        "In cảnh báo và thoát với exit code khác 0 khi vượt ngưỡng",
        "Thử làm đầy disk bằng `fallocate -l 1G /tmp/bigfile` để kiểm chứng cảnh báo",
      ],
    },
    {
      id: "systemd-app-service",
      title: "Chạy app như một service",
      description: "Biến một web app đơn giản thành systemd service tự khởi động lại khi crash.",
      steps: [
        "Viết app nhỏ (vd `python3 -m http.server 8080` hoặc Node) chạy dưới user không phải root",
        "Tạo `/etc/systemd/system/my-app.service` với `User=`, `WorkingDirectory=`, `Restart=on-failure`",
        "`sudo systemctl daemon-reload && sudo systemctl enable --now my-app`",
        "Xem log: `journalctl -u my-app -f`",
        "Giết tiến trình bằng `kill -9 <PID>` và quan sát systemd tự khởi động lại",
        "Reboot VM và xác nhận app tự chạy lại",
      ],
    },
  ],
  deliverable: "Một repo Git chứa backup.sh, healthcheck.sh, file .service/.timer và README hướng dẫn cài đặt trên VM mới.",
  successCriteria: "Không cần GUI; tự debug được tình huống 'service không start' chỉ bằng systemctl status và journalctl; SSH chỉ vào được bằng key.",
  resources: [
    { title: "The Linux Command Line (William Shotts, miễn phí)", url: "https://linuxcommand.org/tlcl.php", kind: "book" },
    { title: "Linux Journey", url: "https://linuxjourney.com/", kind: "course" },
    { title: "OverTheWire: Bandit (luyện CLI qua game)", url: "https://overthewire.org/wargames/bandit/", kind: "practice" },
    { title: "ShellCheck — kiểm tra lỗi bash script", url: "https://www.shellcheck.net/", kind: "tool" },
    { title: "systemd.service man page", url: "https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html", kind: "doc" },
    { title: "explainshell — giải thích từng phần của một lệnh", url: "https://explainshell.com/", kind: "tool" },
  ],
  quiz: [
    {
      id: "fhs-config",
      question: "File cấu hình của Nginx trên hầu hết bản Linux nằm ở đâu?",
      options: ["/bin/nginx", "/etc/nginx/nginx.conf", "/home/nginx/config", "/tmp/nginx.conf"],
      answerIndex: 1,
      explanation: "/etc là 'phòng ban quản lý' chứa cấu hình toàn hệ thống. /bin chứa chương trình, /tmp là bàn nháp.",
    },
    {
      id: "logs-location",
      question: "Website báo lỗi, bạn muốn xem log của hệ thống. Thư mục nào nên xem đầu tiên?",
      options: ["/var/log", "/usr/bin", "/root", "/etc/ssh"],
      answerIndex: 0,
      explanation: "/var chứa dữ liệu thay đổi liên tục; /var/log là 'sổ nhật ký' của hệ thống và ứng dụng.",
    },
    {
      id: "chmod-750",
      question: "`chmod 750 deploy.sh` nghĩa là gì?",
      options: [
        "Mọi người đều đọc, sửa, chạy được",
        "Owner: đọc+sửa+chạy; group: đọc+chạy; others: không gì cả",
        "Owner: chỉ đọc; group: sửa; others: chạy",
        "File bị khoá hoàn toàn",
      ],
      answerIndex: 1,
      explanation: "7 = 4+2+1 (rwx), 5 = 4+1 (r-x), 0 = --- . Mỗi chữ số lần lượt cho owner, group, others.",
    },
    {
      id: "least-privilege",
      question: "Vì sao không nên chạy ứng dụng web bằng user root?",
      options: [
        "Vì root chạy chậm hơn",
        "Vì root không đọc được file log",
        "Vì nếu app bị hack, kẻ tấn công có toàn quyền trên cả máy",
        "Vì systemd không cho phép",
      ],
      answerIndex: 2,
      explanation: "Nguyên tắc least privilege: chỉ cấp đúng quyền cần thiết. Root = chìa khoá vạn năng của cả toà nhà.",
    },
    {
      id: "systemd-restart",
      question: "Dòng nào trong file .service giúp app tự chạy lại khi bị crash?",
      options: ["WantedBy=multi-user.target", "Restart=on-failure", "ExecStart=/usr/bin/app", "User=app"],
      answerIndex: 1,
      explanation: "Restart=on-failure bảo systemd khởi động lại khi tiến trình thoát với lỗi. WantedBy liên quan tới việc bật cùng máy (enable).",
    },
    {
      id: "journalctl",
      question: "Lệnh nào xem log theo thời gian thực của service my-app?",
      options: ["cat my-app.log", "systemctl log my-app", "journalctl -u my-app -f", "tail /etc/my-app"],
      answerIndex: 2,
      explanation: "journalctl đọc 'sổ ghi' của journald; -u chọn unit, -f (follow) theo dõi dòng mới liên tục.",
    },
    {
      id: "pipe-meaning",
      question: "Trong `cat access.log | grep 500 | wc -l`, dấu `|` làm gì?",
      options: [
        "Chạy 3 lệnh song song không liên quan",
        "Đưa output của lệnh trước làm input cho lệnh sau",
        "Ghi kết quả vào file",
        "Chạy lệnh sau chỉ khi lệnh trước thành công",
      ],
      answerIndex: 1,
      explanation: "Pipe nối stdout của lệnh trước vào stdin của lệnh sau — như dây chuyền. Ghi file là `>`, chạy khi thành công là `&&`.",
    },
    {
      id: "sort-uniq",
      question: "Vì sao thường phải `sort` trước khi `uniq -c`?",
      options: ["uniq chỉ gộp các dòng trùng nằm cạnh nhau", "sort làm uniq chạy nhanh hơn một chút", "uniq bắt buộc input có thứ tự chữ cái", "Không cần, chỉ là thói quen"],
      answerIndex: 0,
      explanation: "uniq chỉ so sánh dòng liền kề. sort xếp các dòng giống nhau đứng cạnh nhau để uniq đếm đúng.",
    },
    {
      id: "set-euo-pipefail",
      question: "`set -euo pipefail` ở đầu bash script có tác dụng chính là gì?",
      options: ["Tăng tốc script", "Làm script dừng ngay khi có lỗi, biến chưa khai báo hoặc lệnh trong pipe thất bại", "Bật chế độ debug in từng lệnh", "Cho phép script chạy không cần quyền"],
      answerIndex: 1,
      explanation: "-e dừng khi lỗi, -u báo lỗi biến chưa đặt, pipefail làm cả pipe thất bại nếu một lệnh bên trong lỗi. In từng lệnh là `set -x`.",
    },
    {
      id: "ssh-private-key",
      question: "Khi dùng SSH key, file nào tuyệt đối không được chia sẻ hoặc copy lên server?",
      options: ["id_ed25519.pub", "authorized_keys", "id_ed25519 (private key)", "known_hosts"],
      answerIndex: 2,
      explanation: "Private key là chìa riêng của bạn. Public key (.pub) mới là thứ được đặt vào authorized_keys trên server.",
    },
  ],
};
