import type { ModuleDefinition } from "@/content/content-types";

export const sd02NetworkingCommunicationModule: ModuleDefinition = {
  id: "sd02",
  slug: "sd02-networking-communication",
  phaseId: "sd-phase-0",
  order: 2,
  weeks: "Tuần 3",
  title: "Networking & giao tiếp giữa service",
  emoji: "📡",
  eli5Summary:
    "Các service nói chuyện với nhau như người gọi điện, gửi thư hay bật bộ đàm. Module này giúp bạn hiểu mỗi cuộc gọi tốn bao nhiêu thời gian bắt máy, khi nào nên gửi thư (REST), gọi đường dây nóng (gRPC) hay giữ bộ đàm luôn mở (WebSocket).",
  objectives: [
    "Phân tích thời gian của một request qua DNS, TCP, TLS, HTTP và giải thích lợi ích của keep-alive, connection pooling",
    "So sánh HTTP/1.1, HTTP/2, HTTP/3 và chỉ ra head-of-line blocking xảy ra ở tầng nào",
    "Chọn REST, gRPC hay GraphQL cho từng loại client và luồng giao tiếp",
    "Chọn polling, long polling, SSE hay WebSocket cho tính năng realtime và ước lượng chi phí kết nối",
    "Giải thích TTL, GeoDNS, anycast và ảnh hưởng của chúng tới failover",
    "Mở rộng sd-playground với service gRPC và endpoint SSE/WebSocket, đo bằng k6 và curl",
  ],
  lessons: [
    { slug: "request-journey-dns-tcp-tls", title: "Hành trình một request: DNS → TCP → TLS → HTTP", minutes: 45, summary: "Mỗi lần bắt tay tốn một round trip — keep-alive và pooling tiết kiệm chúng." },
    { slug: "http1-http2-http3", title: "HTTP/1.1 → HTTP/2 → HTTP/3", minutes: 40, summary: "Multiplexing, head-of-line blocking và vì sao HTTP/3 chạy trên UDP." },
    { slug: "rest-grpc-graphql", title: "REST vs gRPC vs GraphQL", minutes: 50, summary: "Ba cách thiết kế API — chọn theo client, contract và chi phí vận hành." },
    { slug: "realtime-polling-sse-websocket", title: "Realtime: polling, SSE, WebSocket", minutes: 50, summary: "Hỏi liên tục, chờ tin, hay giữ đường dây mở — mỗi kiểu một cái giá." },
    { slug: "dns-for-scale-geodns-anycast", title: "DNS cho scale: TTL, GeoDNS, anycast", minutes: 35, summary: "Đưa user tới server gần nhất và chuyển hướng khi một region sập." },
  ],
  labs: [
    {
      id: "rest-vs-grpc-benchmark",
      title: "Cùng một API: REST vs gRPC",
      description: "Viết API báo giá cổ phiếu bằng REST (JSON) và gRPC trong playground, đo payload size và p95 latency bằng k6.",
      steps: [
        "Viết `proto/quote.proto` với `service QuoteService { rpc GetQuote(QuoteRequest) returns (QuoteReply); }`",
        "Thêm service `quote-grpc` (cổng 50051) vào `docker-compose.yml` dùng `@grpc/grpc-js` + `@grpc/proto-loader`; giữ `GET /api/quotes/:symbol` REST trong `app`",
        "So sánh payload: `curl -s localhost:3000/api/quotes/VNM | wc -c` với độ dài protobuf (`QuoteReply.encode(msg).finish().length` bằng protobufjs)",
        "Viết `k6/rest.js` và `k6/grpc.js` (dùng `k6/net/grpc`, `client.load()` ở init, `connect` một lần mỗi VU); chạy cùng 50 VU trong 1 phút",
        "Ghi bảng: payload, p95 `http_req_duration` vs `grpc_req_duration`, request/giây; giải thích vì sao chênh lệch nhỏ khi payload nhỏ",
      ],
    },
    {
      id: "stock-ticker-three-ways",
      title: "Giá cổ phiếu giả lập: polling vs SSE vs WebSocket",
      description: "Làm cùng một luồng cập nhật giá 3 kiểu, so sánh số request và độ trễ nhận update.",
      steps: [
        "Trong `app`, tạo generator đổi giá ngẫu nhiên mỗi 1–5 giây, kèm `updatedAt`",
        "Polling: `GET /api/price` và trang HTML gọi `fetch` mỗi 3 giây; SSE: `GET /stream/price` với `Content-Type: text/event-stream`; WebSocket: `ws://localhost:3000/ws/price` bằng thư viện `ws`",
        "Thêm `proxy_buffering off;` cho SSE và header `Upgrade`/`Connection` cho WebSocket trong `nginx/default.conf`, rồi `docker compose restart nginx`",
        "Mở 3 trang trong 2 phút; đếm request bằng `docker compose logs nginx | grep -c /api/price` và ghi độ trễ `Date.now() - updatedAt` ở client",
        "Lập bảng: số request, độ trễ trung bình, số kết nối mở; kết luận kiểu nào hợp cho chat, feed thông báo, bảng giá",
      ],
    },
    {
      id: "keepalive-http2-inspection",
      title: "Soi keep-alive và HTTP/2 multiplexing",
      description: "Dùng curl và DevTools để thấy connection reuse và nhiều request chạy chung một connection.",
      steps: [
        "`curl -s -o /dev/null -o /dev/null -w '%{num_connects}\\n' localhost:8080/health localhost:8080/health` — lần hai phải in `0` (tái dùng kết nối)",
        "Đo từng pha: `curl -s -o /dev/null -w 'dns=%{time_namelookup} tcp=%{time_connect} tls=%{time_appconnect} ttfb=%{time_starttransfer}\\n' https://example.com`",
        "`curl -sI --http1.1` và `--http2` tới một site công khai, in `%{http_version}` để xác nhận protocol được đàm phán",
        "Mở DevTools → Network, bật cột Protocol và Connection ID trên một trang nhiều asset; so sánh số Connection ID giữa `h2` và `http/1.1`",
      ],
    },
    {
      id: "dns-ttl-anycast-exploration",
      title: "Quan sát TTL và anycast ngoài đời",
      description: "Đọc TTL của DNS record, thấy TTL đếm ngược trong cache và nhận diện PoP anycast bạn đang dùng.",
      steps: [
        "`dig +noall +answer www.cloudflare.com` hai lần cách nhau 10 giây qua cùng resolver — quan sát TTL giảm dần",
        "`dig +short @1.1.1.1 CH TXT id.server` và `curl -s https://www.cloudflare.com/cdn-cgi/trace | grep colo` để biết PoP anycast phục vụ bạn",
        "Nếu có VPN: đổi vị trí và lặp lại, ghi IP trả về và `colo` — IP anycast giữ nguyên, PoP thay đổi",
        "Viết kế hoạch migrate DNS: hạ TTL từ 86400 xuống 60 trước bao lâu, đổi record lúc nào, nâng TTL lại khi nào",
      ],
    },
  ],
  deliverable: "Báo cáo đo đạc REST vs gRPC (payload, p95), demo bảng giá chạy 3 kiểu polling/SSE/WebSocket kèm bảng so sánh, và ghi chú keep-alive/HTTP/2 từ curl + DevTools.",
  successCriteria: "Giải thích được vì sao chat dùng WebSocket còn feed thông báo có thể chỉ cần SSE; chỉ ra được round trip nào keep-alive tiết kiệm và HOL blocking của HTTP/2 nằm ở đâu.",
  resources: [
    { title: "High Performance Browser Networking (Ilya Grigorik, miễn phí)", url: "https://hpbn.co/", kind: "book" },
    { title: "gRPC documentation", url: "https://grpc.io/docs/", kind: "doc" },
    { title: "MDN — Server-sent events", url: "https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events", kind: "doc" },
    { title: "MDN — WebSockets API", url: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API", kind: "doc" },
    { title: "GraphQL — Learn", url: "https://graphql.org/learn/", kind: "doc" },
    { title: "Cloudflare Learning Center (DNS, HTTP/3, anycast)", url: "https://www.cloudflare.com/learning/", kind: "course" },
    { title: "Everything curl", url: "https://everything.curl.dev/", kind: "tool" },
    { title: "Grafana k6 docs (HTTP, gRPC, WebSocket)", url: "https://grafana.com/docs/k6/latest/", kind: "tool" },
  ],
  quiz: [
    {
      id: "keepalive-saves-handshakes",
      question: "Service ở Singapore gọi payment API ở Frankfurt (RTT ~160ms) qua HTTPS, mỗi request mở kết nối mới. Cải tiến rẻ và hiệu quả nhất là gì?",
      options: [
        "Tăng timeout lên 30 giây",
        "Dùng connection pooling/keep-alive để bỏ bắt tay TCP + TLS mỗi request, tiết kiệm cỡ 2 RTT",
        "Chuyển sang gửi JSON nén bằng gzip",
        "Tắt TLS cho nhanh",
      ],
      answerIndex: 1,
      explanation: "Mỗi request mở kết nối mới giống mỗi câu nói lại gọi điện, chờ bắt máy, xác minh danh tính từ đầu. Giữ máy (keep-alive) thì chỉ còn thời gian nói — tiết kiệm ~320ms mỗi request ở RTT 160ms.",
    },
    {
      id: "http2-tcp-hol-blocking",
      question: "Website đã lên HTTP/2 nhưng trên mạng di động mất gói nhiều, tải trang vẫn giật. Nguyên nhân gốc là gì?",
      options: [
        "HTTP/2 không nén header",
        "HTTP/2 mở quá nhiều TCP connection",
        "Mọi stream đi chung một TCP connection; mất một gói làm TCP giữ lại dữ liệu của tất cả stream phía sau",
        "Server không bật keep-alive",
      ],
      answerIndex: 2,
      explanation: "HTTP/2 gộp mọi xe vào một làn đường (một TCP): một xe hỏng giữa đường thì cả làn đứng chờ, dù các xe khác không liên quan. Đó là head-of-line blocking ở tầng TCP.",
    },
    {
      id: "http3-core-difference",
      question: "Khác biệt cốt lõi giúp HTTP/3 tránh head-of-line blocking của HTTP/2 là gì?",
      options: [
        "Chạy trên QUIC (UDP): mỗi stream được đảm bảo thứ tự độc lập, mất gói ở stream này không chặn stream khác",
        "HTTP/3 bỏ hoàn toàn mã hoá",
        "HTTP/3 mở một TCP connection cho mỗi file",
        "HTTP/3 chỉ cho gửi một request mỗi lúc",
      ],
      answerIndex: 0,
      explanation: "QUIC chia đường thành nhiều làn riêng cho từng stream: một xe hỏng chỉ làm làn đó chờ. TLS 1.3 được tích hợp sẵn nên bắt tay cũng ít round trip hơn.",
    },
    {
      id: "grpc-internal-services",
      question: "30 microservice nội bộ gọi nhau với lưu lượng lớn, cần contract kiểu chặt, sinh client cho Go/Java/TypeScript và có streaming. Lựa chọn phù hợp nhất?",
      options: ["GraphQL cho mọi service", "REST với JSON tự viết client", "Long polling", "gRPC với protobuf"],
      answerIndex: 3,
      explanation: "gRPC như đường dây nóng nội bộ có kịch bản cố định: file `.proto` là hợp đồng, client sinh tự động, binary gọn, hỗ trợ streaming. Nhược điểm (browser cần gRPC-Web, khó debug bằng curl) ít quan trọng trong nội bộ.",
    },
    {
      id: "graphql-mobile-screens",
      question: "App mobile có nhiều màn hình, mỗi màn cần dữ liệu từ 4–5 resource khác nhau, mạng yếu, team frontend thay đổi UI hàng tuần. Hướng hợp lý?",
      options: [
        "Mỗi màn hình gọi 5 REST endpoint tuần tự",
        "Cho mobile gọi thẳng gRPC tới từng microservice",
        "GraphQL (hoặc một BFF) để client lấy đúng các field cần trong một round trip",
        "WebSocket cho mọi thao tác đọc",
      ],
      answerIndex: 2,
      explanation: "GraphQL giống gọi món theo thực đơn tự chọn: một lần gọi, lấy đúng thứ cần — giảm round trip và over-fetching trên mạng yếu. Đổi lại phải lo N+1, rate limit theo độ phức tạp query và caching khó hơn.",
    },
    {
      id: "graphql-n-plus-one",
      question: "Query GraphQL lấy 50 đơn hàng kèm thông tin user khiến server chạy 51 query SQL. Vấn đề và cách sửa?",
      options: [
        "N+1 query; gom các lần lấy user thành một batch bằng DataLoader (`WHERE id IN (...)`)",
        "Thiếu index; thêm index cho mọi cột",
        "Do HTTP/1.1; nâng lên HTTP/2",
        "Do JSON; đổi sang protobuf",
      ],
      answerIndex: 0,
      explanation: "Resolver 'user' được gọi riêng cho từng đơn — như bồi bàn chạy vào bếp 50 lần cho 50 bàn. DataLoader gom lại thành một chuyến trong cùng tick.",
    },
    {
      id: "sse-for-notifications",
      question: "Tính năng hiển thị thông báo mới cho user web: chỉ server đẩy xuống, client không cần gửi gì qua kênh đó. Lựa chọn đơn giản mà đủ?",
      options: ["WebSocket với giao thức tự định nghĩa", "Server-Sent Events (SSE)", "Polling mỗi 500ms", "gRPC bidirectional streaming từ browser"],
      answerIndex: 1,
      explanation: "SSE như loa phát thanh phường: một chiều, chạy trên HTTP bình thường, trình duyệt tự nối lại và gửi `Last-Event-ID`. Không cần bộ đàm hai chiều khi user chỉ nghe.",
    },
    {
      id: "chat-needs-websocket",
      question: "App chat cần gửi tin, typing indicator và read receipt hai chiều với độ trễ thấp. Vì sao WebSocket hợp hơn SSE?",
      options: [
        "Vì SSE không chạy được qua HTTPS",
        "Vì WebSocket không cần server giữ kết nối",
        "Vì WebSocket tự đảm bảo tin nhắn không bao giờ mất",
        "Vì cần kênh hai chiều liên tục; client gửi nhiều sự kiện nhỏ trên cùng kết nối, không tốn một HTTP request mỗi lần",
      ],
      answerIndex: 3,
      explanation: "Chat là bộ đàm: cả hai bên nói liên tục. WebSocket vẫn không đảm bảo giao tin — ứng dụng phải có ack, sequence và đồng bộ lại khi reconnect.",
    },
    {
      id: "polling-cost-estimate",
      question: "1 triệu user online, client polling mỗi 5 giây để kiểm tra tin mới; trung bình mỗi user chỉ có 1 cập nhật mỗi 10 phút. Tải đọc cỡ bao nhiêu và phần lớn là gì?",
      options: [
        "Cỡ 2.000 QPS, đa số có dữ liệu",
        "Cỡ 20.000 QPS, đa số có dữ liệu",
        "Cỡ 200.000 QPS, hơn 99% response là 'không có gì mới'",
        "Cỡ 5 triệu QPS, đa số lỗi",
      ],
      answerIndex: 2,
      explanation: "10⁶ / 5 = 200.000 QPS. 10 phút = 600 giây = 120 lần hỏi mới có 1 lần có tin ⇒ hơn 99% response rỗng. Như hỏi bưu điện 'có thư chưa?' mỗi 5 giây — tốn công cho cả hai bên.",
    },
    {
      id: "dns-ttl-migration",
      question: "Record `api.example.com` có TTL 86400. Bạn cần chuyển sang load balancer mới và muốn user chuyển trong vài phút. Làm gì?",
      options: [
        "Đổi record ngay; mọi resolver sẽ cập nhật trong vài giây",
        "Hạ TTL xuống ~60 giây ít nhất 1 ngày trước khi đổi, đổi record, giữ server cũ chạy một thời gian, rồi nâng TTL lại",
        "Đặt TTL = 0 vĩnh viễn",
        "Xoá record rồi tạo lại",
      ],
      answerIndex: 1,
      explanation: "TTL là hạn dùng của tờ ghi địa chỉ trong sổ tay mỗi resolver: sổ cũ ghi 'dùng 1 ngày' thì phải chờ nó hết hạn. Hạ TTL trước, và vẫn giữ nhà cũ mở cửa cho những resolver không tôn trọng TTL.",
    },
  ],
};
