import type { ModuleDefinition } from "@/content/content-types";

export const m07AwsNetworkingComputeModule: ModuleDefinition = {
  id: "m07",
  slug: "m07-aws-networking-compute",
  phaseId: "phase-2",
  order: 7,
  weeks: "Tuần 11–12",
  title: "AWS Networking & Compute",
  emoji: "🌐",
  eli5Summary:
    "Bạn xây một khu đô thị riêng trên cloud: dãy mặt tiền đón khách, dãy phía trong cất đồ quý, bảo vệ ở cổng và lễ tân ở từng căn. Rồi mở một quán có chị điều phối khách và quản lý tự kê thêm bàn khi đông — tắt hẳn một dãy phố, quán vẫn phục vụ.",
  objectives: [
    "Thiết kế VPC 2 AZ với public/private subnet, Internet Gateway, NAT Gateway và route table đúng",
    "Phân biệt Security Group và NACL, dùng VPC endpoint để giảm chi phí và giữ traffic trong mạng AWS",
    "Chạy EC2 từ AMI + user data + instance profile và truy cập chỉ bằng SSM Session Manager",
    "Đặt ALB phía trước Auto Scaling Group, cấu hình health check và scaling policy chịu được mất một AZ",
    "Gắn tên miền và HTTPS bằng Route 53 + ACM, hiểu vai trò của CloudFront và ECS Fargate",
  ],
  lessons: [
    { slug: "vpc-subnets-route-tables", title: "VPC, subnet & route table", minutes: 50, summary: "Khu đô thị riêng: dãy mặt tiền, dãy phía trong và bảng chỉ đường." },
    { slug: "security-groups-nacls-endpoints", title: "Security Group, NACL & VPC endpoint", minutes: 45, summary: "Bảo vệ cổng khu phố vs lễ tân từng căn — stateful và stateless." },
    { slug: "ec2-ami-user-data-ssm", title: "EC2, AMI, user data & SSM Session Manager", minutes: 50, summary: "Thuê xe tự lái theo mẫu có sẵn, vào xe mà không cần mở cửa port 22." },
    { slug: "elastic-load-balancing", title: "Elastic Load Balancing: ALB, NLB & health check", minutes: 45, summary: "Chị điều phối quầy khám bệnh chỉ đưa khách vào phòng còn khám được." },
    { slug: "auto-scaling-ecs-fargate", title: "Auto Scaling Group & ECS Fargate", minutes: 50, summary: "Kê thêm bàn giờ cao điểm, dẹp bớt khi vắng — và chạy container không cần server." },
    { slug: "route53-acm-cloudfront", title: "Route 53, ACM & CloudFront", minutes: 45, summary: "Danh bạ, giấy phép HTTPS và chuỗi cửa hàng tiện lợi ở khắp nơi." },
  ],
  labs: [
    {
      id: "vpc-two-az",
      title: "Dựng VPC 2 AZ bằng Console (ghi lại để làm Terraform)",
      description: "Tạo VPC theo bảng subnet đã tính ở M02, ghi chép từng bước và mọi ID để M10 viết lại bằng code.",
      steps: [
        "Tạo VPC `10.0.0.0/16`, bật DNS hostnames; tag `Project=devops-lab` cho mọi tài nguyên",
        "Tạo 4 subnet: `public-a 10.0.1.0/24`, `public-b 10.0.2.0/24`, `private-a 10.0.11.0/24`, `private-b 10.0.12.0/24` ở 2 AZ",
        "Tạo và gắn Internet Gateway; route table public có `0.0.0.0/0 → igw`, gắn cho 2 public subnet",
        "Tạo NAT Gateway (Elastic IP) ở `public-a`; route table private có `0.0.0.0/0 → nat`, gắn cho 2 private subnet",
        "Thêm gateway endpoint S3 vào route table private",
        "Kiểm chứng bằng `aws ec2 describe-route-tables` và ghi lại sơ đồ + bảng ID vào README",
      ],
    },
    {
      id: "alb-asg-https",
      title: "ASG trong private subnet, ALB public, HTTPS bằng ACM",
      description: "Chạy app mẫu tự scale phía sau Application Load Balancer có certificate ACM.",
      steps: [
        "Tạo SG: `sg-alb` (443 từ Internet), `sg-app` (80 chỉ từ `sg-alb`), không rule SSH nào",
        "Tạo launch template: AMI Amazon Linux 2023, `t3.small`, `sg-app`, instance profile SSM, user data cài nginx + endpoint `/health`, IMDSv2 bắt buộc",
        "Tạo target group `web-tg` với health check `/health`, rồi ALB internet-facing ở 2 public subnet",
        "Xin cert ACM (DNS validation) cho `app.<domain>`, tạo listener 443 và listener 80 redirect sang HTTPS",
        "Tạo ASG `web-asg` (min 2 / max 6) ở 2 private subnet, gắn `web-tg`, `--health-check-type ELB`",
        "Tạo Alias record Route 53 trỏ `app.<domain>` về ALB; `curl -I https://app.<domain>` trả 200",
      ],
    },
    {
      id: "ssm-only-access",
      title: "Truy cập instance chỉ qua SSM Session Manager",
      description: "Chứng minh không cần port 22, không SSH key, không bastion mà vẫn debug được instance.",
      steps: [
        "Kiểm tra role của instance có `AmazonSSMManagedInstanceCore` và subnet private có đường ra qua NAT (hoặc interface endpoints `ssm`, `ssmmessages`, `ec2messages`)",
        "Cài Session Manager plugin trên laptop",
        "`aws ssm describe-instance-information` thấy instance `Online`",
        "`aws ssm start-session --target <instance-id>` rồi xem `/var/log/cloud-init-output.log`",
        "Chạy lệnh tìm SG mở port 22 (`aws ec2 describe-security-groups --filters Name=ip-permission.from-port,Values=22`) → kết quả rỗng",
      ],
    },
    {
      id: "load-test-scaling",
      title: "Load test để scale-out, rồi quan sát scale-in và mất AZ",
      description: "Kích hoạt target tracking policy bằng tải thật và kiểm chứng khả năng chịu lỗi một AZ.",
      steps: [
        "Thêm policy target tracking `ASGAverageCPUUtilization` = 50 bằng `aws autoscaling put-scaling-policy`",
        "Chạy load test: `k6 run load.js` hoặc `hey -z 10m -c 200 https://app.<domain>/`",
        "Theo dõi `aws autoscaling describe-scaling-activities` và CloudWatch alarm: desired tăng, target mới healthy",
        "Dừng tải, quan sát scale-in (chậm hơn) về lại min 2",
        "Terminate toàn bộ instance ở một AZ trong khi chạy `curl` lặp mỗi giây — app vẫn trả 200, ASG tạo instance thay thế",
        "Dọn dẹp: xoá ASG, ALB, NAT Gateway, release Elastic IP để dừng tính phí",
      ],
    },
  ],
  deliverable:
    "VPC 2 AZ + ALB (HTTPS bằng ACM) + ASG trong private subnet, truy cập chỉ qua SSM; README có sơ đồ kiến trúc, bảng subnet/ID, các bước Console đã ghi lại và kết quả load test.",
  successCriteria: "Tắt 1 AZ (terminate mọi instance ở AZ đó) → app vẫn phục vụ qua HTTPS; không Security Group nào mở port 22.",
  resources: [
    { title: "Amazon VPC User Guide", url: "https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html", kind: "doc" },
    { title: "Amazon EC2 User Guide", url: "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/concepts.html", kind: "doc" },
    { title: "AWS Systems Manager Session Manager", url: "https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html", kind: "doc" },
    { title: "Application Load Balancer Guide", url: "https://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html", kind: "doc" },
    { title: "Amazon EC2 Auto Scaling User Guide", url: "https://docs.aws.amazon.com/autoscaling/ec2/userguide/what-is-amazon-ec2-auto-scaling.html", kind: "doc" },
    { title: "Route 53: choosing a routing policy", url: "https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy.html", kind: "doc" },
    { title: "Adrian Cantrill – AWS Certified Solutions Architect Associate", url: "https://learn.cantrill.io/", kind: "course" },
    { title: "Grafana k6 — load testing", url: "https://grafana.com/docs/k6/latest/", kind: "tool" },
  ],
  quiz: [
    {
      id: "public-subnet-definition",
      question: "Điều gì làm một subnet trở thành public subnet?",
      options: [
        "Tên subnet có chữ public",
        "Route table của subnet có route 0.0.0.0/0 tới Internet Gateway",
        "Subnet có NAT Gateway",
        "Security Group cho phép 0.0.0.0/0",
      ],
      answerIndex: 1,
      explanation: "Public hay private là do bảng chỉ đường (route table) quyết định, không phải biển tên. NAT Gateway phục vụ subnet private đi ra ngoài.",
    },
    {
      id: "nat-gateway-az-failure",
      question: "Hai private subnet ở AZ a và b cùng dùng một NAT Gateway đặt ở public subnet AZ a. AZ a gặp sự cố. Hậu quả với instance ở private subnet AZ b?",
      options: [
        "Không ảnh hưởng, NAT Gateway là dịch vụ regional",
        "Instance ở AZ b bị terminate",
        "Instance ở AZ b mất đường ra Internet vì NAT Gateway là tài nguyên zonal",
        "Traffic tự chuyển sang Internet Gateway",
      ],
      answerIndex: 2,
      explanation: "Shipper đứng ở dãy phố A mà dãy A bị phong toả thì dãy B cũng không ai đi chợ giúp. Production nên có một NAT Gateway mỗi AZ.",
    },
    {
      id: "nacl-ephemeral-timeout",
      question: "Sau khi gắn NACL tuỳ chỉnh (inbound allow 443) cho subnet web, client gọi HTTPS bị timeout dù SG cho phép 443. Nguyên nhân khả dĩ nhất?",
      options: [
        "NACL thiếu rule outbound cho ephemeral ports 1024–65535",
        "Security Group thiếu rule outbound 443",
        "ALB không hỗ trợ NACL",
        "Cần thêm route tới NAT Gateway",
      ],
      answerIndex: 0,
      explanation: "NACL stateless như bảo vệ không nhớ mặt: response đi ra tới cổng tạm của client phải có rule outbound riêng. SG thì stateful nên tự cho response qua.",
    },
    {
      id: "s3-gateway-endpoint-cost",
      question: "Ứng dụng trong private subnet đọc/ghi hàng trăm GB lên S3 mỗi ngày qua NAT Gateway, hoá đơn NAT rất cao. Cách giảm chi phí đơn giản nhất?",
      options: [
        "Chuyển instance sang public subnet và mở SG",
        "Thêm gateway VPC endpoint cho S3 vào route table private",
        "Dùng NLB phía trước S3",
        "Tăng băng thông NAT Gateway",
      ],
      answerIndex: 1,
      explanation: "Gateway endpoint cho S3 là lối đi nội bộ không qua shipper NAT, không tính phí endpoint và không tính phí xử lý dữ liệu của NAT.",
    },
    {
      id: "ssm-agent-not-online",
      question: "Instance trong private subnet không có NAT Gateway, đã có role AmazonSSMManagedInstanceCore nhưng không hiện Online trong Session Manager. Cần thêm gì?",
      options: [
        "Mở inbound port 22 trong Security Group",
        "Gắn Elastic IP cho instance",
        "Cài SSH key vào instance",
        "Interface VPC endpoints cho ssm, ssmmessages (và ec2messages theo tài liệu) với SG cho phép HTTPS 443",
      ],
      answerIndex: 3,
      explanation: "SSM Agent phải gọi RA endpoint Systems Manager qua HTTPS. Không có NAT thì cần interface endpoints. Port 22 hoàn toàn không liên quan.",
    },
    {
      id: "user-data-first-boot",
      question: "Bạn sửa user data của một EC2 đang chạy rồi reboot, nhưng script mới không chạy. Vì sao?",
      options: [
        "Mặc định cloud-init chỉ chạy user data ở lần boot đầu tiên của instance",
        "User data chỉ chạy trên Windows",
        "Phải đổi instance type thì user data mới chạy",
        "User data bị giới hạn 1 KB",
      ],
      answerIndex: 0,
      explanation: "Tờ ghi chú trên vô-lăng chỉ dành cho lần lái đầu. Cách chuẩn là cập nhật launch template và thay instance mới (instance refresh).",
    },
    {
      id: "alb-path-routing",
      question: "Cần gửi `/api/*` tới service backend và mọi đường dẫn khác tới frontend, dùng chung một tên miền HTTPS. Chọn gì?",
      options: [
        "Network Load Balancer với 2 listener",
        "Hai Route 53 record khác nhau cho cùng tên miền",
        "Application Load Balancer với listener rule theo path tới 2 target group",
        "CloudFront invalidation",
      ],
      answerIndex: 2,
      explanation: "Chị ALB đọc giấy khám (HTTP path) để chỉ đúng phòng. NLB làm việc ở tầng 4, không đọc được path.",
    },
    {
      id: "asg-elb-health-check",
      question: "App trên một instance bị treo, ALB đánh dấu target unhealthy, nhưng ASG không thay instance đó. Nguyên nhân?",
      options: [
        "ASG đang dùng HealthCheckType=EC2, chỉ xem status check của máy",
        "Target group chưa bật cross-zone",
        "MaxSize quá nhỏ",
        "Instance thiếu Elastic IP",
      ],
      answerIndex: 0,
      explanation: "Máy vẫn 'thở' nên EC2 status check vẫn OK. Bật HealthCheckType=ELB để ASG dùng kết quả health check của ALB và thay máy treo.",
    },
    {
      id: "scaling-policy-choice",
      question: "Web app có tải thay đổi khó đoán trong ngày. Nhóm muốn giữ mỗi instance xử lý khoảng 1000 request/phút mà không phải tự tính ngưỡng từng bậc. Chọn policy nào?",
      options: [
        "Scheduled scaling mỗi giờ",
        "Target tracking theo ALBRequestCountPerTarget",
        "Tăng MinSize lên bằng MaxSize",
        "Simple scaling với một alarm CPU",
      ],
      answerIndex: 1,
      explanation: "Target tracking giống quản lý giữ 'mỗi bàn không quá bận': chỉ cần đặt giá trị mục tiêu, policy tự tạo alarm và tính số instance.",
    },
    {
      id: "cloudfront-cert-region",
      question: "Certificate ACM cho app.example.com tạo ở ap-southeast-1 dùng tốt trên ALB, nhưng không chọn được khi cấu hình CloudFront. Cách xử lý?",
      options: [
        "Export cert rồi import vào CloudFront",
        "Chuyển CloudFront sang region ap-southeast-1",
        "Dùng CNAME thay vì alias",
        "Request thêm một certificate cho cùng domain ở us-east-1",
      ],
      answerIndex: 3,
      explanation: "CloudFront là cửa hàng tiện lợi toàn cầu, chỉ nhận 'giấy phép' từ us-east-1. Hệ thống dùng cả CloudFront và ALB thường có hai cert ở hai region.",
    },
    {
      id: "route53-apex-alias",
      question: "Muốn tên miền gốc example.com (zone apex) trỏ tới ALB. Loại bản ghi nào dùng được?",
      options: [
        "CNAME tới DNS name của ALB",
        "A record với IP hiện tại của ALB",
        "Alias record (A/AAAA) tới ALB",
        "MX record",
      ],
      answerIndex: 2,
      explanation: "CNAME không được đặt ở zone apex, còn IP của ALB thay đổi. Alias record của Route 53 trỏ thẳng tới ALB và tự theo IP mới.",
    },
    {
      id: "fargate-vs-ec2",
      question: "Team nhỏ muốn chạy container API sau ALB, không muốn vá OS hay quản lý cluster node. Lựa chọn phù hợp nhất trên AWS?",
      options: [
        "ECS service với launch type Fargate",
        "EC2 Auto Scaling Group tự cài Docker",
        "EKS với self-managed node group",
        "Một EC2 lớn chạy docker compose",
      ],
      answerIndex: 0,
      explanation: "Fargate như thuê suất ăn từ bếp trung tâm: chỉ khai báo task (CPU/RAM/image), AWS lo máy bên dưới. Các lựa chọn khác đều bắt bạn quản lý EC2.",
    },
  ],
};
