import type { ModuleDefinition } from "@/content/content-types";

export const m17DevsecopsModule: ModuleDefinition = {
  id: "m17",
  slug: "m17-devsecops",
  phaseId: "phase-5",
  order: 17,
  weeks: "Tuần 26–28",
  title: "DevSecOps & Supply Chain Security",
  emoji: "🛡️",
  eli5Summary:
    "Trước đây bảo vệ chỉ đứng gác ở cửa quán (kiểm tra lúc production). DevSecOps giống như kiểm tra nguyên liệu ngay từ chợ, dán tem niêm phong lên từng thùng hàng và chỉ cho vào bếp những thùng có tem thật — bắt lỗi càng sớm càng rẻ.",
  objectives: [
    "Giải thích shift-left security và vì sao phát hiện lỗi sớm rẻ hơn nhiều lần so với phát hiện ở production",
    "Thêm SAST, SCA, secret scanning, DAST và IaC scanning vào pipeline, biết đọc và ưu tiên kết quả quét",
    "Sinh SBOM bằng Syft, ký image bằng cosign (keyless qua OIDC) và giải thích các cấp độ SLSA",
    "Viết policy as code bằng Kyverno để chặn image chưa ký, container chạy root, thiếu resource limits",
    "So sánh HashiCorp Vault và AWS Secrets Manager, thiết kế rotation cho secret",
    "Nêu vai trò của GuardDuty, Security Hub, KMS, WAF trong một kiến trúc AWS an toàn",
  ],
  lessons: [
    { slug: "shift-left-security", title: "Shift-left security & OWASP Top 10", minutes: 35, summary: "Bắt lỗi ở chợ nguyên liệu rẻ hơn bắt lỗi ở bàn ăn của khách." },
    { slug: "pipeline-security-scanners", title: "Scanner trong pipeline: SAST, SCA, secret, DAST, IaC", minutes: 50, summary: "5 trạm kiểm tra tự động trước khi code tới production." },
    { slug: "supply-chain-sbom-cosign-slsa", title: "Supply chain: SBOM, cosign & SLSA", minutes: 45, summary: "Nhãn thành phần, tem niêm phong và cấp độ tin cậy cho image." },
    { slug: "policy-as-code-kyverno", title: "Policy as code với Kyverno", minutes: 40, summary: "Người gác cổng tự động: chặn image chưa ký, chặn container chạy root." },
    { slug: "secrets-management-vault-aws", title: "Secrets management: Vault vs AWS Secrets Manager", minutes: 35, summary: "Két sắt cho mật khẩu — ai mở được, và tự đổi khoá định kỳ." },
    { slug: "aws-security-services-overview", title: "AWS security services: GuardDuty, Security Hub, KMS, WAF", minutes: 35, summary: "Camera an ninh, phòng điều hành, két sắt và bảo vệ cổng của AWS." },
  ],
  labs: [
    {
      id: "pipeline-scan-fail-on-critical",
      title: "Thêm gitleaks + Semgrep + Trivy + SBOM vào pipeline",
      description: "Mở rộng pipeline GitHub Actions từ M05: quét secret, SAST, image & IaC, sinh SBOM; fail build khi có lỗi CRITICAL.",
      steps: [
        "Thêm job `gitleaks detect --source . --no-git -v` chạy trước mọi job khác, fail pipeline nếu tìm thấy secret",
        "Thêm `semgrep --config auto --error` quét SAST cho code; xem lại và xử lý false positive bằng `# nosemgrep` có lý do",
        "Thêm `trivy fs --severity CRITICAL,HIGH --exit-code 1 .` quét dependency (SCA) trước khi build image",
        "Build xong, quét image: `trivy image --severity CRITICAL --exit-code 1 <registry>/checkout:${{ github.sha }}`",
        "Sinh SBOM: `syft <registry>/checkout:${{ github.sha }} -o cyclonedx-json=sbom.json` và upload làm artifact của pipeline",
        "Quét Terraform từ M10 bằng `checkov -d infra/ --compact` hoặc `trivy config infra/`, fail nếu có HIGH/CRITICAL chưa được suppress có lý do",
        "Xác nhận: cố tình commit một secret giả hoặc dependency có CVE cũ để thấy pipeline đỏ đúng như thiết kế",
      ],
    },
    {
      id: "cosign-keyless-kyverno-verify",
      title: "Ký image bằng cosign keyless & Kyverno chỉ cho chạy image đã ký",
      description: "Dùng GitHub OIDC để ký image không cần quản lý private key, và cấu hình Kyverno từ chối image chưa ký.",
      steps: [
        "Thêm quyền `permissions: { id-token: write }` cho job trong GitHub Actions workflow",
        "Ký image: `cosign sign --yes <registry>/checkout@sha256:<digest>` (keyless, dùng OIDC token của GitHub Actions làm danh tính)",
        "Xác minh thủ công: `cosign verify <registry>/checkout@sha256:<digest> --certificate-identity-regexp 'https://github.com/<org>/<repo>/.github/workflows/.*' --certificate-oidc-issuer https://token.actions.githubusercontent.com`",
        "Cài Kyverno: `helm install kyverno kyverno/kyverno -n kyverno --create-namespace`",
        "Áp dụng `ClusterPolicy` kind `verify-images` với `attestors.keyless.issuer` và `subject` khớp workflow repo của bạn",
        "Thử deploy một image CHƯA ký vào namespace có policy — xác nhận bị admission controller từ chối với thông báo rõ ràng",
        "Deploy lại image ĐÃ ký — xác nhận được chấp nhận",
      ],
    },
    {
      id: "kyverno-baseline-policies",
      title: "Kyverno: bắt buộc limits, cấm latest tag, cấm privileged",
      description: "Viết 3 policy nền tảng áp dụng cho mọi namespace ứng dụng.",
      steps: [
        "Policy 1 `require-resource-limits`: `validationFailureAction: Enforce`, từ chối Pod thiếu `resources.limits.cpu` hoặc `resources.limits.memory`",
        "Policy 2 `disallow-latest-tag`: từ chối image có tag `:latest` hoặc không có tag; bắt buộc digest hoặc tag cụ thể",
        "Policy 3 `disallow-privileged-and-root`: từ chối `securityContext.privileged: true` và bắt buộc `runAsNonRoot: true`",
        "Áp dụng ở chế độ `Audit` trước, chạy `kubectl get policyreport -A` xem vi phạm hiện có mà không chặn gì",
        "Sửa hết vi phạm hiện có, sau đó chuyển 3 policy sang `Enforce`",
        "Thử deploy một manifest cố tình vi phạm cả 3 policy, xác nhận bị chặn với thông báo chỉ đúng policy nào",
      ],
    },
    {
      id: "capstone-production-grade-platform",
      title: "🏁 Capstone: Production-grade platform trên AWS",
      description: "Dự án tổng hợp toàn khoá — dựng một nền tảng cấp production cho app mẫu trên AWS, dùng làm portfolio chính khi phỏng vấn. Steps dưới đây là checklist bắt buộc từ đề bài capstone.",
      steps: [
        "Hạ tầng 100% Terraform (VPC, EKS, RDS, ElastiCache, S3, IAM), dùng remote state (S3 + DynamoDB lock hoặc S3 native locking), tách 2 môi trường (vd `dev` và `prod`) bằng workspace hoặc thư mục riêng",
        "CI bằng GitHub Actions: test → SAST/SCA (Semgrep, Trivy, gitleaks) → build image → scan image → sinh SBOM (Syft) → ký bằng cosign (keyless OIDC) → push lên ECR, xác thực bằng OIDC (không dùng access key tĩnh)",
        "CD bằng Argo CD theo mô hình GitOps; triển khai canary cho service API (Argo Rollouts hoặc tương đương)",
        "Secrets đi qua External Secrets Operator đồng bộ từ AWS Secrets Manager, không có secret nào nằm trong Git hay ConfigMap",
        "Observability đầy đủ: Prometheus/Grafana/Loki/OpenTelemetry (kế thừa M15); có alert dựa trên SLO/burn-rate (kế thừa M16), không chỉ ngưỡng CPU/RAM",
        "Policy: Kyverno bắt buộc image đã ký, cấm chạy container root, bắt buộc có resource limits trên mọi namespace ứng dụng",
        "Autoscaling: HPA cho pod theo metric phù hợp; Karpenter (hoặc Cluster Autoscaler) cho node",
        "Tài liệu đầy đủ trong repo: sơ đồ kiến trúc, ít nhất 2 ADR (Architecture Decision Record) cho các quyết định lớn, runbook cho ≥2 alert quan trọng, DR plan, và báo cáo ước tính chi phí/tháng",
        "Cung cấp `make up` dựng toàn bộ hạ tầng + app từ đầu, và `make down` xoá sạch — cả hai chạy được trên máy mới không cần thao tác tay thêm",
        "(Bonus, không bắt buộc) Quay demo video 5 phút, viết blog 'Từ commit tới production', hoặc thử multi-region DR / so sánh chi phí EKS vs ECS Fargate",
      ],
    },
  ],
  deliverable:
    "Repo capstone hoàn chỉnh: Terraform modules, GitHub Actions workflow (scan → sign → push), Argo CD app-of-apps, Kyverno policies, dashboard/alert SLO, tài liệu kiến trúc + ADR + runbook + DR plan + ước tính chi phí, và script make up/make down.",
  successCriteria:
    "Một người khác clone repo, chạy `make up` trên tài khoản AWS trống là dựng được toàn bộ hệ thống; pipeline tự chặn khi có secret lộ, dependency CRITICAL hoặc image chưa ký; giải thích được mọi quyết định kiến trúc bằng ADR.",
  resources: [
    { title: "OWASP Top 10", url: "https://owasp.org/www-project-top-ten/", kind: "doc" },
    { title: "Sigstore / cosign documentation", url: "https://docs.sigstore.dev/", kind: "doc" },
    { title: "SLSA — Supply-chain Levels for Software Artifacts", url: "https://slsa.dev/", kind: "doc" },
    { title: "Kyverno Policy Library", url: "https://kyverno.io/policies/", kind: "tool" },
    { title: "Trivy documentation (Aqua Security)", url: "https://trivy.dev/latest/", kind: "doc" },
    { title: "HashiCorp Vault documentation", url: "https://developer.hashicorp.com/vault/docs", kind: "doc" },
    { title: "AWS Well-Architected — Security Pillar", url: "https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/welcome.html", kind: "doc" },
    { title: "OWASP ZAP (DAST)", url: "https://www.zaproxy.org/", kind: "tool" },
  ],
  quiz: [
    {
      id: "shift-left-cost",
      question: "Vì sao 'shift-left security' (quét lỗi ngay khi code được viết) được xem là tiết kiệm chi phí hơn?",
      options: [
        "Vì công cụ SAST miễn phí hoàn toàn",
        "Vì lỗi bảo mật phát hiện ở production đắt hơn nhiều lần so với phát hiện lúc code review hay pull request, do phải rollback, vá khẩn cấp, xử lý sự cố",
        "Vì shift-left loại bỏ hoàn toàn nhu cầu security review thủ công",
        "Vì nó làm pipeline chạy nhanh hơn",
      ],
      answerIndex: 1,
      explanation: "Kiểm nguyên liệu ở chợ rẻ hơn nhiều so với thu hồi món ăn đã đến tay khách. Chi phí sửa lỗi tăng theo cấp số nhân qua từng giai đoạn: code → build → staging → production.",
    },
    {
      id: "sast-vs-sca-vs-dast",
      question: "Một thư viện npm bạn dùng có CVE mới công bố, dù code của bạn không có lỗi logic nào. Loại scanner nào phát hiện đúng vấn đề này?",
      options: ["SAST (Semgrep)", "SCA (Trivy/Dependabot) — quét dependency đã biết có lỗ hổng", "DAST (OWASP ZAP)", "Secret scanning (gitleaks)"],
      answerIndex: 1,
      explanation: "SAST phân tích code bạn viết ra; SCA (Software Composition Analysis) kiểm tra thư viện bên thứ ba dựa trên cơ sở dữ liệu CVE — đúng loại lỗi này.",
    },
    {
      id: "secret-scanning-purpose",
      question: "gitleaks quét được gì mà Trivy image scan không quét?",
      options: [
        "Lỗ hổng CVE trong base image",
        "Secret (API key, private key, password) bị commit nhầm vào lịch sử Git",
        "Cấu hình Terraform sai",
        "Container chạy bằng root",
      ],
      answerIndex: 1,
      explanation: "gitleaks chuyên tìm chuỗi trông giống secret trong nội dung và lịch sử commit — một secret đã commit rồi xoá ở commit sau vẫn còn nằm trong lịch sử Git.",
    },
    {
      id: "sbom-purpose",
      question: "Một CVE nghiêm trọng mới công bố cho log4j. Có SBOM cho mọi image production giúp ích gì đầu tiên?",
      options: [
        "SBOM tự động vá lỗi",
        "Tra cứu nhanh image nào đang chứa log4j và phiên bản nào, thay vì phải quét lại từng image thủ công",
        "SBOM thay thế hoàn toàn việc quét CVE",
        "SBOM chỉ dùng để tính chi phí license",
      ],
      answerIndex: 1,
      explanation: "SBOM (Software Bill of Materials) là 'nhãn thành phần' của image — như đọc nhãn thực phẩm để biết có đường trong thùng hàng nào mà không cần mở từng thùng ra nếm.",
    },
    {
      id: "cosign-keyless-benefit",
      question: "Vì sao ký image bằng cosign 'keyless' (qua OIDC của GitHub Actions) thường an toàn hơn ký bằng private key cố định lưu trong Secret?",
      options: [
        "Keyless nhanh hơn về mặt tốc độ CPU",
        "Không có private key dài hạn nào để bị rò rỉ; danh tính ký gắn với chính workflow/run cụ thể đã tạo ra image, có thể xác minh lại",
        "Keyless không cần internet",
        "Keyless miễn phí còn ký bằng key phải trả tiền",
      ],
      answerIndex: 1,
      explanation: "Tem niêm phong ký bằng 'danh tính tạm thời của đúng dây chuyền sản xuất' (workflow run) khó giả mạo hơn nhiều so với con dấu vật lý có thể bị đánh cắp và dùng lại.",
    },
    {
      id: "slsa-purpose",
      question: "SLSA levels dùng để làm gì?",
      options: [
        "Đo tốc độ build của pipeline",
        "Xếp hạng mức độ tin cậy và khả năng chống giả mạo của quy trình build/supply chain một artifact, từ build thủ công tới build có provenance được ký và kiểm chứng",
        "Thay thế hoàn toàn SAST và SCA",
        "Chỉ áp dụng cho image Docker, không áp dụng cho package khác",
      ],
      answerIndex: 1,
      explanation: "SLSA (Supply-chain Levels for Software Artifacts) đo 'chuỗi cung ứng đáng tin tới đâu' — build có provenance, có ký, có cách ly build environment — không phải công cụ quét lỗi.",
    },
    {
      id: "kyverno-admission-deny",
      question: "Kyverno policy `disallow-latest-tag` ở chế độ `Enforce` từ chối một Pod dùng `image: checkout:latest`. Điều gì xảy ra?",
      options: [
        "Pod vẫn được tạo nhưng có cảnh báo trong log",
        "Admission controller từ chối request tạo Pod ngay tại API server, Pod không bao giờ được tạo ra",
        "Pod được tạo, Kyverno sẽ xoá nó sau 5 phút",
        "Chỉ namespace mặc định bị ảnh hưởng",
      ],
      answerIndex: 1,
      explanation: "Kyverno hoạt động như một admission webhook: ở chế độ Enforce, nó chặn request tại cửa API server — giống bảo vệ không cho xe không có tem qua cổng, chứ không phải phạt sau khi xe đã vào.",
    },
    {
      id: "vault-vs-secrets-manager-choice",
      question: "Team đã có toàn bộ hạ tầng trên AWS, cần rotation tự động cho mật khẩu RDS và không muốn vận hành thêm hệ thống mới. Lựa chọn hợp lý?",
      options: [
        "AWS Secrets Manager với rotation Lambda có sẵn tích hợp RDS — không cần tự vận hành cluster",
        "HashiCorp Vault self-hosted vì mạnh hơn về mọi mặt",
        "Không cần secret manager, lưu mật khẩu trong biến môi trường Kubernetes ConfigMap",
        "Dùng file .env commit vào Git riêng cho mỗi môi trường",
      ],
      answerIndex: 0,
      explanation: "AWS Secrets Manager tích hợp sẵn rotation cho RDS/Redshift/DocumentDB mà không cần vận hành thêm cluster. Vault mạnh hơn khi cần multi-cloud, dynamic secrets phức tạp hơn, hoặc không muốn phụ thuộc một cloud.",
    },
    {
      id: "guardduty-vs-security-hub",
      question: "Phân biệt vai trò chính của GuardDuty và Security Hub trong AWS?",
      options: [
        "Cả hai làm y hệt nhau, chọn cái nào cũng được",
        "GuardDuty phát hiện hoạt động bất thường/độc hại (threat detection) bằng machine learning trên log; Security Hub tổng hợp và ưu tiên findings từ nhiều dịch vụ bảo mật (bao gồm GuardDuty) vào một nơi",
        "GuardDuty chỉ quét container, Security Hub chỉ quét EC2",
        "Security Hub thay thế hoàn toàn IAM",
      ],
      answerIndex: 1,
      explanation: "GuardDuty giống camera an ninh phát hiện kẻ lạ; Security Hub giống phòng điều hành trung tâm gom mọi cảnh báo (từ GuardDuty, Inspector, Config...) để xếp ưu tiên xử lý.",
    },
    {
      id: "capstone-oidc-vs-static-keys",
      question: "Trong capstone, pipeline CI cần push image lên ECR. Cách nào đúng với thực hành DevSecOps đã học?",
      options: [
        "Tạo access key/secret key IAM user, lưu vào GitHub Secrets rồi dùng mãi mãi",
        "Dùng GitHub OIDC để pipeline assume một IAM role có quyền giới hạn, không lưu access key tĩnh nào",
        "Dùng root account credentials cho nhanh vì đây chỉ là capstone",
        "Tắt IAM permission boundary để pipeline chạy dễ hơn",
      ],
      answerIndex: 1,
      explanation: "Access key tĩnh là chìa khoá vạn năng có thể bị rò rỉ và tồn tại mãi mãi; OIDC cấp quyền tạm thời đúng phạm vi cho đúng workflow — đúng tinh thần least privilege xuyên suốt khoá học.",
    },
  ],
};
